### ISSUE TITLE
Student: "Fix repo" error after manual recreating gh-pages branch

### ISSUE THREAD

**Issue by alexpataman** [rolling-scopes/rsschool-app#1024]
**Course**
Front-end 2021Q3

**What is wrong**
После пересоздания вручную ветки gh-pages (уже понял, что это было ошибкой), пофиксить репозиторий кнопкой "Fix repo" не удается. 
По клику выдает ошибку "An error occurred. Please try later.", запрос возвращает статус "Status Code: 401 Unauthorized" и ответ {"message":"Bad credentials"}

![image](https://user-images.githubusercontent.com/939507/139594342-00cd9b76-32d6-4ed9-b7b9-638209be695a.png)

**Comment by apalchys** [comment]
@alexpataman проверь пожалуйста теперь

**Comment by alexpataman** [comment]
@apalchys спасибо, заработало.
Единственное, немного вводит в заблуждение модалка с информацией, что на почту будет отправлен invitation email, но по факту ничего не присылает (видимо, потому что разрешения уже были даны ранее). Но gh-pages пофиксилась благополучно.

**Comment by alexpataman** [comment]
Пожелание относительно модалки вынес в отдельную issue
https://github.com/rolling-scopes/rsschool-app/issues/1035
