### ISSUE TITLE
Change reference github in profile app.rsschool

### ISSUE THREAD

**Issue by vitaly-sazonov** [rolling-scopes/rsschool-app#1026]
**Course**
NODEJS-2021Q4

**What is wrong**
Доброго времени суток! 

Ситуация следующая...
Зарегистрировался в приложении app.rs.school через аккаунт в гитхабе, после чего сменил название аккаунта гитхаба, однако в профиле app.rs.school ссылка сохранилась старая.

Пытался перелогиниться со всякими очистками куки, локалсторедж, отзыва ключа с гитхаба и тп. эффекта ноль. Видимо аккаунт привязывается еще и к емейлу. И скорее всего изменить можно только вручную в базе.

 Кто-то может изменить в моем профиле в app.rsschool ссылку на гитхаб?

**Comment by apalchys** [comment]
@vitaly-sazonov попробуй залогиниться снова

**Comment by vitaly-sazonov** [comment]
да, все теперь обновилось, благодарю!
