### ISSUE TITLE
[WIP] Schedule Refactoring

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#1067]
- remove `place` column
- remove `url` column 
- remove 'task' popup
- update 'score'. Fix issue with null.
- highlight current week 
![image](https://user-images.githubusercontent.com/2429680/142435927-ba687a24-ed09-4fd3-8b67-1b428ab37635.png)

**Comment by Semigradsky** [comment]
> remove url column

Имхо, было удобнее с этой колонкой.
Раньше, чтобы открыть несколько заданий в новых вкладках нужно было:
- кликнуть с зажатым ctrl по ссылке 1
- кликнуть с зажатым ctrl по ссылке 2

Теперь:
- перейти на страницу таска 1
- кликнуть с зажатым ctrl по ссылке
- перейти в браузере "назад"
- подождать пока снова загрузится schedule
- перейти на страницу таска 2
- кликнуть с зажатым ctrl по ссылке
- перейти в браузере "назад"
- подождать пока снова загрузится schedule

**Comment by dzmitry-varabei** [comment]
@Semigradsky поправили! спасибо!
@Pulya10c спасибо большое!

**Comment by dzmitry-varabei** [comment]
@Pulya10c Привет! Как будет время, убери пожалуйста колонку duration. Она тоже не нужна.

**Comment by dzmitry-varabei** [comment]
@Pulya10c Привет! Duration все еще есть в настройках расписания 
![image](https://user-images.githubusercontent.com/2429680/158378016-67f30bb4-4f0e-4fc9-bec5-d1993ceb2336.png)
