### ISSUE TITLE
Registration: Confirmation of the mentorship by email

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#1069]
Right now mentors receive confirmation only from the telegram bot. 
It will be great to duplicate this confirmation by email.

**Comment by dzmitry-varabei** [comment]
![image](https://user-images.githubusercontent.com/2429680/146542209-bb9ae3ef-5b56-4626-8e56-5b4456323013.png)

**Comment by aaliakseyenka** [comment]
this is done.
