### ISSUE TITLE
Bug with the caption "Submission deadline has already passed"

### ISSUE THREAD

**Issue by KISLY74** [rolling-scopes/rsschool-app#1084]
**Describe the bug**
If the assignment is not completed, the message "Submission deadline has already passed" appears in the Cross-check submit section. The essence of the problem is that this inscription now appears in all tasks: both old, which have long been done and new that you send.

**To Reproduce**
1. Go to section Cross-check submit
2. Click on any task
3. And you see this problem (the message "Submission deadline has already passed" at all tasks)

**Expected behavior**
This inscription ("Submission deadline has already passed" ) should appear only in those tasks that are not completed or not submitted on time. In my case, it appears in all tasks.

**Screenshots**
here is correct the inscription must be because I did not do the task.
![image](https://user-images.githubusercontent.com/85252629/144055849-852daea9-3b6a-40cd-a53e-1a705991d6c3.png)
And in the second screenshot, the inscription should not appear because this task I have already done and received points.
![image](https://user-images.githubusercontent.com/85252629/144055903-0dda26cb-a0f1-4a12-a17f-1561144fd96c.png)
![image](https://user-images.githubusercontent.com/85252629/144056528-482f786b-ee3c-46b1-8a1b-c9f0fe29c617.png)

**Device (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [96.0.4664.45]

**Comment by AlreadyBored** [comment]
I don't think it's a bug because this message only shows that deadline has passed at the current moment. This fact doesn't depends on your personal task submission.

**Comment by AlreadyBored** [comment]
But we can improve UI
