### ISSUE TITLE
#gratitude - comments field, previous groups

### ISSUE THREAD

**Issue by cathzetjo** [rolling-scopes/rsschool-app#109]
1. Make bigger comment field ( screenshot from Safari browser): 

![21BA02E1-9668-474D-9970-1752218FB16E](https://user-images.githubusercontent.com/44948376/64480690-d054c880-d1d4-11e9-9d6a-45ac532eb8d3.jpeg)
 2. Add possibility (for example button near “My profile“ button ) to add gratitudes for students from previous groups. I had to register on 2019Q3 to be able to add gratitude. As we are big community now people can help each other no matter that they are ex students. And that’s great to say thank you thru the app from your profile.

**Comment by cathzetjo** [comment]
Sorry it’s not a bug.. my mistake in label.

**Comment by apalchys** [comment]
@cathzetjo please check how it works now.

**Comment by cathzetjo** [comment]
Point 2 - done. Great! Thank you!

**Comment by cathzetjo** [comment]
Point 1. Still you need to scroll your message if it’s longer then available field: 
 
![2DF39644-19B8-4E0F-B631-C79807531FC5](https://user-images.githubusercontent.com/44948376/64951747-4cab7380-d887-11e9-86e4-af7a60f9b712.jpeg)

**Comment by cathzetjo** [comment]
Also some people found a bit irritating the red message )

![2C0A1FD6-CDF5-4003-902E-F5F997831118](https://user-images.githubusercontent.com/44948376/64951854-867c7a00-d887-11e9-829b-d96103fa973a.jpeg)

**Comment by apalchys** [comment]
@cathzetjo 
the #1 point was fixed. 

Regarding the message. Do have any ideas how we can improve it? We want to have feedbacks more meaningful and use limit to 20 symbols right now.

**Comment by cathzetjo** [comment]
> @cathzetjo
> the #1 point was fixed.
> 
> Regarding the message. Do have any ideas how we can improve it? We want to have feedbacks more meaningful and use limit to 20 symbols right now.

Can add this checking and warning when person press Submit button. And maybe text doesn’t have to be so insistent. Maybe something standard - Enter minimum 20 symbols please.
