### ISSUE TITLE
Обновил свой github 

### ISSUE THREAD

**Issue by AndreiChaika** [rolling-scopes/rsschool-app#1103]
**Course**
JS / FE Pre-School 2022 stage0

**What is wrong**
Обновил свой ник github (был krestowsky, стал AndreiChaika). Однако в профиле он не обновился. Прошу внести изменение.
Ссылка https://github.com/AndreiChaika

**Comment by apalchys** [comment]
@AndreiChaika  Просто перелогинься через https://app.rs.school/login и все должно быть ок
