### ISSUE TITLE
Telegram notifications

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#1105]
Собираю пожелания по нотификациям, которые должен присылать RS APP через Telegram Bot

**Comment by Loktysh** [comment]
- Получение оценки по Cross-check.
- Изменение оценки по Cross-check.
- Дедлайны Submit и  Cross-check.
- Изменение технических требований к заданию если оно уже выдано.
- Назначение пользователю интервьюера.
- Дедлайны тестов.

В идеале чтобы была возможность убрать ненужные уведомления и добавить информацию по Sort Track.

**Comment by Fodin** [comment]
①. Преддедлайновые, предкроссчековые, предлекционные уведомления.
↊. "Ты не отправил ссылку PR на кроссчек!" "Ты не проверил 4 работы на кроссчеке!" за несколько часов до дедлайна.
Ⅲ. "Ты закончил школу и получил сертификат!"
🂤. Перенос лекции или дедлайна.

**Comment by AV-Shell** [comment]
Не знаю насоклько реализуемо, но мне кажется было бы классно, если бы можно было в app.rs.school выбрать галочками те уведомления, которые должны приходить, например "Оценки" "Дедлайны за сутки" "Дедлайны за 4 часа" , ну или несколько подписок на бота  вроде:
1) Оценки
2) Дедлайны
3) Лекции

**Comment by aaliakseyenka** [comment]
email & telegram notifications are added and can be configured via 
https://app.rs.school/profile/notifications
