### ISSUE TITLE
Сorrect the text

### ISSUE THREAD

**Issue by PDmitryY** [rolling-scopes/rsschool-app#1106]
In the materials for the stage 0 (https://github.com/rolling-scopes-school/tasks/tree/master/stage0/modules/git) there is a mistake in word "прочитать". You can see the issue in the image below.
![image](https://user-images.githubusercontent.com/19780026/146657101-665ced77-1ac5-4304-ae15-e027b58510e3.png)

**Comment by Semigradsky** [comment]
Уже исправлено.

**Comment by apalchys** [comment]
> Уже исправлено.

Closing
