### ISSUE TITLE
Auto-tests: Load balancing queue

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#1107]
Сейчас при превышении лимита обращений к GitTub из RS APP авто-тесты в RS APP подают:
![telegram-cloud-photo-size-2-5337076591831922586-y](https://user-images.githubusercontent.com/2429680/146950166-c7544115-a5fb-46d3-a46a-813f4095f1fc.jpg)
![telegram-cloud-photo-size-2-5337076591831922587-y](https://user-images.githubusercontent.com/2429680/146950207-1ee8f002-08cc-4c72-8d81-b0015312cbf9.jpg)
![image](https://user-images.githubusercontent.com/2429680/146950320-08741a21-0875-45ae-a30e-2ef346cc5542.png)

Возможное решение - все запросы пользователей помещать в очередь, отображать статус проверки на странице Auto-test и обрабатывать без превышения лимита (например, 1500 сабмитов в час).

**Comment by apalchys** [comment]
Fixed
