### ISSUE TITLE
Telegram Bot doesn't work if no username in Telegram

### ISSUE THREAD

**Issue by apalchys** [rolling-scopes/rsschool-app#1108]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

**Additional context**

**Comment by aaliakseyenka** [comment]
tg bot now responds for users without username. although notifications won't work. This will be covered by https://github.com/rolling-scopes/rsschool-app/issues/1105
