### ISSUE TITLE
Проверка регистрации на курс студентами

### ISSUE THREAD

**Issue by daniil-loban** [rolling-scopes/rsschool-app#111]
На данный момент при проверке студентом регистрации на курсе (по адресу: https://app.rs.school/course/score?course=rs-2019-q3) появляется такое сообщение если он не зарегистрирован:
![image](https://user-images.githubusercontent.com/14092002/64519478-dba31380-d2fc-11e9-80ea-4411b9f2d056.png)
Оно может быть неоднозрначно воспринято студентом, поэтому предлагаю написать что-то более релевантное, например: "You are not registred on this course."

**Comment by apalchys** [comment]
@daniil-loban Подскажи, а есть какой-то способ увидеть эту ссылку студенту на UI?

**Comment by daniil-loban** [comment]
вероятно, нет

**Comment by apalchys** [comment]
@daniil-loban updated
