### ISSUE TITLE
Замена GITHub логина

### ISSUE THREAD

**Issue by Pobirskiy** [rolling-scopes/rsschool-app#1110]
Прошу сменить логин GITHub 
Я зарегался на курс JavaScript/Front-end. Stage 0 несколько недель назад, прошел уже первый тест RSS и HTML.
Сменил пароль в GITHub и подтвердил почту. При входе в https://app.rs.school/ - пишет, что you are not student or mentor in any active course.
Как понять, почему app меня не пускает? 
Предположительно, что у меня при сбросе пароля сменился аккаунт с pobirsky на pobirskiy.
Как можно заменить аккаунт в регистрации?
Гитхаб не дает поменять на pobirsky-аккаунт занят.

**Comment by apalchys** [comment]
@pobirsky и @pobirskiy два разных аккаунта, как в гитхабе, так и приложении. К сожалению нету просто возможности их обьединить. Остался ли доступ к старому аккаунту @pobirsky? Если да, я предлагаю продолжать им пользоваться. Например:


1) Поменять pobirskiy на любой произвольный в github
2) Залогиниться в приложение под ним через app.rs.school/login

Эти шаги помогут "освободить" pobirskiy.

3) Затем залонииться в гитхаб под pobirsky и поменять его на pobirskiy
4) Залогиниться через app.rs.school/login

**Comment by pobirsky** [comment]
Получилось залогиниться под старым логином. Спасибо за помощь! @apalchys
