### ISSUE TITLE
Перерегистрация.

### ISSUE THREAD

**Issue by karmalystatiana** [rolling-scopes/rsschool-app#1112]
**rss-stage0**

**При регистрации в github неверно указала фамилию (да, бывают и такие косяки)), далее начала выполнять тесты и уже когда начала делать CV увидела ошибку. Поменяла с  @karmaiystatiana на  @karmalystatiana, после этого я, конечно, перестала быть связанной с репозиторием школы. это ведь можно исправить.)) **

**Comment by apalchys** [comment]
@karmalystatiana актуальна ли проблема? я вижу что нету @karmaiystatiana в системе?

**Comment by apalchys** [comment]
В то же время, я вижу что вы неактивны уже на курсе? Вы самоисключились?

**Comment by karmalystatiana** [comment]
> @karmalystatiana актуальна ли проблема? я вижу что нету @karmaiystatiana в системе?

с курса я не отключалась, по крайней мере специально. В первый день выдавало ошибку, а потом я стала не активна, наверное после обновления результатов. У меня пройдено 4 теста, но тк результат ни куда не идет, можно ли меня внести как-нибудь с новым именем, пусть и с обнулением результатов.
PS: заранее спасибо
PPS: извините за проблемы))
