### ISSUE TITLE
Проблема с регистрацией

### ISSUE THREAD

**Issue by Luffi2539** [rolling-scopes/rsschool-app#112]
Зашел под данным гитхаб аккаунтом(luffi2539) и не могу пройти регистрацию ни как ментор ни как студент (пишет что регистрация прошла, но домашняя страница опять предлагает пройти регистрацию). Проверял score по ссылке там я тоже не числюсь. Пробовал в 2-х браузерах(Хром и сафари) и в режиме инкогнито. Зарегистрировал новый аккаунт гитхаба и все прошло с первого раза.

**Comment by cathzetjo** [comment]
Витю нам потерять никак нельзя. Он же наш ментор текущий ) А они на вес золота )

**Comment by apalchys** [comment]
@Luffi2539 Подскажи, а ты все таки планируешь быть студентом или ментором?

Ты столкнулся с проблемой, что мы недостаточно четко объясняем новым менторам процесс + UX проблемы. Сегодня я исправлю проблему.

Что произошло:
1. Ты подал заявку как `luffi2539` на ментора и она попала в статус `pending`, так как ты раньше ни разу не был ментором. Процесс аппрува менторов ручной и занимает какое-то время
2. Сейчас нету никакого механизма ограничивающего повторную подачу заявки на стороне UI (ментором или стеднтом), но она просто игнорируется, так как первая считается приоритетной. Это я и исправлю.

Итог:
Твоя заявка на ментора не потерялась и просто ожидает рассмотрения.

**Comment by Luffi2539** [comment]
@apalchys  Привет, планирую быть ментором, но регистрировался как студент, потому что в субботу буду делать стрим для студентов и мне нужен был дашборд студента. Сейчас уже сделал себе гитхаб аккаунт для этой цели, поэтому можете снять мою регистрацию как студента

**Comment by apalchys** [comment]
@Luffi2539 твоя заявка аппрувнута. ты теперь ментор. студента удалил.
