### ISSUE TITLE
bug in sorted list

### ISSUE THREAD

**Issue by ineg22** [rolling-scopes/rsschool-app#113]
1. Go to 'app,rs.school' => score
2. Click on sort by location
3. Scroll down to any page
4. See error. First row with guy from Astana is not sorted

**Device (please complete the following information):**
 - OS: win10
 - Browser chrome
 - Version 76
![Аннотация 2019-09-10 145056](https://user-images.githubusercontent.com/49589225/64611595-79204500-d3da-11e9-9238-1a2a1e5f40b7.jpg)

**Comment by apalchys** [comment]
@ineg22 fixed. thanks
