### ISSUE TITLE
Дайте ещё один шанс сабмитить задание "Portfolio"

### ISSUE THREAD

**Issue by maksat07** [rolling-scopes/rsschool-app#1131]
**Course**
JS / FRONT-END. STAGE 0
13 декабря 2021

**What is wrong**
Прошу администрации RS School дать один шанс  сабмитить "Портфолио " Cross-Check: Review!!! потому что я до дедлайна сабмитил не тот сылку, точнее забыл Pull requests заполнить !  Пожалуйста  дайте ещё один шанс!
**screenshot ![FireShot Capture 054 - Portfolio - 127 0 0 1](https://user-images.githubusercontent.com/87502665/149896395-4f5b62ef-92ba-4455-a2b6-c8b0bfc6f7c0.png)

https://github.com/rolling-scopes-school/maksat07-JSFEPRESCHOOL/
[FireShot Capture 052 - Portfolio - 127.0.0.1.pdf](https://github.com/rolling-scopes/rsschool-app/files/7887303/FireShot.Capture.052.-.Portfolio.-.127.0.0.1.pdf)

**Comment by dzmitry-varabei** [comment]
@maksat07 по скору вижу, что все хорошо закончилось

**Comment by maksat07** [comment]
👌👍
