### ISSUE TITLE
There isn't a possibility to Expel/Unassign students

### ISSUE THREAD

**Issue by IrinaBorkina** [rolling-scopes/rsschool-app#1133]
**Describe the bug**
There isn't a possibility to Expel/Unassign students

**To Reproduce**
1. Go to '[Expel/Unassign Student Route](https://app.rs.school/course/mentor/expel-student?course=js-fe-2021Q3)'
2. See error (input is blocked for choosing any students)

**Expected behavior**
There is a possibility to choose students

**Screenshots**
![image](https://user-images.githubusercontent.com/44750544/149947617-bf55a770-0b52-49ca-9cca-7fbce09469ff.png)
![image](https://user-images.githubusercontent.com/44750544/149948046-03960dc7-2b47-4c64-b450-35ee53137717.png)

**Device:**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 97.0.4692.71 (Official Build) (64-bit)

**Comment by apalchys** [comment]
@IrinaBorkina  thanks for reporting. could you please check it now?

**Comment by IrinaBorkina** [comment]
Yes, it works now. Thank you for resolving this issue)
