### ISSUE TITLE
Не работает кнопка Reset в фильтрах

### ISSUE THREAD

**Issue by natein** [rolling-scopes/rsschool-app#1134]
Не работает кнопка Reset везде в фильтрах. 

Допустим что-то нашла по ключевым словам.

![filter](https://user-images.githubusercontent.com/12632270/150153859-b24a6bce-4b1f-4590-8826-dbd9fe11228e.JPG)
Далее хочу отменить фильтр и нажимаю Reset. Поле очищается, но не происходит обновление результатов.

![reset](https://user-images.githubusercontent.com/12632270/150154259-4184ccc4-f382-44ae-9158-fdaaa1455d1b.JPG)

**Comment by apalchys** [comment]
thanks. fixed
