### ISSUE TITLE
Нарушен порядок сортировки заданий

### ISSUE THREAD

**Issue by natein** [rolling-scopes/rsschool-app#1149]
Вместо сортировки по дате выдачи задания, колонки в скоре располагаются случайным образом. Например:
![150892705-85dcacc3-c72f-455a-b334-845d51a99d95](https://user-images.githubusercontent.com/12632270/150902281-8696a213-71e3-41ad-bdd2-87e1fd0e09f0.png)

**Comment by apalchys** [comment]
Fixed
