### ISSUE TITLE
Отсортировать задания по дате выдачи

### ISSUE THREAD

**Issue by natein** [rolling-scopes/rsschool-app#1150]
Предлагаю отсортировать задания по дате выдачи в статистике, их будет проще находить в списке.
Сейчас они в произвольном порядке.

![Снимок](https://user-images.githubusercontent.com/12632270/150980333-87662995-2fdb-49c6-89ee-188a45954463.PNG)

**Comment by AlreadyBored** [comment]
Course tasks are sheduled by deadline
