### ISSUE TITLE
Problem with rs-app

### ISSUE THREAD

**Issue by alivar391** [rolling-scopes/rsschool-app#1157]
**Describe the bug**
Rs-app platform give me this result unexpectedly . when i reloaded the page and rellogin the problem was resolved. This is situation was happend one time.

**To Reproduce**
I didn`t do any unusaul things.

**Expected behavior**

**Screenshots**
![unknown](https://user-images.githubusercontent.com/74236807/151201044-5dc18ce4-d863-44fe-b0c4-87ba021e34e8.png)

**Device (please complete the following information):**
 - OS: [e.g. iOS] windows 7 64
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] the last version

**Additional context**

**Comment by enginsan** [comment]
Same issue I have. Registered on FE 2022 and stage0, but don't see courses list, only this with two buttons Register as Mentor and Register as Student.
OS - Ubuntu 21.10
Browser - Chrome 97.0.4692.99

**Comment by apalchys** [comment]
it should be fixed
