### ISSUE TITLE
Unexpected horizontal scroll display on register/student page

### ISSUE THREAD

**Issue by zavada123** [rolling-scopes/rsschool-app#116]
**Describe the bug**
Unexpected horizontal scroll display on register/student page

**To Reproduce**
1. Go to 'https://app.rs.school/registry/student'
2. See horizontal scroll

**Expected behavior**
Horizontal scroll should be hidden

**Screenshots**
https://prnt.sc/p4t3l1

**Device (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 76.0.3809.132

**Comment by apalchys** [comment]
@zavada123 please check. it should be fixed now.
