### ISSUE TITLE
Don't have access to score 

### ISSUE THREAD

**Issue by alekseyswork** [rolling-scopes/rsschool-app#118]
**Course**
RS 2019 Q3

**What is wrong**
No Access
Probably you do not participate in the course. Please register or choose another course.

**Comment by apalchys** [comment]
@alekseyswork cейчас есть проблема с истечение сессии и правильной обработки такой ситуации. Можешь попробовать пожалуйста перейти на главную (https://app.rs.school), залогиниться, если надо и опять открыть score снова.

**Comment by alekseyswork** [comment]
Спасибо так и есть. Показывает что залогинин но сессия истекла.
Перелогинился все работает. Спасибо.

пт, 13 сент. 2019 г. в 12:49, Andrei <notifications@github.com>:

**Comment by apalchys** [comment]
@alekseyswork fixed
