### ISSUE TITLE
Wrong condition for displaying `your stats` and `your mentor` sections

### ISSUE THREAD

**Issue by dmitrydutin** [rolling-scopes/rsschool-app#1184]
If you select a course where you were a student on the main page, the sections `your stats` and `your mentor` will appear.
![image](https://user-images.githubusercontent.com/70740801/152310710-660c3f84-0954-4c61-952c-5ed1f683156c.png)
Further, if you choose a course where you were a mentor, then the sections `your stats` and `your mentor` will remain.
![image](https://user-images.githubusercontent.com/70740801/152310762-a818c438-5d8d-4fcd-8227-6d3d2aff288b.png)
But if you reload the page, the `your stats` and `your mentor` sections will disappear.
![image](https://user-images.githubusercontent.com/70740801/152310928-d24bda50-2c55-4db5-9e27-3f9184e02c83.png)

**To Reproduce**
1. Go to https://app.rs.school/
2. Select the course where you were a student
3. Select the course where you were a mentor

**Expected behavior**
The `your stats` and `your mentor` sections should not be visible if you are a mentor

**Device (please complete the following information):**
 - OS: [windows, iOS]
 - Browser [chrome]
 - Version [latest]

**Comment by apalchys** [comment]
It should be fixed. Thanks
