### ISSUE TITLE
Cross-Check Review: disable submit button after cross-check deadline

### ISSUE THREAD

**Issue by WiiJoy** [rolling-scopes/rsschool-app#1198]
При наступлении дедлайна по кросс-чеку в разделе Cross-Check: Review навесить disabled на кнопку submit, чтобы убрать возможность производить проверку по окончанию дедлайна.
<img width="742" alt="Снимок экрана 2022-02-07 в 13 37 46" src="https://user-images.githubusercontent.com/73646765/152772665-48d2cb3e-2371-446e-ae9d-51a565031843.png">

**Comment by AlreadyBored** [comment]
Fixed by https://github.com/rolling-scopes/rsschool-app/pull/1484
