### ISSUE TITLE
Schedule tab issue

### ISSUE THREAD

**Issue by ts-andrey** [rolling-scopes/rsschool-app#1200]
**Course**
JavaScript/Front-end 2021Q3

**What is wrong**
I went through the `CoreJS Interview` and get scored. I can clearly see my score points in `Score` tab, as well as `Completed` status in `Interviews` tab, but in `Schedule` and `Dashboard` tab it looks like I didn't finish my `CoreJS Interview` at all. When I found this problem I asked about it in Discord channel and got answer from `moderator (owner)` that it's just an issue and I was asked to report it, that's it.

**Comment by apalchys** [comment]
@ts-andrey please check now

**Comment by ts-andrey** [comment]
![изображение](https://user-images.githubusercontent.com/49396376/155212360-83fcbcc0-f830-4b6b-82af-4eeb88a2364f.png)

As you can see still face the same issue. Even tried relogin.

**Comment by ts-andrey** [comment]
Yeah, now this problem is completely solved, thank you for your efforts! :)
