### ISSUE TITLE
Status: Inactive

### ISSUE THREAD

**Issue by PolinaYu** [rolling-scopes/rsschool-app#1202]
RS LT (Planned) 2022

Hello, for some reason i have Status: inactive
 
![изображение](https://user-images.githubusercontent.com/57799907/153062203-63cb521f-be16-40fa-9e2b-6d7de245c763.png)

**Comment by dzmitry-varabei** [comment]
@PolinaYu fixed. Login again plz.

**Comment by PolinaYu** [comment]
Thank you!)

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
