### ISSUE TITLE
Horizontal scroll on score page

### ISSUE THREAD

**Issue by MaksNik** [rolling-scopes/rsschool-app#122]
Стоит немного переделать страницу скора и добавить горизонтальный скролл, иначе очень неудобно смотреть оценки. Приходится крутить до самого конца списка, скроллить, а потом возвращаться и искать своего студента. Вместо этого можно сделать сделать див на высоту окна, который будет скроллиться вертикально и горизонтально.

**Comment by apalchys** [comment]
@MaksNik 
Спасибо за фидбек. Если можно, я хотел бы уточнить немного деталей:
1. Мог бы ты описать, как и с какой целью пользуешься страницей Score
2. Я правильно понял, что основная проблема в том, что ты не видишь одновременно имя студента и его total score?
3. Я правильно понял, что ты предлагаешь fixed column как решение (колонка, которая остается видимой не важно в каком направлении ты скролишь)?
4. Укажи пожалуйста OS / Browser / Resolution

**Comment by MaksNik** [comment]
1. Иногда я смотрю тенденцию по потоку в целом: кто в топах, иногда интересно глянуть, какая оценка у того либо иного студента за определенный таск, пусть даже и не моего. Когда нужно посмотреть конкретно своих студентов - да, фильтруешь по своему нику и скролл появляется.

2. Нет, проблема в том, что total score виден, но когда уже прошло несколько тасок, оценки за них прячутся за правый край экрана и нужно скроллить. Или допустим такая ситуация: мой студент на первых местах. Вот я его вижу в скоре и хочу посмотреть, какая оценка стоит у него за CoreJS интервью к примеру. Для этого мне нужно либо фильтровать список по своему гитхабу, либо крутить страницу вниз до конца, скроллить и возвращаться обратно (если не сортировал по своему гитхабу). Также если скроллишь страницу до конца вниз, а потом хочешь перейти к другому разделу школы, нужно возвращаться обратно вверх, чтобы перейти на главную, либо зайти в свой профиль. Не очень удобно.

3. Я предлагаю сделать вот так: 
![image](https://user-images.githubusercontent.com/25370021/65127818-f19d8c00-da00-11e9-9ba6-7c3cb8859c8f.png)
И еще добавить подсветку строки по клику, не только по ховеру.

4. Windows 10 64bit / Chrome 76.0.3809.132 / 1920x1080

**Comment by PavalEscoba** [comment]
падтрымліваю! 
тут відавочная патрэба ў гарызантальным скроле ў вакна браўзера, а не ў табліцы.
