### ISSUE TITLE
Bug with total score

### ISSUE THREAD

**Issue by hhh1361** [rolling-scopes/rsschool-app#126]
1. Submit completed(correct) task through the submit form.
2. Achieve 100pts to the score (either score for the task, or the final score)
3. Than submit another(incorrect) result for the same task through the subit score.
4. See error: 
4.1 The score for the task is changed, so it became 0. Its ok
4.2 But the total score is still 100pts. Its not ok

![image](https://user-images.githubusercontent.com/47751762/65216869-ffafe300-daba-11e9-98f9-8a4076621b28.png)

**Comment by apalchys** [comment]
@hhh1361 проверь пожалуйста. Проблема должна быть исправлена.

**Comment by hhh1361** [comment]
Все корректно

**Comment by hhh1361** [comment]
Возможно из-за этого теперь не тянутся данные в тотал

![image](https://user-images.githubusercontent.com/47751762/65246318-f5abd580-daf6-11e9-86c9-1634c24b5c20.png)

**Comment by apalchys** [comment]
@hhh1361 total score обновляется раз в 5 минут. Как я вижу у тебя, сейчас `100`.
