### ISSUE TITLE
Пропали тесты и задания 

### ISSUE THREAD

**Issue by PitsuhaVladislaw** [rolling-scopes/rsschool-app#1273]
У меня пропали тесты, еще утром, я выполнял все, как по расписанию, все было хорошо, а сейчас ничего, пусто. Будьте добры объяснить.....

**Comment by dzmitry-varabei** [comment]
@PitsuhaVladislaw Обновили расписание курса. Все снова будет доступно после 13 марта.

**Comment by PitsuhaVladislaw** [comment]
Спасибо большое

чт, 3 мар. 2022 г. в 23:45, Dzmitry Varabei ***@***.***>:
