### ISSUE TITLE
Не совпадают ссылки на сертификате

### ISSUE THREAD

**Issue by natein** [rolling-scopes/rsschool-app#1288]
У большей части сертификатов, выданных на курсе JS/FE Pre-School 2022 не совпадают ссылки в профиле и на самом сертификате.
Например на сертификате https://app.rs.school/certificate/lb60bc00
указана ссылка https://app.rs.school/certificate/eherurzz

![Снимок](https://user-images.githubusercontent.com/12632270/158013172-37b2f450-bc7e-48e1-992c-ef58cf3906cf.PNG)

**Comment by apalchys** [comment]
Fixed. Please check new link on the profile page
