### ISSUE TITLE
Ошибка: Нету доступа к странице проверки записи на курс.

### ISSUE THREAD

**Issue by 07Spirit** [rolling-scopes/rsschool-app#1289]
**Describe the bug**
При попытке проверить себя в системе курса (по посыланию из дискорда) получаю ошибку 403. (скриншот ниже, пункт 4)

**To Reproduce**

1) Получив Сообщение на почту, о курсе. Выполил регистрацию указаную в письме, и на сайте курса 
    (https://app.rs.school/registry/student)
    ![image](https://user-images.githubusercontent.com/101456317/158028188-e6e86761-d31a-423c-b9f8-113c9bcd7faa.png)

2) В пункте "Присоединиться к [открытому чату](https://discord.gg/QvEYg7EaQ4) для участников тренинга" зарегистрировался в 
    дискорде и GitHub, привязал их к дискорду и к аккаунту https://app.rs.school/

3) Перешел в дискорде в пункт "Pre-school - announsments" и перешел в сообщение: "Что делать до старта курса:" перешел на 
    страницу указаную как: 
    " 1. проверить записаны ли вы на курс 
    https://app.rs.school/course/score?course=js-fe-preschool 
    если нет, записаться 
    https://app.rs.school/registry/student?course=js-fe-preschool "

4)И увидел сообщение как на первой странице, так и на второй такого вида:
![image](https://user-images.githubusercontent.com/101456317/158028399-9fe0d901-8a35-4b99-993b-c146250c162f.png)
![image](https://user-images.githubusercontent.com/101456317/158028406-488406cb-1d29-4b03-96d1-b082008f44e4.png)

П.С: При этом доступ к расписанию курса у меня есть:
![image](https://user-images.githubusercontent.com/101456317/158028626-c4a57c33-5b48-42f3-bb7f-860561a9b179.png)

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

- OS: [e.g. iOS] Windows 7
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] Версия 99.0.4844.51 

**Additional context**

**Comment by dzmitry-varabei** [comment]
@07Spirit вот правильные ссылки
---------
Что делать до старта курса: 

1. проверить записаны ли вы на курс https://app.rs.school/course/score?course=js-fe-2022Q1 если нет, записаться https://app.rs.school/registry/student?course=js-fe-2022Q1

**Comment by 07Spirit** [comment]
Спасибо.
