### ISSUE TITLE
Incorrect dropdown list placement

### ISSUE THREAD

**Issue by karpinskaya** [rolling-scopes/rsschool-app#1297]
1. Go to https://app.rs.school/
2. Go to Schedule
3. Click on top left Settings icon in table header
4. Dropdown list is displayed offscreen

- OS: Windows
- Browser: Chrome
- Version: 99.0.4844.51 (Official Build) (64-bit)
<img width="654" alt="Screenshot" src="https://user-images.githubusercontent.com/39993454/158233331-95683c0b-fb04-4e26-869d-00979deb37b9.png">

**Comment by dzmitry-varabei** [comment]
@karpinskaya спасибо! поправили!
