### ISSUE TITLE
Ошибка меню сортировки в приложении.

### ISSUE THREAD

**Issue by dnavarich** [rolling-scopes/rsschool-app#1298]
Прошу исправить ошибку вызова меню сортировки https://app.rs.school/course/schedule?course=js-fe-2022Q1 в табличном виде. При нажатии на шестеренку меню вызывается вне активного окна.
![unknown](https://user-images.githubusercontent.com/89609232/158250004-da346e8e-46b6-42f5-a806-ac00a0ed6f5b.png)

Операционная система Windows 10. Используемый браузер Google Chrome последней версии.
![unknown](https://user-images.githubusercontent.com/89609232/158249886-7b45dd4d-46b3-4f09-a082-ee878f4b8496.png)

**Comment by nupaT** [comment]
Поддерживаю. Окно получает по-умолчанию позицию left: -235pх
![1](https://user-images.githubusercontent.com/47768237/158252684-68aab655-b060-4266-9711-7a0f3e581ba4.PNG)

**Comment by aaliakseyenka** [comment]
fixed, credits to @Kreezag
