### ISSUE TITLE
After applying sorting on the page "Score" pagination is reset

### ISSUE THREAD

**Issue by Angelina-Kamyshova** [rolling-scopes/rsschool-app#130]
**After applying sorting on the page "Score" pagination is reset**

1. Authorize in https://app.rs.school
2. After redirect click on "Score" link
3. On the "Score" page at bottom of the page choose any number of page (except of 1st) in the pagination panel
4. Then scroll up the page and click on any column (for example, "Name") for sorting

**Expected result:** Sorting is applied, selected results changed, there is still the page selected at step 3
**Actual result:** Sorting is applied, but the pagination is reset to the 1st page

**Additional info.:**
No screenshot needed
OS: Windows 7 professional
Browser: Chrome 
Version: 76.0.3809.132

_Not functional but usability for sure_

**Comment by dzmitry-varabei** [comment]
@Angelina-Kamyshova It's not a bug, it's a feature
