### ISSUE TITLE
RSS TEST. возможно неверная обработка. 

### ISSUE THREAD

**Issue by AlexKhvostov** [rolling-scopes/rsschool-app#1317]
При прохождении RSS теста все вопросы были тщательно изучены.
отчеты на них найдены или в документах или в гите. но всеравно 97%. есть подозрение что какой-то вопрос не правильно обрабатывается. 

возможно вопрос с  временем обновления данных  в Score. раньше это было полночь. сейчас это 4 часа ночи по минску. 
в доке написано 4 и в Skore написано 4:00 GMT +3.

или как подсказывают люди в discord .
что я ошибся в вопросе объективности оценки при проверке Cross-check. 
однако в самих доках написано что один из недостатков такой системы : 
"оценивание работ не всегда бывает объективным". 
Поэтому я и не выбрал его.

**Comment by helenakrasnova** [comment]
Привет! 

- Обновление score по времени в 4:00 (GMT+3) работает уже несколько курсов, в этом ошибки нет. 
- Оценивание работ не всегда бывает объективным, но каждый студент должен ставить своей целью проверить честно и объективно, в этом ответе нет противоречия
