### ISSUE TITLE
Expression-calculator task: score bug

### ISSUE THREAD

**Issue by ieopvl** [rolling-scopes/rsschool-app#132]
Points add in score incorrectly, in despite of all tests passed score is 99.

Screenshot app.rss verification - https://imgur.com/a/tvtL51r
Screenshot from vscode - https://imgur.com/a/kumiJXQ

**Comment by apalchys** [comment]
@ieopvl as I see, it seems you've been able to fix the test, right? Could you please describe what was the issue?

**Comment by ieopvl** [comment]
Test was fixed by task’s author. Now it works correctly.


Отправлено из мобильной Почты Mail.ru


воскресенье, 29 сентября 2019 г., 20:33 +0300 от notifications@github.com  <notifications@github.com>:
