### ISSUE TITLE
Greeting. I've registered on Frond end course on English, but in docs it still shows everything in russian language

### ISSUE THREAD

**Issue by slomtadze** [rolling-scopes/rsschool-app#1321]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

**Additional context**

**Comment by dzmitry-varabei** [comment]
@slomtadze The curriculum & docs are here - https://github.com/rolling-scopes-school/js-fe-course-en
In you need more information, please join our Discord server https://discord.com/invite/xpw7V5bEsy
