### ISSUE TITLE
Ошибка 405 при попытке регистрации на курс

### ISSUE THREAD

**Issue by Sarantail** [rolling-scopes/rsschool-app#1331]
**Describe the bug**
Ошибка 405 при попытке отправки данных на уже начавшийся курс 2022Q1 JavaScript/Front-end Stage#1.

**To Reproduce**

1. Зайти на регистрацию курса: https://app.rs.school/registry/student?course=js-fe-2022Q1
3. Ввести данные в соответствии с правилами анкеты
4. Нажать на кнопку "Submit"
5. Увидеть ошибку "An error occurred. Please try later."

**Expected behavior**
После введения данных и нажатии на кнопку отправки, должна была произойти регистрация на курс. 

**Screenshots**
![HPeS2niJ7cQ](https://user-images.githubusercontent.com/102371972/160193729-a2d60ded-2d18-4fda-b903-9aad4d65dafe.jpg)

**Device (please complete the following information):**

- OS: [Windows 10]
- Browser [chrome]

**Comment by apalchys** [comment]
Fixed
