### ISSUE TITLE
Ошибка Auto-Test JavaScript/Front-end 2022Q1 "Js Scope & Function Test"

### ISSUE THREAD

**Issue by OlyaPolya** [rolling-scopes/rsschool-app#1342]
Здравствуйте.
Я думаю, что в Авто-тесте https://app.rs.school/course/student/auto-test?course=js-fe-2022Q1  в задании  "Js Scope & Function Test" содержится ошибка в ответе - не хватает знаков препинания.
В задании написано следующее: console.log(`hello, ${this.name}!`); , т.е. содержится запятая и восклицательный знак. И эти знаки препинания отсутствуют в ответе. Т.о. сейчас нет верного ответа.

Скриншот на задание прилагаю 
![2022-03-29_17-27-18](https://user-images.githubusercontent.com/83548013/160592930-88e00cde-0d68-4929-8717-e50b71ac4dd8.png)

**Comment by helenakrasnova** [comment]
@OlyaPolya исправлено, спасибо
