### ISSUE TITLE
Bug in tests

### ISSUE THREAD

**Issue by Zhenya235** [rolling-scopes/rsschool-app#1346]
**Describe the bug**

Before submitting the JS Basics [RU] test, everything was fine and gave 4 attempts per test. After sending, 1 attempt was left behind in absolutely all tasks

**To Reproduce**

1. Go to '[Auto-Test]'
2. Click on 'JS Basics [RU]'
3. Scroll down to 'submit'

**Expected behavior**
decrease the number of attempts by 1 only in the JS Basics [EN] test

**Screenshots**

**Device (please complete the following information):**

- OS: [windows 11]
- Browser [Yandex]
- Version []

**Additional context**
![БАГ](https://user-images.githubusercontent.com/101385048/160771923-b03c449a-1cc6-4ea3-88f8-941cc3503af9.png)

**Comment by dzmitry-varabei** [comment]
@Zhenya235 fixed. Please check again
