### ISSUE TITLE
Тест JS Basics после прохождения незасчитался

### ISSUE THREAD

**Issue by Vladimir-Shabalin** [rolling-scopes/rsschool-app#1347]
**Course**
Specify your course (e.g. rs-2019-q1)

**What is wrong**
Describe data issue

Добрый день! Сегодня 30.03.22 проходил тест JS Basics. По окончанию нажал на submyt, меня перекинуло на страничку с тестами а результата не выдало. Как будто я не проходил его. Попыток осталось 2
![Безымянный](https://user-images.githubusercontent.com/101561964/160808911-3551dd56-621e-4580-9713-1b061d169991.png)
.

**Comment by dzmitry-varabei** [comment]
@Vladimir-Shabalin Привет! Сабмитни тест еще разю
