### ISSUE TITLE
Возможность изменить количество студентов после регистрации но до старта менторинга

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#135]

**Comment by ekaterina-glazunova** [comment]
Привет! указывала, что возьму 2х, но могу взять 3х (2х укажу своих, и ещё одного возьму рандомного, лучше всего из Минска). Что нужно сделать для этого?)

**Comment by apalchys** [comment]
@ekaterina-glazunova больше ничего. все нужная информация указана

**Comment by mascazo** [comment]
Привет, я указал, что возьму четырех, но немного изменилась нагрузка на следующий квартал, смогу взять только трех. Заранее спасибо :)

**Comment by belashjack** [comment]
Когда заполнял форму то указал 4-ых не зная про правило 2+ студента. С учётом этого правила поставьте мне, пожалуйста, 3-их.

**Comment by olegkoleda** [comment]
Привет, в анкете указал что возьму 5х хочу изменить на 3их.

**Comment by SerafimovichEugene** [comment]
Привет, в анкете указывал 2х, но один мой товарищ просится ко мне. Можно мне изменить на 3х и добавить мне его https://github.com/lobanyov ?

**Comment by Vad199it** [comment]
Привет, можно мне добавить https://github.com/Ajololr ?

**Comment by stanislawa** [comment]
Добрый день, можно ли еще добавить одного студента себе?

**Comment by apalchys** [comment]
@stanislawa да конечно. Завтра добавим. 

(Если же есть предпочтение и хотелось бы менторить конкретного человека, напиши  мне в дискорд: apalchys)
