### ISSUE TITLE
Picture of the avatar in my profile does not match the githab

### ISSUE THREAD

**Issue by rallosa** [rolling-scopes/rsschool-app#1355]
**Describe the bug**
Picture of the avatar in my profile 
https://app.rs.school/profile
is different from the avatar picture in my profile at 
https://github.com/rallosa

**To Reproduce**
Assumption.

1. I registered and confirmed the github in app.rs.school a long time ago.
2. Then I changed my avatar to github.
3. The avatar in app.rs.school/profile has remained old and has not changed.

**Expected behavior**

**Screenshots**
https://snipboard.io/ov4NBy.jpg
https://github.com/rallosa

**Device (please complete the following information):**

- OS: [Windows 11]
- Browser [chrome]
- Version [99.0.4844.84 (Official Build) (64-bit)]

**Additional context**

**Comment by rallosa** [comment]
good

**Comment by apalchys** [comment]
@rallosa we cache avatars on our side for 1 week or so in order to prevent rate limiting on github side.
