### ISSUE TITLE
Help button behavior 

### ISSUE THREAD

**Issue by TattiMikhailava** [rolling-scopes/rsschool-app#1356]
**Uncorrect  button behavior**
Students find using of the Help button embarrassing. 

**To Reproduce**
The Help button in the header is assigned to open a content in the current tab and hides previous information for the user. 

1. Go to the header RS app
2. Click on the Help button
3. See error: helpful information is opened in the current tab.

**Expected behavior**
Assign this Help button to open a new tab showing a content. 

**Screenshots**
![help button behavior](https://user-images.githubusercontent.com/100757852/161720559-1ce043b2-a8c1-4ecc-aa14-8e720a38d0bf.png)

**Comment by valerydluski** [comment]
done
