### ISSUE TITLE
Cross-check: Review - Task statuses are calculated according to tasks submit deadlines, not cross-check deadlines

### ISSUE THREAD

**Issue by ThorsAngerVaNeT** [rolling-scopes/rsschool-app#1371]
**Describe the bug**
JS/FE 2022Q1 Course. `Cross-check: Review` for task `Shelter. Desktop` started today and status in Select is `Expired`, because status is calculated according to task submit deadline, not cross-check deadline.

**To Reproduce**

1. Go to '[Cross-Check: Review](https://app.rs.school/course/student/cross-check-review?course=js-fe-2022Q1)'
2. Click on 'Task'
3. Scroll down to 'Expired' section

**Expected behavior**
Task statuses at `Cross-check: Review` should be calculated according to cross-check deadlines.

**Screenshots**
![image](https://user-images.githubusercontent.com/17920285/162980621-9cf1643b-46a3-47d9-a676-20ba332826a0.png)

**Comment by dzmitry-varabei** [comment]
Dublicate: https://github.com/rolling-scopes-school/tasks/issues/690

**Comment by apalchys** [comment]
Fixed
