### ISSUE TITLE
New "Your stats" widget

### ISSUE THREAD

**Issue by ktnktag** [rolling-scopes/rsschool-app#1375]
**New "Your stats" widget**
Widget design changes.

Additional changes:
1. Remove the "status"
2. Add a line with the amount of% required to obtain a certificate

Figma [file ](https://www.figma.com/file/D3O7GJzjlG38YLh8FpmetI/RS-Design?node-id=121%3A11246)

**Additional context**
Since students do not understand what speedometers indicator shows, it serves as a decorative element. 
It also turned out that it is important for a student to see the current % - necessary to obtain a certificate
<img width="1135" alt="Frame 156" src="https://user-images.githubusercontent.com/101800066/163128744-d1f539b0-99b0-43ef-9ae5-1dbc397ebc0b.png">

**Comment by I-vasilich-I** [comment]
Is it ready to implement or it's still on approval stage?

**Comment by ktnktag** [comment]
Agreed with Dima, ready to implement

**Comment by I-vasilich-I** [comment]
On position what total students count should be displayed: all or  only active? (80 / 5187)

**Comment by ktnktag** [comment]
Your popsition / active students

**Comment by ktnktag** [comment]
@I-vasilich-I in release missed info about necessary % to receive certificate

**Comment by I-vasilich-I** [comment]
> @I-vasilich-I in release missed info about necessary % to receive certificate

@ktnktag I haven't missed it, @apalchys insisted that this info shouldn't be there:

> Sorry, I think it's better to remove right now. % and condition to get certificate are unique per course. There are no any formal rules right now and 70% could lead to confusion for example for ios courses or others.

**Comment by I-vasilich-I** [comment]
@ktnktag how about adding icon in front of `Your stats` like on all other widgets?

![Screenshot from 2022-06-08 13-16-12](https://user-images.githubusercontent.com/67139199/172592771-faf56418-ee4e-4c40-a40d-d0e5c4f8a278.png)

**Comment by ktnktag** [comment]
@I-vasilich-I Hello, 
We discussed it and decided to remove icons from all wigets 
If it not take a lot of time, can you remove them from others?

**Comment by I-vasilich-I** [comment]
sure

**Comment by I-vasilich-I** [comment]
@ktnktag I think this issue could be closed
