### ISSUE TITLE
Email: confirmation link

### ISSUE THREAD

**Issue by I-vasilich-I** [rolling-scopes/rsschool-app#1377]
**Describe the bug**
Email confirmation link came as a plane text(not clickable). What strange is that email contains a clickable link for Unsubscribe.

**Expected behavior**
Should be a real link (clickable)

**Screenshots**
![Screenshot from 2022-04-16 08-59-10](https://user-images.githubusercontent.com/67139199/163663869-be1fe5fd-4bf7-4a9d-a280-d703bfd1e609.jpg)

**Comment by aaliakseyenka** [comment]
@I-vasilich-I plz provide your OS and email client name(version)

**Comment by I-vasilich-I** [comment]
> @I-vasilich-I plz provide your OS and email client name(version)

OS: Ubuntu 20.04.4 LTS
email client: Thunderbird 91.7.0 (64-bit)

**Comment by I-vasilich-I** [comment]
Just checked same mail directly on google mail -> link is clickable there, so I guess the problem is with my email client or maybe google mail just is smart enough to recognize that it's a link and makes it a link.

**Comment by aaliakseyenka** [comment]
should be fixed now. @I-vasilich-I, thanks.
