### ISSUE TITLE
Schedule: show cross-check deadline

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#1378]
<img width="843" alt="image" src="https://user-images.githubusercontent.com/2429680/163681866-90ca1026-7005-4c18-bbc4-451ac0e93489.png">

**Comment by WiiJoy** [comment]
С учетом последних изменений в UI Schedule видится подобное отображение:

<img width="1665" alt="Снимок экрана 2022-05-19 в 13 50 36" src="https://user-images.githubusercontent.com/73646765/169277136-76a8675b-fea8-4917-8c95-98275f6671cf.png">

По умолчанию эти даты могут быть вычисляемыми значениями (старт сразу после дедлайна сабмита + дедлайн кросс-чека ночью с четверга на пятницу - 02.59 по Мск)

**Comment by oibioib** [comment]
Хочу внести предложение с позиции студента.
Удобно, если бы дедлайн по кросс-чеку, да и по автотестам отображалась в самом таске, например как на сриншоте. Тогда четко понимаешь, когда, а не ищешь в документации, анонсах, переспрашиваешь в чате.
![2022-06-16_090042](https://user-images.githubusercontent.com/103119318/174003743-975b00e1-d6a2-4797-8b30-8fd96794a3c5.jpg)
.
