### ISSUE TITLE
add links to github repo to app

### ISSUE THREAD

**Issue by Shastel** [rolling-scopes/rsschool-app#138]
It will be nice to add links to github of app somewhere (for example header) to have the ability to star repo or create issue 'directly' from the app

**Comment by sonejka** [comment]
Hi @Shastel ,
I've placed the link to GitHub repo in the footer (see section 'Join us'):
https://app.rs.school/
Please confirm if this matches your idea.

**Comment by Shastel** [comment]
Hi @sonejka,
Confirmed
