### ISSUE TITLE
Git quiz question misprint

### ISSUE THREAD

**Issue by MaksimRachkov** [rolling-scopes/rsschool-app#1383]
**Course**
JS/FE Course EN 2022

**What is wrong**
There is "**You** is the difference between git branch -d and git branch -D?" instead of "**What** is the difference between git branch -d and git branch -D?"

![git-quiz-issue](https://user-images.githubusercontent.com/101507791/163734230-ab156adc-8eb4-475e-a0d4-8c3d7ac25d4e.png)

**Comment by helenakrasnova** [comment]
исправлено
