### ISSUE TITLE
JS-FE-EN-2022| Test score issue

### ISSUE THREAD

**Issue by Anik188** [rolling-scopes/rsschool-app#1385]
Студент (https://app.rs.school/profile?githubId=kriss1s) получил за тест 130 баллов из 100 возможных
![image](https://user-images.githubusercontent.com/8234670/164234309-04dbcf9c-a367-4d02-897d-c783270059b4.png)

**Comment by apalchys** [comment]
@Anik188 I can't find the reason of this bug. I suggest to close and re-open if it occurs again.

**Comment by valerydluski** [comment]
reproduce 
student github - 238samixd
course - [js-fe-en-2022q3](https://app.rs.school/course/score?course=js-fe-en-2022q3)

**Comment by dzmitry-varabei** [comment]
fixed
