### ISSUE TITLE
Weight column of student's schedule table 

### ISSUE THREAD

**Issue by TattiMikhailava** [rolling-scopes/rsschool-app#1391]
**Weight column**
Students expect to see weight score in the schedule table. 

![Score Max](https://user-images.githubusercontent.com/100757852/165081122-6d34dd04-2f5d-489c-b43c-4c41499c6891.png)

**There isn't any information about weight in the schedule.**
Add the Weight column between Organizer column and Score / max column. 
Use Multiplication sign × (symbol’s code 00D7 by Unicode). 
 
![Weight](https://user-images.githubusercontent.com/100757852/165081369-c5c5632e-deb6-4bde-a07c-e59107f4379c.png)

Figma [file](https://www.figma.com/file/k9nxoLz5Vg19fRmEt8MB0V/Weight-column-Schedule-RS-app?node-id=2%3A10) for developing.

**Comment by TattiMikhailava** [comment]
Displaying weight in inside a column cell in small text isn't informative and clear. 
Create a standalone column for a score weight.

**Comment by MemoS77** [comment]
стиль изменить не проблема, но лишний столбец, считаю тут не нужен.
