### ISSUE TITLE
Special column in the table settings   

### ISSUE THREAD

**Issue by TattiMikhailava** [rolling-scopes/rsschool-app#1398]
**Column Special of the Table settings**
The column Special should be deleted of the table, so change the Drawer of the table settings. 
![Special column table settings](https://user-images.githubusercontent.com/100757852/165926599-97c8b9b9-24a5-47ca-a537-5bdab2b3c6d6.png)

**Delete this item Special of the checkbox group.**

**Comment by apalchys** [comment]
Removed.
