### ISSUE TITLE
User testing: Notifications 

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#1402]

**Comment by OlyaPolya** [comment]
Добрый день.
Хотела настроить себе нотификацию на email, но не могу пройти верификацию, т.к. не приходит подтверждающее письмо. Спам проверяла - там пусто. Моя почта polyanskaya3000@gmail.com

**Comment by WiiJoy** [comment]
Надеюсь, я не перепутал ботов (это ведь относится к телегроммоботу с нотификациями?) :)

1. Если событие по нескольким таскам - приходит N число одинаковых сообщений, где N - количество тасков.  
Нужно чтобы либо приходило одно сообщение на все таски, либо каждый таск отдельным сообщением.
<img width="708" alt="Снимок экрана 2022-04-30 в 19 48 05" src="https://user-images.githubusercontent.com/73646765/166114825-a1443d60-7172-49d7-a5ea-1057ef4b35bc.png">

2. Сообщения об апдейте расписания крайне неинформативны. Было бы хорошо получать в этих сообщениях чуть более конкретику о том, что в итоге поменялось
<img width="700" alt="Снимок экрана 2022-04-30 в 19 51 44" src="https://user-images.githubusercontent.com/73646765/166114918-993b48c5-2c30-40a6-8106-320e220fd8c4.png">

**Comment by aaliakseyenka** [comment]
1) должно быть исправлено.
2) по апдейтам расписания создан таск https://github.com/rolling-scopes/rsschool-app/issues/1406
