### ISSUE TITLE
Score: Don't see  info at small screen

### ISSUE THREAD

**Issue by LGers** [rolling-scopes/rsschool-app#1420]
**Describe the bug**
don't see  info at small screen

**To Reproduce**

1. Go to  (https://app.rs.school/course/score?course=react-2022-q1)'
2. Resize your window

- OS: [win10]
- Browser [chrome]
![bug1](https://user-images.githubusercontent.com/87089817/167902604-10e3e00d-7d43-4258-bff3-5bd10010cd6c.png)

**Comment by I-vasilich-I** [comment]
I assume this issue reports the problem with min height of the table, when on small screens you can only see table header and footer, no info; 
![Screenshot from 2022-05-25 10-34-23](https://user-images.githubusercontent.com/67139199/170206850-a33a83e3-3ee9-4ada-9ad8-a379667b8447.png)

I also have found the problem with seen content on devices with width less than 400px: 
column Github is fixed, so the space left for info itself is tiny, especially on 320px width.
![Screenshot from 2022-05-25 10-33-25](https://user-images.githubusercontent.com/67139199/170206636-abcdb527-5a9c-42a8-983d-2d2427927851.png)
 
@apalchys 
I'd like to fix both issues by setting min-height: 200px(9-10 rows) on table, and unfix Github column on screens with width less then 400px, which would leave more space for visible info, row counter column still going to be fixed so user would be able to fix eyes on right row if wants;

**Comment by I-vasilich-I** [comment]
@apalchys this issue could be closed
