### ISSUE TITLE
Algorithmic Task: the second solution

### ISSUE THREAD

**Issue by me-am-i** [rolling-scopes/rsschool-app#143]
rs-2019-q3

1. Добавить возможность отправлять второй вариант решённого задания на проверку без уменьшения начисленных баллов. (или предлагать выбор при отправке)
Пример: задача решена примитивно, if-ми, но проходит все проверки. Читаю документацию, пробую возможности языка, переписываю функциями, теперь проходит меньше тестов. Если отправить вторым это решение, то баллы срежут. То есть меньше мотивации разбираться и писать красивый код.

2. Сменить статус Planned на актуальный 
![screenshot](https://user-images.githubusercontent.com/38408782/66088190-eca11680-e582-11e9-8359-db4452b6965c.png)

**Comment by dzmitry-varabei** [comment]
@me-am-i 
Спасибо за предложение!
1) В ближайшее время мы не планируем поддерживать два вариант решения одной задачи. 
2) Статус сменили на актуальный
