### ISSUE TITLE
Возможность найти пользователя по telegram аккаунту

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#144]

**Comment by dzmitry-varabei** [comment]
@apalchys огромное спасибо! это была очень нужная фича

**Comment by apalchys** [comment]
@dzmitry-varabei это спасибо @anastasiaprivalova. Она реализовывала эту фичу.

**Comment by dzmitry-varabei** [comment]
@anastasiaprivalova Настя, спасибо за твой вклад в разработку RSApp и менторинг студентов!
