### ISSUE TITLE
Header/Ukraine support

### ISSUE THREAD

**Issue by ktnktag** [rolling-scopes/rsschool-app#1443]
**Vector flag with text**
Because the text floats below its place, it was decided to make vector text and make it part of the image.

**NB. Don't forget about header shadow**
Figma file [here](https://www.figma.com/file/D31S4jMK4EQfnpvguVjc8W/RS-Redesign_Ant-design?node-id=129222%3A206987).
![Снимок](https://user-images.githubusercontent.com/101800066/169656811-134fcf2c-a4f0-4436-96d9-af6cbcd584d7.PNG)

**Comment by dzmitry-varabei** [comment]
@valerydluski текст исчез :(
<img width="429" alt="image" src="https://user-images.githubusercontent.com/2429680/170242989-614666ec-b14e-4a4a-a87c-284ddf788933.png">

**Comment by valerydluski** [comment]
fixed
