### ISSUE TITLE
Task grade received notifications got lost

### ISSUE THREAD

**Issue by 022022** [rolling-scopes/rsschool-app#1456]
**Describe the bug**
Signed up for task grade notifications, all was well at the beginning, but  haven't received two latest task grade notifications, nothing at all. 

**To Reproduce**
n/a

**Expected behavior**
Task grade received

**Screenshots**
n/a

**Device (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by aaliakseyenka** [comment]
discord notifications for now are unavailable. Will add alert banner on the page
