### ISSUE TITLE
Wrong order in event list

### ISSUE THREAD

**Issue by ShkredovDmitriy** [rolling-scopes/rsschool-app#1457]
**Describe the bug**
Wrong order in event list

**To Reproduce**
1. Open - https://app.rs.school/
2. Select 2022Q2 - https://i.imgur.com/xoMhF4C.png
3. Click on dashboard - https://i.imgur.com/N5UUZMv.png
4. Select 5 events - https://i.imgur.com/vMn0TW3.png
7. See wrong order - https://i.imgur.com/azfIFKR.png

**Expected**
I expect CV1 to be displayed before CV2

**Screenshot**
https://i.imgur.com/9nwqFUR.png

**Device :**
- OS: [Ubuntu]
- Browser [Firefox]
- Version [100.0.2 64bit]

**Comment by mikhama** [comment]
Hi @ShkredovDmitriy!
FYI you can past images this way to Markdown:
`![](https://i.imgur.com/xoMhF4C.png)`
So it will be easier to read:

1. Select 2022Q2
![](https://i.imgur.com/xoMhF4C.png)

2. Click on dashboard
![](https://i.imgur.com/N5UUZMv.png)

3. Select 5 events
![](https://i.imgur.com/vMn0TW3.png)

4. See wrong order
![](https://i.imgur.com/azfIFKR.png)
___
**expected**
![](https://i.imgur.com/9nwqFUR.png)

**Comment by ShkredovDmitriy** [comment]
Works good now, thanks :)
