### ISSUE TITLE
Мobile version, fix layout.

### ISSUE THREAD

**Issue by seozdev** [rolling-scopes/rsschool-app#1459]
In the mobile version, the names of tasks are floating

**Screenshots**
https://i.gyazo.com/bde5453fc66e22ed530e1d6710ebba6b.png

**Device (please complete the following information):**

- OS: ios
- Browser Chrone
- Device - Iphone 11 pro max

**Comment by valerydluski** [comment]
this schedule mode will be deprecate 
https://github.com/rolling-scopes/rsschool-app/issues/1543
