### ISSUE TITLE
I find a mistake in test

### ISSUE THREAD

**Issue by ShkredovDmitriy** [rolling-scopes/rsschool-app#1461]
**Course**
front-end-2022q1

**What is wrong**
Auto-Test > Test Git  & GitHub #2
Screenshot: https://i.imgur.com/dK5BtQV.png
Mistake: "git fetch AMD git pull"

**Comment by dzmitry-varabei** [comment]
@ShkredovDmitriy спасибо!
@helenakrasnova поправь пожалуйста опечатку в тесте

**Comment by helenakrasnova** [comment]
исправлено
