### ISSUE TITLE
Score: incorrect calculation of the position in the rating

### ISSUE THREAD

**Issue by Andrean-82** [rolling-scopes/rsschool-app#1462]
Incorrect calculation of the position in the rating. The student's position counts for all students on the course. This includes students who are expelled. I think this is not correct. A student who has remained on the course may not be invited by the mentor because his/her rating will not be sufficient for the interview. 
It is necessary to remove students who have been expelled from the rating calculation. 

https://gyazo.com/8489d824a77e083d2c3f093933cd1a64

**Comment by apalchys** [comment]
Student may leave the course but we still keep information about it and this info could be used in the future for CV or anything similar. Calculating position for non-active student should not affect active students in any case. Please let me know if you see scenario where it could be an issue
