### ISSUE TITLE
Вышел с курса, но хочу вернуться(обстоятельства)

### ISSUE THREAD

**Issue by AleksandrKochalko** [rolling-scopes/rsschool-app#1463]
Здравствуйте! Нажал выйти из курса, потому что поменял имя пользователя, там целая конетель была, зашел проверить все ли впорядке с моим гитом на курсе, она перенаправляла меня на 404, ну я и вышел, чтобы заново зайти с новым именем на гите, а сейчас не знаю, что делать дальшеВышел с курса, но хочу вернуться(обстоятельства)

**Comment by dzmitry-varabei** [comment]
@AleksandrKochalko вернули
