### ISSUE TITLE
in CV can't select taken courses

### ISSUE THREAD

**Issue by AliaxeiSehiyenia** [rolling-scopes/rsschool-app#1464]
**Describe the bug**
I can't select taken courses on the CV edit page

**To Reproduce**

1. Go to in my profile https://app.rs.school/profile?AliaxeiSehiyenia
2. Click on 'my CV'
3. Scroll down to choose courses
4. No courses to show

**Expected behavior**
I have some courses and 2 certificates

**Screenshots**
![image](https://user-images.githubusercontent.com/37799096/170865919-21604c18-4975-45ee-8b82-d9c0775fc8eb.png)

**Device: in laptop HP ProBook 470 G3. Processor: Intel(R) Core(TM) i7-6500 CPU @ 2.50GHz 2.59GHz.  Installed RAM 8.00 GB. System type 64-bit operation system**

- OS: [Windows 10 Education Version 20H2 Installed on 1/24/2022]
- Browser [chrome]
- Version [Version 102.0.5005.61 (Official Build) (64-bit)]

**Additional context**
![image](https://user-images.githubusercontent.com/37799096/170866453-ef394914-b5d8-4243-b110-f2632712678e.png)

**Comment by dzmitry-varabei** [comment]
<img width="843" alt="image" src="https://user-images.githubusercontent.com/2429680/171445627-0379ce7d-3e05-47b3-8467-4782c22e8ea1.png">
@AlreadyBored Максим, глянь плиз это issue, много жалоб в последнее время, и сегодня снова вспоминали
