### ISSUE TITLE
UX: RS APP Tests Refactoring

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#1471]
1) Show incorrect answers after the test deadline
2) ...

**Comment by IvanSpN** [comment]
Предлагаю добавить возможность после прохождения тестов увидеть свои ошибки? Объясню почему мне так кажется и в каких случаях. Например человек сдал тест на 70%, соответственно он достойно подготовился и прикладывал усилия, что подтверждается его баллами, да не 90, но 70 тоже норм как мне кажется, и следовательно такой человек хотел бы приложить еще усилия в тех моментах где ошибся или не понял какие то моменты. Потому как главная цель курсов это получить знания, проводить работу над ошибками в случае необходимости, а не просто радоваться высоким оценкам. А к примеру если набрал только 20% понятно, что знания совсем слабые и будет полезно весь тест про решать  снова и как только дошел к примеру до 70% у тебя есть возможность восполнить пробелы для более качественного изучения материала (когда видишь хотя бы где ошибки, не нужно даже давать правильные ответы, просто подсветить ошибочные.
