### ISSUE TITLE
Schedule: End date for self-study in the schedule 

### ISSUE THREAD

**Issue by TattiMikhailava** [rolling-scopes/rsschool-app#1478]
**Current value of the table cell End date for self-study is incorrect.**  
Start date and End date are equel in the schedule.

**Assign** new End date for self-study in 7 days period beginning Start date. 

![Start date self-study](https://user-images.githubusercontent.com/100757852/171813728-8d803d2f-8518-4f77-b881-7670030a324c.png)

**Comment by dzmitry-varabei** [comment]
@mikhama 
1) Please add possibility to set EndDate for the Events.
2) Please deprecate duration field.
<img width="633" alt="image" src="https://user-images.githubusercontent.com/2429680/173844351-b36eac77-4b7a-474b-b451-745e0d852116.png">

**Comment by dzmitry-varabei** [comment]
Same for the https://app.rs.school/course/admin/events?course=js-fe-preschool-2022q2 page 
<img width="494" alt="image" src="https://user-images.githubusercontent.com/2429680/173844626-4df15199-43a1-4132-b92e-d403cb8a0bd3.png">
