### ISSUE TITLE
 unauthorized access

### ISSUE THREAD

**Issue by cruecer** [rolling-scopes/rsschool-app#148]
getting  unauthorized access with React Development Tool

1. Open the app as unregistered as a mentor or student user
2. Open react development tool
3. Make changes as in the picture
![image](https://user-images.githubusercontent.com/25794013/66204423-7cde7900-e6b3-11e9-84ea-472681d4b53b.png)
4. Get access

 - OS: windows 10
 - Browser: chrome

**Comment by apalchys** [comment]
@cruecer have you been able to view any date using this approach?

**Comment by cruecer** [comment]
![image](https://user-images.githubusercontent.com/25794013/66204955-d2ffec00-e6b4-11e9-96c7-6d1678eee634.png)
all link work

**Comment by cruecer** [comment]
i`m not sure that it is possible to change something, but to see something...

**Comment by apalchys** [comment]
@cruecer i made a fix which improves security a little bit.
could you please try view any data which you don't have access to or try to change something. Don't afraid to break anything.
Yes, you can see all links - it's fine because it's JavaScript and browser only. But you shouldn't be able to view unauthorized data. 
Thanks for making RS App better.

**Comment by cruecer** [comment]
can download a schedule.
![image](https://user-images.githubusercontent.com/25794013/66207447-7bb14a00-e6bb-11e9-8822-ecfa129ab56e.png)

**Comment by cruecer** [comment]
able to search people
![image](https://user-images.githubusercontent.com/25794013/66208999-2bd48200-e6bf-11e9-8837-b8eb481491e6.png)

**Comment by apalchys** [comment]
@cruecer 

>can download a schedule.
Thanks. Fixed.

>able to search people
It's a feature available to everyone via user search inputs (e.g. https://app.rs.school/private-feedback). We will think how to improve it.
