### ISSUE TITLE
Failed to validate HTML. (Status: Validator returned unexpected statuscode: 522)

### ISSUE THREAD

**Issue by IrynaGlytsko** [rolling-scopes/rsschool-app#1483]
При отправке через Auto-Test задания CV#2. HTML, CSS & Git Basics на проверку появляется такая ошибка   -   Failed to validate HTML. (Status: Validator returned unexpected statuscode: 522)
![image](https://user-images.githubusercontent.com/82415832/171860407-88f0cce5-b000-459d-990c-9972f43eacbb.png)
Помогите пожалуйста разобраться!

**Comment by dzmitry-varabei** [comment]
@IrynaGlytsko Спасибо! Готово

**Comment by IrynaGlytsko** [comment]
Все работает отлично! Большое спасибо)
