### ISSUE TITLE
Nickname search in Score does not work

### ISSUE THREAD

**Issue by Romnasi** [rolling-scopes/rsschool-app#1487]
**Describe the bug**

**To Reproduce**

1. Go to [score page](https://app.rs.school/course/score?course=react-2022-q1)
2. Click on search bar
3. Input random name
4. Click 'search'
5. See error

**Expected behavior**

**Screencast**
http://skrinshoter.ru/v/040622/rSkHBdZi

**Device (please complete the following information):**

- OS: Windows 10* 64-bit
- Browser chrome
- Version 102

**Comment by apalchys** [comment]
Fixed
