### ISSUE TITLE
Time zones in the schedule settings.

### ISSUE THREAD

**Issue by Bumble-sakh** [rolling-scopes/rsschool-app#1489]
Previously, you could select any time zone in the schedule settings.
Now only a few options are fixed.

![image](https://user-images.githubusercontent.com/71071594/172041766-99cb7be0-5003-4738-a7db-e6b24fcd3909.png)

**Comment by mikhama** [comment]
I can make it like this
![image](https://user-images.githubusercontent.com/3992761/174809599-493c0d55-8f77-477f-81b3-06557e7b7466.png)

But I'm not sure It's better than fixed amount of the timezones
