### ISSUE TITLE
Task submit

### ISSUE THREAD

**Issue by MitskevichVS** [rolling-scopes/rsschool-app#149]
**Course**
rs-2019-q1

**What is wrong**
Can't submit task Doubly Linked List, after submit form nothing happens, Tasks Verifications status not update

**Comment by apalchys** [comment]
@MitskevichVS rs-2019-q1 is completed already. I hope you meant rs-2019-q3 ?

**Comment by apalchys** [comment]
@MitskevichVS я проверил. Твое решение «зависает» и не успевает пройти тесты за 60 секунд. Проверь пожалуйста еще раз локально и желательно используя nodejs 10 версию

**Comment by MitskevichVS** [comment]
ок, попробую
