### ISSUE TITLE
Help: Not able to register course

### ISSUE THREAD

**Issue by Rayyona03** [rolling-scopes/rsschool-app#1491]
Stage 0 JS
The wanted course is JS/FE Pre-School 2022Q2

I want to register for the course JS/FE Pre-School 2022Q2 but accidentally registered for another course and made everything inactive. How can I register for the course written above? 

Sincerely,
Rayyona Abdurashidova

**Comment by apalchys** [comment]
@Rayyona03 try this link https://app.rs.school/registry/student

**Comment by valerydluski** [comment]
can be closed
