### ISSUE TITLE
Dashboard & Score table bug (Node.JS course) 

### ISSUE THREAD

**Issue by I-vasilich-I** [rolling-scopes/rsschool-app#1493]
**Describe the bug**
I've assigned myself to Node.js course today, missed first task deadline, maybe it's related somehow;

- Dashboard (position 9999999):
![Screenshot from 2022-06-06 09-10-26](https://user-images.githubusercontent.com/67139199/172106052-10b4d35a-3bc4-475b-b68a-6505d085c512.png)

- Score table (almost all indexes are 1, few are 'New') : 
![Screenshot from 2022-06-06 09-18-34](https://user-images.githubusercontent.com/67139199/172106257-9af078d3-8dac-4fe2-b30a-ff5bb4c3128a.png)
![Screenshot from 2022-06-06 09-20-01](https://user-images.githubusercontent.com/67139199/172106334-b2ceef0c-2e52-4b31-a3d9-756f1c49836d.png)

UPDATE: just watched intro stream and saw that not only I have trouble with ids in score table.

- OS: [Ubuntu 20.04.4 LTS]
- Browser [google chrome]
- Version [102.0.5005.61 (Official Build) (64-bit)]

There're no problems on archived courses that I have access to

**Comment by I-vasilich-I** [comment]
@Pulya10c So 'New' is the proper way, got it. What about same number indexes for a lot of students? Looks like it related to function that calculates position, those students has the same total score, is it backend problem?

**Comment by I-vasilich-I** [comment]
On the second thought I don't see the way to set positions fairly when students have the same total score, yet having 50 people with position 1 is kind of weird.

**Comment by apalchys** [comment]
yes, it's weird but we decided to pick this approach because it doesn't demotivate students. Previously we had 1 position per 1 student and as you said, it's not fair to students. So, we focus more on showing students where they are rather then trying to find the best of the best.

**Comment by I-vasilich-I** [comment]
ok then, I'll close this issue
