### ISSUE TITLE
Markdown & Git: Неверная оценка.

### ISSUE THREAD

**Issue by apalchys** [rolling-scopes/rsschool-app#150]
**Course**
rs-2019-q3

**What is wrong**
Неверно выставлена оценка.

**Comment by jetalai3** [comment]
https://prnt.sc/pfntd0

Файл в репозитории назван не README.md, а readme.md.
https://prnt.sc/pfnu61

**Comment by lobanyov** [comment]
Здравствуйте, придерживался гайдлайна по коммитам, ругается на реверт коммита, но что сделать, когда он был нужен...
1. Детали ошибки - https://ibb.co/3rxXrMk
2. коммиты в ветке - https://github.com/lobanyov/rsschool-cv/commits/gh-pages

**Comment by En-Murphy** [comment]
Здравствуйте! В деталях: Failed PR requirements: No Pull Request with task name (Markdown & Git). Pull-request  создан и название тоже присуствует -  https://github.com/En-Murphy/rsschool-cv/pull/1

**Comment by Aliaksandrsen** [comment]
Здравствуйте! 

Проблема:
Failed PR requirements: No Pull Request with task name (Markdown & Git)
![причина](https://user-images.githubusercontent.com/51503682/66274967-bc13f200-e88c-11e9-90be-55820e39ac85.png)

название присутствует:
![мое название](https://user-images.githubusercontent.com/51503682/66274975-d0f08580-e88c-11e9-9f93-2b2f33804691.png)
https://github.com/Aliaksandrsen/rsschool-cv/pull/1

если возникает сомнение по поводу добавки в конце руководствовался следующим
![почему](https://user-images.githubusercontent.com/51503682/66274991-06956e80-e88d-11e9-853a-5bb9a4850867.png)
probably additional info  -  было расценено мной как призыв что-то добавить
скрин отсюда:
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/codejam-cv.md

**Comment by BarikQ** [comment]
> Здравствуйте!
> 
> Проблема:
> Failed PR requirements: No Pull Request with task name (Markdown & Git)
> ![причина](https://user-images.githubusercontent.com/51503682/66274967-bc13f200-e88c-11e9-90be-55820e39ac85.png)
> 
> название присутствует:
> ![мое название](https://user-images.githubusercontent.com/51503682/66274975-d0f08580-e88c-11e9-9f93-2b2f33804691.png)
> [Aliaksandrsen/rsschool-cv#1](https://github.com/Aliaksandrsen/rsschool-cv/pull/1)
> 
> если возникает сомнение по поводу добавки в конце руководствовался следующим
> ![почему](https://user-images.githubusercontent.com/51503682/66274991-06956e80-e88d-11e9-853a-5bb9a4850867.png)
> probably additional info - было расценено мной как призыв что-то добавить
> скрин отсюда:
> https://github.com/rolling-scopes-school/tasks/blob/master/tasks/codejam-cv.md

ты ведь неправильно пр назвал

**Comment by kalinatimka** [comment]
Здравствуйте. Я сделал коммит с неправильным неймингом и запушил его в репозиторий, потом заметил и исправил, но предыдущий ко
![screen](https://user-images.githubusercontent.com/46251042/66275278-a7852900-e88f-11e9-95cf-062af7f311a5.jpg)
ммит остался в репе. Считается ли это за ошибку?

**Comment by dmitriy365377** [comment]
Добрый вечер,мне поставили 50 баллов,в задание было написано, что комментарии нужно писать в Present Simple, но я ошибся по своей невнимательности и написал первый комментарий в прошедшем времени,согласен была допущена ошибка,но остальные написал в P.S + правила по PR были мною соблюдены возможен ли пересмотр моего балла в сторону 75 баллов?)
Спасибо 👍 
![111](https://user-images.githubusercontent.com/51651226/66275262-86243d00-e88f-11e9-9729-09855e5b13d9.png)

**Comment by IgorBarbashov** [comment]
Добрый день!
При выставлении оценки за задание «Markdown & Git» оценка была снижена по причине:

> Failed commit requirements: Commits do no follow guideline -> ["html-css/feat: add main section" "html-css/feat: add CV header & footer" "markdown/feat: add code example" "markdown/feat: add all other sections" "markdown/feat: add name, contacts and summary sections" "markdown/feat: add cv.md file" "markdown/docs: add link to CV in README.md"]

Как я понимаю, в данном случае проверку не прошли префиксы в названии коммитов: «html-css/», «markdown/».

В то же время в официальной документации RS-school в разделе «Процесс обучения -> Stage#1 -> Требования к коммитам и Pull Request» (https://docs.rs.school/#/stage1) есть ссылка на страницу (https://github.com/rolling-scopes-school/lectures/blob/master/lectures/git.md)
на которой приведены следующие требования к commit'ам:
[скрин](https://drive.google.com/file/d/13mqPFnNd84hJIUAvEcykzLKIzA_H-y5o/view?usp=sharing)
Коммиты в моем задании соответствуют этим требованиям.

В итоге сложилась ситуация когда два официальных источника школы давали несколько различающуюся информацию при этом ни где не обозначив приоритета источника.

Принимая во внимание, что эти требования были найдены не где-то на сторонних ресурсах, а в официальной документации школы (необходимость следования пунктам которой неоднократно озвучивалось менторами и на знание которой проводился отдельный тест), просьба пересмотреть оценку за данное задание и выставить ее максимальной.

Заранее спасибо за ответ.

**Comment by bogdeebee** [comment]
Добрый день.

Вопрос по именованию PR.
Всего было 2 таска:

Markdown & Git (https://github.com/rolling-scopes-school/tasks/blob/master/tasks/git-markdown.md);
HTML, CSS & Git Basics (https://github.com/rolling-scopes-school/tasks/blob/master/tasks/codejam-cv.md).
Я именовала PR согласно каждому из тасков, но в первом из-за невнимательности написала название с маленькой буквы, а именно вместо "Markdown & Git" у меня "Markdown & git".

Причина оценки 50 и статус "Failed PR requirements: No Pull Request with task name (Markdown & Git)" в этом? И можно ли надеяться на то, что это будет засчитано как верное название?

Большое спасибо.

**Comment by Dmitryi-Lukyantsov** [comment]
Здравствуйте не прошел задание по причине: Failed task requirements: No CV at https://dmitryi-lukyantsov.github.io/rsschool-cv/cv
но репозиторий с CV есть, вот он: https://github.com/Dmitryi-Lukyantsov/rsshool-cv
это моя ошибка и я неправильно что-то сделал, или всеже проверяющего?
спасибо

**Comment by xfides** [comment]
Здравствуйте. 
1) 50 баллов по причине "Failed PR requirements: No Pull Request with task name (Markdown & Git)"
2) Вот мой pull request ( https://github.com/xfides/rsschool-cv/pull/1 )
3) Мое название  pull request "Create a markdown document ( "Markdown & Git" )" содержит необходимое название. Задача на английском - "PR name should contain the task name and probably additional info." 
а) Данная фраза была воспринята мною, что заголовок pull request -а должен содержать название задачи и дополнительную информацию, а не просто равен в точности посимвольно названию task-а.
б) Не указано что  вся дополнительная  информация должна идти в комментарии
в) В статье "How to write the perfect pull request" написана фраза "Include the purpose of this Pull Request". Что опять же подразумевает, что в заголовке PR лучше сразу указывать цель   pull request -а
4) Как вывод, просьба пересмотреть оценку в сторону максимальной. Спасибо.

**Comment by lmoroz** [comment]
Здравствуйте.

За задание стоит 0 с причиной: "Failed task requirements: No CV at https://lmoroz.github.io/rsschool-cv/cv"

Но репозиторий на месте ( https://github.com/lmoroz/rsschool-cv ) и cv по ссылке открывается

**Comment by Nikolay1984** [comment]
добрый день!
1.50 баллов по причине Failed commit requirements: Commits do no follow guideline -> ["Fead: add markup and styles\......................."]
2.У меня произошла небольшая опечатка в слове Fead(нужно Feat)! 
3.Я всего 10 месяцев плотно изучаю английский язык и у меня иногда случаются такие казусы!!!
4.Прошу не гневаться и молниями не бросаться, а войти в мое положение, пересмотреть мою ошибку - сделать правильный вывод и накинуть мне еще 50 балов!))))

**Comment by Rozitta** [comment]
Здравствуйте.

Получила 50 баллов по причине "Failed PR requirements: No Pull Request with task name (Markdown & Git)"
 Мой pull request (https://github.com/Rozitta/rsschool-cv/pull/1 )

Я так понимаю название  Pull Request должен был быть в кавычках,  а у меня без кавычек. Если кавычки все же не столь серьезная ошибка - прощу пересмотреть мою оценку. Или возможно причина была в другом? тогда прошу объяснить.

спасибо.

**Comment by MaxKuznecov89** [comment]
Здравствуйте!

1. Причина снятых баллов: "Failed commit requirements: Commits do no follow guideline -> ["doc: add index and css"]"
2. Репозиторий https://github.com/MaxKuznecov89/rsschool-cv
3. Видемо произошла опечатка при составлении коммита. Написал doc вместо docs. Я строго следовал гайду, но так как я новичок в Git технологии и только учусь, случайно опечатался. Прошу не наказывать строго, ведь задание выполнено и вернуть снятые баллы.

Спасибо.

**Comment by AlreadyBored** [comment]
За маркдаун выставлена оценка 50, в подробностях указано "Failed PR requirements: No Pull Request with task name (Markdown & Git)", однако, он есть.

**Comment by anthunderous** [comment]
Выставлена оценка 50 с описанием "Failed repository requirements: No cv.md file".
Но файл cv.md **присутствует** - [скрин](http://prntscr.com/pfs8x9).
Предполагаю, что дело в местоположении файла, который находится не в корне репозитория, а по адресу "rsschool-cv/cv/". Но тогда у меня возникает вопрос: какая логика у задания, которое предполагает, что нужно создать папку cv и положить туда только файл README.md, а сам файл cv.md по какой то причине не ложить в папку с **таким же** названием?

**Comment by ryntsevich** [comment]
Доброго дня!

Failed task requirements: No CV at https://ryntsevich.github.io/rsschool-cv/cv
0 баллов за задание. 

Изначально неверно был назван мой репозиторий(rsschool-2019Q3-cv). И, все ссылки формировались на основании этого названия. Но, они доступны. 
https://github.com/ryntsevich/rsschool-2019Q3-cv
https://ryntsevich.github.io/rsschool-2019Q3-cv/cv

Если, это критичная ошибка, но возможен пересмотр, я готова легко переименовать репозиторий.

**Comment by Margo24** [comment]
Доброго времени суток. Мне была выставлена оценка в 50 баллов по причине "Failed commit requirements: ....", при этом число коммитов больше 3х, и те, что указанные как ошибочные, написаны согласно требованиям гайдлайна. Так же их оформление не отличается от остальных коммитов моего репозитория и коммитов стобальников. Скрины прилагаются
image
image

Ссылка на репозиторий:
https://github.com/Margo24/rsschool-cv

**Comment by dragonKat24** [comment]
Здравствуйте!

Оценка за задание Markdown & Git: 50 (Failed repository requirements: No cv.md file)

[Этот файл](https://github.com/dragonKat24/rsschool-cv/blob/gh-pages/cv/cv.md) присутствует в папке `rsschool-cv/cv/cv.md`, ветка `gh-pages`.

В задании явно не сказано где должен находиться этот файл, но по-моему было правильным положить его в папку `rsschool-cv/cv`, т.к. в корне уже был свой `md` файл и название `cv.md` файла совпадает с названием папки, в которой он лежит - тоже хорошо.

**Comment by KarneyenkaDzmitry** [comment]
https://karneyenkadzmitry.github.io/rsschool-cv/  открывает нужный Readme.md как положено, Но вот далее не открывает /cv - хотябы подскажите, что именно я сделал не так как надо?

**Comment by fainz777** [comment]
Добрый день,
Получено за таск 5 балов с формулировкой:

Failed commit requirements: Commits do no follow guideline -> ["codejam-cv/feature: desktop layout" "codejam-cv/feature: mobile layout" "codejam-cv/feature: basic layout" "git-markdown/fix: heading fix" "git-markdown/feature: Add About me, Skills, Code examples, Education and Languages sections" "git-markdown/fix: headings fix" "git-markdown/feature: add personal information and contact info" "git-markdown/feature: add cv file with basic structure" "git-markdown/docs: add CV link" "git-markdown/files: add .gitignore"]
--

В одной из инструкций был совет давать наименования коммитам вида: название таска/тип коммита: описание

Подозреваю, что оно как рааз и не прошло проверку алгоритмом, просьба проверить.
Мой репозиторий - https://github.com/fainz777/rsschool-cv

Спасибо.

**Comment by apalchys** [comment]
Были обновлены оценки некоторым студентам. Основные причины для обновления:
- В задании не было указано в каком состоянии должен остаться PR, поэтому валидным на данный момент считается как Open так и Merged (Было только Open).
- Пункт из задания, что название PR должно содержать название таска, не указывало как именно называется задание и как должно быть указано. Поэтому на данный момент считается верным любой вариант написания названия.
- Один из студентов справедливо указал на расхождения в правилах между требованиям к коммитам в лекции Git Basics и задании. Это будет исправлено, но засчитались оба варианта.
- Опечатки в коммитах, наличие лишних символов (пробелов), случайные коммиты, увы, не являются причиной к пересмотру оценки.

Основная цель задания: обучиться базовой работе с Git и показать важность следования требованиям по оформлению. Отсюда строгие критерии для оценки (опечатка -> -50% баллов), но в то же время маленькие общие баллы за задание (максимум 10 баллов). В будущих заданиях, нарушение правил оформления будет ввести к намного более значительным потерям.

P.S.
@fainz777 "название таска/тип коммита: описание".  В любом случае, ваши типы не следуют типам из требований к заданию.
@KarneyenkaDzmitry сравните ваш репозиторий и бранч gh-pages, с репозиториями тех, кто получил 100

**Comment by fainz777** [comment]
@apalchys выше уже приводили ссылку на документацию, где использовался именно такой нейминг (https://github.com/rolling-scopes-school/lectures/blob/master/lectures/git.md)

**Comment by MihailStar** [comment]
Здравствуйте.
> 2019-10-06 21:23 | Markdown & Git | 50 | Failed repository requirements: No README.md file

Файл именован в нижнем регистре ([readme.md](https://github.com/MihailStar/rsschool-cv/blob/master/readme.md)). Возможно это обстоятельство приведет к пересмотру оценки.

**Comment by nixon2105** [comment]
Здравствуйте. Выставлена оценка 50 балов.
С учетом последних изменений: 
![1](https://user-images.githubusercontent.com/40052037/66299736-ccfc4c00-e8fc-11e9-8799-0e20d1f9d4c9.png)


Проблема:
Failed PR requirements: No Pull Request with task name (Markdown & Git)
![Безымянный](https://user-images.githubusercontent.com/40052037/66299260-d46f2580-e8fb-11e9-929a-8bee5af36ba4.png)
Название и Pull Request присутствуют

**Comment by ekater1na** [comment]
Здравствуйте!
 оя оценка за задание  снижена по следующей причине:
Failed commit requirements: **Commits do no follow guideline -> ["build: add README.md"]**
Если я правильно понимаю, снижение оценки произошло из-за слова "build". 
Но оно, в свою очередь, разрешено гайдлайном (https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional).

**Comment by SergeyCodeJs** [comment]
Доброе время суток.

Мне снизили оценку на 50 баллов по следующей причине: Failed commit requirements: Commits do no follow guideline -> ["Add cv.md file to gh-pages"].

Указанный программой неверный коммит - самый первый к таску (из 14 коммитов) он действительно был написан не по гайдлайну из-за опечатки (не указал feat: перед внесенными изменениями). В дальнейшем все остальные коммиты называл верно (https://github.com/SergeyCodeJs/rsschool-cv/commits/gh-pages - ссылка на страницу с коммитами).

![image](https://user-images.githubusercontent.com/53942885/66301382-100fec80-e908-11e9-8223-4ca72b7d6735.png)

Я понимаю, что с точки зрения компьютера это действительно серьезная ошибка и основание для снижения оценки на 50 баллов. Но с точки зрения человека понятно, что это опечатка, поскольку абсолютно все последующие коммиты (в большом количестве, в том числе и тот, который сделан в тот же день после создания неверно названного коммита) поименованы верно, и это свидетельствует о том, что я знаю и понимаю как называть коммиты правильно, соблюдаю гайдлайны.

Очень надеюсь на понимание, ведь если бы было заранее известно о том, что такая незначительная опечатка может привести к потере всего прогресса, я бы нашел способ внести исправления заранее.

С уважением, Сергей.

**Comment by alpy86** [comment]
Доброго дня! 
У меня оценка за задание Markdown & Git: 0  Failed task requirements: No CV at https://alpy86.github.io/rsschool-cv/cv
На момент сдачи задания и открытия pull-request файл cv.md находился в ветке gh-pages. 
https://github.com/alpy86/rsschool-cv/pull/1
Однако после решения задания HTML, CSS & Git Basics, я по ошибке удалил файл cv.md одновременно в ветках rsschool-cv-html и gh-pages:
https://github.com/alpy86/rsschool-cv/commit/95ab8b2d21e150441a773c95cb2b9675dc8087cc
После того, как мне не зачли задание и обнаружив эту досадную ошибку, я сделал возврат файла cv.md в ветку gh-pages. 
Просьба рассмотреть возможность начисления части баллов, с учетом того, что выполнялись требования задания и pull-request был открыт до дедлайна.

**Comment by PavelSashnikov** [comment]
Добрый день! В деталях к заданию комментарий  Failed PR requirements: No Pull Request with task name (Markdown & Git). По последним изменениям принимается любое имя, однако баллы не были изменены

**Comment by SvetlaZ** [comment]
Добрый день! 
Мне зачли 50 балов из 100. Основная проблема в "не следовании гайдлайнам при описании коммитов". 
У меня есть только 2 коммита, которые не соответствуют гайдлайну: 
1) Initial commit, который был создан гитом автоматически при создании репозитория и на что я никак не могла повлиять 
2) Update README.md commit, который также был сгенерирован гитом вместе с комментарием, тк модификация файла производилась не из под IDE с дальнейшим пушем, а непосредственно из интерфейса github. На что я, соответственно, также не могла повлиять. 

Все остальные коммиты следуют гайдлайнам на 100%. Потому прошу пересмотреть балл в пользу повышения, если это возможно.
Спасибо.

**Comment by YauhenDavidovich** [comment]
Добрый день, по невнимательности дал не строгое название для PR.  Баллы снижены с формулировкой: Failed PR requirements: No Pull Request with task name (Markdown & Git). С учетом последних изменений могу ли рассчитывать на пересмотр оценки?
Ссылка на PR https://github.com/YauhenDavidovich/rsschool-cv/pull/3

**Comment by NastyaKvachenok** [comment]
Добрый день. При работе с заданием была допущена ошибка в коммите и был сделан revert. Сообщение о реверт коммите было сформировано автоматически плюс мой комментарий. Прошу учесть revert коммиты и программе не учитывать их в принципе при выставлении оценки( ибо это откат до предыдущего состояния).

Failed commit requirements: Commits do no follow guideline -> ["Revert \"fix: fix displaying of spoiler\"\n\nThis reverts commit f358ffea5fc276812b09ca3f9ca7a1c2d1dc7291.\n\nSpoiler can't be displayed right way according this method."]

Гитхаб. https://github.com/NastyaKvachenok

**Comment by slolkunchik** [comment]
Доброго времени. 
Оформляла коммиты в соответствии с [требованиями, которые давались в материалах к лекции Git Basics ](https://github.com/rolling-scopes-school/lectures/blob/master/lectures/git.md)(в расписании колонка "материалы" к лекции Git Basics). 
Согласно этих требований коммиты следовало оформлять, указывая название задания. Мои коммиты выглядят так: Failed commit requirements: Commits do no follow guideline -> ["HTML, CSS & Git Basics/feat: add CV HTML page" , "cv/docs: update cv Technical Toolbox" , "cv/docs: add cv points" , "cv/init: start Markdown & Git task"] 
[Ссылка на мои коммиты в репозитории. ](https://github.com/slolkunchik/rsschool-cv/commits/gh-pages)

прошу пересмотреть результаты. В дальнейшем использовать руководство из лекции Git Basics больше нельзя?

**Comment by slolkunchik** [comment]
также прошу отметить расхождения в требованиях к заданию "HTML, CSS & Git Basics"
Я выполняла задание в соответствии с требованиями, которые даны в документации школы - [первое домашнее задание](https://docs.rs.school/#/first-home-task)  Про это домашнее задание Дмитрий Воробей говорил на первой лекции.
[По ссылке из документации ](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/codejam-cv.md) в задании не было требований по количеству коммитов. 
В то время, как впоследствии я обнаружила, что задание "HTML, CSS & Git Basics" также выдавалось позже [в расписании](https://github.com/rolling-scopes-school/tasks/blob/2018-Q3/tasks/codejam-cv.md) , где уже есть требование не менее 5 коммитов.

**Comment by dimazx83** [comment]
Если я написал коммит в котором написал проблему которую не знаю как решить, для того чтобы мне ответили менторы, то это считается ошибкой? (Мне сняли 50 баллов)
https://github.com/dimazx83/rsschool-cv

**Comment by AlinaKarpenkova** [comment]
Describe the bug
Неверно выставлены баллы.
Мне отняли 50 баллов за то, что в названии PR отсутствует название задания, но ссылаясь на сообщения на скриншоте в discord - это допустимо

Screenshots

![image](https://user-images.githubusercontent.com/49345663/66335188-1ff8f200-e943-11e9-9cfb-3eabac1a86d0.png)

сообщение из discord

![image](https://user-images.githubusercontent.com/49345663/66335145-08ba0480-e943-11e9-9a70-f2b4d30bccc6.png)

История коммитов(больше 3, соблюдены требования к коммитам)

![image](https://user-images.githubusercontent.com/49345663/66335107-fb9d1580-e942-11e9-8588-e1afa8349dce.png)

Соблюдены требования к репозиторию

![image](https://user-images.githubusercontent.com/49345663/66335071-eb853600-e942-11e9-9cc5-b5f8a92de85a.png)

Мои PR (отсутствует название задания)

**Comment by Nikolaenko94** [comment]
Добрый день.
Оформлял коммиты в соответствии с требованиями, которые давались в материалах к лекции Git Basics.
**Вот сообщение после проверки задания :** 
_> Failed commit requirements: Commits do no follow guideline -> ["\"init: start taks \"HTML, CSS & Git Basics\" and create index and style files" , "Update cv.md"]
> --_

[**ссылка на мои 27 коммитов** ](https://github.com/Nikolaenko94/rsschool-cv/commits/gh-pages)
Неужели выполненного задания в таком объёме недостаточно для получения наивысшего балла ?

**Comment by apalchys** [comment]
К сожалению, в данном задании не предполагается персональный подход. Я прекрасно понимаю, что обидно терять баллы из-за мелких ошибок и это вызывает очень неприятные эмоции. В дальнейшем почти все задания с кодом также будут проверяться на правильность оформления (с намного большим количеством баллов) и там уже будет возможность все сделать идеально. 

Общие ответы, так как нету возможности ответить каждому:
1. Мое сообщение в discord касательно названия PR было не совсем ясным. Принимается любое название содержащее название задания. (Markdown & Git, Markdown Git, markdown & git, Markdown&Git и т.д.)
2. Да, ошибки в коммитах ведут к потере 50% как было описано в задании и подход не будет меняться. :(

**Comment by AlinaKarpenkova** [comment]
Неужели за некорректное название PR и в целом правильно выполненное задание стоит снимать 50 баллов?

**Comment by Shastel** [comment]
@AlinaKarpenkova в результате для этого таска это потеря 5 баллов из общего счета

**Comment by ryntsevich** [comment]
Здравствуйте!

Failed task requirements: No CV at https://ryntsevich.github.io/rsschool-cv/cv
0 баллов за задание.

Прошу перепроверить репозиторий. Спасибо!

**Comment by anthunderous** [comment]
Здравствуйте! 
Выставлена оценка 50 с описанием "Failed repository requirements: No cv.md file".
Но файл cv.md **присутствует** - [скрин](http://prntscr.com/pfs8x9).

Предполагаю, что дело в местоположении файла, который находится не в корне репозитория, а по адресу "rsschool-cv/cv/". 
В моём случае в данном отрезке пути ".../cv/" cv - это папка, а проверка роботом, как я понимаю, должна на этом месте увидеть файл cv.md, который лежит по адресу "rsschool-cv/". Но в таком случае, мне кажется, что задание сформулировано не совсем понятно, и с помощью [этого скрина](http://prntscr.com/pgbbff) я это попробую доказать (*нужно смотреть на цифры на скрине*):
1. четко сказано, что по адресу 2 должен лежать **только** файл 1;
2. из первого пункта следует, что для выполнения этого условия нужно создать **папку** cv;
3. для того, чтобы файл 1 был доступен по адресу 2, его нужно переместить в ветку gh-pages именно в такой структуре;
4. из 3 пункта следует, что адрес "rsschool-cv/cv" уже занят папкой с таким же названием и файл cv.md нет смысла размещать рядом с ней, из чего следует вывод, что можно его расположить в этой папке и он будет доступен по [адресу](https://anthunderous.github.io/rsschool-cv/cv/cv)
***
Из задания "There should be only one file in the master branch - a README.md file with a link like this https://your-github-account.github.io/rsschool-cv/cv in it" в принципе следует то, что адрес "rsschool-cv/cv" уже занят файлом README.md и чисто физически там не сможет открываться файл cv.md. А если папку cv не создавать, что сделали большинство студентов, как я понял, то каким образом можно выполнить данное задание? Как можно открыть по такому адресу markdown файл с названием, которое отличается от последнего слова в адресе?
Очень прошу дать хоть какой-то ответ, потому что я уже голову сломал пока думал что не так, потому что я считаю, что я четко следовал условиям задания и именно это привело к ошибке, иначе я бы эту папку cv и не создавал бы и всё было бы гуд.

**Comment by katsu223** [comment]
Здравсвтуйте! Получил неверную оценку 
![Capture](https://user-images.githubusercontent.com/54061864/66377501-69d0ef00-e9ba-11e9-887b-4fb29591376a.PNG)
![Capture2](https://user-images.githubusercontent.com/54061864/66377502-69d0ef00-e9ba-11e9-8277-65a997298409.PNG)
Я сделал более 3-х коммитов, но робот мне пишет обратное

**Comment by dragonKat24** [comment]
@anthunderous, у меня такая же ошибка (Failed repository requirements: No cv.md file), и я ее поняла и приняла.

Посмотрела на репозиторий того, у кого оценка 100, всем советую так сделать ;)

Потом перечитала задание, и посмотрела на него уже по-другому. Конкретно в вашей претензии вы не акцентрируете внимание на ветку мастер.

> There should be only one file in the **master branch** - a README.md file with a link like this https://your-github-account.github.io/rsschool-cv/cv in it

Т.е. один файл в мастер, а второй `cv.md` уже в ветке `gh-pages`, но в той же папке, чтобы ссылка https://your-github-account.github.io/rsschool-cv/cv открывала именно `cv.md`

**Comment by anthunderous** [comment]
@dragonKat24 для создания ветки мастер нужно создать хоть какой то файл, например, README.md. Когда создается ветка gh-pages, то она создается на основе ветки мастер, где уже лежит файл README.md в папке cv, если следовать заданию, а значит и эта папка перемещается в новую ветку. Я смотрел первых 5 человек в рейтинге и у них нет папки cv **даже** в ветке master, что не соответствует заданию. Поправьте меня, если я не прав.

**Comment by dragonKat24** [comment]
@anthunderous Просто ссылка https://your-github-account.github.io/rsschool-cv/cv путает тем, что она указывает не на папку, а на файл `cv.md`, и, возможно, организаторы немного поменяют описание задачи для следующих потоков. Либо это была уловка, для таких как мы )

получается если мы создаем папку cv - то ссылка не рабочая, пока мы в эту папку не добавим index.html - а это уже другое задание...

**Comment by anthunderous** [comment]
@dragonKat24 я это понимаю, но каким в задании четко сказано что по ссылке  https://your-github-account.github.io/rsschool-cv/cv должен лежать файл README.md, а значит просто никак по ней не может лежать файл cv.md.
Если бы было сказано, что по этой ссылке должен лежать файл cv.md, то тогда всё понятно и вариант с папкой будет ошибкой, но ведь задание то говорит о другом.
У тех, кто получил 100 баллов, файл README.md лежит по адресу **/rsschool-cv/**, а в задании указан адрес **rsschool-cv/cv**. Тут даже не нужно смотреть на файл cv.md и думать о путанице с названиями папок, потому что речь идёт о файле README.md

**Comment by dragonKat24** [comment]
Да нет же!

Repository Requirements:
1. Make a public repository called rsschool-cv on your GitHub account.
Сделать публичный репозиторий rsschool-cv на вашем GitHub аккаунте

2. There should be only one file in the master branch - a README.md file with a link like this https://your-github-account.github.io/rsschool-cv/cv in it 
Здесь должен быть только **один файл в ветке master** - это README.md файл со ссылкой https://your-github-account.github.io/rsschool-cv/cv **внутри**

3. The CV document itself called cv.md should be in the branch gh-pages.
**Сам CV документ** называется **cv.md**, и должен быть **в ветке gh-pages**

4. Once you are done, open a Pull Request gh-pages->master. Do not merge this Pull Request!
Когда вы закончите, откройте Pull Request gh-pages->master, но не мержите этот пул реквест


Представьте ссылку https://your-github-account.github.io/rsschool-cv/cv как ссылку
 [https://your-github-account.github.io/rsschool-cv/**cv.md**](#) и надеюсь поймете - иначе я не могу вам объяснить.

**Comment by anthunderous** [comment]
@dragonKat24 всё, до меня дошло) Я читал "...доступен по ссылке" вместо "...в котором должна лежать ссылка". Значит всё правильно, извиняюсь за тупость)
Спасибо вам большое!

**Comment by Torondil** [comment]
Здравствуйте! В деталях: Failed PR requirements: No Pull Request with task name (Markdown & Git). Pull-request создан и название тоже присуствует -https://github.com/Torondil/rsschool-2019Q1-cv/pull/1

**Comment by IlyaShihutin** [comment]
Здравствуйте, мне выдает ошибку Failed task requirements: No CV at https://ilyashihutin.github.io/rsschool-cv/cv, но по переходу по ссылке я вижу свою страницу , а также по переходу по ссылке  https://ilyashihutin.github.io/rsschool-cv я вижу свою страницу, файл cv.md имеется.

**Comment by apalchys** [comment]
@Torondil Репозиторий в котором PR не проходит по требованию задания.  
_Make a public repository called `rsschool-cv` on your GitHub account._


@IlyaShihutin url был недоступен на момент проверки и коммиты в бранче сделаны после деадлайна 
https://api.github.com/repos/ilyashihutin/rsschool-cv/commits?sha=gh-pages

**Comment by ZakharovAleksandr** [comment]
Добрый вечер, получил за таск 50 баллов, не могу разобраться почему, хотя все верно. Возможно ошибка, Заранее благодарю за ответ.
https://github.com/ZakharovAleksandr/rsschool-cv

**Comment by apalchys** [comment]
@ZakharovAleksandr Названия коммитов не следуют требованиям:

https://github.com/rolling-scopes-school/tasks/blob/master/tasks/git-markdown.md#commits-requirements

https://docs.rs.school/#/git-convention

**Comment by Torondil** [comment]
@apalchys Прошу прощения, прикрепил репо с прошлого набора. А в том, что надо - действительно не оставил комментарий к PR. Спасибо за ответ!
https://github.com/Torondil/rsschool-cv/pull/1
***********************
https://github.com/rolling-scopes/rsschool-app/issues/150#issuecomment-539494375

**Comment by IlyaShihutin** [comment]
@apalchys Так получается что если поздно присоединился к курсу , то задания Markdown & Git,"HTML, CSS & Git Basics" и HTML-CSS-self не будут засчитаны? Просто я читал что если больше недели после дедлайна то хотябы 30% баллов поставят

**Comment by kotcher1** [comment]
Course
rs-2019-q3

На данный момент за задание у меня стоит оценка 50.
В комментарии написано "Failed commit requirements: Commits do no follow guideline -> ["Create README.md"]"
Этот коммит появился в связи с тем, что я создавала файл README для ветки gh-pages через гитхаб, а не консоль. То есть этот коммит автоматический. Все остальные коммиты написаны по правилам.
