### ISSUE TITLE
HTML-builder

### ISSUE THREAD

**Issue by Vasyaruberoid** [rolling-scopes/rsschool-app#1504]
**Course**
Specify your course (e.g. rs-2022-q1)

**What is wrong**
 https://github.com/Vasyaruberoid/HTML-builder 
Добрый день мне поставили двое 130 баллов, двое других поставили по 140баллов,а мне не зачисляется в выполненное задание

**Comment by valerydluski** [comment]
Cross-check review must be completed by May 27.
You reviewed the work of other students on May 29.
