### ISSUE TITLE
Ability to review old tasks

### ISSUE THREAD

**Issue by polivodichka** [rolling-scopes/rsschool-app#1517]
**Describe the bug**
Possibility to review old-old tasks (crosscheck for which is already closed).

**To Reproduce**

1. Go to 'Crosscheck-review'
2. Select old task with closed cross-check from tasks-list
3. Select a student
4. You have ability to write feedback and put a new mark

**Expected behavior**
No such possibility

**Screenshots**
![image](https://user-images.githubusercontent.com/68563445/173435135-2a55e478-2c28-428d-b58a-602693d6a3f3.png)
Cross-check of this task was closed in April

**Device (please complete the following information):**

- OS: Windows
- Browser: Yandex Browser
- Version: 21.9.2.169 (64-bit)

**Additional context**
I'm sorry if this is a feature and I didn't figure it out

**Comment by polivodichka** [comment]
Yesterday I was evaluated by a student on the Node JS course, but the cross-check was closed the day before. In my opinion, this behavior can lead to misunderstandings

**Comment by AlreadyBored** [comment]
Fixed by https://github.com/rolling-scopes/rsschool-app/pull/1484
