### ISSUE TITLE
Неправильная сортировка таблицы Score

### ISSUE THREAD

**Issue by natein** [rolling-scopes/rsschool-app#1526]
Сортирует каждую страницу отдельно. Например сортируем по колонке Name:

Страница 1
![1](https://user-images.githubusercontent.com/12632270/174185186-803d6122-3d27-4807-b0bd-8df257ede855.PNG)

Страница 2
![2](https://user-images.githubusercontent.com/12632270/174185217-155a1ff0-743c-4e13-9ddd-90a530180def.PNG)

**Comment by I-vasilich-I** [comment]
I'm pretty sure my sorter function from [PR#1481](https://github.com/rolling-scopes/rsschool-app/pull/1481) had broken it, I was afraid something like that could happen. I'll try to figure it out

P.S. Something wrong with # Column too (5803 id repeats a lot), looks like the same issue like [that one](https://github.com/rolling-scopes/rsschool-app/issues/1493)

**Comment by I-vasilich-I** [comment]
issue fixed and could be closed

**Comment by dzmitry-varabei** [comment]
@I-vasilich-I thank you!!
