### ISSUE TITLE
The name of an anonymous student is visible

### ISSUE THREAD

**Issue by polivodichka** [rolling-scopes/rsschool-app#1529]
**Describe the bug**
The name of an anonymous student is visible on github

**To Reproduce**

1. Go to 'Cross-check submit'
2. Select a task where is exists review from anonymous student (Student1/Student2 ect.)
3. Go to your pullrequest from submit
4. Scroll down and you cat see github account of anonymous student

**Expected behavior**
Either it is not possible to leave anonymous reviews or comments with names do not appear on PR

**Screenshots**
![image](https://user-images.githubusercontent.com/68563445/174457133-004ae8be-af10-414a-9f52-8a46242ed704.png)
![image](https://user-images.githubusercontent.com/68563445/174457143-cee7b776-ecc3-4b29-8b72-eaa4cfd111b0.png)

**Device (please complete the following information):**

- OS: Windows
- Browser: Yandex browser
- Version: 21.9.2.169 (64-bit)

**Comment by AlreadyBored** [comment]
Comments in RS App are not automatically synced with Github, this student submitted a comment manually. So this is not an RS App bug. And thank you for helping me figure out what happened :)
