### ISSUE TITLE
Extend test db (Contributing)

### ISSUE THREAD

**Issue by I-vasilich-I** [rolling-scopes/rsschool-app#1533]
**Describe the feature**
Would be great if test db contained enough students to have at least 2 sections in score table pagination.

Wouldn't introduce this issue in the first place: 
[PR#1532](https://github.com/rolling-scopes/rsschool-app/pull/1532)
[issue#1526](https://github.com/rolling-scopes/rsschool-app/issues/1526)
[PR#1481](https://github.com/rolling-scopes/rsschool-app/pull/1481)

**Additional context**
Apparently label `deploy` on PR from the `fork repository` doesn't deploy, there're some security limitations, therefore PR got merged into master branch without test deploy and code that woks fine on test db get production bugged

**Comment by MemoS77** [comment]
I agree. It would be nice if the test base was better filled and there was enough information in all sections. A lot of time is spent to prepare test data and sometimes after these manual manipulations, the application breaks down, errors occur and it is not clear what is the reason. There are many ideas, but it is difficult to make improvements on this dataset.
