### ISSUE TITLE
Cross-check: Preview with md during the cross-check

### ISSUE THREAD

**Issue by Diluks93** [rolling-scopes/rsschool-app#1534]
**Describe the bug**
If you click on preview during the cross-check review, then a preview with md markup will pop up and everything is nice and clear, but if you make a submit in this form, then this whole view remains and is not updated when students change. Now it is being treated by returning to write mode or restarting the browser

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

**Additional context**

**Comment by apalchys** [comment]
This bug is probably fixed by @Pulya10c . Could you please check again?
