### ISSUE TITLE
Duplicate interviews

### ISSUE THREAD

**Issue by ShaxxKh** [rolling-scopes/rsschool-app#1536]
**Course**
JavaScript/Front-end 2022Q1

**What is wrong**
Duplicate interviews.

On the June 20th I had 3 students in section "My Students" and No interviews in section "Interviews". On the June 21st I got 6 interviews, but 2 students have 2 interviews appointed there.

"Interviews" section:
<img width="1487" alt="Screen Shot 2022-06-21 at 14 07 29" src="https://user-images.githubusercontent.com/60749883/174766304-15dd88d0-5620-41ab-a9bb-0a45c98d8044.png">

"My Students" section:
<img width="848" alt="Screen Shot 2022-06-21 at 14 25 22" src="https://user-images.githubusercontent.com/60749883/174766169-e685e06e-f3ab-4400-b7b1-b9d37c050834.png">

**Comment by valerydluski** [comment]
@ShaxxKh remove duplicate

**Comment by papkovskaya** [comment]
@valerydluski Have the same issue

**Comment by MadinaNishanbaeva** [comment]
@valerydluski same issue

**Comment by Satlykov** [comment]
I have the same issue
![image](https://user-images.githubusercontent.com/70792214/175917823-5a81a0d7-52bf-4303-9d73-8fbcb0882608.png)
@dimitrianderi
@jaha-iskhakov

**Comment by SlikeX** [comment]
![image](https://user-images.githubusercontent.com/78522259/176235920-b099612b-84ef-4580-80dd-00d88a322cf5.png)
Have one duplicate

**Comment by XanDrDz** [comment]
@valerydluski I have the same issue with duplicate

**Comment by valerydluski** [comment]
@SlikeX @XanDrDz i removed duplicates

**Comment by JaneEllison** [comment]
The same
![image](https://user-images.githubusercontent.com/65969334/176851843-ddc476e9-535d-4f14-a144-8488778685b4.png)
