### ISSUE TITLE
Открыл PR и потом сделал Merge

### ISSUE THREAD

**Issue by magerrrr** [rolling-scopes/rsschool-app#154]
**Проблема**: _Failed PR requirements: No Pull Request with task name (Markdown & Git)_
**Мой Score**: _50_
**Причина (статус) на фото ниже:**
![Снимок экрана 2019-10-07 в 0 44 30](https://user-images.githubusercontent.com/17405745/66276470-25e7c800-e89c-11e9-9072-e1b6f58b49b7.png)

_Требования **выполнены** все, PR открыт был, название указано верно и остальные критерии тоже, сделан был Merge так как обычно же так делать нужно :)_

- [x] Make a public repository called rsschool-cv on your GitHub account.
- [x] There should be only one file in the master branch - a README.md file with a link like this https://your-github-account.github.io/rsschool-cv/cv in it
- [x] The CV document itself called cv.md should be in the branch gh-pages.
- [x] Once you are done, open a Pull Request gh-pages->master.

![Снимок экрана 2019-10-07 в 0 50 13](https://user-images.githubusercontent.com/17405745/66276551-01402000-e89d-11e9-8dff-2dcfafda040f.png)

Merge не должен быть причиной сброса баллов за PR, так как он был успешно выполнен. Прошу рассмотреть мою просьбу об учете данного таска как выполненного и засчитать 50 баллов. Благодарю :)

**Comment by apalchys** [comment]
@magerrrr Да, отсутствовало явно условия в задании, что PR должен быть `Open`. В будущем будет исправлено. Проверка была перезапущена и "Merged" теперь тоже учитываются.

**Comment by magerrrr** [comment]
Спасибо большое! Быстрое и четкое решение вопроса! Приятно
