### ISSUE TITLE
Autotest: I can submit any codewars login name in autotest

### ISSUE THREAD

**Issue by LGers** [rolling-scopes/rsschool-app#1544]
**Describe the bug**
I can submit any codewars login/username in autotest and give max score without solve tasks

**To Reproduce**

1. Go to 'autotest codewars'
2. Write any valid Login/username in codewars
3. You see result another user, because if I know a valid username, I can write it and test give me max score

**Comment by dzmitry-varabei** [comment]
Thanks for noticing this issue!
We decided to require students to use a special notation in their username: rsschool_${GitHubUsername}. For example:
<img width="438" alt="image" src="https://user-images.githubusercontent.com/2429680/177575507-5c258692-5d5d-4c7d-a53a-258c931235d6.png">

In this case, students will not enter their codewars' nicknames, and RS APP will obtain them automatically.
