### ISSUE TITLE
Schedule: Can't change color for "RS School App Test" tag

### ISSUE THREAD

**Issue by AnastasiaLL** [rolling-scopes/rsschool-app#1549]
**Describe the bug**
Отсутствует возможность смены цвета тега "RS School App Test" в расписании.

**To Reproduce**

1. Откройте  Schedule
2. Нажмите на Schedule settings
3.Нажмите на Change tag colors

**Expected behavior**
Ожидалась возможность сменить цвет у тега "RS School App Test" в окне Change tag colors

**Screenshots**
![image](https://user-images.githubusercontent.com/93924737/175770391-0338be88-503c-401c-bcf7-67f6aa8dde40.png)

**Device (please complete the following information):**

- OS: Windows
- Browser chrome
- Version 102.0.5005.115 (Официальная сборка), (64 бит)

**Comment by dzmitry-varabei** [comment]
@mikhama Please synchronize the tag names in the schedule with the tag names in the settings.
Schedule:
<img width="210" alt="image" src="https://user-images.githubusercontent.com/2429680/177595564-2e695ebc-d5e2-4ac3-92e0-498b66a111db.png">
Settings:
<img width="292" alt="image" src="https://user-images.githubusercontent.com/2429680/177595709-15c3110b-b207-4aee-b056-c3474566f850.png">
