### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Vasyaruberoid** [rolling-scopes/rsschool-app#1562]
Добрый день ,у меня просьба, пересмотреть мои задания ![Снимок](https://user-images.githubusercontent.com/84591840/177031350-7eaa6d6f-e24c-498b-9280-d1449405dd3a.PNG)
 :
1.В одном задании ![Снимок1](https://user-images.githubusercontent.com/84591840/177031358-daf99211-2d49-4041-905f-87d15e638393.PNG)   Не начисляется мне баллы сслыка на задание https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/html-builder
2. В другом задании четвёртый человек не проверил https://github.com/rolling-scopes-school/tasks/tree/master/stage1/stream1/shelter
3. В теретьем тоже четвёртый не проверил https://github.com/rolling-scopes-school/tasks/blob/master/stage1/modules/clean-code/clean-code-s1e1.md

**Comment by valerydluski** [comment]
@Vasyaruberoid 
перенеси [сюда](https://github.com/rolling-scopes-school/support/issues)
