### ISSUE TITLE
bug: Submit button is always disabled

### ISSUE THREAD

**Issue by Gena888** [rolling-scopes/rsschool-app#1565]
test link: https://app.rs.school/course/student/cross-check-review?course=aws-2022q2
issue: submit button is always disabled. 
<img width="693" alt="Screenshot 2022-07-04 at 18 10 46" src="https://user-images.githubusercontent.com/74081058/177186557-a370fcdc-8df9-46c3-a033-7b2835023c16.png">

**Comment by dzmitry-varabei** [comment]
@Gena888 thanks! 
This is related to #1569
