### ISSUE TITLE
error

### ISSUE THREAD

**Issue by puchkovSasha** [rolling-scopes/rsschool-app#157]
Здравствуйте, случайно закомител package-lock.json, после чего удалил его и комител дальше,Это читается ошибкой.?

Детали ошибки -Failed commit requirements: Commits do no follow guideline -> ["delete package-lock.json" , "transfer .vscode"]
коммиты в ветке - https://github.com/lobanyov/rsschool-cv/commits/gh-pages

**Comment by dzmitry-varabei** [comment]
@puchkovSasha Revert ошибкой не считается.

**Comment by puchkovSasha** [comment]
Эххх точно. Спасибо. В следущий сделаю так лучше.
