### ISSUE TITLE
Auto-Test feature

### ISSUE THREAD

**Issue by MDViktor** [rolling-scopes/rsschool-app#1573]
**Select in Auto-Test feature**
The essence of the proposal is the ability to select an answer only when you click on the select button area when working with tests. Now it is possible to select an answer by clicking on the answer text, not only select button area, which can lead to an unconscious choice when scrolling the screen with the mouse.
**Additional context**
Ivan G (@juliv) suggested to solve this problem considering adding line highlighting by using the extension Stylus.

**Comment by dzmitry-varabei** [comment]
@MDViktor Thanks for bringing this up! We discussed it today and decided that we would use background highlighting. Here is an example:
<img width="641" alt="image" src="https://user-images.githubusercontent.com/2429680/177563106-85ec0939-ebb2-4df6-80a2-548167c4d452.png">

**Comment by MDViktor** [comment]
It looks like good

**Comment by AlreadyBored** [comment]
We decided not to implement this, because it breaks widely used accessibility patterns.
But thanks for your activity anyway! :)
