### ISSUE TITLE
Student Statistics(Bug or Feature)

### ISSUE THREAD

**Issue by I-vasilich-I** [rolling-scopes/rsschool-app#1578]
**Describe the bug**
I've checked my stats on [Profiel page](https://app.rs.school/profile#view) and on [NodeJS course](https://app.rs.school/course/student/dashboard?course=nodejs-2022-q2), it shows different percent of completeness, 37.5% on Profile and 51% on course page. First one - completed tasks/all tasks, second one -  completed score/ total score. 
Is it intended behavior or bug? Shouldn't it be the same percent?

**Screenshots**
![Screenshot from 2022-07-06 15-32-36](https://user-images.githubusercontent.com/67139199/177552374-2c770561-da19-4e71-80f3-04bdb8e6a10e.png)
![Screenshot from 2022-07-06 15-32-17](https://user-images.githubusercontent.com/67139199/177552380-83e7d03f-425d-4712-81e4-9819be1adc87.png)

**Comment by dzmitry-varabei** [comment]
@I-vasilich-I Thanks for bringing this up! We discussed this issue today and decided to deprecate both indicators and display only position and total score. If you can remove them yourself, it will be wonderful :) 
If you have any questions or suggestions, feel free to ask.

**Comment by I-vasilich-I** [comment]
@dzmitry-varabei so on "Your stats" card I should delete the speedometer and just leave position and total score the way it is now
And on course info I'll delete speedometer too, but what to do with text "Course progress..."? should I leave it the way it is now or remove completely or maybe just remove percentage in parentheses?

**Comment by dzmitry-varabei** [comment]
@I-vasilich-I Please remove both speedometers and the text "Course progress..." as well

**Comment by I-vasilich-I** [comment]
@dzmitry-varabei Should I do anything about this line indicators? It shows the same data as speedometers.
![Screenshot from 2022-07-07 09-58-03](https://user-images.githubusercontent.com/67139199/177711343-3643bd5f-ef76-4869-b6df-b73fa70ffe68.png)
