### ISSUE TITLE
Technical screening: Unable to cancel an interview

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#1587]
https://app.rs.school/course/admin/stage-interviews?course=js-fe-2022Q1
Student GitHub: [alimbaeva](https://app.rs.school/profile?githubId=alimbaeva)
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/2429680/178354276-0a1dd960-7efd-42a0-a533-037d045da05b.png">

**Comment by apalchys** [comment]
@dzmitry-varabei  this interview has not completed feedback already... it's a bug but anywhere we can't cancel it

**Comment by apalchys** [comment]
my bad. actually it's another bug. nevermind. We should not try to delete it.
