### ISSUE TITLE
Ментору не приходит приглашение для доступа к репозиториям студентов

### ISSUE THREAD

**Issue by natein** [rolling-scopes/rsschool-app#1596]
Ментор Mikhail-Hursky не получает invitation после выполнения команды Sync with GitHub Teams на странице [https://app.rs.school/course/admin/mentors?course=js-fe-2022Q1](https://app.rs.school/course/admin/mentors?course=js-fe-2022Q1)

![image](https://user-images.githubusercontent.com/12632270/179214809-9be47746-90a2-43a7-9f5d-d76417a39230.png)

**Comment by apalchys** [comment]
Я сделал `Sync with GitHub Teams` и вижу что он invited

<img width="403" alt="image" src="https://user-images.githubusercontent.com/618807/179605281-12fe2f73-9e7b-4679-9d75-ce189df7296f.png">
