### ISSUE TITLE
change my Git name profile

### ISSUE THREAD

**Issue by AlexVoronenko** [rolling-scopes/rsschool-app#1600]
Как можно изменить привязку к GitHub в профиле RS-School?

Было: AlexanderVoronenko
Стало: AlexVoronenko

**Comment by apalchys** [comment]
@AlexVoronenko  Попробуй просто перелогиниться https://app.rs.school/login

**Comment by AlexVoronenko** [comment]
Спасибо, помогло. После того, как перелогинился и в разделе Dashboard выбрал Fix Repository + принял приглашение от Rs-school...

**Comment by AlexVoronenko** [comment]
Спасибо. Все получилось.

пн, 18 июл. 2022 г., 22:46 Andrei ***@***.***>:
