### ISSUE TITLE
New statuses of tasks and events in the student schedule 

### ISSUE THREAD

**Issue by TattiMikhailava** [rolling-scopes/rsschool-app#1603]
Status enables to define a condition of assignments in relation to completion. Several statuses are defined based on types of tasks and events, deadlines and way of checking.  

It would be clearly keeping track students results in the table schedule. 

**Add statuses for tasks, events and interviews in the schedule table.** 

**Schedule objects** 

There are events (online-lectures, webinars etc.), interviews and tasks for students presented in the schedule.  
Events are assigned by coordinators. They aren’t verified and haven’t any strict deadlines, but recommended start and end dates.  
Tasks are divided into 3 groups: verified automatically, cross-checked by students (peer review) and checked by mentors. All tasks have strict time frames. 
Interviews include Technical Screening (Pre-Screening Interview) and Core Interview. 

![Table](https://user-images.githubusercontent.com/100757852/179760442-79fbf9d1-2ad9-4858-a9d0-d00372725e01.png)

![Scheme 1](https://user-images.githubusercontent.com/100757852/179760770-27fcfe9e-5e53-42cb-8f1e-bef9ba53d1ea.png)

![Scheme 2](https://user-images.githubusercontent.com/100757852/179760996-fa833a61-41b7-4bba-9efa-bc5d949d3997.png)
![Scheme 3](https://user-images.githubusercontent.com/100757852/179761000-f405f296-7f01-4aaf-8fb0-eedec50e69d7.png)
![Scheme 4](https://user-images.githubusercontent.com/100757852/179761001-256697b7-bac5-49a2-a63e-899a676da94a.png)

Figma [file](https://www.figma.com/file/ufFk7FYDLkewzvV5E5HvBL/Status-filtration?node-id=4%3A2) for developing.

**Comment by apalchys** [comment]
Done
