### ISSUE TITLE
Ошибка в примере задания "core-js-101"

### ISSUE THREAD

**Issue by koviatsinets** [rolling-scopes/rsschool-app#1607]
<img width="790" alt="image" src="https://user-images.githubusercontent.com/91376144/180414705-da094f3f-bd60-4167-91f9-a37acc1752d7.png">

index и item перепутаны местами

**Comment by AlreadyBored** [comment]
Thanks for the info, but could you please open this issue in the appropriate repository?
https://github.com/mikhama/core-js-101/issues/new
This problem is not related to RS App :)
