### ISSUE TITLE
Задвоился тех. скрининг и не правильно отобращается результат в score

### ISSUE THREAD

**Issue by PDmitryY** [rolling-scopes/rsschool-app#1642]
По результатам собеседования ментор поставил 45 баллов, но в score стоит 20. На сколько я понимаю из-за того, что задвоился тех.скриннинг в системе
![image](https://user-images.githubusercontent.com/19780026/183265310-5e08c021-2a6e-4b18-8cc1-f3cbf57ed011.png)
Ментор обещал исправить, но пока у него это сделать не получилось.
![image](https://user-images.githubusercontent.com/19780026/183265333-727f70e1-05ae-4a11-86af-8b59f11fb6ac.png)

**Comment by apalchys** [comment]
I see it's fixed
