### ISSUE TITLE
Score: Add a toggle button with "My students only" in RS APP Score page

### ISSUE THREAD

**Issue by IrinaBorkina** [rolling-scopes/rsschool-app#1648]
It would be better to have this functionality instead of searching by myself in the "Mentor" column

![image](https://user-images.githubusercontent.com/44750544/184698865-e3a95ba1-99d7-4b20-81ef-62cd89a9c329.png)

**Comment by ktnktag** [comment]
Rejected, cause 
- score for mentor's tasks can be seen by mentor dashboard, 
- rating for mentor's student can be seen later in "my students" 
- and also, score table can be sorted by "mentor column".
