### ISSUE TITLE
Style of the main page

### ISSUE THREAD

**Issue by cathzetjo** [rolling-scopes/rsschool-app#165]
Just need a little bit more space I think 🙂
Would look nice if block “feedback” & “help” would be in the same style with the first block - line with data stretched  on the whole screen.
It’s Safari browser btw.

![78379939-C7B3-402C-AC63-46AD429244E4](https://user-images.githubusercontent.com/44948376/66470939-3615c800-ea93-11e9-963e-123dd87c4311.jpeg)

**Comment by dzmitry-varabei** [comment]
@cathzetjo Thank you! fixed.
