### ISSUE TITLE
Wrong score in Crosscheck Momentum

### ISSUE THREAD

**Issue by VadimND** [rolling-scopes/rsschool-app#1676]
**Course**
Preschool 2022-Q2

**What is wrong**
I have 4 works to check until 21 of August. I checked them on 19/08/2022 but status in Schedule is 'missed'. I didn't have score for this task. Help me, please.
https://prnt.sc/usiHl7Hs4iYf
Thanks a lot.

**Comment by apalchys** [comment]
@luffi2539 Could you please check it?

**Comment by valerydluski** [comment]
![image](https://user-images.githubusercontent.com/57412523/186376034-465eeb38-67f6-4050-abf6-c2d97fe13de5.png)
scores are fine. the problem was in the schedule, I already corrected it
