### ISSUE TITLE
Schedule:  copy a Schedule from one course to another

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes/rsschool-app#1678]
**Describe the feature**

I would like to be able to copy the schedule from one course to another course

**Additional context**
I am a course manager on the js-fe-2022Q1 course, I need to copy the schedule of this course to the js-fe-2022Q3 course.
we have an export button, but I have no way to get what can be exported

**Comment by dzmitry-varabei** [comment]
<img width="517" alt="image" src="https://github.com/rolling-scopes/rsschool-app/assets/2429680/6de7aefa-74e3-4e28-8126-ddf89c1e2eb0">
@AlreadyBored
