### ISSUE TITLE
Сбрасываются результаты поиска после нажатия на Enter

### ISSUE THREAD

**Issue by natein** [rolling-scopes/rsschool-app#1681]
В таблице Score при поиске по всем полям после нажатия на Enter сначала происходит поиск и отображаются найденные данные, а затем происходит моментальный сброс к исходному состоянию.

**Comment by AlreadyBored** [comment]
@natein 
Could you please provide more detailed instructions on how to reproduce the bug? I tried and it worked correctly.
Screenshots/screen recordings are also welcome :)

**Comment by valerydluski** [comment]
bug is reproduced as described in the JavaScript/Front-end 2022Q1 course

**Comment by natein** [comment]
> bug is reproduced as described in the JavaScript/Front-end 2022Q1 course

На всех курсах, в том числе и archived.

**Comment by natein** [comment]
> 

Описываю более подробно на примере курса JavaScript/Front-end 2022Q1

Нажимаю на кнопку поиска и в открывшееся поле ввожу данные
![search word](https://user-images.githubusercontent.com/12632270/187267271-7fcb08a8-b4b2-4876-8bb3-37f8a30944b4.PNG)
Нажимаю кнопку Enter
Сначала отображаются результаты поиска
![results](https://user-images.githubusercontent.com/12632270/187267447-d89516a0-743e-42eb-8a36-497d225e5fa7.PNG)
Спустя менее секунду появляется полный список студентов
![all](https://user-images.githubusercontent.com/12632270/187267573-27ff6941-a27e-4be5-b68f-c664d314ac31.PNG)

Chrome Version 104.0.5112.102 (Official Build) (64-bit)

**Comment by AlreadyBored** [comment]
Fixed
