### ISSUE TITLE
Не отображается organizer у части заданий

### ISSUE THREAD

**Issue by natein** [rolling-scopes/rsschool-app#1693]
С появлением нового дизайна в Schedule всех курсов перестали отображаться ответственные (Organizer) у части заданий.

Сейчас они отображаются только у некоторых лекций, хотя ранее были у большинства заданий.

**Comment by apalchys** [comment]
@natein  Please check now

**Comment by natein** [comment]
> @natein Please check now

Да, теперь всё в порядке. Спасибо! Теперь студенты будут знать к кому обращаться в случае проблем с заданиями.
