### ISSUE TITLE
Wrong score in Crosscheck-Codejam

### ISSUE THREAD

**Issue by VadimND** [rolling-scopes/rsschool-app#1701]
**Course**
JS/FE Pre-School 2022Q2

**What is wrong**
There is a problem with my score in Crosscheck-Codejam. I checked all works before deadline (02.09.2022 at 18.00 by Minsk time). But I got zero score. My statistics loks like this: https://yadi.sk/d/hTBVeR-ubFI7aQ
Please, help me to correct this problem.

**Comment by apalchys** [comment]
@luffi2539 could you please check ?

**Comment by valerydluski** [comment]
Hi, @VadimND . your score is fine. 
Crosscheck-Codejam was added to the schedule only to display the date of the Crosscheck deadline
