### ISSUE TITLE
Need to change link to GitHub

### ISSUE THREAD

**Issue by darya-shynkevich** [rolling-scopes/rsschool-app#1703]
**Course**
JS/Front-end 2022Q3

**What is wrong**

I've changed my GitHub account name from 'darya-litvinchuk' to 'darya-shynkevich'. But I can not update the link in my profile. Currently, the link leads to https://github.com/darya-litvinchuk BUT it should lead to https://github.com/darya-shynkevich.

I've asked in questions-to-rsapp and Dzmitry Varabe said that it is impossible to do on my own. 

Please help and change my link to GitHub to https://github.com/darya-shynkevich

**Comment by apalchys** [comment]
@darya-shynkevich please just re-login using new account here: https://app.rs.school/login and let me know if it works.

**Comment by darya-shynkevich** [comment]
All works perfectly! Thanks!
