### ISSUE TITLE
Проблема с моим профилем в app.rs.school Нету регистрации и занятий для моего профиля ageeva.vera.minsk@yandex.by. Помогоите!

### ISSUE THREAD

**Issue by VeraAgeevaIT** [rolling-scopes/rsschool-app#1707]
Добрый день!
Проблема с моим профилем в app.rs.school 

Нету регистрации и занятий для моего профиля ageeva.vera.minsk@yandex.by 
Хотя я регистрировалась. 
Помогите!

https://github.com/VeraAgeevaIT
+375 29 616 87 70

**Comment by AlreadyBored** [comment]
@VeraAgeevaIT Hi, Vera! If you're talking about the JavaScript/Front-end 2022Q3 course, then as far as I can see, you're registered on the course.
![image](https://user-images.githubusercontent.com/34455330/188316821-9e980ca6-09f0-4e61-92c3-eeda055923ec.png)
Remember that you must be logged into the github in the browser through which you access the RS App.
If this does not help, then please provide more detailed information about the actions you are taking and the observed result.

**Comment by apalchys** [comment]
Closing. @VeraAgeevaIT Please re-open if you still have any issues
