### ISSUE TITLE
Auto-tests: Поломалась верстка авто-тестов в мобильной версии

### ISSUE THREAD

**Issue by gordinski** [rolling-scopes/rsschool-app#1708]
**Describe the bug**
Поломалась верстка таблицы результатов на странице авто-тестов в мобильной версии

**To Reproduce**
1. https://app.rs.school/course/student/auto-test?course=js-fe-2022Q3
2. Смотреть табличку результатов

**Expected behavior**
Удобочитаемая табличка

**Screenshots**
[Скрин](https://ibb.co/YpNxT3t) 

**Device (please complete the following information):**
- OS: андроид
- Browser хром
- Version последняя

**Comment by valerydluski** [comment]
@nataliagulko  thanks for the fix
