### ISSUE TITLE
Tasks Verifications Error (HTML-CSS-self-education)

### ISSUE THREAD

**Issue by me-am-i** [rolling-scopes/rsschool-app#171]
**Describe the bug**
После отправки задачи на проверку баллы не начисляются, предыдущее количество обнулилось.

**To Reproduce**
1. На странице Submit Task выбрать пункт [Stage#1 HTML-CSS-self-education]
2. Указать логин для Codecademy Account, нажать на кнопку Submit, получить сообщение об успешной постановке в очередь
3. Перейти на страницу Task Verification Status
4. Результат - Score: 0, 
Details: 1. Request failed with status code 404 2. No HTML Account provided 
5. Позиция в рейтинге опустилась 

Проверялось с логином от codecademy (одно поле) и с codeacademy и htmlacademy (два поля).
Для исключения опечаток копировалось из профиля (app)

**Comment by apalchys** [comment]
Напиши пожалуйста мне в discord, чтобы оперативнее решить проблему.

**Comment by apalchys** [comment]
Проблема решена. Оценка выставлена.
