### ISSUE TITLE
Synchronization between 2 different my own accounts

### ISSUE THREAD

**Issue by archi144** [rolling-scopes/rsschool-app#1717]
Completed all tasks on the autocode platform.
![image](https://user-images.githubusercontent.com/37845382/188500845-792ba230-a04e-44cf-b8a4-69c12474f01c.png)
But on RS School for my account (https://github.com/archi144) I see nothing. It's OK.
![image](https://user-images.githubusercontent.com/37845382/188500939-c4426669-d214-4d22-9dff-26144586e843.png)

I used my another GitHub account to complete the course (https://github.com/go1earner).
And log in gives me nothing. It just doesn't see my tasks.
![image](https://user-images.githubusercontent.com/37845382/188501212-950fb404-c054-45d8-befd-2b443df11eff.png)

Could you please link completed tasks of [go1earner](https://github.com/go1earner) to [archi144](https://github.com/archi144) on RS School in order to get pretty certificate?

**Comment by dzmitry-varabei** [comment]
@archi144 We do not allow students to participate in the course from two GitHub accounts and don't help with data transfer.
