### ISSUE TITLE
Обмен студентами между менторами, букинг конкретного студента

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#173]
Формат:
```
{
  "mentorGithubId": "xxx",
  "studentGithubId": "yyyy"
}
```
где xxx - новый ментор

**Comment by Alexshumansky** [comment]
{
  "mentorGithubId": "Alexshumansky",
  "studentGithubId": "yuliagushcha"
}

**Comment by denitrip** [comment]
{
"mentorGithubId": "denitrip",
"studentGithubId": "Lina-malina"
}

**Comment by lsasinovich** [comment]
{
"mentorGithubId" : "juliamargun",
"studentGithubId" : "pavelokun"
}

**Comment by AlleeX** [comment]
{
  "mentorGithubId": "vladlan",
  "studentGithubId": "confesssa"
},
{
  "mentorGithubId": "aliakseibychyk",
  "studentGithubId": "mikhailpakaliuk"
},
{
  "mentorGithubId": "aliakseibychyk",
  "studentGithubId": "dmitryschepa"
}

**Comment by DenisSoft** [comment]
{
"mentorGithubId": "DenisSoft",
"studentGithubId": "absolutelyvoid"
}

**Comment by dzmitry-varabei** [comment]
ВНИМАНИЕ! 
Менторы теперь сами могут поменяться или взять себе еще одного студента для интервью!

Если вы хотите взять себе еще одного студента для интервью:
1) Открываете https://app.rs.school/course/mentor/stage-interviews?course=rs-2019-q3
2) На вкладке "Avaliable students" выбираете студента
3) Нажимаете "Want To Interview"

Если менторы хотят произвести обмен студентами. Например, по договоренности в slack канале #student-market.
1) Оба ментора открывают https://app.rs.school/course/mentor/stage-interviews?course=rs-2019-q3
2) На вкладке "Interview" нажимают Cancel у студентов, которых хотят обменять.
3) На вкладке "Avaliable students" забирают нужных студентов, нажав "Want To Interview"
