### ISSUE TITLE
[CV] Use github username in URL instead of uuid

### ISSUE THREAD

**Issue by thezaff** [rolling-scopes/rsschool-app#1742]
**Describe the feature**
Make Public CVs available through URLs which contain Github username of the student, instead of uuid.
E.g: 
Current URLs: https://app.rs.school/cv/{uuid}
Proposed URLs: https://app.rs.school/cv/{username}

I think it would make easier to share or find CVs, if link is lost.

I don't know why uuid were chosen as slug, maybe I am missing some restrictions.

**Comment by valerydluski** [comment]
done
