### ISSUE TITLE
change my Git name profile

### ISSUE THREAD

**Issue by Yarovenko-Dmitry** [rolling-scopes/rsschool-app#176]
**Course**
rs-2019-q3

**What is wrong**
I want to change my Git name profile from "prostiak2019" to "Yarovenko" ( or YarovenkoDm/YarovenkoDmV)

**Comment by apalchys** [comment]
@prostiak2019 Если я правильно понял, то https://github.com/yarovenko твой новый аккаунт? Если да, то не проблема поменять.

**Comment by prostiak2019** [comment]
не совсем так, я хочу поменять нынешний свой ник с prostiak2019 на Yarovenko-Dmitry
переживаю, что могут быть проблемы со скором и баллами, т.к. здесь решение алгоритмических задач лежит
на данный момент у меня 350 баллов.

**Comment by apalchys** [comment]
Проблем не будет. Просто напиши когда поменяешь и я обновлю в приложении. Только не логинься в приложение (https://app.rs.school) после смены, пока я не отпишусь.

**Comment by Yarovenko-Dmitry** [comment]
Yarovenko-Dmitry
новый ник, только что сменил

**Comment by Yarovenko-Dmitry** [comment]
в скоре пока ничего не делаю.
жду отмашку

**Comment by apalchys** [comment]
попробуй залогиниться: http://app.rs.school/login

**Comment by Yarovenko-Dmitry** [comment]
перешел по ссылке, регится не надо было.

в профиле 
Github | https://github.com/yarovenko-dmitry

баллы остались

**Comment by Yarovenko-Dmitry** [comment]
благодарю за содействие.
