### ISSUE TITLE
[Manage Events] Confirmation pop-up before deleting 

### ISSUE THREAD

**Issue by sonejka** [rolling-scopes/rsschool-app#178]
**Where:** 
page 'Manage Events' (https://app.rs.school/admin/events).
**What needs to do:** 
to show a pop-up window with confirmation before deleting the event.
**Why:** 
the user doesn’t understand that deletion is irreversible.

**Additional details:**
Confirmation pop-up should contain the text:
'Are you sure you want to delete this item?'
and buttons: 'Yes' and 'Cancel'.

**Comment by forkollaider** [comment]
https://github.com/rolling-scopes/rsschool-app/pull/279
