### ISSUE TITLE
Feature: Доступ к профилям других менторов

### ISSUE THREAD

**Issue by PoMaKoM** [rolling-scopes/rsschool-app#1786]
**Describe the feature**
Я как ментор, хотел бы иметь возможность просматривать профили других менторов. Видеть их ментити, проведенные курсы и тд.

**Additional context**
Хотя бы видеть **Public Feedback**. А то мои никто не видит(((

**Comment by dzmitry-varabei** [comment]
Сейчас мы смотрим в сторону "public CV", например https://app.rs.school/cv/e22bebb5-8cde-4252-b590-19434de8bc9e
В котором пользователь (студент или ментор) может пошарить о себе ту информацию, которую хочет. 
Единственное, что в данный момент ссылка на cv не отображается рядом с профилем пользователя

**Comment by PoMaKoM** [comment]
Мне кажется менторам не нужны чужие CV менторов. Интересно посмотреть все градитьюты, всех студентов со всех курсов и возможно контакты для связи
