### ISSUE TITLE
[Schedule] Display the task's start date

### ISSUE THREAD

**Issue by sonejka** [rolling-scopes/rsschool-app#179]
**Where:** 
'Schedule' table (https://app.rs.school/course/schedule?course=rs-2019-q3)
**What needs to do:** 
display a record with info about the task's start date. 
**Why:** 
the user doesn’t know when the task begins.

**Additional details:**
I offer: 
- to rename the current tag 'task' to 'deadline', 
- add a new tag 'new task' for records with the task's start date.

Expected view of schedule:
![image](https://user-images.githubusercontent.com/8710230/66926994-51527b80-f02f-11e9-9a3f-b5ad516b12aa.png)

**Comment by forkollaider** [comment]
https://github.com/rolling-scopes/rsschool-app/pull/200

**Comment by forkollaider** [comment]
closing as feature merged
