### ISSUE TITLE
Changes notification

### ISSUE THREAD

**Issue by Anik188** [rolling-scopes/rsschool-app#1795]
Для координаторов курсов будет полезно получать уведомление об изменениях ( касающихся их работы) в РС платформе, во избежания недоразумений.

Пример. В предыдущем запуске курса в кросс-чек таске нужно было указать дату начала и завершения таска ( включая время на непосредственное выполнение задания и время на перекрестную проверку) и в любой момент, времени в пределах дат, можно было запустить чек. В текущем запуске этот функционал работает иначе, кнопка задизейблена, и для запуска пришлось менять дату завершения таска на дату, когда должна быть завершена имплементация. Что отразилось у студентов в виде нотификаций и привело в довольно агрессивной реакции со стороны студентов, которые не читают анонсы и не посещают Q&A вебинары.

**Comment by dzmitry-varabei** [comment]
@Anik188 привет! твою проблему мы поняли. Из вариантов сейчас только следить за чатом разработки RS APP ((
