### ISSUE TITLE
Courses > Copy a course: Cross-check End date is not related to the course start date

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#1799]
When an admin creates a new course from the template, `cross-check end dates` are copied and pasted from the template without a shift. (But the `start date` and `end date` of the tasks are correct).

Expected behavior: 
All task dates depend on the course start date, and all time periods (`Task Start Date`, `Task End Date`, and `Task Cross-check End Date`) are kept.

Steps to reproduce:
1) Open https://app.rs.school/admin/courses
2) Create a new course from the template:
![image](https://user-images.githubusercontent.com/2429680/197827052-4b6872ef-553e-4620-ada1-f86cfea6047d.png)
3) Open a newly created course 
4) Open `Course Tasks`, e.g. https://app.rs.school/course/admin/tasks?course=nodejs-2022-q4
5) Open any task with `crossCheck` type
![image](https://user-images.githubusercontent.com/2429680/197829743-20611734-04f5-4c2f-a2ff-05f4e536a2fb.png)

**Comment by ShaxxKh** [comment]
Taking over this bug
