### ISSUE TITLE
Admin tasks: Default time 

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#1800]
When Course Manager opens the `Admin tasks` page (e.g. https://app.rs.school/course/admin/tasks?course=nodejs-2022-q4) and clicks on the `Add task` button, the default time on the `Course Task popup` is set to the current time, which is not convenient.
<img width="522" alt="image" src="https://user-images.githubusercontent.com/2429680/197969456-940b494a-5fe1-4e89-b410-414f756a602f.png">

Please change the default time to the following:
Start Time: 00:00 UTC
End Time: 23:59 UTC

**Comment by ShaxxKh** [comment]
taking this task over
