### ISSUE TITLE
[Auto-test] Redirect to Login page when submitted with expired token

### ISSUE THREAD

**Issue by ThorsAngerVaNeT** [rolling-scopes/rsschool-app#1803]
**Describe the feature**
Redirect to Login page when submitted with expired token
Backend returns 401 status code with message `{"message":"Unauthorized"}`, app shows error message, but does not redirect to the login page.
![image](https://user-images.githubusercontent.com/17920285/198519183-ca01445a-e6d0-460b-9429-ee9998510fa8.png)

**Comment by valerydluski** [comment]
implemented without a redirect, a clear error message will be displayed and the form will not be reset
