### ISSUE TITLE
Public CV: required fields

### ISSUE THREAD

**Issue by muannna** [rolling-scopes/rsschool-app#1809]
**Describe the bug:**
In CV edit mode fields with phone number and email have become mandatory. Earlier they were not required.

![CV](https://user-images.githubusercontent.com/88070488/198873460-5c27d5d6-562c-4200-98d5-3be2b5d27b49.jpg)

**Expected behavior:**
Leave the phone number and email fields optional to maintain privacy.

**Comment by valerydluski** [comment]
@muannna  thanks for your issue, fixed.
