### ISSUE TITLE
[Manage Tasks] Add more tasks types

### ISSUE THREAD

**Issue by sonejka** [rolling-scopes/rsschool-app#181]
**Where:**
page 'Manage Tasks' (https://app.rs.school/admin/tasks)

**What should be done:**
add types of tasks

**Additional details:**
To provide a more informative schedule, we need to add the following types of tasks:
- Task 
- Test 
- Interview (can be without a score)
- Code Jam (does not have description URL in advance)

All types have start/end dates, which we need to display in the schedule.

**Comment by forkollaider** [comment]
Enum: 'jstask' ,  'htmltask' ,  'externaltask' ,  'test' , 'codejam' , 'interview' .

**Comment by forkollaider** [comment]
FYI:  @lesnitsky

**Comment by forkollaider** [comment]
https://github.com/rolling-scopes/rsschool-app/pull/210

**Comment by forkollaider** [comment]
https://github.com/rolling-scopes/rsschool-app/pull/213
