### ISSUE TITLE
Clean-code appears as a "Missed" task

### ISSUE THREAD

**Issue by elukashova** [rolling-scopes/rsschool-app#1816]
**Describe the bug**
Clean-code task is now visible under "Missed" tasks in the Schedule, even though the task was submitted on time. Moreover, the submitted task has been already reviewed and has the first grades.
Until this morning, the task was visible under "Review".

**To Reproduce**

1. Go to 'app.rs.school'
2. Click on 'Schedule'
3. Click on 'Missed'

**Expected behavior**
The task should be visible under "Review" for those who submitted it on time.

**Screenshots**
<img width="1143" alt="Schermata 2022-11-01 alle 14 59 58" src="https://user-images.githubusercontent.com/102854917/199251160-b3f1a8aa-ca62-4243-a9b4-46fe3a2b4c13.png">

**Device (please complete the following information):**

- OS: iOS, macOS
- Browser: Chrome

**Additional context**
Based on some Discord messages, other students also see it this way.

**Comment by oibioib** [comment]
Сейчас в schedule два события Clean-code-s1e1. 
Одно **Cross-Check: Review** в **Available**, второе **Cross-Check: Submit** в **Missed**.
Во вкладке **Review** пусто.
![rs](https://user-images.githubusercontent.com/103119318/199261721-8cb7fa46-8409-4053-bca1-0b11edecbb23.jpg)

**Comment by AlreadyBored** [comment]
Fix of this bug require custom approach, we need some time for it
