### ISSUE TITLE
Missed task Clean-code-s1e1

### ISSUE THREAD

**Issue by dairinka** [rolling-scopes/rsschool-app#1817]
**Describe the bug**
I submitted task Clean-code-s1e1 at 2022-10-31. And now is participating in cross-check rewiew. But in Schedule table this task is considered missed

**Screenshots**
![image](https://user-images.githubusercontent.com/104695300/199258594-9451b1de-8117-4eef-b70d-3d408d3c55a1.png)
![image](https://user-images.githubusercontent.com/104695300/199258729-05d1a1c2-d0ec-4cd0-94ad-3dc4036be2ef.png)

**Comment by oibioib** [comment]
https://github.com/rolling-scopes/rsschool-app/issues/1816

**Comment by Andkhiz** [comment]
I also submitted task Clean-code-s1e1 at 2022-10-31. And now is participating in cross-check rewiew. But in Schedule table this task is considered missed.
![image](https://user-images.githubusercontent.com/112403780/199310241-26f1d9cc-bb12-434e-a210-3022968c1c51.png)
![image](https://user-images.githubusercontent.com/112403780/199310600-155e16df-c180-4279-979d-1492df95a55b.png)
