### ISSUE TITLE
Schedule: Deprecate Review Tab

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#1819]
<img width="761" alt="image" src="https://user-images.githubusercontent.com/2429680/199293032-fb0e2275-ce50-4ec6-aa56-53213fa0b75e.png">

I propose to keep all the tasks that need to be done in the "Available" tab.

**Comment by TattiMikhailava** [comment]
Rename the 'Review' tab to the new option 'In review' (just the title).

**Comment by AlreadyBored** [comment]
Ticket in a nutshell: only rename "Review" to "In Review"
