### ISSUE TITLE
[Manage Events] Add more events types

### ISSUE THREAD

**Issue by sonejka** [rolling-scopes/rsschool-app#182]
**Where:**
page 'Manage Events’ (https://app.rs.school/admin/events)

**What should be done:**
add more types of events

**Additional details:**
To provide a more informative schedule, we need to add the following types of events:

- Lectures:
    - Online
    - Offline
    - Online/Offline
    - Self-studying
- Warm-up (training tests)
- Info (additional announcements)
- Workshop
- Meetup

**Comment by forkollaider** [comment]
For now:
enum: 'lecture_online' ,'lecture_offline', 'lecture_mixed', 'lecture_self_study' , 'warmup', 'info', 'workshop', 'meetup'

**Comment by forkollaider** [comment]
FYI:  @lesnitsky

**Comment by forkollaider** [comment]
https://github.com/rolling-scopes/rsschool-app/pull/210
