### ISSUE TITLE
CV.HTML, CSS & Git (EN) "Failed requirements: No index.html file. (Status: 404)"

### ISSUE THREAD

**Issue by cskubra** [rolling-scopes/rsschool-app#1823]
**Describe the bug**

**I successfully completed the HTML, CSS & Git (EN) task and got 100 points. But now it shows error. "Failed requirements: No index.html file. (Status: 404)" and my score was zero. Accordingly, I have no index.html file but I have index.html file.**

**To Reproduce**

**Expected behavior**
**My score in CV.HTML, CSS & Git (EN) task should be 100.**

**Screenshots**
![chrome_1fz0Yg5n5x](https://user-images.githubusercontent.com/96026618/199961423-cb0425fc-3d7c-497d-9e72-05d906200e47.png)

**Device (please complete the following information):**

- OS: [Windows 10]
- Browser [Chrome]
- Version [107.0.5304.88 ]

**Additional context**

**Comment by oibioib** [comment]
From your screenshot, you submit task 11.10.2022, but in your repository, you create solution fo this task only 12 days ago - 24.10.2022.
![2022-11-05_103741](https://user-images.githubusercontent.com/103119318/200109304-361a6bd1-fed3-4558-9704-441d57738146.jpg)

**Comment by valerydluski** [comment]
@oibioib Thanks

**Comment by cskubra** [comment]
Hello,
Because of my mistake i delete my repo but after i did  task CV.HTML, CSS & Git (EN) . Then i again did RS school cv. 
![Screenshot_2022-11-07-03-30-05-657_com android chrome](https://user-images.githubusercontent.com/96026618/200204468-e1620399-c77a-4639-bef0-c55fc6707c91.jpg)

**Comment by cskubra** [comment]
@valerydluski Can you check again please? I am trying Restore for sure but it is not working! I am sure about i did task i know about it. But i dont understand what happened!
