### ISSUE TITLE
Score / Max not displayed

### ISSUE THREAD

**Issue by SvetlanaBand** [rolling-scopes/rsschool-app#1824]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

**Additional context**

**Comment by valerydluski** [comment]
@SvetlanaBand  it would be nice to add at least some description

**Comment by SvetlanaBand** [comment]
На моей странице в rs school во вкладке  Schedule  не отображаются баллы score/max по некоторым заданиям. Напр. нет результата  Clean-code-s1e1 . По ближайшим заданиям не отображаются максимальные баллы. Напр  HTML-Builder
  
>Суббота, 5 ноября 2022, 23:30 +03:00 от Valery ***@***.***>:
> 
> 
***@***.*** it would be nice to add at least some description
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you were mentioned. Message ID:  <rolling-scopes/rsschool-app/issues/1824/1304636311 @ github . com> 
 
 
--
СВЕТА БАНДЮКЕВИЧ
Отправлено из Почты  Mail.ru
