### ISSUE TITLE
Feature to reset default codewars username

### ISSUE THREAD

**Issue by mkazzz** [rolling-scopes/rsschool-app#1827]
Hi.
I have problem with logging in to my actual codewars account and I can't submit second auto-test. Probably the e-mail of the account linked with my github was the same as the one set up a few years ago on codewars. Until I logged out of the browser, everything was ok. After that I lost access to the account with the entered username suggested in RS App . (Still wait for codewars admins response.). There is no way to change this username in RS App and I can't submit it via autotest. Even if I create a new account on codewars, I can't set username from RS App because it is already taken. Any chance to generate that username once again?

**Comment by valerydluski** [comment]
It will not work to form a new nickname, it is formed based on your nickname on the github. you need to regain access to your codewars account
