### ISSUE TITLE
Html-builder as missed task

### ISSUE THREAD

**Issue by dairinka** [rolling-scopes/rsschool-app#1833]
**Course**
Js/Front-end 2022Q3

**What is wrong**
HTML-builder task appeares as missed In Schedule table, but was submitted in time. It's the same situation as Clean-code. When I was submiting this task, clock icon before the task name in the form was red, but time didn't gone.
![Screenshot_20221108-165505_Chrome](https://user-images.githubusercontent.com/104695300/200598456-2238c06a-1f6e-4a11-8922-e197a54fa2f0.jpg)
![Screenshot_20221108-165649_Chrome](https://user-images.githubusercontent.com/104695300/200598487-bcf2c6c9-e2d0-4887-97c8-b07587efbbb8.jpg)

**Comment by AlreadyBored** [comment]
@dairinka Could you please provide info, is it still displayed as missed? Should be displayed correctly now

**Comment by dairinka** [comment]
> @dairinka Could you please provide info, is it still displayed as missed? Should be displayed correctly now


everything is correct now
