### ISSUE TITLE
Missed task

### ISSUE THREAD

**Issue by TheExtraOne** [rolling-scopes/rsschool-app#1835]
Статус задания HTML-builder отображается как 'Missed', хотя ссылка на него была засабмичена вовремя. Скрин ниже:

![image](https://user-images.githubusercontent.com/99993058/200858519-dec05ae0-0252-4fdf-96e8-9b2b0b92e1ad.png)

**Comment by AlreadyBored** [comment]
@TheExtraOne Please re-check, it should be displayed correctly now
