### ISSUE TITLE
Student's dashboard: Tasks statistics widget

### ISSUE THREAD

**Issue by ktnktag** [rolling-scopes/rsschool-app#1838]
**1. Widget view**
The widget is too large.
Too much indentation at the top and bottom of the chart.
Remove "Archived" from statistics.

Figma [link ](https://www.figma.com/file/D31S4jMK4EQfnpvguVjc8W/RS-Redesign_Ant-design?node-id=131345%3A440606&t=iI0bT2AsBHseDmcI-1)
<img width="570" alt="Screenshot 2022-11-13 at 22 50 57" src="https://user-images.githubusercontent.com/101800066/201546301-2263d7a2-e1ca-46a7-8bfa-b047e13af7e4.png">

**2. Resizing**
widget crashes on page resize
![Frame 461](https://user-images.githubusercontent.com/101800066/201546226-a8714b92-20ef-4849-a308-aecd9047d73e.png)

**Comment by aaliakseyenka** [comment]
@ktnktag 
1) The widget is too large.
could u please be more specific. figma contains only one resolution 1440px. For this case the chart is 208px X 208px as on figma. Are u talking about the width of the round? please provide desired width .

![Screenshot 2022-11-14 at 09 43 44](https://user-images.githubusercontent.com/1570982/201614686-b2baf75a-a8b8-480d-8c46-b868f5a4bba5.png)

2) widget crashes on page resize

could u please provide video? does it break and never gets to right state or is it about constant re-rendering and during it having a bad state?
