### ISSUE TITLE
RS 2019 Q3: Issues по распределению студентов

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#186]

**Comment by ragexe** [comment]
Smth went wrong:
https://app.rs.school/course/mentor/stage-interviews?course=rs-2019-q3
![image](https://user-images.githubusercontent.com/10881229/67085450-871a7000-f1a7-11e9-937f-8da66f03df9c.png)
![image](https://user-images.githubusercontent.com/10881229/67085470-8d105100-f1a7-11e9-8e44-a270cc721810.png)
![image](https://user-images.githubusercontent.com/10881229/67085479-926d9b80-f1a7-11e9-8dad-e6e325263bcf.png)
![image](https://user-images.githubusercontent.com/10881229/67085488-9699b900-f1a7-11e9-91a6-a24e1de1e9dd.png)

**Comment by MagicCurlyHair** [comment]
![2019-10-18_12h56_12](https://user-images.githubusercontent.com/38192464/67085637-d660a080-f1a7-11e9-8746-f157c5e81b40.png)
One of my students is assigned to another mentor.

**Comment by prodislav** [comment]
не отобразился в списке менторов
github:
prodislav

**Comment by sushchenja** [comment]
albertkengerli was already booked by another mentor (kreezag)
![image](https://user-images.githubusercontent.com/32489046/67085834-41aa7280-f1a8-11e9-8f41-7bc6b2cf1ae4.png)

**Comment by Ivan456** [comment]
Ко мне не попали студенты, которых я запросил

**Comment by ekaterina-glazunova** [comment]
https://github.com/Grenzen - студенка, которая была добавлена через форму, но в финальный распред не попала. 

и она минская, а остальные все из России. можно всё же всех минских? 

если нет, то я всё равно объединяюсь с @artsiomkhvastsiuk, а ему как раз все минские попались (4 человека), мы могли бы всех 5х на двоих взять.

**Comment by EvgeniiGrh** [comment]
![issue](https://user-images.githubusercontent.com/31861813/67086487-8be02380-f1a9-11e9-9026-bccbaa7cc5c5.jpg)

**Comment by stanislawa** [comment]
![image](https://user-images.githubusercontent.com/25182725/67086676-f42f0500-f1a9-11e9-8eed-428cfb207b58.png)
![image](https://user-images.githubusercontent.com/25182725/67086698-001ac700-f1aa-11e9-9f65-8c849860bd1b.png)
https://github.com/Alice-Ermakova
https://github.com/margo24

**Comment by andrey-karnaukhov** [comment]
Ко мне попали студенты откуда угодно только не из Сергиева Посада, при том что студенты из Сергиева Посада попали другим людям.
![image](https://user-images.githubusercontent.com/55391431/67086887-74ee0100-f1aa-11e9-9fd4-d2eacf576640.png)

**Comment by sakenalimbayev** [comment]
Не нашёл студентов githubId: sakenalimbayev

**Comment by mishapateyuk** [comment]
olgamazyuk попала ко мне и к другому ментору

**Comment by denitrip** [comment]
![Untitled](https://user-images.githubusercontent.com/29579085/67087589-e5e1e880-f1ab-11e9-85da-aee699f81d32.jpg)
выбранный мной студент попал к другому человеку

из указанных студентов не попала ко мне
anastasiyahomanava

**Comment by antonpalinau** [comment]
Не нашёл студентов githubId: antonpalinau

**Comment by apalchys** [comment]
@denitrip 

>из указанных студентов не попала ко мне anastasiyahomanava 

подскажи, а где ты указывал эту студентку? В гугл форме ее не видно.

**Comment by denitrip** [comment]
@apalchys 

я добавил её после того. как была первая привязка студентов к менторам. Возможо не выгружали новые данные?
Скрин текущей формы прикрепляю


![Untitled](https://user-images.githubusercontent.com/29579085/67088455-d82d6280-f1ad-11e9-9f4b-6af0e007cfe0.jpg)

**Comment by apalchys** [comment]
@ekaterina-glazunova у нас к сожалению нету такой студентки зарегистрированной на текущий курс. Регистрировалась ли она в https://app.rs.school?

**Comment by apalchys** [comment]
@ragexe @sushchenja @EvgeniiGrh @stanislawa @Ivan456 @sakenalimbayev @antonpalinau Проблема должна быть исправлена. Спасибо за тестирование.

**Comment by apalchys** [comment]
@prodislav @tuwhoo вы попали в резервный пул. Из распределения были убраны студенты которые проходят собеседования на short track, но так как не все попадут туда, то нужен запас менторов для них. 
А также по опыту всегда происходят "неожиданности" и у кого из ментором не получается провести собеседование.

**Comment by ekaterina-glazunova** [comment]
> @ekaterina-glazunova у нас к сожалению нету такой студентки зарегистрированной на текущий курс. Регистрировалась ли она в https://app.rs.school?

регистрировалась (на прошлый набор)
сейчас она видит вот что 
![image](https://user-images.githubusercontent.com/46481330/67090977-12016780-f1b4-11e9-99d9-4be38794f527.png)

**Comment by ekaterina-glazunova** [comment]
и ещё я удаляла студента https://github.com/tial1 (он решил, что в этом наборе у него не получается), но он мне всё равно выпадает при шаффле :)

**Comment by vpanteleev** [comment]
После первого шаффла были все ребята из РБ, сейчас нету ни одного из РБ. Это оки или что-то пошло не так?

location: Minsk

**Comment by apalchys** [comment]
@ekaterina-glazunova напиши пожалуйста мне в дискорде при возможности `apalchys`

@vpanteleev это ок. первое распределение было не совсем корректным и было много дубликатов. К сожалению менторов из Минска больше чем студентов в процентном соотношении.

**Comment by ton9q** [comment]
github: ton9q

не отображаются студенты
имеется только следующее:
![image](https://user-images.githubusercontent.com/26420726/67103541-028f1800-f1ce-11e9-8157-0d9ccc746927.png)

**Comment by apalchys** [comment]
@ton9q Так как выявилось несколько проблем организационного порядка, нужны доработки и будет новое распределение в течении выходных. Пока все старые пары "удалены"

**Comment by Iliyapunko** [comment]
Доброго времени суток. Я студент из Минска и до сих пор без ментора. 
Пробовался на Short Track, но меня вроде как отклонили.
Ilya Punko.

**Comment by MarchenkoRuslan** [comment]
Как попасть к ментору? Luffi свободен еще?

**Comment by BlazarQSO** [comment]
Доброго времени суток. Позвонил своему ментору @vladsemenik, соответственно указанного в ссылке https://app.rs.school/course/student/stage-interview?course=rs-2019-q3. Он сказал, что заявки на ментора не подавал.

**Comment by JackFrost58** [comment]
Доброго времени суток. Подскажите куда писать ментору, не имею понятия, что значит Live
![image](https://user-images.githubusercontent.com/33397907/67230395-e1d0f780-f445-11e9-8ce8-bac59aa6e6df.png)

**Comment by MagicCurlyHair** [comment]
@JackFrost58 привет, это скайп скорее всего

**Comment by JackFrost58** [comment]
Я искал в Скайпе, но результатов нет

пн, 21 окт. 2019, 23:46 Heorhi Shakanau <notifications@github.com>:

**Comment by xxxzez** [comment]
Здравствуйте. Мой ментор (aloeugene) сказал что организаторы не успели вычеркнуть его из списка менторов. Сказал обращаться к организаторам чтобы перераспределили. Я @xxxzez(telegram, github, discord) Что делать?

**Comment by starff** [comment]
Добрый день, ментор к которому меня распределили, сказал что у него не получится этим заниматься, что делать?

**Comment by apalchys** [comment]
@Iliyapunko студенты шорт-трека будут распределены сразу, когда мы получим финальный список кого взяли, а кого нет. stay tuned!

@MarchenkoRuslan достаточно прочитать анонсы в дискорде, где описано как узнать кто твой ментор :) https://app.rs.school/course/student/stage-interview?course=rs-2019-q3

@BlazarQSO свяжись пожалуйста еще раз с ментором. он готов менторить теперь.

@JackFrost58 Добавлена колонка с email. Попробуй связаться по email. И совет на будущее, лучше в github issues не публиковать "контактные данные" людей.

@xxxzez @starff будем искать вам замену.

**Comment by bizarre84** [comment]
Добрый день. Мне назначен ментор lexakot Когда я с ним связался он ответил, что вышло недопонимание. Что он планировал менторить давно, а на текущий момент никакой информации про менторство ему не поступило.

**Comment by 2reek** [comment]
Добрый день.  Мой ментор **@amelyanenka** ответил , что отказался от участия. Попросил связаться с организаторами чтобы меня прикрепили к другому.

**Comment by skysharkk** [comment]
Здравствуйте, хотел связаться с ментором, а он пропал из https://app.rs.school/course/student/stage-interview?course=rs-2019-q3.

**Comment by Dmitryi-Lukyantsov** [comment]
Здравствуйте, уже писал что когда связался с назначенным ментором, он сказал что уже не менторит, попросил перераспределить меня к другому, что у меня убрали а другого так и нет

**Comment by dzmitry-varabei** [comment]
@skysharkk в данный момент у нас нет свободных менторов. Будет еще одно дополнительное распределение, после окончания набора на short track.

**Comment by dzmitry-varabei** [comment]
@Dmitryi-Lukyantsov в данный момент у нас нет свободных менторов. Будет еще одно дополнительное распределение, после окончания набора на short track. Подробнее напишу в анонсы.

**Comment by Lina-malina** [comment]
Добрый день. Ментор назначена, но она не может менторить в этом наборе.

**Comment by denitrip** [comment]
@Lina-malina поидее буду ментором я, если ничего не изменится
если что телеграм: denitrip

**Comment by apalchys** [comment]
@Lina-malina @denitrip да, извините за задержку. обновил приложение.

**Comment by llyaRaduk** [comment]
Здравствуйте, связался с назначенным ментором, он сказал что уже  не  может менторить, попросил перераспределить меня к другому, сейчас в stage-interview он пропал, нового не добавляют

**Comment by apalchys** [comment]
@llyaRaduk лучше всего следить за каналом #announcements в Discord. Там эта проблема описывалась. Пока что надо немного подождать.

**Comment by AKutrapali** [comment]
Добрый день. 2 дня назад писали что ментор @amelyanenka не будет работать со студентами.  У меня так же он был назначен и пропал. Прошу назначить другого ментора.

**Comment by serh** [comment]
Добрый день. Я не собираюсь идти во второй этап, не распределяйте на меня ментора.

**Comment by ShotAlex** [comment]
у lsasinovich не получается.
![image](https://user-images.githubusercontent.com/44380695/67492262-cf8dce00-f67e-11e9-91fe-fdd32f6fec30.png)
На данный момент ментор отсутствует.

**Comment by VladimirTyagunov** [comment]
Добрый день. Ментор @anastasia1627 Не выходит на связь.
![image](https://user-images.githubusercontent.com/43645356/67510444-a16bb680-f69d-11e9-9c8e-7baa10153848.png)

**Comment by Gypsynkov** [comment]
Доброе время суток. 2 дня назад по ссылке выдавало ментора, но не было возможности связаться.  Сегодня хотел связаться, но обнаружил по этой же ссылке ничего нету в таблице.  По рекомендациям отписываюсь сюда.

**Comment by dzmitry-varabei** [comment]
@ShotAlex lsasinovich нашла тебе другого ментора. В системе пока не поменяли, так что контакты можешь узнать у lsasinovich

**Comment by dzmitry-varabei** [comment]
@VladimirTyagunov попробуй плиз другие контакты (почта, скайп и т.д.)

**Comment by VladimirTyagunov** [comment]
@dzmitry-varabei писал трое суток назад, ментор сообщения прочитала, но ничего не ответила. Я решил подождать сутки, все таки люди работают, середина недели.
Вчера написал ей еще одно сообщение с вопросом о менторстве - ментор просто удалила все мои сообщения в телеграме. И возникает вот вопрос, есть ли смысл пытаться связываться с ней через почту или скайп?

**Comment by apalchys** [comment]
@ShotAlex у тебя должен быть ментор теперь

**Comment by foxiSfox** [comment]
Добрый день, назначенный мне ментор отказался от меня по причине своей ошибки. Сказал, что мне будет назначен другой ментор в течение дня. Это было утром в четверг. До сих нет.

**Comment by apalchys** [comment]
@foxiSfox а кто был ментором?

**Comment by foxiSfox** [comment]
@apalchys , в телеграмме username @AlevtinaY.

**Comment by apalchys** [comment]
@foxiSfox к сожалению, пока надо подождать. мы ожидаем, что на выходных появится больше доступных менторов.

**Comment by dzmitry-varabei** [comment]
@VladimirTyagunov понял. Сам ей написал. Пока ждем.

**Comment by BuskoViktoryia** [comment]
Здравствуйте, написала своему ментору @beatpilot на указанную почту ( medved.vladislav@gmail.com ) по вопросу согласования даты собеседования, но он до сих пор не ответил. как быть дальше?

**Comment by SergSmith64** [comment]
Сообщаю,  что нашел себе ментора из Саратова:  Ali Gasymov,
https://github.com/alik0211

**Comment by Ambrance** [comment]
Здравствуйте. Прошла собеседование еще в понедельник, а сегодня ментор написал, что несмотря на хорошие результаты у него не получается взять меня к себе. Есть ли еще шанс продолжить учебу в этом наборе или уже нет?..

**Comment by apalchys** [comment]
@Ambrance а кто ментор? Я вижу два интервью у вас.

**Comment by ekaterina-glazunova** [comment]
> Здравствуйте. Прошла собеседование еще в понедельник, а сегодня ментор написал, что несмотря на хорошие результаты у него не получается взять меня к себе. Есть ли еще шанс продолжить учебу в этом наборе или уже нет?..

можно написать khvastsiukartsiom, он как раз ищет человека

**Comment by apalchys** [comment]
@Ambrance как я вижу ваш ментор нашел вам другого. Проверьте контакты м свяжитесь с ним

**Comment by Ambrance** [comment]
@apalchys спасибо, буду пробовать

**Comment by EpicMachine** [comment]
Добрый день, назначенный ментор (@ilyapasyuk) отказался собеседовать по причине: "Произошло недопонимание", пообещав связаться с RS school. Но прошла неделя, а от него ни слуху ни духу. Как быть?

**Comment by ilyapasyuk** [comment]
Всем привет, нашёл этот issue по своему меншену. Прошу помочь @EpicMachine с предоставлением ментора. В анкете на ментора был указан период менторинга -  25 марта 2019 – 25 июня 2019. В тот период со мной никто не связывался, а сейчас неподходящие время. Со мной можно связаться по почте pasyuk.com@gmail.com Спасибо.

**Comment by teffalStudy** [comment]
Вопрос по ментору. Если за две недели он таки и не нашел время провести собеседование, и не появился ни в одно из трех назначенных им же собеседований, как следует действовать в дальнейшем? Со мной можно связаться по почте teffal@mail.ru Спасибо.

**Comment by dzmitry-varabei** [comment]
@EpicMachine будем искать тебе другого ментора
@teffalStudy жду ответа от текущего ментора, если что - буду искать нового

**Comment by SergSmith64** [comment]
Дмитрий, подскажите есть "свободные" менторы из Саратова, работающие в EPAM?

**Comment by teffalStudy** [comment]
Сегодня прошел собеседование со своим ментором. Спасибо, вопрос решился.

**Comment by dzmitry-varabei** [comment]
@SergSmith64 Из саратова у нас всего 2 ментора. Напиши мне плиз в дискорде в чем проблема

**Comment by SergSmith64** [comment]
Дмитрий, написал вам в личку на  Дискорд.

**Comment by IvanMikhailenkaEpam** [comment]
Добрый день. В связи с возросшей проектной нагрузкой не смогу уделять студентам достаточно внимания, не могли бы забрать их себе ? оба прошли интервью 
![image](https://user-images.githubusercontent.com/47179367/68300526-fef4ff80-00ae-11ea-9171-9b160bd3ec12.png)

**Comment by pashaSok** [comment]
Добрый день. Что делать если ментор слетел с менторства?

**Comment by apalchys** [comment]
@IvanMikhailenkaEpam да, забрем студентов.
@pashaSok будем искать замену. как давно ментор сказал, что не будет менторить?

**Comment by pashaSok** [comment]
6 числа

**Comment by Dmitryi-Lukyantsov** [comment]
Здравствуйте в профиле пропал ментор, но в скоре отображается

**Comment by apalchys** [comment]
@Dmitryi-Lukyantsov ненормально. вернули ментора. спасибо.

**Comment by SergeyUV** [comment]
Добрый вечер. Посоветуйте, что делать если ментор вчера ( 13.11.2019 ) сказал, что он уже больше не будет ментором ?
