### ISSUE TITLE
No image in notification email

### ISSUE THREAD

**Issue by oibioib** [rolling-scopes/rsschool-app#1861]
There is no image in notification email.
![2022-11-28_111311](https://user-images.githubusercontent.com/103119318/204227337-d7e23551-b08b-4ac4-8463-20078fa3e690.jpg)

**Comment by aaliakseyenka** [comment]
@oibioib  could u please share OS and the client (web app, mobile app)

**Comment by oibioib** [comment]
@aaliakseyenka 

- OS: Windows 10 Pro (10.0.19042)
- Browser: Google Chrome (107.0.5304.107)
- App: https://mail.google.com/

**Comment by aaliakseyenka** [comment]
thanks, should be fixed in the next emails
