### ISSUE TITLE
Cross-check: Review - Update review doesn't work

### ISSUE THREAD

**Issue by ThorsAngerVaNeT** [rolling-scopes/rsschool-app#1873]
**Describe the bug**
I was going to update my review of student's work at cross-check and when selecting student from select "Student" error appears in the console and submit button does nothing

**To Reproduce**

1. Go to 'Cross-check: Review'
2. Select task
3. Select student that you already have reviewed
4. See error in the console and submit does not work

**Expected behavior**
Submit should work and update student's review

**Screenshots**
![image](https://user-images.githubusercontent.com/17920285/205047379-62583e2c-dfbb-41ed-938c-5263de944807.png)
![image](https://user-images.githubusercontent.com/17920285/205047496-91413904-ce14-49c9-b31e-73ade5d12e23.png)

**Comment by apalchys** [comment]
Fixed by https://github.com/rolling-scopes/rsschool-app/pull/1874

**Comment by apalchys** [comment]
@ThorsAngerVaNeT please check if it's fixed

**Comment by ThorsAngerVaNeT** [comment]
> @ThorsAngerVaNeT please check if it's fixed

Just checked it, everything works fine now. Thank you @andreikovna ♥
