### ISSUE TITLE
"No Data" in Stage Interview

### ISSUE THREAD

**Issue by LighthouseKeeperYN** [rolling-scopes/rsschool-app#188]
**Course**
 rs-2019-q3

**What is wrong**
It seems no mentor was assigned to me despite being in top 1000.

**Comment by Alphajax** [comment]
https://github.com/Alphajax позиция 242

**Comment by dzmitry-varabei** [comment]
@LighthouseKeeperYN 
@Alphajax 
в данный момент вы кандидаты в Short Track, и пока в общих собеседованиях не участвуете

**Comment by anyakonkolovich** [comment]
https://github.com/anyakonkolovich позиция 1002  :))

**Comment by Dmitryi-Lukyantsov** [comment]
здравствуйте, связался с назначенным мне ментором, он сказал что уже не менторит, прошу распределить к другому

**Comment by dzmitry-varabei** [comment]
@Dmitryi-Lukyantsov будет другой

**Comment by SergSmith64** [comment]
https://github.com/SergSmith64
позиция 681
Три дня назад написал  ментору на почту, потом отправил SMS.
Ментор не отвечает.
