### ISSUE TITLE
[Technical screening]   points are not displayed in the score table

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes/rsschool-app#1881]
При сабмите формы Technical screening студентам выставляются баллы, они прибавляются в score, но визуально в таблице не отображаются.
при этом на вкладке submit-review ментор может выставить балл за Technical screening своим студентам, они отобразятся в score и прибавятся к общим баллам студента.

Ожидаемое поведение.
при сабмите формы баллы отображаются в таблице score
на вкладке submit-review таск Technical screening недоступен для выставления баллов

![image](https://user-images.githubusercontent.com/57412523/205578191-f8987d1f-20ce-439c-ad39-2b5ca306ab5d.png)

**Comment by valerydluski** [comment]
в score оценка студентам приходит с таким id
![image](https://user-images.githubusercontent.com/57412523/207010037-bea788f4-0637-4721-89e7-c4608f6eb35a.png)
но таск приходит с другим id
![image](https://user-images.githubusercontent.com/57412523/207010099-d444deb7-d0ae-47ac-ae45-2395ca6d0c18.png)
причем у некоторых студентов нормально приходит

можно посмотреть на моём примере valerydluski - ментор, курс js-fe-2022Q3
![image](https://user-images.githubusercontent.com/57412523/207010339-9b5d33be-73d3-4e80-87ab-7fc7bd97e308.png)

**Comment by Riba0017** [comment]
Студент [mitjasha](https://app.rs.school/profile?githubId=mitjasha) пожаловался на то, что отметка за первое **core-js** интервью **заменилась на 0 и перестала учитываться** в общем скоре спустя какое-то время после выставления. По его словам, она появилась после выставления и позже пропала (возможно из-за манипуляций по исправлению бага).

**Comment by apalchys** [comment]
@Riba0017 Я вижу такое

За первое Core JS стоит 8. Проблема исчезла?

<img width="522" alt="image" src="https://user-images.githubusercontent.com/618807/215761236-c2d953c4-e548-401e-ac74-ec842fe85918.png">

**Comment by Riba0017** [comment]
@apalchys я не верно обозначила, видимо. Да, проблема с Тechnical screening

**Comment by apalchys** [comment]
@Riba0017 поправил для [mitjasha](https://app.rs.school/profile?githubId=mitjasha)

@oibioib такая же проблема у вас?

**Comment by oibioib** [comment]
@apalchys у меня просто 0 за Тechnical screening ещё утром стоял в графе, а сейчас проверил, всё ок, и у всех тоже score за данный task начал отображаться. Всё вроде ок.

**Comment by Riba0017** [comment]
@apalchys да, проблемы больше нет, проверила у всех своих студентов. Спасибо!
