### ISSUE TITLE
Auto-check

### ISSUE THREAD

**Issue by SofiaSevoyan** [rolling-scopes/rsschool-app#1897]
![Screenshot 2022-12-14 121613](https://user-images.githubusercontent.com/119752471/207542884-6deb7545-3081-4dbe-8f08-079e9f71c5d6.png)
 

IDK why but its always showin 404 eror on CV1 MARKDOWN & GIT  . I'm on stage 0 and still can't understend lots of things please I need help with this

**Comment by dzmitry-varabei** [comment]
Duplicate #1107
