### ISSUE TITLE
Problem with the task and scoring 

### ISSUE THREAD

**Issue by Carry144** [rolling-scopes/rsschool-app#1913]
**Course**
JS/FE Pre-School 2022Q4

**What is wrong**
I completed task CV#3. CV. cross check.Сompleted and sent the task on 12/18/2022, the deadline was until 12/19/2022.But it ended up being an overdue assignment.
![Screenshot_2](https://user-images.githubusercontent.com/119880543/208673710-705776a3-90fa-4a9a-8c57-bfe37875d6c7.png)
![Screenshot_3](https://user-images.githubusercontent.com/119880543/208673736-abc10942-e66d-40c9-8281-25444d65994a.png)

**Comment by dzmitry-varabei** [comment]
@Carry144 Fixed. You got 100 points.
