### ISSUE TITLE
Предполагаемый ментор больше не менторит в RSS

### ISSUE THREAD

**Issue by GrafDrakula-BlaBlaBla** [rolling-scopes/rsschool-app#192]
Здравствуйте.
Связался с предполагаемым ментором, но он ответил что  на данный момент не является ментором в RSS.

<img width="1404" alt="Снимок экрана 2019-10-21 в 18 16 28" src="https://user-images.githubusercontent.com/43443152/67218350-e938d680-f42e-11e9-8f27-6b588ebc75f9.png">
<img width="765" alt="Снимок экрана 2019-10-21 в 18 17 56" src="https://user-images.githubusercontent.com/43443152/67218485-1dac9280-f42f-11e9-954d-d76d43dacd7b.png">
<img width="775" alt="Снимок экрана 2019-10-21 в 18 18 26" src="https://user-images.githubusercontent.com/43443152/67218525-2e5d0880-f42f-11e9-80e9-be3e9602379c.png">

**Comment by dzmitry-varabei** [comment]
@GrafDrakula-BlaBlaBla у тебя будет другой ментор

**Comment by GrafDrakula-BlaBlaBla** [comment]
Хорошо
Контакты нового ментора будут там же ?
Спасибо

вт, 22 окт. 2019 г. в 10:40, Dzmitry Varabei <notifications@github.com>:

**Comment by apalchys** [comment]
@GrafDrakula-BlaBlaBla да.
