### ISSUE TITLE
Mentor Registry: Ability to Resend Confirmation

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#1920]
Please add the following actions to the mentor registry page:
1) Ability to Resend Confirmation
2) Copy the confirmation link
<img width="777" alt="image" src="https://user-images.githubusercontent.com/2429680/209321973-591ca638-b2d5-4d49-9667-c6201788edfc.png">

**Comment by valerydluski** [comment]
@dzmitry-varabei, we have the functionality to resend notifications.
To do this, you need to press the edit button and resubmit the form.
![image](https://user-images.githubusercontent.com/57412523/209790921-3493554a-b73a-4ef4-b4e3-6c4b36eb1624.png)
![image](https://user-images.githubusercontent.com/57412523/209790963-1a7feca2-8a34-44cb-9cf0-06c3623621fa.png)

**Comment by dzmitry-varabei** [comment]
> @dzmitry-varabei, we have the functionality to resend notifications. To do this, you need to press the edit button and resubmit the form. ![image](https://user-images.githubusercontent.com/57412523/209790921-3493554a-b73a-4ef4-b4e3-6c4b36eb1624.png) ![image](https://user-images.githubusercontent.com/57412523/209790963-1a7feca2-8a34-44cb-9cf0-06c3623621fa.png)

It's not obvious at all :( It's better to make a separate button

**Comment by dzmitry-varabei** [comment]
@ktnktag ▄ ▄ ▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄ ▄ ▄! S.O.S! We have a UX bug here

**Comment by ktnktag** [comment]
As a part of 
https://github.com/rolling-scopes/rsschool-app/issues/1968
