### ISSUE TITLE
Ошибка с аккаунтом

### ISSUE THREAD

**Issue by OlegLeD** [rolling-scopes/rsschool-app#1932]
**Course**
JS/FE Pre-School 2022Q4

**What is wrong**
When connecting to my account, I got an error that I was not connected to any course, and when I reconnected, all statistics were reset
![ошибка](https://user-images.githubusercontent.com/120183035/210795107-49747986-d0b9-4a88-b157-58de60ca19c7.png)

**Comment by dzmitry-varabei** [comment]
The issue is no longer relevant
