### ISSUE TITLE
[Course Admin - Cross-Check Table] Add ability to extract submitted cross-check URLs to file

### ISSUE THREAD

**Issue by ThorsAngerVaNeT** [rolling-scopes/rsschool-app#1943]
**Describe the feature**
Add an ability for a course admin to extract submitted cross-check URLs to file (csv):
```csv
URL;Github
https://github.com/rolling-scopes-school/thorsangervanet-JSFE2022Q1/pull/7;thorsangervanet
```

**Comment by valerydluski** [comment]
this functionality should be available to admins, course managers and dementors
