### ISSUE TITLE
Cross-Check 'Plants1' - 'elkarabino-JSFEPRESCHOOL2022Q4'

### ISSUE THREAD

**Issue by ElKarabino** [rolling-scopes/rsschool-app#1947]
1. https://rolling-scopes-school.github.io/elkarabino-JSFEPRESCHOOL2022Q4/plants/

2. https://github.com/rolling-scopes-school/elkarabino-JSFEPRESCHOOL2022Q4

3. https://github.com/rolling-scopes-school/tasks/blob/master/tasks/plants/plants-part1.md

4.https://rolling-scopes-school.github.io/checklist/ Plants#1

5.
![image](https://user-images.githubusercontent.com/54068266/212463510-8769ff03-4273-40d7-a24a-b42a6bb1fcb5.png)
![image](https://user-images.githubusercontent.com/54068266/212463574-68a6c491-4ef3-40dc-9304-7ebafd3b9dc6.png)
![image](https://user-images.githubusercontent.com/54068266/212463585-09bfff9c-ff32-4248-88cf-c31e8d1a1b94.png)

6. Я уверен, что в моей работе нет причин, чтобы снимать больше 10 пунктов. Максимум, можно придраться к несовпадениям по перфектпикселю, но нигде нет разницы в 10 пикселей. Возможно, моя оценка не изменится, но я хотел бы обратить внимание на таких проверяющих, как мой аноним. Ведь от его неправильной оценки посрадал, скорее всего, не только я

7. 93 балла

**Comment by dzmitry-varabei** [comment]
@ElKarabino привет! этот репозиторий чисто для RS APP. Апелляции нужно подавать https://github.com/rolling-scopes-school/support/
