### ISSUE TITLE
Cross-Check Review (bug with history)

### ISSUE THREAD

**Issue by i0rdan** [rolling-scopes/rsschool-app#1952]
**Describe the bug**
History is not cleared after task switching.

**To Reproduce**
1. On main page click Cross-Check Review button.
2. Select active task.
3. Select student to check review(you could see your review below History label).
4. Select any future task.
5. You still could see your review below History label.

**Expected behavior**
History clearing

**Screenshots**
First 3 steps:
![image](https://user-images.githubusercontent.com/55188582/212869896-1bddd00c-f187-417a-bcb0-1a947d9c7ca5.png)

4 and 5 steps:
![image](https://user-images.githubusercontent.com/55188582/212870074-d381da73-07c3-4188-8ee8-524fc4b3c795.png)

**Device (please complete the following information):**

- OS: Ubuntu
- Browser Chrome
- Version 22.04

**Comment by valerydluski** [comment]
@i0rdan Thank you for the issue, we have added a warning.
