### ISSUE TITLE
Сломался легендарный waitlist

### ISSUE THREAD

**Issue by EvgeniiKolesnikov** [rolling-scopes/rsschool-app#1955]
**Course**
JavaScript/Front-end 2022Q3

**What is wrong**
Регистрировался на CoreJS Interview 3.01, но это, как оказалось, для вас уже поздно...
Но ментор не смогла найти в waitlist конкретно сегодня 18.01

**Comment by dzmitry-varabei** [comment]
@EvgeniiKolesnikov я вижу что у тебя уже есть оценка за это интервью
