### ISSUE TITLE
[RSSchool 2020 stage#1] Preparation

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#196]
-----------------------------------------------
**Отредактировать скринкасты для stage#1**

Последовательность тем можно брать отсюда: вкладка stage#1 2019Q3
https://docs.google.com/spreadsheets/d/1oM2O8DtjC0HodB3j7hcIResaWBw8P18tXkOl1ymelvE

Оформить на русском здесь:
https://github.com/rolling-scopes-school/lectures/blob/master/lectures/screencast/stage-1-ru.md

Оформить на английском здесь:
https://github.com/rolling-scopes-school/lectures/blob/master/lectures/screencast/stage-1-en.md

Что должно содержаться в описании:
- Тема лекции.
- Автор, с указанием также имени как в дискорде, для того, чтобы можно было в questions-to-admins или proposals ссылаться на автора лекции.
- Ссылка на ютуб видео с таймкодами, либо каждое видео по разделам отдельно.
- Ссылка на слайды / презентации.
- Ссылка на исходники, если они есть в открытом доступе.

-----------------------------------------------
**Разметить видео на Youtube**

- Таймкод, с какого момента начинается раздел.
- '+'  если тема подготовлена хорошо, и переработки не требует. '-' если тема подготовлена плохо, либо есть технические огрехи. Все видео у меня сложены локально, буду переснимать или переделывать.

-----------------------------------------------
**Домашки stage#1**

markups - задания по верстке
- level-1
- level-2
- level-3

stage-1 - задания на первом стейдже, которые не являются макетами

Ключевые моменты:
- .jpg, .psd - должны лежать в той же папке, что и проект.
- 4 файла - rsapp-draft.md , rsapp-ru.md , rsapp-en.md , rsapp-review.md. Draft сожержит в себе все, что относится к остальным файлам, плюс можно добавлять или редактировать файл относительно замечаний. ru и en - ТЗ на русском и англйском языке. review - то что могут использовать менторы для проверки, а также студенты для самопроверки.
- Разработать автотесты для проверки основных моментов верстки.

-----------------------------------------------
**Поправить расписание на стейдж 1**

- подготовить материалы, и привязать скринкасты.
- сделать тесты заранее, и положить их закрытыми.

**Comment by dzmitry-varabei** [comment]
Сделать автоматизацию проверки первых тасков по верстке - https://github.com/rolling-scopes-school/docs/issues/22

**Comment by veteran0606** [comment]
Здравствуйте! Подскажите как и куда скидывать бейджи по HTML и CSS.. Ссылка которая была указана не выводит меня на нужную страницу.. Спасибо

**Comment by dzmitry-varabei** [comment]
@veteran0606 подробная информация в описании задания - https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-1/HTML-CSS-self-ru.md 
Если что-то не понятно, уточни, пожалуйста, в дискорде. Уже более 900 чел. в этом наборе выполнили это задание, так что все должно быть ок.
