### ISSUE TITLE
Cross-check review: no score warning

### ISSUE THREAD

**Issue by nduchin** [rolling-scopes/rsschool-app#1964]
## No Score Warning
Warning message, which prevent users to submit review with no score without confirmation.
![image](https://user-images.githubusercontent.com/101069410/213996605-3c1074e4-cf6b-486d-bc43-3e1ffcf55119.png)
![image](https://user-images.githubusercontent.com/101069410/214000522-504e6ce8-67e2-46ad-bc95-b3bc31200972.png)

**Comment by valerydluski** [comment]
Thank you for the issue, we have added a warning.
