### ISSUE TITLE
No Data

### ISSUE THREAD

**Issue by spytni1212** [rolling-scopes/rsschool-app#197]
**Course**
 RS-2019-Q3

**What is wrong**
здравствуйте, в Stage Interview день два назад был ментор, щас отсутствует, пишет No Data, место в Score 869

**Comment by apalchys** [comment]
@spytni1212 так произошло, потому что ваш ментор отказался учавствовать в менторинге (и не только он). Мы пытаемся решить эту проблему. Лучше всего следить за announcements в Discord.
