### ISSUE TITLE
Проверка случайной работы: получена работа студента с ментором

### ISSUE THREAD

**Issue by MikAleinik** [rolling-scopes/rsschool-app#1985]
**Описание ошибки**
В панели Dashboard на проверку попала работа студента у которого есть ментор. В ПР уже проведено ревью кода ментором этого студента, но оценка в скор не выставлена.

**Для воспроизведения**
1. Перейти в раздел 'Dashboard'
2. Выбрать вкладку 'Random Task'
3. Нажать кнопку получения задания

**Дополнительно**
Ссылка на ПР https://github.com/A-Hanchar/online-store/pull/27

**Скрины**
![image](https://user-images.githubusercontent.com/84644126/215687444-1e885b5b-f5b1-4536-b7ca-d84ef4bb98d4.png)
![image](https://user-images.githubusercontent.com/84644126/215687286-91fb8dcf-d634-4d38-bf95-0de861f6566a.png)

**Comment by valerydluski** [comment]
![image](https://user-images.githubusercontent.com/57412523/215695132-815462e7-534f-4fd9-ae6b-5b83ba43950d.png)
