### ISSUE TITLE
Banners for the RS Teams section at RS School app 

### ISSUE THREAD

**Issue by TattiMikhailava** [rolling-scopes/rsschool-app#1998]
There are two main user flows for performing group tasks: for students and admins (coordinators). 

To define intarfaces and to enter the section easier, banners show information about screen objectives of the and provide a clear way to get a guidance on how to complete a group task (Tutorial button). 

![student banner RS teams](https://user-images.githubusercontent.com/100757852/216318211-6368c812-5ea5-4a62-915d-3f53eb46f51b.png)
_Main screen of RS Teams for students_ 

![admin banner RS teams](https://user-images.githubusercontent.com/100757852/216317972-b966d053-fc1c-4120-8e10-7081f43138f4.png)
 _Main screen of RS Teams for admins and coordinators_ 

Implement this functionality according to [layout](https://www.figma.com/file/D31S4jMK4EQfnpvguVjc8W/RS-Redesign_Ant-design?node-id=133000%3A473568&t=hag2dBUULsB2AHki-1):  
[Student interface](https://www.figma.com/file/D31S4jMK4EQfnpvguVjc8W/RS-Redesign_Ant-design?node-id=132572%3A463290&t=hag2dBUULsB2AHki-1) 
[Admin interface](https://www.figma.com/file/D31S4jMK4EQfnpvguVjc8W/RS-Redesign_Ant-design?node-id=132786%3A470068&t=hag2dBUULsB2AHki-1)

**Comment by valerydluski** [comment]
Everything has been implemented except for the tutorial button. There is no tutorial yet, so there is no point in adding the button for now.

**Comment by TattiMikhailava** [comment]
Thanks
