### ISSUE TITLE
[Course Event] Minsk time zone in form

### ISSUE THREAD

**Issue by sonejka** [rolling-scopes/rsschool-app#201]
**Where:**
page 'Course Events' (https://app.rs.school/course/admin/events?course=rs-2019-q3)

**What needs to do:**
When users add/edit course events in 'Course Event' popup, they should fill the 'Time' field according to the Minsk time zone (UTC+3).

**Additional details:**
Also need to replace '+02:00' to (UTC+3)

![image](https://user-images.githubusercontent.com/8710230/67556591-b84cf000-f713-11e9-87ce-802b5555f4e7.png)

**Please pay attention:** 
The users have to see events in the schedule according to their time zones!

**Comment by apalchys** [comment]
related https://github.com/rolling-scopes/rsschool-app/issues/215

**Comment by forkollaider** [comment]
will be done in the scope of https://github.com/rolling-scopes/rsschool-app/issues/215
