### ISSUE TITLE
Некоторые профили менторов и студентов недоступны для просмотра

### ISSUE THREAD

**Issue by natein** [rolling-scopes/rsschool-app#2025]
Я подобное наблюдала и раньше, но думала, что может мне не положено их видеть. :)
Но сейчас столкнулась, что недоступен профиль, который я раньше совершенно точно видела: https://app.rs.school/profile?githubId=inikonzs

Сейчас отображается стандартный отказ
![image](https://user-images.githubusercontent.com/12632270/218578465-d4609044-5f97-4998-8ec9-2c9e6da669c2.png)

**Comment by AlreadyBored** [comment]
@natein May I ask you to provide a little bit more context? Why do you think that you should have access to this profile?

**Comment by natein** [comment]
> @natein May I ask you to provide a little bit more context? Why do you think that you should have access to this profile?

У меня роль manager на курсе JavaScript/Front-end 2022Q3, где https://app.rs.school/profile?githubId=inikonzs является ментором.
Роль на курсе JavaScript/Front-end 2022Q3
![image](https://user-images.githubusercontent.com/12632270/219884789-e179f3ee-8ca0-4acc-9fad-1bfbde5eac61.png)

Вспомнила ещё один профиль, который мне недоступен - https://app.rs.school/profile?githubId=developerbottle
Он был ментором на курсе JavaScript/Front-end 2021Q1, где у меня тоже есть роль manager. Этот профиль изначально не был мне доступен.
Роли на курсе JavaScript/Front-end 2021Q1
![image](https://user-images.githubusercontent.com/12632270/219884892-62679e7d-eeaf-432f-82fd-b853b4dd3536.png)
