### ISSUE TITLE
I was expelled

### ISSUE THREAD

**Issue by mamont79** [rolling-scopes/rsschool-app#2027]
**Course**
JS/FE Pre-School 2022Q4

**What is wrong**
Describe data issue
"You expelled by Course Manager or Mentor" 
Прохожу курс. Сегодня захожу (хотел засабмитать ссылку на momentum -проделал пару пунктов, и чтоб потом не пропустить дэдлайн): статус "не активен". В профиле светится что был исключён. Можно узнать почему?
Жалоб не было. Как восстановиться

**Comment by natein** [comment]
В канале #moderation указана причина исключения — списывание Plants #3.

**Comment by mamont79** [comment]
странно

**Comment by natein** [comment]
Обратись к руководителю курса, он восстановит, если сможешь доказать, что не списывал.

**Comment by mamont79** [comment]
это кому-то из модераторов? не нашёл в списке руководителя
