### ISSUE TITLE
Некоторые студенты не попадают в waitlist при регистрации на интервью.

### ISSUE THREAD

**Issue by natein** [rolling-scopes/rsschool-app#2028]
Студент https://app.rs.school/profile?githubId=igormotorin регистрировался на CoreJS Intervies 2, 

![image](https://user-images.githubusercontent.com/12632270/219715142-9c31dda2-d399-4fb6-b8d6-b91519ba7b36.png)

но не попал ни на распределение, ни в wait list.

Это уже не первый случай. [Здесь](https://github.com/rolling-scopes-school/support/issues/831#issuecomment-1400141658) студент https://app.rs.school/profile?githubId=letocode аналогично не попал в wait list CoreJS Interview 1.

Update: Ещё один такой студента https://app.rs.school/profile?githubId=antonskalaban не попал ни на распределение, ни в wait list CoreJS Intervies 2.

**Comment by aaliakseyenka** [comment]
this guy looks like a feature not a bug. the reason - these students where removed from the waitlists, which basically removes availability for students. Although we may enchase the removal from the waitlist to be more granular(per interview)

**Comment by natein** [comment]
> this guy looks like a feature not a bug. the reason - these students where removed from the waitlists, which basically removes availability for students. Although we may enchase the removal from the waitlist to be more granular(per interview)

Почему они были удалены из wait list?

**Comment by aaliakseyenka** [comment]
> > this guy looks like a feature not a bug. the reason - these students where removed from the waitlists, which basically removes availability for students. Although we may enchase the removal from the waitlist to be more granular(per interview)
> 
> Почему они были удалены из wait list?

hard to tell as we don't log the reason.  But we discussed this with the team and decided to add confirmations for such actions to make sure course managers won't remove students by mistake
