### ISSUE TITLE
See one studen twice in the Expel section (and can't see another one)

### ISSUE THREAD

**Issue by DzmitryDzemyanovich** [rolling-scopes/rsschool-app#205]
I can't expel the student because I don't see him on the Expel page.
I see another student twice instead.

My students list on Expel page:
![expel page](https://user-images.githubusercontent.com/2733513/67623570-2fbf7400-f827-11e9-8bcd-f7996531bc6e.png)

My students list on the Stage Interviews page:
![my students](https://user-images.githubusercontent.com/2733513/67623571-30580a80-f827-11e9-8140-41980cb034cb.PNG)

OS: Win10
Browsers: Chrome (v77), Firefox Developer (v71)

**Comment by apalchys** [comment]
>I see another student twice instead.
should be fixed.

>I can't expel the student because I don't see him on the Expel page.
he was expelled automatically because you set "Not" in the feedback.
