### ISSUE TITLE
По-прежнему есть менторы, профили которых не доступны

### ISSUE THREAD

**Issue by natein** [rolling-scopes/rsschool-app#2051]
Сегодня занималась аппрувом регистраций на курс React 2023 Q1.
В списке менторов https://app.rs.school/admin/mentor-registry недоступны профили следующих менторов и кандидатов в менторы:
https://app.rs.school/profile?githubId=linegel
https://app.rs.school/profile?githubId=unsafefunction
https://app.rs.school/profile?githubId=aliaksei-niamkovich
https://app.rs.school/profile?githubId=almondy22
Update: ещё один https://app.rs.school/profile?githubId=tambovchanin

**Comment by dzmitry-varabei** [comment]
@natein привет! а можешь сейчас перепроверить?

**Comment by natein** [comment]
> @natein привет! а можешь сейчас перепроверить?

Все из вышеперечисленных не доступны.

**Comment by AlreadyBored** [comment]
@natein please specify course

**Comment by natein** [comment]
> @natein please specify course
Эти 2 ни с какого курса, ранее они не менторили. В Preferred у них React 2023 Q1, но чтобы заапрувить их, мне нужно сначала посмотреть, кто это такие.
https://app.rs.school/profile?githubId=aliaksei-niamkovich
https://app.rs.school/profile?githubId=almondy22

У следующих менторов в  Preferred  выставлен React 2023 Q1, но поскольку они менторили раньше, я их заапрувила без просмотра данных аккаунта.
https://app.rs.school/profile?githubId=linegel
https://app.rs.school/profile?githubId=unsafefunction

Роль на курсе React 2023 Q1
![react role](https://user-images.githubusercontent.com/12632270/223062634-e51b09f5-05f1-47e3-9eba-675020c5a700.JPG)

**Comment by AlreadyBored** [comment]
In previous fix I've made active course mentors visible for corresponding courses managers, it seems that we need another improvement - make profiles of mentor from registry visible too :)
Got it, thx

**Comment by ktnktag** [comment]
Add possibilities for course managers to see new mentors application not only by "preselected course", but also by "Technologies". 
Because not all mentors choose course on registration

**Comment by AlreadyBored** [comment]
> Add possibilities for course managers to see new mentors application not only by "preselected course", but also by "Technologies". Because not all mentors choose course on registration

Good notice, I put this into [separated ticket](https://github.com/rolling-scopes/rsschool-app/issues/2095) for better dev flow
