### ISSUE TITLE
Wrong frase

### ISSUE THREAD

**Issue by pir-stone** [rolling-scopes/rsschool-app#2055]
**Course**
JS/FE-2023-Q1

**What is wrong**

link - https://github.com/rolling-scopes-school/tasks/tree/master/stage1/modules/rs-school-intro
wrong frase "Ссылки на рекомендуемую для изучения теорию находится в модулях"
correct frase "Ссылки на рекомендуемую для изучения теорию находЯтся в модулях"

![screenshot-github com-2023 03 05-23_13_53](https://user-images.githubusercontent.com/109313364/222980975-19d5c400-6875-4d1e-a499-6e7e6de31e84.png)

**Comment by AlreadyBored** [comment]
@pir-stone thank you, fixed! For future request please consider to open issue in corresponging repository, this one is about RS App :)
