### ISSUE TITLE
Score:  invalid list in first page

### ISSUE THREAD

**Issue by WiiJoy** [rolling-scopes/rsschool-app#2056]
**Course**
JSFE-2023Q1

**What is wrong**
В Score при активном состоянии тулбара Active Students Only на первой странице отображаются неактуальные данные по текущему score студентов. На второй странице и далее данные актуальны.
При неактивном состоянии тулбара Active Students Only данные на всех страницах вроде бы актуальны
<img width="581" alt="Снимок экрана 2023-03-06 в 11 21 23" src="https://user-images.githubusercontent.com/73646765/223026517-f70b8117-7ece-4a61-8cde-b0c7525a731d.png">

<img width="585" alt="Снимок экрана 2023-03-06 в 11 21 38" src="https://user-images.githubusercontent.com/73646765/223026544-dfbdea07-044b-494c-a368-f8b921bde4f7.png">

**Comment by valerydluski** [comment]
fixed
