### ISSUE TITLE
My profile isn't available via link with githubId query param

### ISSUE THREAD

**Issue by pavelrazuvalau** [rolling-scopes/rsschool-app#206]
User (mentor) can access his profile via app.rs.school/profile
However, clicking on his name in the Score table of everywhere else leads to navigating via https://app.rs.school/profile?githubId=id and showing the message "No access or user does not exist".

Priority: Lowest

**To Reproduce**
1. Go to the "Score" table
2. Find your mentee
3. Click on your name under "Mentor" column
4. Observe the error

**Expected behavior**
My profile is opened

**Screenshots**
![image](https://user-images.githubusercontent.com/16886406/67746684-075a9400-fa38-11e9-92a6-70d41a3178f1.png)

**Comment by Alxblsk** [comment]
It seems like not an issue anymore.
