### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by pir-stone** [rolling-scopes/rsschool-app#2060]
**Describe the bug**
weblink doesn't function

**To Reproduce**
1. Click on page https://github.com/rolling-scopes-school/tasks/blob/master/tasks/cv/git-markdown.md link https://mrks77.github.io/rsschool-cv/cv
3. I see 404 error.

**Device (please complete the following information):**
- chrome (109.0.5414.129)

**Comment by dzmitry-varabei** [comment]
@pir-stone thanks! fixed
