### ISSUE TITLE
UX Issue: нет сообщения об успешном обновлении данных на странице "My CV"

### ISSUE THREAD

**Issue by DmitriyAndriyanov** [rolling-scopes/rsschool-app#2073]
**Describe the bug**
При обновлении My CV  в rs app после заполнения полей и нажатия кнопки Submit не очень понятно что инфа ушла - пользователь остаётся на той же странице с теми же полями, никакого success сообщения нет, складывается чувство, что форма не работает.

**To Reproduce**

1. Go to 'My CV' page
2. Change personal information in input fields
3. Click on submit button

**Expected behavior**
Success message should be appear or user should be redirected to another page

**Devices:**
- All

**Comment by ktnktag** [comment]
[Figma link ](https://www.figma.com/file/D31S4jMK4EQfnpvguVjc8W/RS-Redesign_Ant-design?node-id=134434%3A488731&t=M9DaXhJ1t14TCB4o-1) 

Based on existing behaviour for Sharing  
<img width="1412" alt="Screenshot 2023-03-19 at 10 52 24" src="https://user-images.githubusercontent.com/101800066/226167686-238089a1-fcb3-4d20-b432-c2ceb968abed.png">
