### ISSUE TITLE
Can't update the event organizer

### ISSUE THREAD

**Issue by pavelrazuvalau** [rolling-scopes/rsschool-app#2077]
**Describe the bug**
During an update of course events, I'm not able to update an event organizer: I can select it from the autocomplete, but after clicking the submit button it's not been updated

**To Reproduce**

1. Go to the "Course Events"
2. Click on "Edit" under any of the course events
3. Update the course organizer by choosing someone else on the Task Owner autocomplete
4. Click on the "Submit button"
5. See the page after the update

**Expected behavior**
A course event organizer should be updated

**Screenshots**
![image](https://user-images.githubusercontent.com/16886406/224756449-782d68b0-5b0b-4899-af94-d81384fc1107.png)
![image](https://user-images.githubusercontent.com/16886406/224756541-66fd4307-05a9-4b87-a9c6-3c07e6bc411a.png)

**Device (please complete the following information):**

- OS: MacOS
- Browser Chrome
- Version 110.0.5481.177 (Official Build) (x86_64)

**Additional context**

**Comment by valerydluski** [comment]
Thank you, @pavelrazuvalau .
We have fixed this issue. Thank you very much for finding the bug.
