### ISSUE TITLE
Notifications about not read messages in the cross-check forms

### ISSUE THREAD

**Issue by CoracaoDoMundo** [rolling-scopes/rsschool-app#2079]
**Feature:**
Set up notifications about new received messages from a student, who's being checked, or a reviewer in the cross-check review and cross-check submit sections.

**Way of implementation:**
Add a widget to the dashboard that will show that user has new messages. 
- Basic realisation: the number of new messages; 
- Advanced realisation: information about the section which contain new message, quantity of messages and senders names.

Additional functionality: integration with notification functionality by telegram and mail.

**Comment by aaliakseyenka** [comment]
duplicate of https://github.com/rolling-scopes/rsschool-app/issues/1858
