### ISSUE TITLE
Cross-Check Table - Comments - Show

### ISSUE THREAD

**Issue by ThorsAngerVaNeT** [rolling-scopes/rsschool-app#2084]
**Describe the feature**
Should show all conversation between students in my opinion. Now it's show only first comment even if reviewer updated review.

**Comment by valerydluski** [comment]
need to migration to nest
https://github.com/rolling-scopes/rsschool-app/issues/2124

**Comment by valerydluski** [comment]
It is necessary to extract into a separate [component](https://github.com/rolling-scopes/rsschool-app/blob/master/client/src/modules/CrossCheck/components/SolutionReview/SolutionReview.tsx#L128) and reuse in the cross-check table.
