### ISSUE TITLE
Unable to rate 0 in cross-check form

### ISSUE THREAD

**Issue by oibioib** [rolling-scopes/rsschool-app#2091]
**Describe the bug**
In cross-check form each item has stars to rate. If task feature **is not implemented by student at all**, I need to put 0 score, but I can't. If I submit review with 0 points, i receive a message like on screenshot. 

**To Reproduce**
Go to 'RS-APP -> React 2023Q1 -> Cross-Check Review -> React. Components'

**Screenshots**
![rs-error](https://user-images.githubusercontent.com/103119318/226403469-8406e9ce-e609-49bf-9e39-49bd12cfd9d4.jpg)
![rs-error-2](https://user-images.githubusercontent.com/103119318/226403479-fb6ae8ba-b0ef-4ded-8030-434e1aeffcf8.jpg)

**Device (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version 111.0.5563.65 (Official Build) (64-bit)

**Comment by AlreadyBored** [comment]
Will be fixed after merge of https://github.com/rolling-scopes/rsschool-app/pull/2082 in scope of https://github.com/rolling-scopes/rsschool-app/issues/664
