### ISSUE TITLE
Mentor Registry: bug with mentor's deletion

### ISSUE THREAD

**Issue by ktnktag** [rolling-scopes/rsschool-app#2105]
**Describe the bug**
When deleting a mentor's application in the "mentor's registry" table, the application is not deleted and the page crashes to the main page

**To Reproduce**

1. Go to 'Mentor Registry' New application tab
2. Click on '.Delete' button
3. See error

**Expected behavior**
<img width="1437" alt="Screenshot 2023-04-03 at 14 21 45" src="https://user-images.githubusercontent.com/101800066/229507733-5a9e9897-899f-4524-ad51-5e26cb913893.png">
<img width="784" alt="Screenshot 2023-04-03 at 14 22 06" src="https://user-images.githubusercontent.com/101800066/229507800-1f5da7fe-6c0c-44f7-9897-4d790e2c0576.png">

**Comment by natein** [comment]
В таблице https://app.rs.school/admin/mentor-registry отображаются удалённые менторы.
Например: 
https://app.rs.school/profile?githubId=brut-de-brut был удалён, так как для него создали новый аккаунт.
https://app.rs.school/profile?githubId=golubeva-webmaster был удалён, так как ментор уже зарегистрировался на курс JavaScript/Front-end 2023Q1 ранее.

**Comment by natein** [comment]
Ментор https://app.rs.school/profile?githubId=vlaadosiiik не удаляется.
После удаления он появляется в начале списка с обновлённой датой в поле "Send"

**Comment by valerydluski** [comment]
@natein thanks, I found problem
