### ISSUE TITLE
Manage tasks screen: Tasks Used in Courses

### ISSUE THREAD

**Issue by ktnktag** [rolling-scopes/rsschool-app#2106]
**Add column with list of active courses where tasks are used** [Figma ](https://www.figma.com/file/D31S4jMK4EQfnpvguVjc8W/RS-Redesign_Ant-design?node-id=134519%3A489859&t=R8YJoWJDAfVjCpvO-1)
Active courses highlighted blue and showed first; inactive courses highlighted grey color.  
![Group 515](https://user-images.githubusercontent.com/101800066/229611933-c423e3a1-875a-4b2f-b51e-3b1b1d026164.png)

**Full list of courses can be seen in modal** [Figma file](https://www.figma.com/file/D31S4jMK4EQfnpvguVjc8W/RS-Redesign_Ant-design?node-id=134519%3A490720&t=R8YJoWJDAfVjCpvO-1)
Add new section to "Edit" Modal, Active courses highlighted blue and showed first
![Group 515](https://user-images.githubusercontent.com/101800066/229613093-98ccfe8e-fee1-4924-afaa-706f6b458bb4.png)

**Comment by ktnktag** [comment]
Refers to https://github.com/rolling-scopes-school/tasks/issues/1007

**Comment by dzmitry-varabei** [comment]
@ktnktag @ThorsAngerVaNeT thanks a lot!
