### ISSUE TITLE
Status - Inactive

### ISSUE THREAD

**Issue by LiubovMorozova90** [rolling-scopes/rsschool-app#2109]
Hello. In my profile there is an inscription Status - Inactive. At the same time, I complete all tasks, participate in training.

**Screenshots**
![профиль](https://user-images.githubusercontent.com/106303213/229722976-9fabfc74-0d71-469e-95a4-99c016fdf692.PNG)

**Device:**

- Android, phone
- Windows 10, computer

**Comment by natein** [comment]
Зайди в канал #moderation
