### ISSUE TITLE
кнопка пароля для новых членов команды уезжает за пределы блока на мобильном устройстве

### ISSUE THREAD

**Issue by sch-aa-vk** [rolling-scopes/rsschool-app#2134]
**Describe the bug**
кнопка пароля для новых членов команды уезжает за пределы блока на мобильном устройстве

**To Reproduce**
1. Перейдите в раздел "[Team Distributions (Beta)](https://app.rs.school/course/team-distributions?course=react-2023-q1)"
2. Далее откройте "GraphiQL distribution"
3. Нажмите на кнопку "My team"
4. И далее если вы все это сделали на телефоне, то должны увидеть проблему

**Expected behavior**
верстка не должна уплывать

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/89934145/235567866-9efe0af2-40dc-4751-b5ef-7ba48cf13f18.jpg)
**Device:**

- OS: Android
- Browser: Yandex
- Version: latest

**Comment by valerydluski** [comment]
fixed
