### ISSUE TITLE
[Manage Tasks, Manage Events, Schedule] Ability to select timezone

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#215]
Возможность выбирать тайм зону, используемую для отображения расписания или создания тасков, ивентов

**Comment by forkollaider** [comment]
schedule: https://github.com/rolling-scopes/rsschool-app/pull/248

**Comment by forkollaider** [comment]
events view only:https://github.com/rolling-scopes/rsschool-app/pull/249

**Comment by forkollaider** [comment]
tasks create: https://github.com/rolling-scopes/rsschool-app/pull/259

**Comment by forkollaider** [comment]
events crud: https://github.com/rolling-scopes/rsschool-app/pull/298
