### ISSUE TITLE
auto-test: генерируются слишком длинные ники для codewars

### ISSUE THREAD

**Issue by natein** [rolling-scopes/rsschool-app#2151]
При сабмите codewars в auto-test начали генерироваться слишком длинные ники, которые не вмещаются в поле username.

![image](https://github.com/rolling-scopes/rsschool-app/assets/12632270/4e5486a8-73af-49f8-ad62-7d10b3e3dbd3)

![image](https://github.com/rolling-scopes/rsschool-app/assets/12632270/d76eed9f-2b31-46dd-879d-73f8b611d976)

**Comment by EternalRival** [comment]
вижу PR на эту тему, но не совсем понимаю, почему там обрезается больше, чем нужно
https://github.com/rolling-scopes/rsschool-app/pull/2152
в своём PR обрезал до 16 символов, как это было до прошлого коммита, после которого появилась проблема с длинными хэшами
https://github.com/rolling-scopes/rsschool-app/pull/2154

**Comment by valerydluski** [comment]
@natein @EternalRival  фикс вмержили
