### ISSUE TITLE
Too many (required) fields in the stage interview form

### ISSUE THREAD

**Issue by cardamo** [rolling-scopes/rsschool-app#216]
в common info много полей для личных данных.

> Why are you interested in this course?
> What did you graduate from? (university/specialty)
> Do you have any work experience? (not only in IT)
> Have you ever won school competitions?
> Other achievements
> Military Service

Как темы на поговорить они ок, но делать их обязательной частью интеврю очень странно. На главный вопрос беру/не беру эти ответы вряд ли могут повлиять. 
Ни мне (ментору), ни студентам не понятно куда идут эти данные и кто к ним будет иметь доступ (гипотеза студентов - hr-ы епама).

Предлагаю удалить их все или хотя бы сделать опциональными. У следующего набора менторов будет больше времени на настоящие вопросы на интервью :)

**Comment by dzmitry-varabei** [comment]
@cardamo спасибо за предложение! 

Поля
```
What did you graduate from? (university/specialty)
Do you have any work experience? (not only in IT)
Military Service
``` вынесем в профайл студента и сделаем optional

Остальные - просто optional
