### ISSUE TITLE
Admin-sider: open group

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes/rsschool-app#2161]
need to save open group in local storage

**Comment by achhayapathak** [comment]
I don't understand the issue can you please elaborate a little?

**Comment by valerydluski** [comment]
1. The application needs to include a functionality that allows users to collapse or expand groups of menu items. This feature provides a convenient way for users to manage the visibility of different sections within the menu. By clicking on a specific control or icon, users can collapse a group of menu items, hiding the individual items within that group. This helps to declutter the interface and allows users to focus on the relevant sections of the menu.
2. In order to enhance the user experience, the application should also save the state of the menu item groups in the local storage of the user's device. This means that when a user collapses or expands a menu item group, the application remembers the state of that group even after the user navigates away from the page or refreshes it. By storing this information locally, users can return to the application at a later time and find the menu item groups in the same collapsed or expanded state as they left them. This feature provides continuity and personalization, making the application more user-friendly and efficient.
