### ISSUE TITLE
Restrict access to Submit Review menu

### ISSUE THREAD

**Issue by nataliagulko** [rolling-scopes/rsschool-app#2192]
**Describe the feature**
![image](https://github.com/rolling-scopes/rsschool-app/assets/28038704/89ed173e-f7ea-486e-bd80-29212b822f95)

With Mentor's Dashboard mentors have opportunity to submit their reviews from dashboard, so there is no need in separate "Submit Review" functionality for them. 
Restricted access to "Submit Review" menu for everyone **except Admins**.

**Comment by valerydluski** [comment]
@nataliagulko thanks, we have decided to completely remove this page
