### ISSUE TITLE
Email confirm

### ISSUE THREAD

**Issue by WiiJoy** [rolling-scopes/rsschool-app#2212]
**Describe the bug**
Confirmed mail again requires confirmation after some time

**To Reproduce**

1. Go to Profile
2. Click on `Send confirmation email`
3. Open mail and confirm it by click on the link
4. Wait some time
5. PROFIT

**Expected behavior**
Confirmed mail don't requires re-confirmation after some time

**Screenshots**
<img width="410" alt="Снимок экрана 2023-06-28 в 09 23 26" src="https://github.com/rolling-scopes/rsschool-app/assets/73646765/e06be165-82eb-4302-8332-99116d4ef2ba">
<img width="1385" alt="Снимок экрана 2023-06-28 в 09 23 44" src="https://github.com/rolling-scopes/rsschool-app/assets/73646765/1df3d05a-b759-47c4-a22e-fa2325d1bc23">

**Comment by WladSheva** [comment]
This problem is actual also for me.
