### ISSUE TITLE
RS 2019 Q3: Нету приватного репозитория

### ISSUE THREAD

**Issue by apalchys** [rolling-scopes/rsschool-app#224]
Указывайте максимум деталей

Ваш репозиторий должен быть вида:
https://github.com/rolling-scopes-school/GITHUB_USERNAME-RS2019Q3

Приглашение должно быть доступно тут: https://github.com/rolling-scopes-school/GITHUB_USERNAME-RS2019Q3/invitations 

`GITHUB_USERNAME` заменить на свой github аккаунт

Пример: 
https://github.com/rolling-scopes-school/applelearnsjs-RS2019Q3
https://github.com/rolling-scopes-school/applelearnsjs-RS2019Q3/invitations

**Comment by andreyKozik** [comment]
добрый день, до сих пор нет приглашения приватного репозитория , собеседование с ментором прошел, ментор уже выставил первые оценки за задания, по ссылкам которые выше выдаёт 404 ошибку, почту и уведомления на гите проверял нигде ничего нет

**Comment by apalchys** [comment]
@andreyKozik репозиторий был создан. В ссылках выше надо подставлять свой github:
https://github.com/rolling-scopes-school/andreykozik-RS2019Q3/settings/collaboration
