### ISSUE TITLE
Students with 'Inactive' status should not be assigned to final task teams

### ISSUE THREAD

**Issue by haslie22** [rolling-scopes/rsschool-app#2240]
**Describe the bug**
The students, who were expelled from course, have been assigned to teams to accomplish final task during the random distribution.

**Expected behavior**
These students should not be assigned to teams at all, or they should have the possibility to form their own teams consisting of only expelled students, to complete the task without participation in final task presentations and without getting score points for it.

**Screenshots**
![image](https://github.com/rolling-scopes/rsschool-app/assets/79032502/83cccd3e-bbc8-4d61-8f1f-d8accb429d51)

**Device (please complete the following information):**
Common RS App platform bug

**Comment by valerydluski** [comment]
fixed
