### ISSUE TITLE
Score: filters by specific criteria among all students don't work properly

### ISSUE THREAD

**Issue by haslie22** [rolling-scopes/rsschool-app#2241]
**Describe the bug**
There is a scenario when 'search' button in filtering students by name among all students (toggle 'Active Students Only' placed in 'off' position) has click animation, but no fetch request is sent and no further data renewal happens. 

**To Reproduce**

1. Make sure you are logged in at https://app.rs.school/
2. Go to 'Score' tab
3. Click at any magnifier icon in table header (GitHub, Name, City or Mentor columns)
4. Type the search criterion text
5. Click 'Search' button
6. Place 'Active Students Only'  toggle bar in 'off' position
7. Click the same magnifier icon you've clicked in step 3
8. See your search criteria text preserved; now click 'Search' button
9. Make sure no fetch request in Network tab of DevTools is sent
10. Make sure no inactive students matching this criterion appear in score table

**Expected behavior**
Inactive students matching the search criteria should appear in the table after the 'Search' button is clicked (step 7 in bug reproduction paragraph)

**Screenshots**
Screencast link: [here](https://www.awesomescreenshot.com/video/19540910?key=757ecc0ba285d97dfcaefc5f567791a1)

**Device (please complete the following information):**

- OS: MacOS Ventura 13.4.1
- Browser: Chrome
- Version: 114.0.5735.198
***
- OS: iOS 16.6
- Browser: Safari 
- Version: 16

**Comment by thirdmadman** [comment]
@haslie22 
Should be fixed, check pls

**Comment by haslie22** [comment]
@thirdmadman 
Works as expected, thank you! 🚀
