### ISSUE TITLE
Mentor dashboard: отображение ранее выставленной оценки в инпуте модалки сабмита оценки

### ISSUE THREAD

**Issue by WiiJoy** [rolling-scopes/rsschool-app#2244]
**Describe the bug**
В Mentors Dashboard после выставления оценки студенту за таск с таба In Review и ее сабмита, при открытии модалки выставления оценки для следующего студента инпут скоры уже заполнен предыдущей выставленной оценкой

**To Reproduce**

1. Go to 'Mentors Dashboard'
2. Click on 'Submit' in any line of the student task in tab 'In Review'
3. Enter value in Score Input
4. Click on Submit
5. Repeat step 2
6. PROFIT

**Expected behavior**
При открытии модалки сабмита оценки за таск в табе 'In Review' инпут оценки всегда пустой

**Comment by valerydluski** [comment]
It looks like the same problem.
https://github.com/rolling-scopes/rsschool-app/issues/2035
