### ISSUE TITLE
Cross-check: student select

### ISSUE THREAD

**Issue by NikitaKorevo** [rolling-scopes/rsschool-app#2253]
**Describe the bug**
AxiosError: Request failed with status code 400 on cross-check review page

**To Reproduce**

1. `npm run start`
2. Go to 'Cross-Check: Review'
3. Choose task
4. Choose student
5. Click close icon inside select
6. See error
![image](https://github.com/rolling-scopes/rsschool-app/assets/48645737/8cf84ece-1503-4bb9-9f72-543ebc043481)

**Expected behavior**
Page without error

**Screenshots**
![before](https://github.com/rolling-scopes/rsschool-app/assets/48645737/f4826cb9-c7d3-4b7b-b0d8-4c5d35116b2b)

**Comment by dzmitry-varabei** [comment]
@NikitaKorevo Hi! We have checked and it looks like this bug is not reproducible in a production environment
