### ISSUE TITLE
Migrate Course Mentors Endpoints from Koa to NestJS

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes/rsschool-app#2255]
We need to migrate the following endpoints from our old Koa server to the new NestJS server:

- `getMentors`
- `getMentorsDetails`
- `createMentors`
- `searchMentors`
- `assignStudents`
- `getMentorsDetailsCsv`

https://github.com/rolling-scopes/rsschool-app/tree/master/server/src/routes/course/mentors

**Comment by ThorsAngerVaNeT** [comment]
Took in work

**Comment by ThorsAngerVaNeT** [comment]
I believe the `getMentors`, `createMentors`, and `assignStudents` endpoints are not used anymore...
@apalchys could you please confirm that?
