### ISSUE TITLE
[Submit Scores] Ability to update score/comments after task review submission 

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#227]
Based on question from mentor:
*“Когда студент что то исправил и нужно поменять ему оценку. Как в апке школы делать? Просто еще раз закомитать задание с новой оценкой или какой алгоритм?”*

**Comment by apalchys** [comment]
Done

**Comment by dzmitry-varabei** [comment]
@apalchys Андрей, спасибо!
