### ISSUE TITLE
[Schedule]: display task owner in "Organizer" column

### ISSUE THREAD

**Issue by sonejka** [rolling-scopes/rsschool-app#228]
**Where:**
'Schedule' table (https://app.rs.school/course/schedule?course=rs-2019-q3) 

**Current situation:**
'Schedule' table displays only event organizers

**What needs to do:**
display task owner in column "Organizer"

**Comment by forkollaider** [comment]
https://github.com/rolling-scopes/rsschool-app/pull/303
