### ISSUE TITLE
Score: show myself always in the first position

### ISSUE THREAD

**Issue by NikitaKorevo** [rolling-scopes/rsschool-app#2285]
**Describe the feature**

![image](https://github.com/rolling-scopes/rsschool-app/assets/48645737/dc8ec98e-1592-4b63-9cf6-339bfc46ed88)
![image](https://cdn.discordapp.com/attachments/752386262635118602/1039388390874947684/score.JPG)

**Additional context**

**Comment by dzmitry-varabei** [comment]
@NikitaKorevo thanks a lot!
