### ISSUE TITLE
[Course Events]: impossible to clear the "Organizer" field

### ISSUE THREAD

**Issue by sonejka** [rolling-scopes/rsschool-app#229]
**Where:**
Go to page: https://app.rs.school/course/admin/events?course=rs-2019-q3  

**Reproduce steps:**
Click the "Edit" button in the "Event" row.
Try to make the "Organizer" field empty.

**What is wrong:**
You can edit the "Organizer" field, but it is not possible to clear the "Organizer" field, although this field is not required.

**Additional info:**
We need to have the ability to clear the 'Organizer' field for 'self-study' lectures.

**Comment by forkollaider** [comment]
https://github.com/rolling-scopes/rsschool-app/pull/348
