### ISSUE TITLE
Task start and end time differs in mobile version of schedule

### ISSUE THREAD

**Issue by haslie22** [rolling-scopes/rsschool-app#2312]
**Describe the bug**
Start Date and End Date of task in Schedule tab of mobile version differ from desktop version (both in DevTools responsive mode and on physical devices).

**To Reproduce**

1. Go to [RS App](https://app.rs.school)
2. Go through login process
3. Make sure you've enrolled in at least one active course
4. Go to Schedule tab
5. Pay attention to the Start Date and the End Date of whichever task
6. Follow one of the two options of your choice:
    - Go to Devtools Responsive mode and make screen width <= 768px
    - Repeat steps 1-4 on physical device which screen width <= 768px
7. Make sure the Start Date and the End Date of the task from the step 5 differ

**Expected behavior**
1. Repeat steps 1-6 from "To Reproduce" instruction
2. Make sure the Start Date and the End Date of the task from the step 5 remain the same

**Screenshots**
https://www.awesomescreenshot.com/video/21255744?key=32ad8ca9f10224777c8e0d5f7f3c9265

**Device (please complete the following information):**

Common RS App bug

**Additional context**
If the timezone used in mobile version differs from the one in desktop version, it would be great to indicate the timezone used, but if the current design doesn't allow it, it seems that it would be more understandable for user to use the same timezone for both the desktop and mobile versions.

**Comment by ThorsAngerVaNeT** [comment]
Get in work

**Comment by ThorsAngerVaNeT** [comment]
Current fix merged
