### ISSUE TITLE
Autotest status doesn't change after 0 attempts left

### ISSUE THREAD

**Issue by bundris** [rolling-scopes/rsschool-app#2327]
**Describe the bug**
When auto test is passed not for 100%, it keep stay in Score and Dashboard tabs as "Available" and present in task lists. 
It happens even if 0 attepts left. 

**To Reproduce**

1. Go to app.rs.school
2. Open Autotest Tab
3. Choose any available test
4. Pass it for not 100% for all available attempts
5. Go to Schedule tab - check status of this auto test (it will be "Available")
6. Go to Dashboard tab - auto test still presented in "Task statistics" and "Available tasks" dashboards
7. Go to Auto test - check availability of this specific auto test (it's not available anymore)

**Expected behavior**
In schedule tab, auto test should have "Done" status. 
In Dashboard tab, "available tasks" shouldn't include this test. 
In Dashboard tab, "Tasks statistics" should mention test as "done".

**Screenshots**
![Screenshot 2023-10-23 at 15 53 25](https://github.com/rolling-scopes/rsschool-app/assets/1170870/ec34e3df-2fc3-4198-a214-6dd6dd933f08)
![Screenshot 2023-10-23 at 15 55 33](https://github.com/rolling-scopes/rsschool-app/assets/1170870/fe4b5daf-38ec-4509-8e0d-c408a671a8ee)
![Screenshot_2023-10-23_at_15 54 41](https://github.com/rolling-scopes/rsschool-app/assets/1170870/35572bc0-83b4-43b9-bb8f-663ed69f9003)

**Device (please complete the following information):**

- OS: MacOS Ventura 13.3
- Browser Chrome
- Version 117.0.5938.149 (Official Build) (arm64)

**Additional context**
No extra content

**Comment by aidfromdeagland** [comment]
Hello, @bundris .
Next statement is not clear for me: 

> Go to Auto test - check availability of this specific auto test (it's not available anymore).

From the screenshot I see that UI in 'auto-test' tab shows that the test is 'Completed'. Despite the fact that test is 'Completed' and 0 attempts left user still can pass it as many times as user wants but with 50% points reduction. The test itself is still available and I don't think that we should hide that test from user in Dashboard and Schedule. Users still can improve their results even with 50% points reduction if current max user score < 50%.
