### ISSUE TITLE
Auto-test. Move task with maximum score to Done immediately

### ISSUE THREAD

**Issue by RiaRiver** [rolling-scopes/rsschool-app#2357]
**Describe the feature**
Currently, there is a discrepancy in the behavior between the "Schedule" and "Auto-Test" tabs. On the "Schedule" tab, when an auto-test is completed with the maximum score, it promptly moves to the "Done" filter, even if the deadline has not yet passed. However, on the "Auto-Test" tab, tasks achieving a perfect score remain visible until the deadline, delaying their transition to the "Done" filter.
I propose aligning the behavior on the "Auto-Test" tab with that of the "Schedule" tab. 

**Additional context**
Auto-test tab

**Comment by valerydluski** [comment]
fixed
