### ISSUE TITLE
Submit Review: Display tasks only without review 

### ISSUE THREAD

**Issue by svoboda-rabstvo** [rolling-scopes/rsschool-app#236]
**Describe the bug**
На данный момент я выбираю таску, а только после этого студента для которого нужно сделать ревью из-за этого становится не ясно какие таски уже с оценками, а какие без.

**Expected behavior**
Выбирать сначала студента, после этого получать список тасок по которым нету оценки и показывать только их.

**Comment by dzmitry-varabei** [comment]
@valerydluski спасибо! закрываю
