### ISSUE TITLE
Положение кнопки "Start task"

### ISSUE THREAD

**Issue by MikAleinik** [rolling-scopes/rsschool-app#2375]
В https://app.rs.school/course/student/auto-test при большом количестве сабмитов решения задания кнопка "Start task" уходит вниз за экран т.к. находится за списком результатов.
Предложение:
- ограничить положение кнопки "Start task" низом экрана и сделать список прокручиваемым в контейнере
- разместить кнопку "Start task" до списка (на том же уровне что и "Refresh")

Экран при открытии вкладки теста
![image](https://github.com/rolling-scopes/rsschool-app/assets/84644126/a79ed03b-9ca5-476f-af5b-66c84a3f78f3)

Кнопка при скролле вниз
![image](https://github.com/rolling-scopes/rsschool-app/assets/84644126/8c1aa674-64f6-4b98-8e66-97c66e07e49b)

**Comment by valerydluski** [comment]
![image](https://github.com/rolling-scopes/rsschool-app/assets/57412523/4d4626db-d0a4-447f-bacf-bc90b272003b)

**Comment by aidfromdeagland** [comment]
> ![image](https://private-user-images.githubusercontent.com/57412523/285457230-4d4626db-d0a4-447f-bacf-bc90b272003b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDMwNDUsIm5iZiI6MTcwMzE0Mjc0NSwicGF0aCI6Ii81NzQxMjUyMy8yODU0NTcyMzAtNGQ0NjI2ZGItZDBhNC00NDdmLWJhY2YtYmM5MGIyNzIwMDNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA3MTIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNThiZTgzMTI3NGQyYTliMzBjZjJlZDM5NzAzNDY1ZDg0NGUwOWFiYzA2OTA5ZjA1MjYwMDgxNmUxMWE1ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6vEZoFT1TeUHnMqBRCw8rPdyTfO1lRhxpfca2qKx5Xo)

@valerydluski  , привет. Ожидаемый вариант решения: "ограничить положение кнопки "Start task" низом экрана и сделать список прокручиваемым в контейнере" , верно?

**Comment by valerydluski** [comment]
Кнопка должна быть до списка

**Comment by valerydluski** [comment]
merged @MikAleinik
