### ISSUE TITLE
Incorrect menu icons

### ISSUE THREAD

**Issue by evgenydus** [rolling-scopes/rsschool-app#238]
**Describe the bug**
(That's not actually bug, but think it have to look another way.) Can't see menu icons correctly. Only 3 of 5 shown correctly but don't look so pretty

**To Reproduce**
Right on the main page.

**Screenshots**
![Clipboard02](https://user-images.githubusercontent.com/50835499/69341602-ed991f00-0c7a-11ea-9ffa-07c6f5da16e5.jpg)

**Device (please complete the following information):**
 - OS: Windows 7 Ultimate
 - Browser: Google Chrome
- Version: 78.0.3904.108

**Additional context**
I understand that many of you already know about it, but it have to look at least correctly. Better to use something universal or don't use at all. Students are looking to it and some of them can think, that that's okay, and then use this way to implement the same ;-)

**Comment by apalchys** [comment]
> That's not actually bug

That's BUG. Thanks for the report. The fix is coming.

**Comment by apalchys** [comment]
fixed.

**Comment by evgenydus** [comment]
The same issue with footer I guess. Can't check yet but, as I remember, on desktop not all the icons have shown at all and on mobile they have shown and they look like emojis, just the same like were in menu

**Comment by Alxblsk** [comment]
@evgenydus Should be fixed now, switched to SVG icons.
