### ISSUE TITLE
RS 2019 Q3: У ментора нет возможности проверять таски

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#239]

**Comment by Yuliya-soul** [comment]
Добрый день. Мой ментор в отпуске до декабря. Поэтому он не сможет проверить таски -- codejam-virtual-keyboard
- codejam-palette 
- Codejam Image-api

**Comment by Karitsky** [comment]
The mentor said he's extremely busy at "RS 2019 Q3". No tasks yet verified.

**Comment by shebekocom** [comment]
Добрый день, мои таски никто не проверял. Хотя я думал это сделают на собеседовании. Еслиб для интервью нужна только теория, зачем тогда так все пыхтят над этими тасками в первой части?

Ментор пока мне написал ждать когда он нас соберёт.

**Comment by ALisetskii** [comment]
Добрый день, прошел собеседование 31 октября, после этого у ментора не было возможности проверять мои таски.

**Comment by apalchys** [comment]
@Karitsky Пусть Антон зарегистрируется ментором тут: https://app.rs.school/registry/mentor (важно выбрать правильный курс - 2019 Q3)

**Comment by Karitsky** [comment]
> @Karitsky Пусть Антон зарегистрируется ментором тут: https://app.rs.school/registry/mentor (важно выбрать правильный курс - 2019 Q3)
Антон зарегался. Что дальше?

**Comment by apalchys** [comment]
@Karitsky Теперь он твой ментор. (cc @papkovskaya)

**Comment by Shpakowski** [comment]
@dzmitry-varabei Привет, нету времени заниматься менторством, кому могу передать менти(@dmnikitin, @vladimirkhrystsich, @vp090391, @radvilovich)?

**Comment by svoboda-rabstvo** [comment]
@dzmitry-varabei Привет, такая же проблема как и поста выше. В связи с выросшей нагрузкой хочу передать менти (@pavlenstory, @errmakovv, @presetslrdev) 

Оставить хочу только одного человека @maksim-karatkevich

Заранее спасибо

**Comment by nicklevkovich** [comment]
> @dzmitry-varabei Привет, такая же проблема как и поста выше. В связи с выросшей нагрузкой хочу передать менти (@pavlenstory, @Errmakovv, @presetslrdev)

Заберу к себе @Errmakovv. перекиньте на меня, пожалуйста

**Comment by pavelrazuvalau** [comment]
Готов забрать @pavlenstory, @presetslrdev, @dmnikitin
cc: @dzmitry-varabei @apalchys

**Comment by vp090391** [comment]
> @dzmitry-varabei Привет, нету времени заниматься менторством, кому могу передать менти(@dmnikitin, @VladimirKhrystsich, @vp090391, @radvilovich)?

Это актуально, если что)) Я занимаюсь, но с ментором мотивация гораздо больше))

**Comment by st6gb** [comment]
@dzmitry-varabei @apalchys прошу перекинуть на меня @Featurist505095 так как у его ментора нет времени проверять его таски

**Comment by dzmitry-varabei** [comment]
@Yuliya-soul хорошо, пусть проверит эти таски после отпуска.

**Comment by dzmitry-varabei** [comment]
@shebekocom Привет! у тебя за codewars (который проверяется автоматом) только 6 баллов. Делал ли ты остальные таски?

**Comment by shebekocom** [comment]
@dzmitry-varabei привет, да конечно делал, по кодварсу просто не успел. А так сейчас делаю виджет.

**Comment by dzmitry-varabei** [comment]
@belashjack Женя, помоги, пожалуйста @shebekocom с проверкой тасков, которые он успел сделать.

**Comment by belashjack** [comment]
@dzmitry-varabei @shebekocom ОК, как появится время проверю

**Comment by JuliaMargun** [comment]
@dzmitry-varabei привет, физически не успеваю менторить. кому могу передать своих студентов? (@pavelokun, @lmoroz)

**Comment by dzmitry-varabei** [comment]
@rianby64 Andres, сможешь забрать студентов у @JuliaMargun?

**Comment by rianby64** [comment]
Да. Собираю их.

**Comment by rianby64** [comment]
Пусть @pavelokun, @lmoroz мне напишут письмо, обменимся контактами для вопросов. Буду ждать. Спасибо @dzmitry-varabei .

**Comment by radvilovich** [comment]
> @dzmitry-varabei Привет, нету времени заниматься менторством, кому могу передать менти(@dmnikitin, @VladimirKhrystsich, @vp090391, @radvilovich)?

Я тоже без ментора осталось. Может, есть желающие таски проверить?

**Comment by rianby64** [comment]
@radvilovich - скинь плз ссылку на свои репо, я проведу code-review.

**Comment by dzmitry-varabei** [comment]
@radvilovich включил тебя в группу к @rianby64

**Comment by radvilovich** [comment]
> @radvilovich - скинь плз ссылку на свои репо, я проведу code-review.

Отправила на почту. Спасибо.

**Comment by dimlbc** [comment]
Добрый день, мой ментор в отпуске, поэтому у нее не было возможности проверить таски:
1. theyalow
2. repair-design-project
3. codejam-canvas
4. codejam-virtual-keyboard
5. codejam-palette
6. Codejam Image-api

**Comment by AlekseyVanyukevich** [comment]
Добрый день! Ментор не проверил следующее таски:

1. theyalow
2. repair-design-project
3. codejam-canvas
4. codejam-palette
5. сodejam Image-api

**Comment by RinneSixPaths** [comment]
Всем привет! Не хватает времени полноценно проверять таски, поэтому отдаю в добрые руки 2ое менти (@OneGoodReas0n и @NikolayShishkin)

**Comment by VladislavDan** [comment]
@dzmitry-varabei https://github.com/wimmind прошу перекинуть на https://github.com/zhcecka так как у меня нет времени проверять его таски

**Comment by dzmitry-varabei** [comment]
@dimlbc вижу, что ментор уже всё поправили
@AlekseyVanyukevich написал твоему ментору. он сказал, что сегодня проверит

**Comment by dzmitry-varabei** [comment]
@VladislavDan готово!

**Comment by dzmitry-varabei** [comment]
@antonpalinau, @wwrcth добавил вам по одному студенту (@OneGoodReas0n и @NikolayShishkin). Очень надеюсь, что у вас будем возможность им помочь

**Comment by tor4** [comment]
Привет. Переведите, пожалуйста, @alexandra24260 ко мне в менти. У ее ментора нет времени в настоящее время. Спасибо.

**Comment by Limurezzz** [comment]
Пожалуйста заберите себе студента https://github.com/oldovec

**Comment by famchankou** [comment]
Привет, @dzmitry-varabei  перекинь пожалуйста студента https://github.com/l0kka на ментора https://github.com/ValiantsinTsikhanau и студента https://github.com/nikolaenko94 на https://github.com/stsepchanka, спасибо!

**Comment by ViktoryiaVerasava** [comment]
Добрый день,
у меня больше нет возможности менторить студентов, буду благодарна, есть их кто-то заберет себе.
https://github.com/purpurplr
https://github.com/Musmen
https://github.com/thespirit3000

**Comment by grenbork** [comment]
> @antonpalinau, @wwrcth добавил вам по одному студенту (@OneGoodReas0n и @NikolayShishkin). Очень надеюсь, что у вас будем возможность им помочь

Здравствуйте, вновь назначенный ментор https://github.com/antonpalinau не выходит на связь

**Comment by NikolayShishkin** [comment]
> 
> 
> @antonpalinau, @wwrcth добавил вам по одному студенту (@OneGoodReas0n и @NikolayShishkin). Очень надеюсь, что у вас будем возможность им помочь

Здравствуйте, вновь назначенный ментор https://github.com/antonpalinau не выходит на связь

**Comment by dzmitry-varabei** [comment]
@NikolayShishkin привет! подскажи, пожалуйста, почему ты не выполнял таск corejs (проверка выполняется без участия ментора) и не принимал участие в cross-check таска portfolio?

**Comment by dzmitry-varabei** [comment]
Новые пары:
1) @purpurplr - @magiccurlyhair
2) @Musmen - @sushchenja
3) @thespirit3000 - @sushchenja
4) @oldovec - отчислен, так как нет активности в ноябре-декабре. Рекомендую продолжить обучение в новом наборе. 

СС: @ViktoryiaVerasava @Limurezzz

**Comment by oldovec** [comment]
Извините, но как это нет активности? Если я делаю и заливаю таски?

вт, 24 дек. 2019 г., 3:40 PM Dzmitry Varabei <notifications@github.com>:

**Comment by dzmitry-varabei** [comment]
@NikolayShishkin у тебя новый ментор - @denitrip.

**Comment by oldovec** [comment]
Большое спасибо, а то я даже растерялся. Хочу и есть желание учиться а тут
такое. Спасибо ещё раз

вт, 24 дек. 2019 г., 5:32 PM Dzmitry Varabei <notifications@github.com>:

**Comment by oldovec** [comment]
Здравствуйте, хотел бы определиться с ситуацией, я окончательно отчислен
или как? Просто после того, как я вам написал в дискорд, вы через некоторое
время отписали мне, что ментор @denitrip Но гитхаб указали не мой. Хотя
активность у меня за ноябрь-декабрь присутствует, можете пожалуйста
предоставить мне ментора для дальнейшего прохождения обучения. Имеются
свободные менторы
Заранее благодарю

вт, 24 дек. 2019 г. в 18:43, Гейц Максим <oldovec.cool@gmail.com>:

**Comment by NikolayShishkin** [comment]
> 
> 
> @NikolayShishkin привет! подскажи, пожалуйста, почему ты не выполнял таск corejs (проверка выполняется без участия ментора) и не принимал участие в cross-check таска portfolio?
За core-js у меня 80 баллов стоит, а портфолио пропустил, да

**Comment by dzmitry-varabei** [comment]
@igorbarbashov у тебя новый ментор - @igorexec

**Comment by ArlinskiEV** [comment]
Не успеваю проверить Task Piskel-clone у Artur Pakhomau (artur1986ad)

**Comment by BGRTi** [comment]
Не могу проверить piskel clone студента(https://github.com/karway211) из-за госпитализации

**Comment by muratx10** [comment]
14-го числа написал своему ментору [viachaslau-latushkin](https://github.com/viachaslau-latushkin) по проверке `piskel-clone` в [Telegram](https://t.me/rushpocentru), сообщение прочитал, но не отвечает. PR открыт, в ревьюверы добавил его. Доставать его сообщениями не хочется, всё понимаю, занят может, но можно же ответить хотя бы написав «Привет». Не хотелось бы в последний момент лишится оценки за таск. Как быть ребята?

**Comment by ADozhyna** [comment]
Ментор, проверяющий piskel не выходит на связь, даже сообщение в телеграм не прочитано.  Пуллреквест открыт, в ревьюеры его добавила, но тишина. Ментор @vinfinit.

**Comment by andreyKozik** [comment]
Ментор, проверяющий piskel clone не отвечает звонил по оставленному номеру , трубку не берет, в ревьюеры добавил, пуллреквест так же сделан, ментор - @aborisenok

**Comment by pavel232** [comment]
Ментор до сих пор не проверил неpiskel clone. PR сделан, ментор добавлен в ревьюверы.

**Comment by dermeister** [comment]
Мой ментор по Piskel не отвечает уже три дня. Написал ему два раза, он онлайн, но сообщения не читает. В reviwer на гитхабе тоже не добавился. Ментор @pandekh

**Comment by dzmitry-varabei** [comment]
@ADozhyna ментор вышел на связь и обещал проверить. 
@andreyKozik Написал твоему ментору. Ждем.

**Comment by dzmitry-varabei** [comment]
@karway211 тебе поможет с проверкой @sleepwalky

**Comment by chelvideo** [comment]
Ментор не выходит на связь с 15.01, а piskel так хочет, чтобы его проверили )
Ментор:  anastasia1627

**Comment by Arzamas-ka** [comment]
Назначенный ментор для проверки simple-piskel не проверяет работу.
В скайпе по указанным данным поиск отрицательный, в linkedin - тишины, связывалась через своего основного ментора - тоже тишина.
PR оформлен, ментор добавлена в reviewers с 15 января
Ментор: yana_kalandarova

**Comment by wlukla** [comment]
Ментор не проверяет piskel и не отвечает в скайпе. Его логин: vovikilelik

**Comment by dzmitry-varabei** [comment]
@wlukla Если еще актуально. Напиши плиз в телеграм @niki_night Виктории, она может проверить твою работу.
