### ISSUE TITLE
Task was submitted twice

### ISSUE THREAD

**Issue by ton9q** [rolling-scopes/rsschool-app#241]
**Describe the bug**
Task was submitted twice.
(Student **madashindeinai**)

**To Reproduce**
1. Go to 'Submit review'
2. Filling fields
3. Click on 'Submit'
4. Waiting for submit, without result
5. Click second time on 'Submit'
6. Review was submitted
4. See result in student profile (score also contains two results)

**Expected behavior**
Submitting task review with score once.

**Screenshots**
![image](https://user-images.githubusercontent.com/26420726/69497752-74efc800-0ef1-11ea-8697-df67852637e8.png)

**Comment by apalchys** [comment]
Thanks! fixed.
