### ISSUE TITLE
Inactive account

### ISSUE THREAD

**Issue by hopebernard** [rolling-scopes/rsschool-app#2414]
**Course**
JavaScript/Front-End 2023Q4

**What is wrong**
Today 24.01 I opened my account in RS school app and it is inactive. Why? I'm doing all the tasks. I think my account was disactivated by mistake.
Please help me to solve the issue.
Thank you!

**Comment by valerydluski** [comment]
yoy expelled for cheating on Hangman assignment.

**Comment by valerydluski** [comment]
You can find out in Discord chats what needs to be done, this is not the place to discuss such matters
