### ISSUE TITLE
[Login to profile][Mentoring] Нет возможности залогиниться: Oops, looks like we couldn't find your profile in RS School App! 

### ISSUE THREAD

**Issue by den-smith-dev** [rolling-scopes/rsschool-app#2427]
При переходе по ссылке - https://app.rs.school/ - ошибка доступа
![image](https://github.com/rolling-scopes/rsschool-app/assets/159664030/acc1df46-7376-4bfe-a871-2d3d669ec6ef)

Я залогинен в свой гитхаб. Попытки ре-логина не дают результата. Всё та же страница с ошибкой. На разный устройствах, с разным интернетом. 

По словам модератора "С аккаунтом визуально всё в порядке."

response from 
https://app.rs.school/api/session: 

`{
    "data": {
        "id": 88712,
        "isAdmin": false,
        "isHirer": false,
        "githubId": "den-smith-dev",
        "appRoles": [
            "user"
        ],
        "roles": {},
        "courses": {},
        "iat": 1707727248,
        "exp": 1707900048
    }
}`

- OS: любая
- Browser любой

**Comment by valerydluski** [comment]
подтверди регистрацию на курс и тогда появится доступ
https://app.rs.school/course/mentor/confirm?course=js-fe-2023Q4
