### ISSUE TITLE
RS 2019: Баллы за webpack

### ISSUE THREAD

**Issue by vovikilelik** [rolling-scopes/rsschool-app#243]
**Баллы за webpack**
Рациональность требования по использованию webpack и вопрос о начислении/снятии баллов.

**Причины**
Настоящее предложение исходит из следующих предпосылок:
* При решении задач разрешено (официально) применять только JSCore, что в свою очередь не позволяет полностью раскрыть потенциал webpack.
* Конфигурирование и использование webpack не имеет практической ценности для навыков программирования
* Непрозрачность (сопнительность) оценки. Во многих случаях, само по себе конфигурирование сводится к просто копированию файлов (или копипасте). В связи с этим, возникает вопрос: "А за что баллы то?"
* Проекты с вебпаком не всегда и не везде можно проверить на работоспособность. Не всегда есть ПК достаточной мощности и хороший интернет. Прошу понять, ментор - это не бездельник... =)

**Предложения**
1. Убрать из задач требование по webpack
2. Организовать отдельную задачу по "использованию webpack".

**Положительный эффект**
* Уход от обязательности не означает отказ полностью. По этому, если студент будет видеть разницу применения/не применения webpack на проекте - он лучше оценит его приемущество
* Студент будет видеть инфраструктуру языка, а не ширмы, которую выставляют IDE и webpack. Это полезно для новичков.
* Отдельной задачей по использованию webpack можно ещё больше показать его потенциал
* Проекты станут поменьше и попроще. У менторов (у меня по крайней мере =)), появится больше возможностей для проверки. Признаюсь - это, наверное, самое главное =) Не смотря на волонтёрство, всё же не стоит менторам усложнять жизнь.

**Comment by leovvay** [comment]
>При решении задач разрешено (официально) применять только JSCore, что в свою очередь не позволяет полностью раскрыть потенциал webpack.
По мере появления новых тасок роль webpack будет увеличиваться. Суть инкрементного подхода тут играет роль.
>Конфигурирование и использование webpack не имеет практической ценности для навыков программирования
RSSchool учит не только программировать.
>Непрозрачность (сопнительность) оценки. Во многих случаях, само по себе конфигурирование сводится к просто копированию файлов (или копипасте). В связи с этим, возникает вопрос: "А за что баллы то?"
На начальных тасках это имеет смысл, так как подстегнет менти использовать новую тулзу.
>Проекты с вебпаком не всегда и не везде можно проверить на работоспособность. Не всегда есть ПК достаточной мощности и хороший интернет. Прошу понять, ментор - это не бездельник... =)
Webpack(который не особо сложно сконфигугрирован) не особо ест ресурсы, особенно в тасках которые выдовались до этого момента. Интернет там понадобиться в пару сотен мегабайт от силы, к тому же с менти нужно проводить собесы(используя скайп и тд) и если у человека нет условий для менторинга нужно спросить себя дважды стоит ли начинать не имея нормальных условий.

Соответственно текущий рекваермент по вебпаку мне кажется правильным подходом.

**Comment by mikhama** [comment]
Без вебпака на таких тасках, как раньше был YouTube, а затем Game (Piskel), нечего делать. Ну т.е. можно конечно наподключать миллион скриптов в html, либо писать весь код в одном единственном файле (иногда студенты так и делают), либо использовать не вебпак, а что-то другое (но опять же нужно учится что-то конфигурировать). По поводу копипасты конфига, да, какая-то часть студентов скопипастит у других, какая-то разберется самостоятельно. Также с учетом требований, которые диктует рынок, отказываться от вебпака бессмысленно, так как мы не просто учим студентов, а готовим их к реальной работе.

**Comment by stanislawa** [comment]
Курс все же называется Javascript / Frontend, так что не JS единым. Не забываем, что ребята активно используют препроцессоры, поэтому им нужно знать хотя бы один из способов сборки стилей.

Почти любую таску можно свести к копипасту(спасибо стековерфлоу) так то.

Про интернет очень смешной пункт, позабавило.

**Comment by Kreezag** [comment]
Согласен с мнением автора. Но лишь отчасти.
Я сторонник того, чтобы не усложнять жизнь студентам обязаловкой.
Кажется, что лучше ввести доп балы за использование в задачах техналогий, как вебпак. 
И рекомендовать пройти офлан курс, так как на реальном рабочем месте это пригодится.

Так или иначе, всегда будут студенты, которым интересно, у которых есть время и желание разбираться. И будут менти, которые "копипастнут у соседа" потому что в требованиях так написано. От такого подхода ни менторам, ни студентам пользы не нет.

**Comment by vovikilelik** [comment]
Есть небольшие уточнения в связи с комментариями:
* Не предлагается запретить webpack. Предлагается не начислять за него баллы
* Опыт подсказывает, что "увеличение сложности проекта" не даёт новых, принципиально уникальных настроек. Как изначально он был настроен, так можно к нему не обращаться очень долгое время

**Comment by leovvay** [comment]
>Не предлагается запретить webpack. Предлагается не начислять за него баллы

то есть сделать это дефолтным рекваерментом? тогда надо весь концепт пересматривать, ибо даже за самый костяк начисляются балы.

>Опыт подсказывает, что "увеличение сложности проекта" не даёт новых, принципиально уникальных настроек. Как изначально он был настроен, так можно к нему не обращаться очень долгое время

Это опыт продакшена, тут совершенно другая ситуация, вебпак конфиг будет эволюционировать вместе с тасками.

>Чтобы webpack работал, нужно установить и настроить инфраструктуру. Это сложно сделать на нет-буке... не все же с маками и постоянно сидят за рабочим местом...

Не совсем понимаю. NPM поставить чтоли? Не вижу особой проблемы. Так или иначе если у кого-то конкретного ментора возникает с этим проблемы, можно попросить сбилдить готовый джсник и ссник для вас, покажите/научите, это не сложно.

**Comment by raichev-dima** [comment]
А почему речь идет только про вебпак? Почему, например, парсель не предлагается? Это тоже бандлер, и студентам с ним разобраться было бы легче, как по мне. Можно и галпом все сделать. Но это тоже не предлагается и не понятно, можно ли так делать.

**Comment by leovvay** [comment]
@raichev-dima потому что webpack это стандарт и конкурентов ему пока не предвидится.

**Comment by ArlinskiEV** [comment]
https://github.com/rolling-scopes-school/lectures/blob/master/lectures/js-modules.md
имхо уже после этой лекции каждый класс в отдельном файле - мастхэв.

**Comment by vovikilelik** [comment]
<script type="module">?

**Comment by raichev-dima** [comment]
> https://github.com/rolling-scopes-school/lectures/blob/master/lectures/js-modules.md
> имхо уже после этой лекции каждый класс в отдельном файле - мастхэв. а собирать все в бандл как-то надо, поэтому сборщик должен быть.

Ну, можно ведь и без сборщика. А если даже и со сборщиком - то почему обязательно вебпак? Насчет стандарта я не совсем согласен. Например, многие крупные опенсорсные проекты собираются роллапом (правда, это больше библиотек касается, но тем не менее) и тем же парселем, а то и галпом. В бизнес приложениях - тоже далеко не всегда вебпак используется. Да и раз уж про стандарты речь - сильно ли много приходится настраивать вебпак, когда пользуешься CRA, angular cli или vue cli? Вот честно - часто ли это нужно и оправданно? Я считаю, что у вебпака достаточно сложная конфигурация для начинающего разработчика, и нужно потратить время на изучение документации (которая опять-таки для начинающего может быть достаточно сложной для восприятия), чтобы сделать все с пониманием происходящего, а не просто копипастить, не зная зачем нужна эта куча всего. Парсель вот вообще не требует никакой конфигурации, но про него речи почему-то вообще не идет. Пусть лучше потратят время на рефакторинг, на доработку функционала, изучение лучших практик, чем на то, что вряд ли кому-то пригодится в первый год работы

**Comment by leovvay** [comment]
@raichev-dima крупные в смысле легаси?
 и ничто не мешает использовать галп с вебпаком поскольку это разные вещи.
>сильно ли много приходится настраивать вебпак, когда пользуешься CRA, angular cli или vue cli

Да, конечно, ибо как только проект разрастается нужно экспортать дефолтный конфиг и модифицировать. Все же помнят что эти тулзы используют под собой вебпак? Еще один аргумент в пользу стандарта.

>Я считаю, что у вебпака достаточно сложная конфигурация для начинающего разработчика, и нужно потратить время на изучение документации (которая опять-таки для начинающего может быть достаточно сложной для восприятия), чтобы сделать все с пониманием происходящего, а не просто копипастить, не зная зачем нужна эта куча всего. 

Для сборки sassa там будет строчек 15, логически связанных и очевидных.

>парсель вот вообще не требует никакой конфигурации прямо со старта

у вебпака есть 0-base конфигруация.

>Пусть лучше потратят время на рефакторинг, на доработку функционала, изучение лучших практик, чем на то, что вряд ли кому-то пригодится в первый год работы

мне пригодился вебпак в первый год работы, как и подавляющему большинству моих знакомых

**Comment by raichev-dima** [comment]
> @raichev-dima крупные в смысле легаси?

@leovvay Легаси, хм... А ничего, что rollup поновее вебпака? Крупные в смысле крупные, и многими из них пользуется огромное количество разработчиков: react-router, redux, react-redux, etc... 

> и ничто не мешает использовать галп с вебпаком поскольку это разные вещи.
> 
> >

А зачем их вместе использовать? Можно и одним галпом обойтись. Где написано, что так можно?

> Для сборки sassa там будет строчек 15, логически связанных и очевидных.
> 
> >

Если вся задача в сборке sassa - то зачем js bundler нужен тогда вообще?

> у вебпака есть 0-base конфигруация.
> 
> >

Только он с ней почти ничего не умеет, а парсель - почти все умеет вообще без конфигурации

> мне пригодился вебпак в первый год работы, как и подавляющему большинству моих знакомых

А как именно он пригодился? И что больше пригодилось: знание вебпака или знакомство с best practices?

**Comment by Kreezag** [comment]
> А зачем их вместе использовать? Можно и одним галпом обойтись. Где написано, что так можно?
Напрмиер, [тут сказано](https://learn.javascript.ru/screencast/webpack), что так можно

**Comment by leovvay** [comment]
>Легаси, хм... А ничего, что rollup поновее вебпака? Крупные в смысле крупные, и многими из них пользуется огромное количество разработчиков: react-router, redux, react-redux, etc...

ну покажи мне кто из крупных отказался от вебпака в пользу роллаута.
а пока пикрилейтед
![image](https://user-images.githubusercontent.com/41321050/69786968-89bbac80-11cc-11ea-9196-b8b956a0821a.png)
![image](https://user-images.githubusercontent.com/41321050/69786974-8d4f3380-11cc-11ea-8cdc-e171cab5e386.png)

парсель даже близко нельзя сравнивать с вебпаком когда говорим о проектах.

>Можно и одним галпом обойтись.

Можно, а можно вообще баш скриптами все билдить как в деды делали, только вебпак как сборщик получше чем галп.

 >Не вижу связи между разрастанием проекта и необходимостью модифицировать дефолтную конфигурацию. На это могут быть вполне конкретные причины, но увеличение кодовой базы здесь точно не является определяющим фактором.

Корреляция между рекваерментами и увеличение кодбейза.

>Если вся задача в сборке sassa - то зачем js bundler нужен тогда вообще?

Сборка sass это на первых порах как пример самого базового конфига. Js bundler пригодится например билд залить на gh-pages.

>Только он с ней почти ничего не умеет, а парсель - почти все умеет вообще без конфигурации

Это конечно круто, но тут нужно не забывать, чего у parcel нет, например tree-shaking.

>А как именно он пригодился? И что больше пригодилось: знание вебпака или знакомство с best practices?

Первым что я делал это версионирование билда, потом chuncking, если с первым все обошлось помощью старшего товарища, то со вторым уже нужно было понять что к чему.

**Comment by raichev-dima** [comment]
> Это конечно круто, но тут нужно не забывать, чего у parcel нет, например tree-shaking.
> 
> >

Да ну? Уверен?

**Comment by raichev-dima** [comment]
Да и в целом - речь для меня здесь не идет о том, что лучше и что хуже. Я сам использую в рабочих проектах вебпак. Речь о том - нужно ли это студентам на данном этапе и нужно ли за это начислять дополнительные баллы. Плюс должна быть свобода выбора. Парсель, например, очень просто подключить. Можно вообще с codesandbox (а там будет парсель для ванильного джс) взять готовый шаблон и не заморачиваться - и уделить больше времени написанию нормального кода.

**Comment by raichev-dima** [comment]
Плюс, если студент помучается, настраивая все без бандлера вообще - то быстрее поймет, зачем это нужно, отложится на подкорке, так сказать :)

**Comment by raichev-dima** [comment]
> Напрмиер, [тут сказано](https://learn.javascript.ru/screencast/webpack), что так можно

Я только в рамках обучения в RSS пишу, я не имел в виду - в принципе можно или нужно

**Comment by leovvay** [comment]
> > Это конечно круто, но тут нужно не забывать, чего у parcel нет, например tree-shaking.
> > >
> 
> Да ну? Уверен?

когда я последний раз проверял это было так.



> Да и в целом - речь для меня здесь не идет о том, что лучше и что хуже. Я сам использую в рабочих проектах вебпак. Речь о том - нужно ли это студентам на данном этапе и нужно ли за это начислять дополнительные баллы. Плюс должна быть свобода выбора. Парсель, например, очень просто подключить. Можно вообще с codesandbox (а там будет парсель для ванильного джс) взять готовый шаблон и не заморачиваться - и уделить больше времени написанию нормального кода.

Я всё пытаюсь понять в чем сложность подключения webpack? 🤔



> Плюс, если студент помучается, настраивая все без бандлера вообще - то быстрее поймет, зачем это нужно, отложится на подкорке, так сказать :)

можно просто давать первые таски без бандлера.

**Comment by davojta** [comment]
@raichev-dima я согласен про parcel - можно и его советовать подключать. 

Про вебпак в целом - я добавляю это требование, тк реально стандарт и если позднее его вводить - многие не успевают разобраться. Это по опыту прошлых наборов.

Подход - сначала бонус если разобрались, потом часть как основного скоупа, потом - штраф если за 2 месяца не разобрались. 

@vovikilelik по сути если с чем то не согласны - можно писать автору задания, можно договариваться со студентом и немного менять критерии оценки (если юзает парсель а не вебпак). 

Аргумент что нельзя сделать `npm i` не понял.  Нетбук, офлайн - а как использовать сторонние апи? Сам часто сижу с 3g- вроде ок и проверять, и запускать проект. Не без неудобств иногда конечно )

**Comment by davojta** [comment]
Если у менторов будет консенсус, что вебпак не нужен до финальной таски - можно его писать бонусом везде и не требовать. 

Мне кажется `fancy weather` вполне уже позволяет оценить преимущества веб пака.

**Comment by raichev-dima** [comment]
> когда я последний раз проверял это было так.
> 
> >

Уже год как есть, правда не по дефолту и пока в ранге experimental

> Я всё пытаюсь понять в чем сложность подключения webpack? 
> 
> >

Мне кажется, что может быть сложно в рамках обучения, когда нужно помимо этого массу материала усвоить - сужу по тому, что вижу, когда проверяю таски. Даже в package.json можно накосячить, оказывается :)

**Comment by leovvay** [comment]
> > когда я последний раз проверял это было так.
> > >
> 
> Уже год как есть, правда не по дефолту и пока в ранге experimental
> 
> > Я всё пытаюсь понять в чем сложность подключения webpack?
> > >
> 
> Мне кажется, что может быть сложно в рамках обучения, когда нужно помимо этого массу материала усвоить - сужу по тому, что вижу, когда проверяю таски. Даже в package.json можно накосячить, оказывается :)

Мы же в RSSchool учим всему критичному стеку на текущее состояние в вебе, и webpack это стандарт, кто бы что не говорил, но с цифрами спорить не получиться. Так что текущая система с бонусами до поры до времени мне кажется оптимальной и логичной.
А то что в package.json кто то косячит... Ну чтож нам package.json вырезать?

**Comment by raichev-dima** [comment]
> @raichev-dima я согласен про parcel - можно и его советовать подключать.

@davojta Тогда было бы хорошо обозначить это в задании, в скобочках, например. По крайней мере, для кого-нибудь будет лишний повод вообще посмотреть, какие есть альтернативы.

**Comment by raichev-dima** [comment]
> А то что в package.json кто то косячит... Ну чтож нам package.json вырезать?

Ну, тут пока серьезных альтернатив нет :)  Я в целом за право выбора.

**Comment by leovvay** [comment]
> > А то что в package.json кто то косячит... Ну чтож нам package.json вырезать?
> 
> Ну, тут пока серьезных альтернатив нет :) Я в целом за право выбора.

Лично я против столь либерального отношения. Я считаю что студен по окончанию должен знать главный технологический стек на состояния этого года. А парсель с 30к тут никак не подходит.

**Comment by vovikilelik** [comment]
Коллеги, мне кажется мы немного отошли от темы. Попробую переформулировать:
* Выставляя баллы за реализацию таски, давайте выставлять баллы именно за "реализацию", а не за "использовоние" каких-либо средств разработки. - "Главное же не штаны, а кто в штанах" (с)
* Какой сборщик использовать или использовать вообще - должно быть свободным выбором.
* Если хотим научить именно веб-паку - давайте придумает таску по веб-паку + на собеседовании спросим

**Comment by leovvay** [comment]
@vovikilelik 
>Выставляя баллы за реализацию таски, давайте выставлять баллы именно за "реализацию", а не за "использовоние" каких-либо средств разработки

Но ведь можно ставить и за реализацию, и за подстегнуть изучить что-то сверх доп. балами? 

>Какой сборщик использовать или использовать вообще - должно быть свободным выбором.

На первых порах -- да. Это сейчас так и есть собственно. До определенной точки. Потом -- нет.

>Если хотим научить именно веб-паку - давайте придумает таску по веб-паку + на собеседовании спросим

Хорошая идея.

**Comment by raichev-dima** [comment]
> * Если хотим научить именно веб-паку - давайте придумает таску по веб-паку + на собеседовании спросим

Да, вот это очень хорошая идея - по поводу таски. Можно придумать задачку, чтобы нужно было свой loader написать, например. Мне кажется, это было бы интересно и полезно, плюс совсем другой уровень понимания

**Comment by dzmitry-varabei** [comment]
@vovikilelik @leovvay @raichev-dima @davojta 
Всем привет!
а) Вчера пришли результаты соц опрос по EPAM Poland (где проекты в основном для финтех) "На какой стек учить джуниоров в 2020 году?".
По результатам - Webpack в приоритете (из конкурентов назвали только rollup). Подавляющее большинство проектов, которые набирает джуниоров используют именно его.
b) Проще учить, если требовать у всех студентов использовать только один сборщик. Тогда у студентов возникают одинаковые вопросы и они реиспользуют ответы.
с) Мы действительно можем не начислять баллов за webpack - просто сделать это использование на определенных заданиях обязательным. 
d) Отдельное маленькое задание на webpack - это отлично. Остается вопрос - в какое место учебной программы его поставить.

**Comment by davojta** [comment]
@vovikilelik @dzmitry-varabei а почему текущий таски canvas / palette / image api не подходят на таск для веб пака? или именно что-то более хардкорное хочется? Чем текущая система не работает?

Аргументов вроде против и не было (кроме как выкинуть вебпак и не обучать ему).

Я бы не давал студентам писать свой лоудер - сам их никогда не писал и такие задачи будут очень редкие.

С другой стороны больше заданий вроде как и полезней для студентов )

**Comment by raichev-dima** [comment]
> Я бы не давал студентам писать свой лоудер - сам их никогда не писал и такие задачи будут очень редкие.

Ну, рисование чего-то на канвасе, по-моему, тоже не очень распространенная задача в реальной жизни)

**Comment by dzmitry-varabei** [comment]
@davojta текущие таски подходят, но в целом ИМХО @vovikilelik поднял актуальную проблему и недостатки в текущей системе: 
- Сейчас баллы за использование webpack есть только в таске image api
- Лекция по webpack стоит только через полторы недели после дедлайна по image api, а не перед выдачей таска.
- В таске fancy-weather, который задают уже после лекции по webpack, использование webpack - [optional](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/fancy-weather.md#%D1%81%D1%80%D0%B5%D0%B4%D0%BD%D0%B8%D0%B9-%D1%83%D1%80%D0%BE%D0%B2%D0%B5%D0%BD%D1%8C)
- Часть студентов используем webpack уже во время stage#1, хотя выделенной лекции там не было. 

Также полностью с тобой согласен, что давать студентам писать свой loader в рамках stage#2 это перебор. Да и тасков сейчас уже очень много. Если и задавать, то только во время изучения nodejs в stage#3
 
Что можно сделать:
1. В stage#1 добавить что-то вроде лекции по Webpack Basics, а лекцию из stage#2 поставить в расписании пораньше. 
2. В тасках stage#1 сделать использование webpack по желанию или как бонус, а в stage#2 webpack уже часть основного скоупа (Про это ты уже писал выше)
3. Отдельный мини таск в серии Piskel Clone?

И еще идеи
1. провести опрос среди наших бывших студентов, менторов и текущих джуниоров в целом - какой стек они используют и чем занимаются в первый год работы. Результаты такого опроса можно пошарить студентам на митапе, open днях и тд 
2. В документации к следующему запуску явно прописать техстек на который мы учим студентов и который студенты должны освоить для успешного окончания обучения в RSSchool.

**Comment by irinainina** [comment]
Про webpack. Он был нужен ещё на этапе вёрстки, чтобы собирать sass. То есть лекцию по вебпаку хорошо было бы провести ещё на первом этапе, и тогда же предложить студентам хорошую качественную сборку вебпака. Сейчас в канале materials есть ссылки на три сборки вебпака от студентов, спасибо тем, кто их добавил, но совсем хорошими эти сборки назвать трудно.
Про задания . Их тематика: canvas - dom - canvas - canvas - api - canvas - canvas. Портфолио из выполненных в рамках курса заданий получится довольно унылым.
Задания было бы хорошо менять ещё и потому, что часть студентов проходит курс по второму кругу. И ещё не хватает простых, вот совсем простых заданий по js.
Опрос это действительно очень хорошая идея.

**Comment by dzmitry-varabei** [comment]
Спасибо @irinainina @lmoroz за пожелания по готовой webpack сборке для студентов следующего набора RSSchool - https://github.com/rolling-scopes-school/webpack-boilerplate/pull/1

@vovikilelik @raichev-dima @leovvay может быть вы можете помочь с реализацией boilerplate?
