### ISSUE TITLE
[Cross-Check]: Don't allow to submit a link with private PR of RS School

### ISSUE THREAD

**Issue by NikitaKorevo** [rolling-scopes/rsschool-app#2451]
**Describe the feature**
In the `Cross-Check: Submit` section, don't allow to submit a link with private PR of RS School.

Show a error message like: `Please provide another link. Students can't see private Pull Requests of RS School`
Example link: `https://github.com/rolling-scopes-school/nikitakorevo-JSFE2023Q4/pull/1`

**Additional context**
Feature [from](https://discord.com/channels/516715744646660106/1197895569297899560/1204338997929975809)
![image](https://github.com/rolling-scopes/rsschool-app/assets/48645737/2b892fc4-8212-4e8b-b173-0e4ff0144100)

**Comment by AlreadyBored** [comment]
Done
