### ISSUE TITLE
[App]: A reloaded page without CSS styles within the first second

### ISSUE THREAD

**Issue by NikitaKorevo** [rolling-scopes/rsschool-app#2452]
**Describe the bug**
A reloaded page without CSS styles within the first second

**To Reproduce**

1. Log out from your profile
1. Go to https://app.rs.school/login
2. Reload the current page
4. See the page without CSS styles

**Expected behavior**
Page with CSS styles within the first second

**Screenshots**

![image](https://github.com/rolling-scopes/rsschool-app/assets/48645737/b8494b71-ad71-4c8d-bc21-c01cb1231228)

https://github.com/rolling-scopes/rsschool-app/assets/48645737/ce5a351e-a392-4910-99ab-620021e55fda

**Comment by AlreadyBored** [comment]
Fixed
