### ISSUE TITLE
[Courses Registration] Course list includes courses with expired registration date

### ISSUE THREAD

**Issue by ThorsAngerVaNeT** [rolling-scopes/rsschool-app#2494]
**Describe the bug**
Course list on Course Registration page includes courses with expired registration date.

**To Reproduce**

1. Go to https://app.rs.school/registry/student
2. Click on Course Select
3. Courses with expired registration date appear

**Expected behavior**
Courses with expired registration date should not be shown

**Screenshots**
![image](https://github.com/rolling-scopes/rsschool-app/assets/17920285/363d9d55-b1df-473c-90bd-5e1a9d47b2ed)
![image](https://github.com/rolling-scopes/rsschool-app/assets/17920285/d9753cca-6a01-4674-9029-08265f150b3a)

**Comment by AlreadyBored** [comment]
@valerydluski thanks for investigation!
