### ISSUE TITLE
Bug with registrations on the RS School app

### ISSUE THREAD

**Issue by Hantsev** [rolling-scopes/rsschool-app#2495]
Здравствуйте! 

Столкнулся з проблемой. 

Курс https://rs.school/courses/javascript-preschool-ru При регистрации на платформе RS School https://app.rs.school/login?url=%2Fregistry%2Fstudent%3Fcourse%3Djs-fe-preschool-2024q2 выдает ошибку:

{"statusCode":500,"message":"Internal server error"} 
Можете объяснить в чём дело и как решить сложившуюся проблему?

Писал в Discord раздел questions-stage0, questions-to-admins, questions-to-rsapp не смогли помочь. В разделе questions-to-admins natein рекомендовали issue сделать.

В учётную запись GitHub захожу без проблем. Учётная запись на RS School App у меня ранее была и был подвязан данный GitHub. Мой GitHub https://github.com/Khantsev

![IMG_2121](https://github.com/rolling-scopes/rsschool-app/assets/141030024/750ce63f-407d-4cef-90d7-07156eff07f8)

**Comment by Khantsev** [comment]
{"message":"Unauthorized","statusCode":401} теперь выдает новую ошибку при попытке войти RS School app через учётную запись GitHub

**Comment by Hantsev** [comment]
Проблема решена. Понял и нашел, что вызывало ошибку. Исправил.
