### ISSUE TITLE
[Course students] Unable to create a private repo

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#251]
**Describe the bug**
Андрей, когда будет время, посмотри пожалуйста проблему c созданием приватного репозитория для студента KotdenGit

**To Reproduce**
1. Go to 'https://app.rs.school/course/admin/students?course=rs-2019-q3'
2. Filter by GitHub -   "KotdenGit"
3. Click on 'Create Repo'
4. See error "An error occured. Please try later."

**Comment by apalchys** [comment]
fixed
