### ISSUE TITLE
[BUG] Loss of access to mentoring in the Angular course (angular-2024Q3)

### ISSUE THREAD

**Issue by RomanGorenkov** [rolling-scopes/rsschool-app#2513]
Access to the platform and students GitHub has been lost. 

**Steps to reproduce the behavior**
1. Mentor's GitHub:  RomanGorenkov (https://github.com/RomanGorenkov)
2. Students' GitHub: peachess-dev, shramkoweb, hapikus

**Expected behavior**
Access to the platform and GitHubs for checking tasks and grading.

**Screenshots**
Student's GitHub
![image](https://github.com/user-attachments/assets/d56846e6-1048-4e90-abd2-c14f3e9f8f8b)

Platform (https://app.rs.school/course/mentor/students?course=angular-2024Q3)
![image](https://github.com/user-attachments/assets/4c6f1ce9-3e24-4b5b-9f72-da2d559f680b)

**Additional context**
It looks like the platform no longer considers me as a mentor. When parsing a JWT token, I get the following data:
```
{
  "id": 951,
  "isAdmin": false,
  "isHirer": false,
  "githubId": "romangorenkov",
  "appRoles": [
    "user"
  ],
  "roles": {
    "1": "student",
    "11": "student",
    "65": "student"
  },
  "courses": {
    "1": {
      "roles": [
        "student"
      ],
      "studentId": 239
    },
    "11": {
      "roles": [
        "student"
      ],
      "studentId": 6664,
      "isExpelled": true
    },
    "65": {
      "roles": [
        "student"
      ],
      "studentId": 85513
    }
  },
  "iat": 1720963933,
  "exp": 1721136733
}
```

**Comment by valerydluski** [comment]
This is not a bug. As I understand it, you have two GitHub accounts. You registered as a mentor with the GitHub account "romangorenkovhiqo."

**Comment by RomanGorenkovHiQo** [comment]
Yes you are right. This is my work email 😥. I had to clean the cookies with my hands and re-login.
