### ISSUE TITLE
[Test] How to learn in RS School FROM NodeJSCourse

### ISSUE THREAD

**Issue by StanislavM31** [rolling-scopes/rsschool-app#2536]
**Course**
Specify your course (e.g. rs-2019-q1)

**What is wrong**
Describe data issue
and according to the documentation
https://docs.rs.school/#/nodejs-course
![image](https://github.com/user-attachments/assets/af7d5586-a850-4239-b09f-d2b80c31f281)
and according to the link in the test we have
https://app.rs.school/course/student/auto-test?course=nodejs-2024-q3
![image](https://github.com/user-attachments/assets/34e20288-c49a-4963-a1de-6554eef13c75)
I think that a more unambiguous answer option needs to be added.
"from 8" or ">8" or 8, потому что фраза "...потребуется от 8 часов в неделю." также может быть истолкована как " 8 часов в неделю - Вам хватит для прохождения курса" -  and it will be true.

**Comment by AlreadyBored** [comment]
@StanislavM31 thank you for reporting. As we currently don't have Russian version of the course, these docs will be removed :)
