### ISSUE TITLE
Changed Mentor's info is not available for mentee

### ISSUE THREAD

**Issue by ALisetskii** [rolling-scopes/rsschool-app#255]
My mentor has changed.
Can't access new mentor's contacts, niether in Score, niether in Profile.in Stage Interview contacts of my previous mentor.
a. 
1. Go to the "Score" table
2. Find yourself
3. Click on mentor's name under "Mentor" column
4. Observe the error

b.
1. Go to the "My Profile" 
2. Click on mentor's name under "Mentor" column
3. Observe the error

**Expected behavior**
mentor's contact info is available for mentee

**Screenshots**
in Stage Interview contact info of my previous mentor
![image](https://user-images.githubusercontent.com/55103628/69994243-e02b4100-1566-11ea-8dbd-75f26d45bed2.png)

via Score
![image](https://user-images.githubusercontent.com/55103628/69994388-38624300-1567-11ea-89a8-42314fc49b1f.png)

mentor's name is correct but clicking it leads to an error
![image](https://user-images.githubusercontent.com/55103628/69994435-516af400-1567-11ea-9bdc-ee53b57d92d1.png)

same via MyProfile:
![image](https://user-images.githubusercontent.com/55103628/69996108-d0156080-156a-11ea-80f0-3682248b299d.png)

![image](https://user-images.githubusercontent.com/55103628/70069463-3ce03780-160b-11ea-8032-a83a8cc1cb0c.png)

 - OS: Windows 10 
 - Browser Chrome 
 - Version 78.0.3904.108

**Additional context**

Might be similar https://github.com/rolling-scopes/rsschool-app/issues/206

**Comment by apalchys** [comment]
Контакты ментора сейчас должны быть доступны на главной странице при выборе курса
