### ISSUE TITLE
Списывание алгоритмическиих заданий

### ISSUE THREAD

**Issue by Gektor-51reg** [rolling-scopes/rsschool-app#2552]
**Describe the bug**
Опечатка в слове "алгоритмическиИх".

https://docs.rs.school/#/dismission?id=%d0%a1%d0%bf%d0%b8%d1%81%d1%8b%d0%b2%d0%b0%d0%bd%d0%b8%d0%b5-%d0%b0%d0%bb%d0%b3%d0%be%d1%80%d0%b8%d1%82%d0%bc%d0%b8%d1%87%d0%b5%d1%81%d0%ba%d0%b8%d0%b8%d1%85-%d0%b7%d0%b0%d0%b4%d0%b0%d0%bd%d0%b8%d0%b9

**Comment by stardustmeg** [comment]
Fixed
