### ISSUE TITLE
Mentor can give yourself feedback

### ISSUE THREAD

**Issue by anton-paskanny** [rolling-scopes/rsschool-app#256]
**Describe the bug**
In the course's program, there is a link for students to give feedback about the mentor's work. But I as a mentor can also follow that link and write anything about myself. I don't think that's a correct behaviour.

**To Reproduce**
1. Go to https://app.rs.school/gratitude?course=rs-2019-q3
2. Find yourself via serch input field
3. Write anything
4. Submit the form

Actually, I didn't submit the form, but I guess it's possible to do that either you are a student or mentor.

**Expected behavior**
The form should work only for students, not mentors.

**Comment by forkollaider** [comment]
https://github.com/rolling-scopes/rsschool-app/pull/356
