### ISSUE TITLE
RS 2019 Q3: Отчислен по ошибке

### ISSUE THREAD

**Issue by apalchys** [rolling-scopes/rsschool-app#257]
Укажите причину почему вы считаете, что бы отчислены по ошибке и почему не было активности в private repository.

**Comment by teffalStudy** [comment]
Данные: 
итоги первого собеседования: нет,
ментора: не появлялся,
приватный репозиторий: не выдавался
процесс: работы делать перестал
деятельность: изучаю теорию

Вопрос: почему меня нет в списке отчисленных?

P.S. заметка для контроля алгоритма. (если меня вообще перевели после первого этапа, кстати итог и характеристику собеседования первого этапа можно где-нибудь увидеть?)

**Comment by dmsomov** [comment]
Здравствуйте. Отчислен по ошибке потому что, все таски 2 этапа выполнял и сдавал во время. 
Не было активности в private repository - не знал как перейти в свой приватный репозиторий, и поэтому на каждое задание создавал отдельный репозиторий на Github.

**Comment by apalchys** [comment]
@dmsomov Прими инвайт в репозиторий и скопируй/перенеси туда свои проекты, чтобы была активность. После этого будет восстановление. (активность студента привяза к его активности в приватном репозитории).

@teffalStudy спасибо за информацию. В том списке отчисленных были люди, отчисленные только по последним критериям. Ты был к сожалению отчислен еще раньше, до начала второй стадии. Касательно характеристики по собеседованию: лучше спросить фидбек у ментора который проводил собеседование и узнать у него что стоит улучшить.

**Comment by dzmitry-varabei** [comment]
@apalchys Андрей, привет! восстанови пожалуйста @oldovec

**Comment by apalchys** [comment]
@oldovec востановлен (сс @dzmitry-varabei)

**Comment by Abbos-rON2** [comment]
Нет активности в приватном репозитории, потому что я не понял как им пользоватся, создавал публичные репозитории для сабмита таска

**Comment by marias-code** [comment]
@apalchys Здравствуйте, активность в private repository есть в январе (https://github.com/rolling-scopes-school/marias-code-RS2019Q3/tree/piskel-clone) Пересмотрите пожалуйста

**Comment by staskorotkiy92** [comment]
Здравствуйте! Не было активности в private repository т.к. задания начинал делать в обычных и так как-то забыл про него. Сдавал ментору ПР. Жестких требований не было, ментор проверил задания, которые я сделал и выставил баллы, но сказал, чтобы я все такси запушил в приватный. Я сделал, но меня уже отчислили. До 500 баллов не дотягиваю, но Прошу Вас восстановить меня. Я занимаюсь, просто многое не успеваю.

**Comment by Silver248** [comment]
здравствуйте, прошу восстановить профиль с возможностью ментора оценивать таски, т.к. делал некоторые задания в публичном репозитории, просил ментора не выставлять финальную оценку для доработки 
с ментором всё согласовано

**Comment by dzmitry-varabei** [comment]
@marias-code у тебя выполнено (или проверенно) слишком мало заданий по ходу обучения. Предлагаю записаться на следующий набор. Сейчас слишком поздно.

**Comment by dzmitry-varabei** [comment]
@staskorotkiy92 у тебя аналогичная ситуация. Очень мало задач сдано по ходу процесса обучения (даже с учетом то, что у тебя есть в публичном репозитории). Ты не участвовал в cross-check, не участвовал в тестах stage#2. Предлагаю записаться на следующий набор.
