### ISSUE TITLE
Logout button

### ISSUE THREAD

**Issue by cathzetjo** [rolling-scopes/rsschool-app#263]
Please add logout button.
I need to re-login for new updates and it’s a bit problematic in Safari on my iPad.

**Comment by forkollaider** [comment]
fixed, you don't need now to logout to have new updates, please check

**Comment by cathzetjo** [comment]
I couldnt check it unfortunatly. I have no more new updates.
Why are you so against of Logout button?)

**Comment by forkollaider** [comment]
@cathzetjo , it is not needed :)
