### ISSUE TITLE
 Cross-Check: необходима возможность просмотра комментариев. 

### ISSUE THREAD

**Issue by Net-zen** [rolling-scopes/rsschool-app#278]
В кросс-чек необходима возможность просмотра комментариев проверявших к своей работе, иначе смысл комментариев равен нулю. То есть, проверяющий пишет комментарий к работе и ставит балл. Автор работы потом смотрит на свою оценку и видит как прокомментировали проверяющие свое решение выставить ту или иную оценку. Возможно, анонимно или не анонимно, но возможность необходима.

**Comment by apalchys** [comment]
сделано
