### ISSUE TITLE
Portfolio cross-check 

### ISSUE THREAD

**Issue by HyBeard** [rolling-scopes/rsschool-app#280]
В кросс-чеке портфолио два различных человека имеют одну и ту же ссылку на проект (принадлежащий второму из них).

Выставил оценку лишь проекту Shynggys Kairkhan.

![image](https://user-images.githubusercontent.com/47788411/71292840-295ffb00-2385-11ea-9915-3b06299577b1.png)
![image](https://user-images.githubusercontent.com/47788411/71293011-34b32680-2385-11ea-9d1d-322b1b7edef6.png)

**Comment by apalchys** [comment]
@HyBeard исправлено. спасибо.

@needle06 @qairkhan у вас такая же могла быть проблема. перепроверьте пожалуйста правильно ли вы оценили задание.

**Comment by Qairkhan** [comment]
Действительно была такая проблема , поздно заметил. Спасибо

вс, 22 дек. 2019 г., 22:31 Andrei <notifications@github.com>:
