### ISSUE TITLE
Cross-check: fancy-weather has incorrect max-points value displayed

### ISSUE THREAD

**Issue by LighthouseKeeperYN** [rolling-scopes/rsschool-app#283]
Score (Max 230 points) should be Score (Max 210 points)

1. Go to "https://app.rs.school/course/student/cross-check?course=rs-2019-q3"
2. Select Fancy-weather Cross-Check

**Comment by apalchys** [comment]
we display what was entered in the app. @dzmitry-varabei please take a look.

**Comment by LighthouseKeeperYN** [comment]
it's fixed now
