### ISSUE TITLE
CoreJs. Не выставилась оценка в score

### ISSUE THREAD

**Issue by anreikas** [rolling-scopes/rsschool-app#285]
Задание было выполнено в срок и засабмичено 2019-12-22 в 22:11, дедлайн был  2019-12-22 23:59. В Task Verifications, в графе details написано: Linter errors: 0 errors, 1 warning. Passing: 98. Pending: 3;

**Comment by apalchys** [comment]
`Linter errors: 0 errors, 1 warning. Passing: 98. Pending: 3;`
это сообщение значит, что была lint ошибка и в таком случае вроде выставляется 0.

@dzmitry-varabei @mikhama поправьте меня, если я ошибаюсь.

**Comment by anreikas** [comment]
> `Linter errors: 0 errors, 1 warning. Passing: 98. Pending: 3;`
> это сообщение значит, что была lint ошибка и в таком случае вроде выставляется 0.
> 
> @dzmitry-varabei @mikhama поправьте меня, если я ошибаюсь.

Но это же было предупреждение, но никак не ошибка. И было бы наверное несправедливо не начислять баллы.

**Comment by dzmitry-varabei** [comment]
@mikhama Дима, подскажи плиз какие было требования к линту этого задания?

**Comment by mikhama** [comment]
@anreikas @dzmitry-varabei 
Пожалуйста, обратите внимание на описание таска, в самом конце так и написано, что будет 0 если есть варнинги или ошибки линтера:

> You will get 0 (zero) if you have any eslint's errors or warnings.

https://github.com/mikhama/core-js-101/blob/master/README.md
