### ISSUE TITLE
RS 2019 Q3: CoreJS Interview issues

### ISSUE THREAD

**Issue by apalchys** [rolling-scopes/rsschool-app#291]
Опишите здесь вашу проблему

**Comment by spirithntr** [comment]
https://github.com/rolling-scopes/rsschool-app/blob/54bf225512809fb719d28819bba042037d4aefde/client/src/pages/course/mentor/interview-corejs.tsx#L28
должно быть 
`{ questionId: 'event-prevention', questionText: 'PreventDefault, stopPropagation, stopImmediatePropagation' }, `

**Comment by evgenydus** [comment]
Не могу связаться с ментором. Указан только контакт скайпа, но скайп не находит такой аккаунт.

**Comment by apalchys** [comment]
@evgenydus в приложении появился емейл ментора. Также советую уточнить у ее текущих студентов, как они общались. (можно найти через Score)

**Comment by ReaziS** [comment]
Ментор сказал, что произошла ошибка и не он мой ментор. Сказал ждать нового, но ничего не происходит уже несколько дней

**Comment by apalchys** [comment]
@ReaziS уточни детали к кому ты обращался. На всякий случай уточняю, твой интервьювер указан на странице Interview в https://app.rs.school.

**Comment by ReaziS** [comment]
@apalchys 

Github: shstorm 
telegram: SHStorm

обращался к нему в telegram

**Comment by natallia-js** [comment]
Не получается встретиться с dasha.mamchyts@gmail.com (Telegram: darya_mamchyts). Она может только с 18:00 до 19:00 в среду и четверг. Онлайн собеседование она вообще не обсуждает. Посоветовала поискать другого ментора для собеседования

**Comment by ArlinskiEV** [comment]
Не успеваю провести CoreJS: Interview с Alesia Yermakova (alice-ermakova) alesya.ermakova91@gmail.com

**Comment by AlekseyVanyukevich** [comment]
Не получается провести CoreJS: Interview с Telegram: Muneeesh, так как она из Узбекистана и будет проводить очные интервью с местными ребятами

**Comment by ButterBrot777** [comment]
Добрый день,
у назначенного ментора (Telegram: @abdu_malikov) не получается провести со мной интервью в связи с его занятостью. К сожалению, это выяснилось только сейчас.
Большая просьба назначить мне другого интервьюера, дедлайн близко.
Спасибо.

**Comment by apalchys** [comment]
@ButterBrot777 @AlekseyVanyukevich @alice-ermakova @natallia-js  @ReaziS 
у вас новые интервьюверы.

**Comment by LighthouseKeeperYN** [comment]
Прошел интервью, есть оценка в скоре, нет оценки в профиле, во вкладке Interviews интервью помечено как непройденое.

**Comment by apalchys** [comment]
@LighthouseKeeperYN теперь все должно быть ок. спасибо за помощь!

**Comment by NatalikaFishka** [comment]
Добрый день. Прошла интерьвью с "nodiraibrogimova", она выставила мне оценку, но как оказалось, в какой-то момент в кабинет добавили еще одного интервьюера "nastabulak", с которой я не проходила интервью, но которая очевидно выставила мне оценку "0". Именно эту последнюю оценку я вижу в скоре - можете удалить третьего интервьюера  "nastabulak" и выставленную ею оценку?

**Comment by apalchys** [comment]
@NatalikaFishka как я вижу, у тебя нету ни одной оценки по интервью. попроси пожалуйста `nodiraibrogimova`  сабмитнуть фидбек и оценку. `nastabulak` удалил.

**Comment by jamask** [comment]
Не отвечает ментор, который должен провести corejs интервью. В начале отвечал, и просил подождать. Сейчас от него нет ответа

**Comment by apalchys** [comment]
@jamask у тебя новый интервьювер
