### ISSUE TITLE
Пропал ментор)

### ISSUE THREAD

**Issue by Vir45** [rolling-scopes/rsschool-app#301]
**Course**
Specify your course (e.g. rs-2019-q3)

**What is wrong**
Добрый день. В разделе interviews на сайте app.rss.school пропал ментор, у которого я должен проходить техническое собеседование, остался только мой ментор, у которого я проходил stage interviews с отметкой completed. Это значит, что ментор, у которого я должен проходить stage interviews  решил его не проводить? 09.01.2020 я с ним связывался в телеграмме, ментор сообщил, что доведет порядок прохождения интервью позже, больше сообщений от него не было, на мое новое сообщение он также не ответил и пропал из раздела interviews на сайте app.rss.school

**Comment by apalchys** [comment]
@Vir45 а кто был ментор?

**Comment by apalchys** [comment]
новый ментор назначен. В след раз, лучше писать в Issue по теме (в данном случае: https://github.com/rolling-scopes/rsschool-app/issues/291)

**Comment by Vir45** [comment]
понял, спасибо)
