### ISSUE TITLE
Bug: Double registration

### ISSUE THREAD

**Issue by Marina-Poprotskaya** [rolling-scopes/rsschool-app#307]
Здравствуйте! Сегодня создавала профайл студента для обучения на курсе JS на сайте https://app.rs.school и в результате зарегистрировалась дважды. Могли бы вы удалить один из моих профилей? Спасибо.

**Comment by apalchys** [comment]
@Marina-Poprotskaya удалил. 
Спасибо за сообщение о баге, система не должна такого позволять. Исправим.

**Comment by Marina-Poprotskaya** [comment]
Спасибо!
