### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by spirithntr** [rolling-scopes/rsschool-app#309]
**Typo**
https://github.com/rolling-scopes/rsschool-app/blob/1e50f323d443aa29e5a37a9e946bcf6853d50c40/client/src/pages/registry/mentor.tsx#L275
label should be `"About Yourself"`

**Comment by nachiketbhuta** [comment]
Kindly refer #310 regarding this issue.

**Comment by nachiketbhuta** [comment]
Kindly close this issue
