### ISSUE TITLE
Не получается записаться на курс.

### ISSUE THREAD

**Issue by rsodst** [rolling-scopes/rsschool-app#315]
После регистрации в https://www.training.ru/, через google почту (openId) и записи на курс frontend/js online, не появляется доступ к курсе по адресу https://app.rs.school/course/score?course=rs-2020-q1. 
Видно только сообщение No Access
Probably you do not participate in the course. Please register or choose another course.

Пробовал перезаписаться и привязать local/pmc адрес, без результатно. В чем может быть причина?

**Comment by apalchys** [comment]
@rsodst В данный момент и не должно быть доступа к этой странице. 
На первом вебинаре расскажут как получить доступ к https://app.rs.school/course/score?course=rs-2020-q1. 
Регистрации на https://www.training.ru/ достаточно для записи на курс.

**Comment by rsodst** [comment]
Вообще, вопрос решился)) https://docs.rs.school/#/how-to-enroll
