### ISSUE TITLE
Can't add Codewars account link to my profile 

### ISSUE THREAD

**Issue by xmelsky** [rolling-scopes/rsschool-app#316]
**Describe the bug**
As a logged in user I try to add Codewars account link into my profile. When add the link and save changes, success message appears but after the refresh page - there is no changes and Codewars input field is still empty.

**To Reproduce**
1. Login to App and go to *My Profile*
2. Click on *Edit Profile* button and enter the link into Codewars input field (Accounts section of the web form)
3. Click on *Save* button (the *The profile has been updated* message should appear)
4. Refresh page (or click on *My profile*  to exit edit mode and click *Edit Profile* again) 
5. See the Codewars input field is empty (with no previous changes). 

**Expected behavior**
In step 5 of **To Reproduce** section you should see Codewars input field with changes been made (your codewars account link present)

**Device:**
 - OS: Linux Mint 19 Cinnamon, ver. 3.8.9, kernel 4.15.0-36-generic  
 - Browser chrome
 - Version 79.0.3945.79 (64-bit)

**Additional context**
All of the steps above have been reproduced on mobile device (Xiaomi Remi Note 7, Chrome ver. 79.0.3945.116) with the same bug. No difference.

**Comment by mikhama** [comment]
Hi @xmelsky,

Thank you opening the issue.
This feature for adding `Codewars login` to profile is deprecated, and will be deleted soon. Now we have another way to submit the `codewars-task`.
