### ISSUE TITLE
Can't find myself in the score list and cant submit tasks

### ISSUE THREAD

**Issue by Anton-Balbatun** [rolling-scopes/rsschool-app#322]
**Describe the bug**
I registered on r courses 10/02/2020,but can't see myself and cant submit tasks
Could u help me,plz :)

**To Reproduce**
1. Go to https://app.rs.school/
2. Click on 'Cross-Check: Submit'
3. See attachments

**Expected behavior**
I want to submit tasks and see myself in the score list

**Screenshots**
![1](https://user-images.githubusercontent.com/55106977/74156976-7d21ee80-4c28-11ea-8116-a351f5065d0d.PNG)

**Additional context**
Registered on courses but cant submit tasks and cant find myself in the score list

**Comment by apalchys** [comment]
I see you in the score (try to filter by github id). Also you need to go to “Auto-Test” page, not cross check
