### ISSUE TITLE
 Bug when entering text

### ISSUE THREAD

**Issue by AlekseiBY** [rolling-scopes/rsschool-app#326]
Enter something in the field of input github nick, name or location. Then try entering something else into the same field. Text update will not happen.

1. Go to 'https://app.rs.school/course/score?course=rs-2020-q1'.
2. Enter something in the field of input github nick, name or location.
3. Then try entering something else into the same field.
4. Text will not  be updated.

 - OS: [Win 10]
 - Browser [Chrome]
 - Version [ 79.0.3945.130]

**Comment by apalchys** [comment]
Please try it now and re-open if still exists. It should be fixed. there was a bug in a UI framework.
