### ISSUE TITLE
Location "Other" not very helpful

### ISSUE THREAD

**Issue by ipelekhan** [rolling-scopes/rsschool-app#340]
**Course**
rs-2020-pl (I guess)

**What is wrong**
It's not possible to select any Polish city while creating mentoring profile. Selecting "Other" and specifying location in a second field still produces profile information below:
![image](https://user-images.githubusercontent.com/2616427/75253307-8ab9a580-57de-11ea-9d77-9962c880f160.png)

Doesn't seem much helpful.

**Comment by apalchys** [comment]
@ipelekhan thanks for reporting. Forgot to update the city list for Poland. We will do it shortly.

**Comment by apalchys** [comment]
@ipelekhan temporary added some Polish cities. A better solution is coming soon.

**Comment by ipelekhan** [comment]
Are you planning to support letters with  diacritic marks? For cities like Kraków or Łódź?

**Comment by NiksRakevich** [comment]
> Are you planning to support letters with diacritic marks? For cities like Kraków or Łódź?

@ipelekhan yes, it will be supported after data migration and merging [new location select feature](https://github.com/rolling-scopes/rsschool-app/pull/347)
