### ISSUE TITLE
Self-expel 

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#351]
The student should be able to expel yourself from the course.

**Expected behavior**
1. Open expel page (e.g. https://app.rs.school/course/mentor/expel-student?course=react-2020-Q1)
2. Specify reason
3. Submit form

**Comment by alekseyvlivanov** [comment]
Yep, it will be very helpfull!
Right now I have no time to follow NodeJS course, so I'd like to leave the course and have to ask admins to do it.

**Comment by forkollaider** [comment]
https://github.com/rolling-scopes/rsschool-app/pull/412
https://github.com/rolling-scopes/rsschool-app/pull/411
