### ISSUE TITLE
User profile >  Student Statistics > Course info > Reason for expelling

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#352]
Display reason for expelling next to course information
![image](https://user-images.githubusercontent.com/2429680/75876285-b27bbf80-5e15-11ea-817e-aebbe7448d0c.png)

**Comment by apalchys** [comment]
@mikhama @dzmitry-varabei i think it make sense do not show it for everyone when a person opens profile for everyone.

**Comment by dzmitry-varabei** [comment]
@apalchys sure! let's display this only for admins/course managers/supervisors

**Comment by mikhama** [comment]
@dzmitry-varabei I've also made it visible for mentors. Used the same permissions visibility pattern as for interviews. They probably should know possible "student-risks".

**Comment by dzmitry-varabei** [comment]
@mikhama ok! thank you!
