### ISSUE TITLE
Interview page is not translated and still in Russian

### ISSUE THREAD

**Issue by ipelekhan** [rolling-scopes/rsschool-app#358]
**Course**
rss-pl-2020-q1

**What is wrong**
Interview page is in Russian and needs translation.

![Screenshot 2020-03-05 at 20 29 53](https://user-images.githubusercontent.com/2616427/76018164-168aaa80-5f20-11ea-93db-76a62a1c73fa.png)

**Comment by ipelekhan** [comment]
I can help, by the way.
Should [this page](https://github.com/rolling-scopes/rsschool-app/blob/710018258b8208ccd6abb1282729acc895504d9e/client/src/pages/course/mentor/interview-corejs.tsx) to be translated directly or you have any i18n approach in the app?

**Comment by dzmitry-varabei** [comment]
@ipelekhan Thank you! We do not plan to support i18n, so please translate directly

**Comment by ipelekhan** [comment]
Got it, on my way 😄

**Comment by ipelekhan** [comment]
@dzmitry-varabei Contribution guide for the REST API should be updated. Can't run the app locally because of GH login page. Nothing mentioned in the guide regarding it (also run docker compose script installed PostgreSQL instead of MongoDB, #nezhdanchik 😄). Will do the translation without running the actual app (commented out login and stuff to run a single page only).
