### ISSUE TITLE
Wrong status

### ISSUE THREAD

**Issue by ArtLavr** [rolling-scopes/rsschool-app#370]
**Course**
The Rolling Scopes Poland
![image_1](https://user-images.githubusercontent.com/57012306/76892396-b854b480-689b-11ea-9b4a-7db6e0ca018c.png)

**What is wrong**
noticed that the account was marked as inactive, although no deadlines had yet occurred. Completed one task but is still inactive, please correct

**Comment by dzmitry-varabei** [comment]
fixed
