### ISSUE TITLE
Bug: Incorrect display of the table header.

### ISSUE THREAD

**Issue by InvisibleSpectator** [rolling-scopes/rsschool-app#371]
**Describe the bug**
You see incorrect table head when open score. 

**To Reproduce**
1. Switch to 'RSS React 2020 Q1 (Active)'
2. Open score
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/33596224/76906436-5b69f600-68bd-11ea-98d0-a957bf9d145e.png)

**Device (please complete the following information):**
 - OS: Windows 7 Ultimate
 - Browser Google Chrome
 - Version 80.0.3987.132

**Comment by apalchys** [comment]
fixed
