### ISSUE TITLE
Supervisor is not able to expel a student

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#372]
**Describe the bug**
Supervisor is not able to expel a student

**To Reproduce**
1. Go to "https://app.rs.school/course/admin/students?course=rs-2020-q1"
2. Click on "Exple"
3. Leave a comment
4. Click "Expel"
4. See error - "an error occuried"

**Comment by apalchys** [comment]
@dzmitry-varabei should be fixed
