### ISSUE TITLE
Feature: "Student is looking for a mentor"

### ISSUE THREAD

**Issue by irinainina** [rolling-scopes/rsschool-app#375]
## Описание  проблемы
После первого собеседования и в процессе прохождения второго этапа у менторов будут появляться свободные места, а часть студентов может оказаться без ментора.

- **Студенты, у которых нет ментора**
  - перед началом второго этапа студенты, которые могут и хотят учиться,  могут не пройти собеседование с ментором или вовсе не попасть на него
  - студенты могут остаться без ментора  уже после начала второго этапа, если ментор по каким-то причинам решит отказаться от менторства
- **Менторы, у которых есть свободные места**
  - по результатам собеседования менторы могут не набрать планируемое количество студентов 
  - после начала второго этапа у ментора могут появиться свободные места, если студент, который прошёл собеседование, оставит курс 

## Предложение
- после распределения студентов по результатам первого собеседования в RS APP на вкладке Interviews добавить кнопку "Ищу ментора"
- нажать на эту кнопку может только студент, у которого в графе "Ментор" пусто
- не отчислять этих студентов автоматически после начала второго этапа, а дать им возможность выполнять таски, отправлять их на проверку и получать баллы по результатам кросс-чека
- если ментор отказывается от менторства, он проверяет таски своих студентов, предупреждает их о своём уходе и удаляет свои данные из графы "Ментор"
- после этого студенты, оставшиеся без ментора уже после начала второго этапа, тоже могут нажать на кнопку "Ищу ментора" 
- в RS APP напротив студентов, нажавших на эту кнопку, показывать  менторам плашку "Студент ищет ментора" и контакты студента для связи 
- сделать в RS APP фильтр по таким студентам, чтобы менторы, у которых есть свободные места, могли сравнить их скор, посмотреть результаты выполнения заданий

**Comment by Musmen** [comment]
Отличная идея. Как вариант предложения для большей справедливости (по отношению к тем студентам, кто успешно прошел собеседование) и отсеивания ищущих ментора "на всякий случай" можно рассмотреть возможность активации плашки "ищу ментора" только при условии скора студента >= 0,4 * скора ТОП-1. Т.е. такой стимулирующий фактор дополнительный
