### ISSUE TITLE
Возможность сабмита тасков после дэдлайна

### ISSUE THREAD

**Issue by DenisKhatsuk** [rolling-scopes/rsschool-app#376]
Если открыть сабмит страницу, когда дедлайны еще не наступили, то задания не закрываются после его наступления. Делал таск и по недосмотру засабмитил решение с бесконечной петлей, оно повисло как pending. Страницу сабмита не закрывал и периодически обновлял, чтоб сабмитнуть новое решение. В итоге из спортивного интереса доделал задачу после дэдлайна и автоматом нажимая на сабмит\рефреш засабмитил его.

![2](https://user-images.githubusercontent.com/60316134/77293650-c9665100-6cf3-11ea-99dd-20454bd769d3.png)

На скрине видно, что верхний таск засабмичен после дэдлайна (22/03 23:59) и что я все еще могу сабмитать истекшие таски с этой страницы.

**Comment by mamtys** [comment]
Тоже встретил этот баг. Cross check тоже можно сабмитить.
![s](https://user-images.githubusercontent.com/47928382/78017135-85f38e80-7354-11ea-87a0-88519d4702cd.PNG)
Дедлайн был до 30 числа
