### ISSUE TITLE
quick filter in score - show mentees

### ISSUE THREAD

**Issue by cardamo** [rolling-scopes/rsschool-app#383]
As a mentor I want to quickly see my students in the score table.
Currently it's doable with a filter by "mentor" column, but it would be nice to have a quick filter for that similar to "Active students only".
Another option would be applying filter values from query string. I could bookmark a link like this https://app.rs.school/course/score?course=rs-2020-q1&mentor=cardamo
This solution looks much more flexible and fits other purposes.

What do you think?

**Comment by dzmitry-varabei** [comment]
@cardamo nice feature! thanks!

**Comment by dzmitry-varabei** [comment]
@cardamo  привет! функционал готов -  https://app.rs.school/course/score?course=js-2020-q3&mentor.githubId=cardamo
