### ISSUE TITLE
не обновляется результат по basicJS в rsapp

### ISSUE THREAD

**Issue by DmitriySmolin** [rolling-scopes/rsschool-app#386]
Столкнулся с проблемой, что выполненный task по basicJS не засчитывается в rsapp.
![unknown](https://user-images.githubusercontent.com/45199267/77829593-6d109080-713c-11ea-8708-71ece5a87ca3.png)

**Comment by dzmitry-varabei** [comment]
@DmitriySmolin Привет!
похоже что ты списал этот таск 
![image](https://user-images.githubusercontent.com/2429680/77912141-4ebca900-7292-11ea-9505-f1115f03c690.png)

**Comment by DmitriySmolin** [comment]
Привет, эм, по каким критериям определяется что было списывание? Если я
запушил все задачи в один день, в моем случае это было так, что я решал
сначала локально, а потом лишь решения ко всем задачам запушил

пн, 30 мар. 2020 г. в 17:10, Dzmitry Varabei <notifications@github.com>:

**Comment by dzmitry-varabei** [comment]
@DmitriySmolin форкнул репозиторий, решал все задачи локально, но не коммитал? а потом коммитал по одному файлу каждую минуту, серьезно?

**Comment by DmitriySmolin** [comment]
да и что в этом такого? как хочу так и комичу, не?

**Comment by apalchys** [comment]
Выполнение тестов в репозитории зависает.

**Comment by DmitriySmolin** [comment]
хм, странно, я у себя проверяю командой npm run test, у меня все чекает
![1](https://user-images.githubusercontent.com/45199267/77928064-04025780-72b9-11ea-9d6e-2fa56e7f5ccf.PNG)
![2](https://user-images.githubusercontent.com/45199267/77928073-05cc1b00-72b9-11ea-8fc5-1f2f6095cf2b.PNG)

**Comment by apalchys** [comment]
@DmitriySmolin у тебя же на скриншоте она зависла.

**Comment by DmitriySmolin** [comment]
эх,капееец, не углядел я внизу подвисание, действительно, там зависало только из-за одной неправильно решенной задачи carbon-dating.js. Можно ли засчитать баллы за задачи, кроме получается нерешенной carbon-dating.js?!
![3](https://user-images.githubusercontent.com/45199267/77933976-7dea0f00-72c0-11ea-97c8-cc83733fca17.PNG)
![4](https://user-images.githubusercontent.com/45199267/77933982-7f1b3c00-72c0-11ea-9253-22186ecdd79d.PNG)
![5](https://user-images.githubusercontent.com/45199267/77933983-7fb3d280-72c0-11ea-9929-498489efe9eb.PNG)
