### ISSUE TITLE
Feedback modal window

### ISSUE THREAD

**Issue by Sannnao** [rolling-scopes/rsschool-app#387]
**Course**
rs-2019-q1

**What is wrong**
There is no provided feedback (comment) in result feedback modal window from this text area:
![image](https://user-images.githubusercontent.com/44711578/77830391-1b1a3b80-7139-11ea-92fa-7fe29b5c8e94.png)

**Comment by dzmitry-varabei** [comment]
@Sannnao Could you please provide more details?
I tried to reproduce, but everything seems fine (comment is available on the student profile page)

**Comment by Sannnao** [comment]
> @Sannnao Could you please provide more details?
> I tried to reproduce, but everything seems fine (comment is available on the student profile page)

When I open a feedback modal window there is no info from this text field but I'm sure I left it

![image](https://user-images.githubusercontent.com/44711578/77949264-5189bf00-72cf-11ea-8830-cf2722b7f97c.png)
