### ISSUE TITLE
Time zones don't update

### ISSUE THREAD

**Issue by rootical** [rolling-scopes/rsschool-app#392]
**Describe the bug**
When editing a task, time zone doesn't get saved

**To Reproduce**
1. Go to Course Tasks
2. Click on More dropdown - edit task
3. Update time zone to a different one (Warsaw)
4. Save
5. Open again

**Expected behavior**
Time zone changes to be saved

**Comment by apalchys** [comment]
@rootical technically timezone editing was implemented incorrectly  in Course Task modal. I made a fix which can make your life easier. Could you please check how it works for you?
