### ISSUE TITLE
Student -> Technical screening -> Status

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#397]
![image](https://user-images.githubusercontent.com/2429680/78472760-bc0d8580-773b-11ea-9d5d-4c86c5b5b8b7.png)
Display interview status for the student:
- You need to contact the mentor no later than {DATE}
- Interview completed and {mentor decision}
- Interview canceled

**Comment by Alexey-Koren** [comment]
@apalchys It would be nice to change the status text to passed/not passed. Also, if status will show you if you in wait list
