### ISSUE TITLE
Idea: Cross-check 2.0

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#399]
Собираю проблемы и идеи как можно сделать текущую cross-check систему лучше.

![image](https://user-images.githubusercontent.com/2429680/78545794-af049b00-77fc-11ea-9498-58dafa0003b2.png)

![image](https://user-images.githubusercontent.com/2429680/78548186-a31ad800-7800-11ea-9634-00e4a5c655a0.png)

**Comment by Pulya10c** [comment]
Что бы исключить занижение оценок проверяющими без оснований(бывают случаи когда студенты из зависти снижают оценки, руководствуясь принципом 'ничего не знаю у меня это не работало'), предлагаю сделать следующее: если оценка за работу снижается, то проверяющий должен обязательно оставить контакты для связи, что бы можно было выяснить за что именно была снижена оценка и имеет ли место объективная оценка работы со стороны проверяющего.
Со стороны проверяющего ввести небольшую ответственность за свои проверки и выдавать им штрафы если по результатам опеляции выяснитсяч, что оценка была снижена на пустом месте и не объективно.

**Comment by dzmitry-varabei** [comment]
![image](https://user-images.githubusercontent.com/2429680/80203634-bf53ad00-8627-11ea-8d0d-dfbf616c195f.png)

**Comment by kagafon** [comment]
Предлагаю добавить поддержку markdown в комментарии по cross-check. Сейчас длинные комментарии плохо читаемы.

**Comment by cardamo** [comment]
Начал описывать задание по созданию инструмента для кросс-чека, для ближайшего курса по реакту или или на будущее.

https://github.com/rolling-scopes-school/tasks/pull/232/files

Стараюсь учесть все требования из предложенных сдесь. 
Коментарии и преложения в пулл реквесте приветствуются.
