### ISSUE TITLE
Wrong link on modal window with students private repos

### ISSUE THREAD

**Issue by quaddamag** [rolling-scopes/rsschool-app#415]
**Describe the bug**
Hi everyone! I have a problem with links related to private repos of my students. It seems, these links are not correct.

![image](https://user-images.githubusercontent.com/19718236/79974525-2a737700-84a2-11ea-9818-524dc4aaea73.png)

When I click on this link I'm redirected to page 404 because this link has spaces and they are encoded to %20. However, the correct link to the private repo doesn't have any spaces at all.

![image](https://user-images.githubusercontent.com/19718236/79974681-6dcde580-84a2-11ea-9599-0950a9b71121.png)

**To Reproduce**
1. Open "My profile" page.
2. Expand students list.
3. Try to open private repo on github.

**Expected behavior**
Redirecting to the correct page with private repository.

**Device (please complete the following information):**
Win10 x64, Chrome v81.0.4044.113

**Comment by spirithntr** [comment]
Подозреваю, что имя курса содержит пробелы
https://github.com/rolling-scopes/rsschool-app/blob/90855ff424eddf20e986a05a6fe21c6ded53ed4e/client/src/components/Profile/MentorStatsModal.tsx#L19
https://github.com/rolling-scopes/rsschool-app/blob/90855ff424eddf20e986a05a6fe21c6ded53ed4e/client/src/components/Profile/MentorStatsModal.tsx#L27

**Comment by apalchys** [comment]
fixed. Thanks!
