### ISSUE TITLE
Can't change how many people is shown on score page

### ISSUE THREAD

**Issue by hghgrtut** [rolling-scopes/rsschool-app#423]
**Describe the bug**
On the score page I can't choose variants 10, 20, 50 peoples per page. I can click on them, but it do nothing except hidding panel with variants.

**To Reproduce**
1. Go to 'score';
2. Click on '100/page' in right down corner;
3. Choose any variant

**Expected behavior**
I expect to cut number of shown people on current page to 50 people.

**Device (please complete the following information):**
 - OS: windows 10
 - Browser Yandex
 - Version 20.3.2.242

- OS: Android
 - Browser Chrome (page open in PC version)
 - Version 81.0.4044.117

**Comment by dzmitry-varabei** [comment]
Can't reproduce. This seems to be fixed already.
