### ISSUE TITLE
 [WEB] Results of Android Task 3 are displayed with zero values for Total and Failed on Auto-Test Android 2020 Q1 tab

### ISSUE THREAD

**Issue by Trezeguet1** [rolling-scopes/rsschool-app#424]
**Environment:**
 - OS: macos catalina
 - Browser: Version 81.0.4044.129 (Official build), (64 bit)

**Preconditions:**
Push the results of completed task to own github

**Steps:**
1. Go to https://app.rs.school/
2. Tap on Auto-test tab
3. Select task and tap submit button
4. Wait for sone minutes for results appearing

**Actual result:** Results of Android Task 3 are displayed with zero values for Total and Failed on Auto-Test Android 2020 Q1 tab.

**Expected result:**
The verification status is set as completed and the corresponding result is given for completing the task.

**Attachments:**
<img width="711" alt="Снимок экрана 2020-05-06 в 16 37 46" src="https://user-images.githubusercontent.com/51509139/81186361-5a9b3980-8fbb-11ea-9e5d-3ec0d9546166.png">

**Repro rate**: 100%

**Note**: checking the results is scheduled for the 6th day inclusive and I would like to solve the problem and have my results displayed today.

**Comment by apalchys** [comment]
@Trezeguet1 sorry, but your code doesn't compile at all.

```
> Task :compileKotlin FAILED
e: /src/main/kotlin/subtask6/FullBinaryTrees.kt: (20, 5): Expecting member declaration
e: /src/main/kotlin/subtask6/FullBinaryTrees.kt: (20, 8): Expecting member declaration
e: /src/main/kotlin/subtask6/FullBinaryTrees.kt: (20, 9): Expecting member declaration
e: /src/main/kotlin/subtask6/FullBinaryTrees.kt: (20, 14): Expecting member declaration
e: /src/main/kotlin/subtask6/FullBinaryTrees.kt: (20, 15): Expecting member declaration
e: /src/main/kotlin/subtask6/FullBinaryTrees.kt: (20, 16): Expecting member declaration
```
