### ISSUE TITLE
Codewars#2 missclick with 0 points

### ISSUE THREAD

**Issue by Atamananet** [rolling-scopes/rsschool-app#430]
**Describe**
It is possible to submit a codewars # 2 task now, after that it automatically sets 0 points

**Screenshots**
https://drive.google.com/open?id=1WxKoMqLAk_8HgpP5M1SgIMLf4fSEE9po
![bug](https://user-images.githubusercontent.com/25937528/81780373-1948e380-94ff-11ea-82ec-4fc58e92ac27.png)

**Device**
 - OS:  iOS
 - Browser Chrome
 - Version 80

**Comment by apalchys** [comment]
fixed

**Comment by apalchys** [comment]
to be clear: I reset your latest submit.
yes, it's possible to submit but it takes into account only completed in time tasks.

in your case, it can't find your profile at codewars.
