### ISSUE TITLE
Some problems with score

### ISSUE THREAD

**Issue by UnReaL08** [rolling-scopes/rsschool-app#438]
**Course**
rs-2020-q1

**What is wrong**
I’ve done some new tasks, so my score gonna increase, but it just decrease(yesterday it was 180 without test and movie-search, now it’s 166 with test and movie-search). Thx if u can fix my problem.

**Comment by dzmitry-varabei** [comment]
@UnReaL08 Вчера изменил коэффициент по таску CoreJS с 1 до 0.5, видимо проблема в этом.
