### ISSUE TITLE
RSSchool 2019Q1 Data issues

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#44]
Issue для трекинга проблем с данными по набору RSSchool 2019Q1

Например: 
- неверный скор
- нету скора
- т.д.

Указывайте, если возможно, пожалуйста github студента и имя таска

**Comment by Oigen43** [comment]
Неверный скор за cv, ментор ставил 100, в таблице 25

**Comment by EugeneCh** [comment]
закиньте на меня в приложении плиз студентов PsqNew и lexBogos, они перешли ко мне месяц назад, но в прилаге старая инфа ещё

**Comment by NikitaRudy** [comment]
Поспешно отчислил свою студентку https://github.com/505Flamingo

Восстановите, пожалуйста, ее ко мне в группу.

Спасибо!

**Comment by dzmitry-varabei** [comment]
@Oigen43 Проверили два раза. Твой ментор поставил 25, еще до того как мы перешли на использование http://app.rs.school

**Comment by apalchys** [comment]
@NikitaRudy @EugeneCh Обновили. проверьте плиз.

**Comment by suzik86** [comment]
Здравствуйте. Ментор, которого мне выдала система для собеседования по CoreJS (Алексей - unsafefunction), говорит, что больше не ведет студентов. Назначьте мне, пожалуйста, другого. Мой гитхаб-никнейм - suzik86. Спасибо.

**Comment by apalchys** [comment]
@suzik86 назначил

**Comment by suzik86** [comment]
спасибо ;)

**Comment by PavelYermakov1** [comment]
Здравствуйте, неверно считает скор github name: pavelyermakov1.

**Comment by dzmitry-varabei** [comment]
@PavelYermakov1 привет! в чем проблема? какой баг? как должно быть

**Comment by PavelYermakov1** [comment]
![Безымянный](https://user-images.githubusercontent.com/47759016/59683600-c1afd400-91d8-11e9-8079-2c92092f5b55.png)

**Comment by PavelYermakov1** [comment]
Если сложить имеющиеся баллы с применением этих коэффициентов то не получается данный тотал. Либо я что то неправильно считаю.

**Comment by apalchys** [comment]
@PavelYermakov1 
Codewars имеет коэффициент 0.3, поэтому вместо 75 баллов за это начисляется 23 балла.

сс @dzmitry-varabei

**Comment by PavelYermakov1** [comment]
Спасибо, разобрался)

**Comment by ViktoryiaVerasava** [comment]
Привет, у моего студента https://github.com/koverboy не появился скор за "Task Markup Neutron Mail" в приложении http://app.rs.school/, хотя в таблице отображается (сабмитала еще старой формой). Поправьте пожалуйста.

**Comment by apalchys** [comment]
@ViktoryiaVerasava done

**Comment by ungear** [comment]
Открываю страницу с анкетой моего студента вида http://app.rs.school/profile?githubId=<myStudentGithubId>. Получаю сообщение No Access. Так со всеми моими студентами.

**Comment by vadikmash** [comment]
Добрый день. У меня есть такая проблема. Я проходил собеседование у ментора, который был мне назначен на момент 31 мая. Однако, как я понимаю, потом менторы были пересортированы и теперь у меня стоит другой ментор, который должен был проводить собес. В результате тот ментор, который на самом деле провел моё собеседование теперь не может засабмитать мой результат. Что в мне в такой ситуации делать?

**Comment by apalchys** [comment]
@ungear Подскажи, а зачем тебе анкета студента? Можешь описать свой use case.

@vadikmash
Напиши пожалуйста github Id ментора, который проводил собеседование.

**Comment by ungear** [comment]
@apalchys Студентка усердно занималась и вдруг посреди последнего задания пропала из мессенджеров, где мы переписывались. Хотел посмотреть альтернативные способы связаться с ней.

**Comment by apalchys** [comment]
@ungear проверь, должен быть доступ

**Comment by vadikmash** [comment]
@apalchys собеседование проводил @ksmolniy

**Comment by apalchys** [comment]
@vadikmash исправлено. он теперь должен иметь возможность оставить фидбек.

**Comment by IvanKononovich** [comment]
![Снимок](https://user-images.githubusercontent.com/41195901/61528335-2738ef80-aa27-11e9-9d80-0f29f94c0a23.PNG)
Нету "apalchys" в поле "User"

**Comment by apalchys** [comment]
@IvanKononovich если напечатаешь `apalchys` - должен появится

![image](https://user-images.githubusercontent.com/618807/61611623-f2b27700-ac64-11e9-96a2-ad82b196fea6.png)

**Comment by MarharytaKrasikava** [comment]
В моем профиле http://app.rs.school/profile не заполнено поле location, т.е. нет никаких признаков, что пренадлежу к Минску. В старом аккаунте у меня было это указано. Редактировать невозможно. Проблема не у меня одной.

**Comment by apalchys** [comment]
@MarharytaKrasikava к сожалению данные при миграции могли потеряться. Исправил. спасибо. 
Если у кого-то еще нету location, предлагаю указывать их вот тут и я перенесу в приложение
https://docs.google.com/spreadsheets/d/1ay756aQwB8UUWgxt1-HjItpf7JBHOPdQ-lCa9qxNeuQ/edit?usp=sharing

**Comment by apalchys** [comment]
Closing. Please use https://github.com/rolling-scopes/rsschool-app/issues/new?assignees=apalchys&labels=&template=data-issue-report.md&title= template in the future
