### ISSUE TITLE
Add max students count to the "Course mentors" page

### ISSUE THREAD

**Issue by artem-bagritsevich** [rolling-scopes/rsschool-app#440]
**Add max students count to the "Course mentors" page**
We have a Course Mentors page where the course manager can add students to the mentors.
As a course manager, I want to see how many students all of my mentors can cover.

**Comment by dzmitry-varabei** [comment]
![image](https://user-images.githubusercontent.com/2429680/100525391-c8f65200-31c0-11eb-8a62-d8a9e563a35e.png)
