### ISSUE TITLE
Unable to expel mentor from the course

### ISSUE THREAD

**Issue by artem-bagritsevich** [rolling-scopes/rsschool-app#455]
**Describe the bug**

**To Reproduce**
1. Go to 'Course mentors page'
2. Click on 'Expel button'

**Expected behavior**
The mentor should be expelled

**Comment by sakenalimbayev** [comment]
@artem-bagritsevich 
Could you please specify more details? (error message for example)
I tried to reproduce the issue on my local environment, but no luck.
Everything works as expected.

cc: @apalchys

**Comment by artem-bagritsevich** [comment]
@sakenalimbayev 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15815450/85679492-20543b80-b6d2-11ea-9ea1-269ff11d24fc.gif)

**Comment by artem-bagritsevich** [comment]
Message: An error occurred. Please try later.
