### ISSUE TITLE
Score: position number column ('#') is not displaying actual student's position

### ISSUE THREAD

**Issue by ReAleR09** [rolling-scopes/rsschool-app#456]
**Describe the bug**
Poisition number on the "Score" page is always going from 1st to N (no matter of which page user choose in pagination)

**To Reproduce**
1. Go to 'Score' page
2. Navigate to 2nd (or any other) page using pagination bar
3. Observe that the '#' column always has values from 1 to N

**Expected behavior**
Depending on page selected, values '#' should display actual positions in the "top score" list 

**Screenshots**
![image](https://user-images.githubusercontent.com/10167453/85806696-84b9de00-b758-11ea-9876-3c98ac829e92.png)

**Device (please complete the following information):**
 - OS: Windows 10
 - Chrome last stable build

**Additional context**
Not sure if this is an actual bug or under-implementation.

**Comment by DmitryRomaniuk** [comment]
add render function client/src/pages/course/score.tsx:158 and use pagination.current inside render function
