### ISSUE TITLE
Not display the private repository of student

### ISSUE THREAD

**Issue by MariaKirdun** [rolling-scopes/rsschool-app#466]
**Describe the bug**
Not display the private repository of student

**To Reproduce**
1. Go to profile

**Expected behavior**
Near every student have a "more" button

**Screenshots**
![image](https://user-images.githubusercontent.com/34130890/86770753-d9633000-c059-11ea-9598-32c30e457cd9.png)

**Device (please complete the following information):**
 - Browser chrome

**Comment by apalchys** [comment]
@MariaKirdun thanks for the report.

Unfortunately, it's UX bug... "More" button works for the whole course section and shows a modal with all students.

<img width="720" alt="image" src="https://user-images.githubusercontent.com/618807/86804252-6ff61800-c07f-11ea-8cc2-f23c21776098.png">
