### ISSUE TITLE
Gratitude feature

### ISSUE THREAD

**Issue by DmitryLebetsky** [rolling-scopes/rsschool-app#472]
**Describe the feature**
It will be good idea to add the checkbox to the gratitude page. The duplication of gratitude in discord will depend on this checkbox. For example, if checkbox is active, the gratitude will duplicated in discord, other way, it won't.

**Additional context**
Sometimes I want my gratitude to be seen only by the person, whom I wrote it. That's why I decided to propose this feature.

**Comment by dzmitry-varabei** [comment]
Thanks for the proposal!
By default we publish gratitude on:
- discord
- https://app.rs.school/heroes
- user profile page
In my opinion, it is better to use direct messages (TG, Discord, etc. ) instead of RS APP if someone wants to make private gratitude.
