### ISSUE TITLE
Wrong counting points for Core JS Interview

### ISSUE THREAD

**Issue by hallovarvara** [rolling-scopes/rsschool-app#482]
**Describe the bug**
1. Score for Core JS Interview is 100 with coefficient 0.1. In some cases people see it in their profiles as 8/100 instead of 80/100.
2. It looks like coefficient doesn’t work. Because people are changing in top despite there are no ponta but Core JS Interview now. And these points should not affect to top of score this way (because 10 points make no sense).

**Screenshots**
![78124F39-081F-4930-BCE9-BDDA293AF97F](https://user-images.githubusercontent.com/9438195/88471769-786e9f80-cf15-11ea-93aa-ca16cb2826ca.jpeg)

**Comment by Pulya10c** [comment]
@dzmitry-varabei @hallovarvara 
При добавлении таски на курс необходимо выставлять максимальный бал за интервью 10, а стоял 100. Это неверно, потому что ментор может выставить максимальную оценку - 10.
![image](https://user-images.githubusercontent.com/30927000/93667193-8ca1c980-fa8c-11ea-8108-1151cdf4c1da.png)

**Comment by dzmitry-varabei** [comment]
@Pulya10c хорошо, что нашел откуда ноги растут! спасибо!
