### ISSUE TITLE
Teams: Create mechanism to distribute students by teams

### ISSUE THREAD

**Issue by irinainina** [rolling-scopes/rsschool-app#487]
Для командных заданий нужен механизм, который позволит в rs app распределить студентов по командам примерно равным по их суммарному скору и позициям студентов в общем рейтинге.
1. Для выполнения командного таска студенты регистрируются в rs app, отмечая своё согласие участвовать в командном задании кликом по чекбоксу
2. Студенты, у которых на момент регистрации меньше 50% баллов от лидера скора к командному таску не допускаются
3. Зарегистрировавшиеся студенты распределяются по командам в соответствии с их позицией в рейтинге. При этом количество участников в командах и суммарный скор команд должны быть примерно равными
4. При распределении учитываются баллы только за те задания, за которые выставлены баллы всем зарегистрировавшимся студентам
5. По результатам распределения создаётся таблица со списком команд. Студент с максимальным скором является тимлидом команды. 
6. Если в командном таске принимают участие менторы, они так же как и студенты регистрируются в rs app, выражая своё согласие быть ментором команды
7. Если в командном таске принимают участие менторы, зарегистрировавшиеся студенты распределяются в команды своих менторов независимо от их скора
8. У менторов, которые курируют таск, или у тимлидов команд должна быть возможность отметить выбывших студентов или студентов, которые проявляют низкую активность при выполнении командного задания

Преимущества такого распределения
1. Быстро, точно, не нужно тратить время на распределение, на подсчёт и выставление баллов и т.д

Недостатки такого распределения
1. Выбор технологии осуществляется только после распределения по командам
2. Не учитываются пожелания студентов. Друзья знакомые родственники и т.д могут оказаться в разных командах (но может это и не недостаток)

**Comment by ShekoMaxim** [comment]
Сомнительно про пункт номер 4
"При распределении учитываются баллы только за те задания, за которые выставлены баллы всем зарегистрировавшимся студентам"
если попадает 2-3 студента у которых выполнено меньше всего заданий, но они их выполнил на максимальный балл, то получается они будут сильнее всех остальных, которые сделали больше заданий, но не так качественно?
Получается формировать команды будем по самым неуспевающим студентам.

**Comment by ShekoMaxim** [comment]
Предлагаю не учитывать баллы менторов за задания и баллы за опциональные таски.

**Comment by hallovarvara** [comment]
Правильно понимаю, что если будет студент, у которого ментор не проверил ни одного задания, при распределении у всех студентов будет учитываться только результаты прошедших кроссчеков, оценок от автотестов с прошедшим дедлайном и оценок за 1 этап? И скор будет соответственно снижен (для распределения) у тех, у кого уже есть баллы за задания, проверяемые ментором? И так же, 50% от скора лидера с учетом этого снижения для распределения?

Мое мнение:
Надо учитывать желание студентов объединяться. Лучшая команда этого потока собралась сама и показала отличный результат. Ещё и с ментором сами договорились. Это показатель успешного подхода.
Оставшихся можно распределить. Но, по-моему куда лучше, чтобы студенты сами проявили инициативу и сами собрались, это тоже часть процесса обучения, нетворкинг, умение свой скилл продать лидеру хорошей команды или собрать свою не хуже (презентация, здоровая самооценка, лидерство). Все равно в этом будет рандом, узнать нормально человека с профессиональной позиции нельзя за время обучения (однако это приближенно к рандому на работе — ты хотя бы пытался выбрать по «собеседованию»). Собирая команду сам или вступая в существующую, студент берет на себя ответственность. Решение попасть именно в эту команду — только его, и он же вынесет из него больше, чем при случайном распределении, даже если команда не справится.

**Comment by irinainina** [comment]
> Предлагаю не учитывать баллы менторов за задания и баллы за опциональные таски.

Разве это предложение лучше чем то, которое уже есть в issue?
> При распределении учитываются баллы только за те задания, за которые выставлены баллы всем зарегистрировавшимся студентам

**Comment by ShekoMaxim** [comment]
Так же считаю что проблему с 
"Выбор технологии осуществляется только после распределения по командам"
мы можем решить при регистрации студента на финальный таск, просто добавить выбор технологии на которой хотел бы делать итоговый таск.
Как происходит добор студентов в команды к студентам с ментором?
"Если в командном таске принимают участие менторы, зарегистрировавшиеся студенты распределяются в команды своих менторов независимо от их скора"?

**Comment by irinainina** [comment]
> Так же считаю что проблему с "Выбор технологии осуществляется только после распределения по командам" мы можем решить при регистрации студента на финальный таск, просто добавить выбор технологии на которой хотел бы делать итоговый таск.

Сильные студенты чаще хотят использовать технологии. Команды будут разными по скору.
Студенты одного ментора могут хотеть использовать разные технологии или не использовать их вообще
Распределение по трём критериям сложнее, чем по двум

Как происходит добор не знаю. А на мой предыдущий вопрос можно ответить?
Почему не нужно учитывать баллы менторов, при условии что все менторы проверили таск?

**Comment by ShekoMaxim** [comment]
> > Так же считаю что проблему с "Выбор технологии осуществляется только после распределения по командам" мы можем решить при регистрации студента на финальный таск, просто добавить выбор технологии на которой хотел бы делать итоговый таск.
> 
> Сильные студенты чаще хотят использовать технологии. Команды будут разными по скору.
> Студенты одного ментора могут хотеть использовать разные технологии или не использовать их вообще
> Распределение по трём критериям сложнее, чем по двум
> 
> Как происходит добор не знаю. А на мой предыдущий вопрос можно ответить?
> Почему не нужно учитывать баллы менторов, при условии что все менторы проверили таск?

Потому что по логике будут студенты без менторов, у которых просто не будет оценок за этот такс в любом из двух вариантов.
Во вторых если смотреть по минимальному кол-ву выполненных заданий, то там уже скор не показатель, может получится что топ по скору попадет в среднюю команду просто из-за того, что у него не получилось первое или второе задание и наоборот, студенты одинакового скора попадают в одну команду, так как у них оценки за первые задания были разные, но итоговый скор почти одинаковый.

**Comment by irinainina** [comment]
> будут студенты без менторов, у которых просто не будет оценок за этот такс в любом из двух вариантов

Разве это противоречит пункту "учитываются баллы только за те задания, за которые выставлены баллы всем зарегистрировавшимся студентам"?

Студентов без менторов среди зарегистрировавшихся не будет, потому что "Студенты, у которых на момент регистрации меньше 50% баллов от лидера скора к командному таску не допускаются".
Баллы за кросс-чек выставляются с коэффициентом 0.3, баллы за другие типы заданий минимальные. У студентов, у которых нет и не было ментора, нет шансов получить половину баллов лидера скора

Баллы за задания первого этапа выставляются с большим понижающим коэффициентом. Задания второго этапа не совсем примитивные и в них нет особой разницы первый это таск или третий. Этот аргумент я совсем не поняла

**Comment by ShekoMaxim** [comment]
> зарегистрировавшихся

Вот про студентов без менторов ты не права, даже сейчас посмотреть, начиная с 200-ых позиций попадаются студенты без менторов + у многих менторы выставили не за все таски баллы и когда будет регистрация студент без ментора и студент с ментором в действительности не будут иметь большую разницу в скоре.

**Comment by valerydluski** [comment]
Ну вот я знаю студента, который прошёл весь набор без ментора и очень старался. Я бы был не против, чтобы он например был в моей команде.

**Comment by irinainina** [comment]
> Ну вот я знаю студента, который прошёл весь набор без ментора и очень старался. Я бы был не против, чтобы он например был в моей команде.

Я была бы не против, чтобы у него был ментор.
Ограничение в 50% баллов для попадания в командный таск связано с тем, что у студентов с более низким скором нет шансов на получение сертификата

**Comment by valerydluski** [comment]
А если дать возможность, студентам самим собраться в команды, это может позволить сильным студентам изучить новые библиотеки, а также попробовать использовать самые продвинутые технологии. Мне кажется в этом тоже есть смысл

**Comment by irinainina** [comment]
> Сомнительно про пункт номер 4
> "При распределении учитываются баллы только за те задания, за которые выставлены баллы всем зарегистрировавшимся студентам"
> если попадает 2-3 студента у которых выполнено меньше всего заданий, но они их выполнил на максимальный балл, то получается они будут сильнее всех остальных, которые сделали больше заданий, но не так качественно?
> Получается формировать команды будем по самым неуспевающим студентам.

Пропустила этот комментарий
Если студент выполнил 2-3 задания и не выполнил остальные 10-15, у него по невыполненным таскам стоят нули.

**Comment by irinainina** [comment]
> А если дать возможность, студентам самим собраться в команды, это позволит сильным студентам изучить новые библиотеки, а также попробовать использовать самые продвинутые технологии. Мне кажется в этом тоже есть смысл

Если они согласятся не участвовать в общем скоре, запросто
Команды должны быть равными по силам, иначе в соревновании пропадает смысл

**Comment by irinainina** [comment]
Вижу, что ментор поддерживает это предложение.
Возможно, ему интересно быть лидером команды аутсайдеров, но согласятся ли на это другие менторы?

**Comment by ShekoMaxim** [comment]
> равными



> Если они согласятся не участвовать в общем скоре, запросто
> Команды должны быть равными по силам, иначе в соревновании пропадает смысл

Тут уже пропадает смысл в соревновании, когда мы игнорируем скор для команд с ментором.
Тогда я предлагаю сильным командам участвовать в альтернативном таске, если он останется.
Не вижу смысла чтоб людей насильно распределять в команды, в которых они потеряют интерес к разработке.

**Comment by hallovarvara** [comment]
Все пришли на один курс, всем доступны одни и те же материалы, любого человека в чате (включая преподавателей) можно спросить, если что-то непонятно. Поэтому у всех +- одни и те же возможности, другое дело, как они ими распоряжаются — но это личный выбор каждого, личная ответственность (это хорошо, учит выживанию в реальной жизни). Почему для выполнения самого сложного задания надо делить по скору, который из-за кроссчека, отсутствующих оценок от менторов, отсутствующих менторов необъективен — до сих пор непонятно. Студенты, которые делятся сами, более замотивированы, не вынуждены тащить навязанных алгоритмом участников (почему фатализм и воля случая присутствует на курсе программирования, в профессии, где без самомотивации и умения принимать решения ничего не добиться?), чувствуют ответственность и в полной мере могут оценить командную работу в полевых условиях. Умение собраться в команду и отвечать за принятые решения — очень крутой скилл, почему его сознательно не хотят давать на курсе?

**Comment by irinainina** [comment]
> Тут уже пропадает смысл в соревновании, когда мы игнорируем скор для команд с ментором.
Кто-то это предлагает?
> Тогда я предлагаю сильным командам участвовать в альтернативном таске
Обсудите идею такого таска админами курса
> Не вижу смысла чтоб людей насильно распределять в команды, в которых они потеряют интерес к разработке
Большинство команд остались довольны рандомным распределением
Да "насильно распределять" можно только вручную. Если распределение будет автоматическим в рамках rs app. никаких других вариантов не останется, кроме как не регистрироваться на командный таск вообще.

**Comment by ShekoMaxim** [comment]
> Кто-то это предлагает?
Если в командном таске принимают участие менторы, зарегистрировавшиеся студенты распределяются в команды своих менторов независимо от их скора


> Большинство команд остались довольны рандомным распределением
> Да "насильно распределять" можно только вручную. Если распределение будет автоматическим в рамках rs app. никаких других вариантов не останется, кроме как не регистрироваться на командный таск вообще.

Ну так же все те команды которые объединились сами показали превосходные результаты, отличную атмосферу в команде, вроде как в этих командах все участники дошли до конца, была очень здоровая поддержка в команде.
В рандомных командах уже все зависело от удачи.
Правильно Варя заметила, что все зависит конкретно от того, что мы хотим получить на выходе.
Если просто людей которые должны устроится на работу и сидеть там в независимости нравится им коллектив или нет, то случайное распределение в этом случае оправдано.
Если мы хотим показать как классно работать с друзьями, как получать кайф от разработки, возможно даже готовить будущие стартапы, то тут мы должны позволить людям самим объединиться в команды.

**Comment by valerydluski** [comment]
Плюс умение заводить друзей во время учёбы с которыми можно делать финальное задание, очень полезный скилл, который на работе тоже пригодится.

**Comment by irinainina** [comment]
![](https://s8.hostingkartinok.com/uploads/images/2020/07/cca6fe4f23245cd4b2ceb4613d02b8ab.png)
Перед проведением таска rs lang мы проводили опрос среди студентов. Большинство высказалось за рандомное распределение по командам. На втором месте - распределение по желанию ментора. 
Предложенный вариант распределения учитывает мнение этих двух групп.
Ещё хотелось бы узнать мнение менторов. Но по сложившейся в школе традиции менторы получают студентов разных по скору. Мало кто захочет взять только слабых студентов. Точно так же несправедливо предлагать менторам менторить группы, в которой остались только студенты с низким скором.

**Comment by kagafon** [comment]
Есть другое предложение: топ-70 (например, критерий может быть любым) назначаются тим-лидами и размещают "объявления" о планируемых к использованию технологиях и планах по разработке. Затем в течение недели проводятся раунды мини-собеседований в команды. Кто остается в пуле - распределяется рандомно по свободным местам.

**Comment by davojta** [comment]
Да, мы с @dzmitry-varabei когда-то давно обсуждали командные таски - был поинт, что сильные студенты "тащат" более слабых и помогают менторам в "дотягивании" более слабых студентов. Это элемент обучения. 
Он полезен сильным студентам (они понимают за счет чего сильные + углубляют знания по нужным другим студентам вопросам).

А так получается 20% студентам будет интересно работать, у них будут крутые работы, крутые менторы (много менторов готовых МНОГО работать со слабыми студентами? и много ли тех, у кого остается энтузиазм ?), хорошие оценки и презентации. А остальные 80% вообще теряют мотивацию (как можно угнаться за теми, у кого есть и умения, и время, и менторы).

**Comment by davojta** [comment]
И кстати, в react курсе особо не работала система со скором, там много "внешних" студентов, у которых не известен скор. 

У меня еще был критерий распределения - один город \ часовой пояс, чтобы мальчики и девочки были в каждой группе, или разные возраста (но у нас вроде инфа по возрасту не собирается)

**Comment by ShekoMaxim** [comment]
> Да, мы с @dzmitry-varabei когда-то давно обсуждали командные таски - был поинт, что сильные студенты "тащат" более слабых и помогают менторам в "дотягивании" более слабых студентов. Это элемент обучения.
> Он полезен сильным студентам (они понимают за счет чего сильные + углубляют знания по нужным другим студентам вопросам).
> 
> А так получается 20% студентам будет интересно работать, у них будут крутые работы, крутые менторы (много менторов готовых МНОГО работать со слабыми студентами? и много ли тех, у кого остается энтузиазм ?), хорошие оценки и презентации. А остальные 80% вообще теряют мотивацию (как можно угнаться за теми, у кого есть и умения, и время, и менторы).

В таком случае что делать с командами у которых выбывают студенты или проявляют невысокую активность(пропадают на неделю, не присутствуют на митингах и тд)

**Comment by kagafon** [comment]
> 
> 
> > Да, мы с @dzmitry-varabei когда-то давно обсуждали командные таски - был поинт, что сильные студенты "тащат" более слабых и помогают менторам в "дотягивании" более слабых студентов. Это элемент обучения.
> > Он полезен сильным студентам (они понимают за счет чего сильные + углубляют знания по нужным другим студентам вопросам).
> > А так получается 20% студентам будет интересно работать, у них будут крутые работы, крутые менторы (много менторов готовых МНОГО работать со слабыми студентами? и много ли тех, у кого остается энтузиазм ?), хорошие оценки и презентации. А остальные 80% вообще теряют мотивацию (как можно угнаться за теми, у кого есть и умения, и время, и менторы).
> 
> В таком случае что делать с командами у которых выбывают студенты или проявляют невысокую активность(пропадают на неделю, не присутствуют на митингах и тд)

Как минимум 2 варианта: при критически малой численности объединять команды, либо сделать аварийно-спасательную бригаду из тех же топов, которая будет все помогать за процент от скора.

**Comment by davojta** [comment]
> В таком случае что делать с командами у которых выбывают студенты или проявляют невысокую активность(пропадают на неделю, не присутствуют на митингах и тд)

В предыдущих командных заданиях, мы распределяли людей не впритык, а чуть с запасом.
В таком случае, почти всегда есть половина команд где чуть больше людей и где просто больше людей

1) кейс когда 1 человек выбыл (команды по 5-6-7 человек)
Обычно это не критично и команда вполне может продолжать работать

2) кейс когда выбыло 3 и больше людей
Команда распределяется к тем, у кого выбыл 1-2 человека \ изначально было мало людей
Или если есть аналогичная - то склеиваются

**Comment by davojta** [comment]
Из практики - обычно 90% команд сами решают свои проблемы, из 50 может быть 1-2-3 которые распались, не сработались, не смогли об этом сообщить, не было друзей \ не смогли найти другую команду

как помочь командам решать свои проблемы?
1) давать людям самостоятельно объединяться (для реакта напомню = это норм ситуация). Обычно только 5 команда где-то полностью из друзей, потом туда активно другие люди с разным скором добавляются. Если команда топов - то потом можно и часть "откусить" и раздать другим командам (зависит от поведения всех людей).
2) распределять оставшиеся команды с разным скором - там людям легче договариваться, легче лидершип проявлять
3) в конце есть  команды которым не повезло - их надо склеивать или присоединять. Тоже делают сами в основном. 

На это все надо время, инструкции и этапы хаоса и структуризации. Обычно недели хватает - пару дней найтись, пару дней дораспределить)

**Comment by ShekoMaxim** [comment]
> > В таком случае что делать с командами у которых выбывают студенты или проявляют невысокую активность(пропадают на неделю, не присутствуют на митингах и тд)
> 
> В предыдущих командных заданиях, мы распределяли людей не впритык, а чуть с запасом.
> В таком случае, почти всегда есть половина команд где чуть больше людей и где просто больше людей
> 
> 1. кейс когда 1 человек выбыл (команды по 5-6-7 человек)
>    Обычно это не критично и команда вполне может продолжать работать
> 2. кейс когда выбыло 3 и больше людей
>    Команда распределяется к тем, у кого выбыл 1-2 человека \ изначально было мало людей
>    Или если есть аналогичная - то склеиваются

Нужно ли давать командам решать, справляется тимлид со своей работой или нет?
Что делать если один из участников ведет себя неадекватно, агрится, оскорбляет и тд?
Что делать если человек совсем не идет на контакт, боится общаться с людьми и тд, но при этом делает свою работу?
Если уже прорабатывать кейсы, то нужно максимально учитывать ситуации которые были в этом итоговом задании

**Comment by davojta** [comment]
В массовом бесплатном обучении нельзя (очень дорого) помочь всем успешно закончить курс, люди должны учится сами проявлять инициативу и решать свои проблемы. Тут конечно приходится мирится и с суперкомандами (которые всегда в силу удачи будут), и с "распавшимися" командами, которые не смогли сработаться в силу невезения \ личных обстоятельств и тд

**Comment by not-SAINT** [comment]
Для командных тасков найти идеальное решение в наших условиях - фантастика. Более привлекательным выглядит подход, у которого будут не самые критичные минусы по отношению к целям командного таска.
Вручную формирование команд - это ужас на сколько могу себе представить. И без рандомного формирования не обойтись. Но его можно дополнить фичами. Пусть в командах по умолчанию будут лимиты на количество людей.
6 человек для случайных команд, 5 - для самособранных. 
Случайные команды формируются по рейтингу, который берется на момент формирования команд за все таски, по которым прошли дедлайны и кросс-чеки, включая опциональные. Если кому-то ментор не успел оценить одну работу, это ни на что не повлияет. Но полный скор косвенно говорит, что у ученика есть не только знания, но и время. И таких учеников желательно раскинуть по разным командам. Для учеников без менторов вместо 50% от лидера можно брать 50% от максимума по кросс-чеку за последние 2-3 работы (это показатель того, что ученик продолжает учиться и не будет обузой команде)

1. Основные желающие участвовать в командной таске должны оставить заявку, где смогут указать пожелание в технологии (из списка, можно несколько пунктов, но если был выбран angular и распределили в команду с ним, назад выбора нет). Именно пожелание, без гарантий.  Если кинуло в команду с другой технологией, то будет несколько вариантов.

2. Желающие работать своей командой. Будущие тимлиды создают команду в заявке. Указывают технологию. Другие участники команды в заявке выбирают созданную команду.

- У рандомных команд и самособранных будет пометка, как команда собрана. 

- Приоритет по назначению ментора команде - у случайных, ведь организовать работу вместе им будет сложнее. Последнее слово за ментором, если в самособранной команде есть его ученики.

- Если в случайной команде все попали с выбранной в заявке технологией - выбор они сделали, но единогласно могут изменить его. Если нет, то команде придется выбирать. Приоритетные голоса - ментор и тимлид, ведь им потом работать с их выбором.

- После формирования команд (рандомные и самособранные) будет появляться возможность перейти между командами или просто в какую-то команду, если там есть место. Переходы должны быть одобрены ТЛ обеих команд или куратором таски или еще кем с нужными правами. 

- На формирование команд нужно будет какое-то время, до оф. старта таски. Это можно запускать недели за две, а общие правила формирования были бы объявлены как можно раньше. Чтобы ученики знали что их ждет. И было меньше недовольных. Они будут, но их число можно уменьшить, если объявить правила заранее и дать максимально возможный выбор.

- К концу дедлайна по формированию команд, ожидается, что большинство команд сформировано. Резервные места в обеих типах команд (2 места в самособранной, 1 место в рандомной) будут отдаваться по мере нахождения тех, кто забыл записаться/какая-то команда распалась и т.п. Это будет в основном в последние дни до дедлайна формирования команд и первую неделю-две начала таска. Идеально, если в команде будет до 7 человек,

- Если в процессе выполнения таска, у команды отвалилось несколько человек и они явно не успевают закрыть ТЗ на достойном уровне, команда должна уведомить админов/кураторов, которые помогут найти решение (расформировать/помочь найти пару желающих).

Еще пару моментов. Почему явно выделил самособранные команды и рандомные. В равных условиях, случайная команда скорее всего проиграет собранной, особенно если у второй уже есть опыт работы в команде. И если уж называются лучшие работы, пусть будут названы лучшие по каждой категории команд. 

Понимаю, что написанное тут реализовать в приложении, возможно, очень затратно. Да и сами правила надо бы подправить. 

P.S. А алгоритм формирования рандомных команд по скору и не только можно было бы попробовать вынести как опциональную таску для следующего набора.

**Comment by irinainina** [comment]
У предложенной схемы несколько недостатков
1. Она очень сложная. Даже держать её в голове непросто, тем более - перевести в код. Ещё сложнее донести такую схему до нескольких сотен студентов и менторов.
2. Уже говорила и приводила примеры. Объединяться будут сильные студенты.  Им вместе удобнее, комфортнее, они друг друга лучше понимают. То есть вся первая сотня скора будет в самособранных командах. Они выполнят отличные приложения, на максимально возможный балл. Рандомные команды приложения сделают скажем в два раза хуже. В итоге ни один студент из рандомной команды не наберёт достаточно баллов чтобы получить сертификат.
3. Назначать менторов так себе идея. Менторы приходят добровольно. Большинство менторов выберут сильные команды Как сильным студентам интереснее вместе, так и менторам интереснее работать с сильными студентами. Так они сразу видят результат своего труда, причём хороший результат, который не может не радовать.
4. В ходе командной работы студенты делятся знаниями и опытом. Сильные студенты менторят более слабых, при этом получают навыки тимлидства. Это хороший опыт, который возможен только в командах разных по скору. 
5. На курсе по реакту команды собираются по желанию. После выполнения таска можно будет сделать опрос о впечатлениях от командной работы при рандомном формировании команд и при формировании команд по желанию студентов

**Comment by not-SAINT** [comment]
Схему легко упростить - оставляем только рандом. Все в равных условиях +/- на старте.
Просто тогда нужна определенность с тем, как будут формироваться команды, максимально заранее.
Если на курсе реакта уже точно будут команды, тогда это надо было бы более четко донести всем. Через анонсы, канал в дискорде сделать для поиска команд. И не очень ясно, что делать тем, кто команду не нашел.
