### ISSUE TITLE
Score page. Sorting bug

### ISSUE THREAD

**Issue by tastypurgen** [rolling-scopes/rsschool-app#490]
Сортировки работают только по текущей странице, а не по всем участникам (то же самое и в сортировке по локации и тд)
![image](https://user-images.githubusercontent.com/43437265/89038439-064cef00-d349-11ea-8dd9-bf1ee28a57d6.png)

**Comment by dzmitry-varabei** [comment]
![image](https://user-images.githubusercontent.com/2429680/92362222-f2d33780-f0ef-11ea-83c2-a33c34b457a6.png)
