### ISSUE TITLE
Выставление оценки за кросс-чек вместо отсутствующей оценки ментора

### ISSUE THREAD

**Issue by irinainina** [rolling-scopes/rsschool-app#491]
Предложение как можно решить некоторые проблемы
- студенты без ментора получают баллы только за кросс-чек с коэффициентом 0.3 и не имеют шанса получить сертификат даже при условии полностью выполненных всех тасков
- ментор может покинуть курс, при этом его студенты остаются без ментора и получают баллы только за кросс-чек. Их скор снижается, мотивация падает
- менторы проверяют задания в разное время, в результате скор не отображает действительный рейтинг студентов

Решение включает небольшие изменения в требованиях заданий
1. оценка ментора и оценка за кросс-чек выставляются с одинаковыми коэффициентами 0.5
2. в оценке ментора учитываются только функциональные требования, ментор оценивает таск по тем же критериям, что и студенты при кросс-чеке

Изменения в rs app
1. если ментор проверил задание и выставил за него оценку в течении двух недель после дедлайна, эта оценка не добавляется в общий скор и отображается только в личном профиле студента
2. через две недели после дедлайна все выставленные менторами оценки отображаются в общем скоре
3. если ментор не проверил работу, или у студента нет ментора, вместо отсутствующей в общем скоре оценки ментора, студенту выставляется ещё одна оценка за кросс-чек
4. ментор может проверить работу когда у него появится для этого время и выставить свой балл, который заменит балл за кросс-чек

Что касается качества кода, использование webpack, eslint, написания тестов и т.д за всё это в конце курса ментором выставляется одна оценка или ещё лучше пишется отзыв, который добавляется в профиль студента

**Comment by InikonZS** [comment]
Я предлагаю рассмотреть более простую и универсальную систему. Оценка ментора включается в оценки кроссчека. В случае если она минимальна (вероятно 0) то она исключается из расчета. Возможно вес оценки ментора задать как 2 - 4. Оценка за таск получится одна.
Для текущего набора за применение системы от Ирины.

**Comment by Musmen** [comment]
Идея хорошая и со всем согласен, кроме ``в оценке ментора учитываются только функциональные требования`` и ``Что касается качества кода, использование webpack, eslint, написания тестов и т.д. за всё это в конце курса ментором выставляется одна оценка или ещё лучше пишется отзыв, который добавляется в профиль студента``.
Код-ревью (качество кода), соблюдение правил по коммитам и ПР - это все достаточно важные вещи, которые проверяет ментор, дает им оценку, советует и т.п.
Про качество кода - я считаю это вообще самое важное в работе пары "студент-ментор". Иначе в чем смысл наличия ментора.
Да и выставить одну оценку за все это в конце - такое себе. Студент развивается, качество кода улучшается (хочется верить), подходы совершенствуются и т.п. Как это оценить в конце - будет больше вопросов чем ответов.
А если просто оставить вариант, что оценки ментора и за кросс-чек одинаковы по максимальному баллу и коэффициенту. И если у студента нет ментора или он не проверяет его работы, то через 2 (или 3-4) недели оценка за кросс-чек удваивается? Я думаю, никто не будет в обиде

**Comment by irinainina** [comment]
Согласна с тобой. Мне этот пункт тоже не нравится и его считаю недостатком в предложенной схеме. Но другого способа создать одинаковые условия хотя бы по возможности получить одинаковые баллы, для студента, у которого есть ментор, и студента у которого ментора нет и код проверить некому, я не увидела.
Твой вариант не поняла. Ты предлагаешь оставить оценку за качество кода, но при этом пишешь, что "оценки ментора и за кросс-чек одинаковы". Как это может быть?

**Comment by Musmen** [comment]
Ментор может давать оценку качества кода, применять доп. штрафы, в т.ч. за нарушения соглашений школы по коммитам и ПР, иные перечисленные специальные моменты в ТЗ, но верхний предел оценки у ментора = верхнему пределу оценки при кросс-чеке. Коэффициенты их тоже равны. 
Если кто-то из студентов подумает, что его положение при наличии ментора в таком случае ухудшается (т.е. ему мнимая возможность потенциально получить больший скор от кросс-чека без возможности доп. штрафов от ментора важнее, чем наличие фидбека, советом и т.п. от ментора), то можно отказывается от ментора - я думаю найдутся желающие и все всех устроит

**Comment by irinainina** [comment]
Ты определённо выстроил какую-то схему, но я не могу её понять. Давай посмотрим как она реализуется на примере конкретного таска? Вот, например, [MovieSearch](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/movie-search.md). В нём указан максимальный балл за задание: 180 баллов при кросс-чеке / 220 баллов при проверке ментором. Оценка ментора выше потому что в Advanced scope есть пункт "выполнены требования к коду (+40) (оценивает только ментор)". И так во всех тасках, которые проверяются и с ходе кросс-чека и в ходе проверки ментором - у ментора есть дополнительные баллы, которые выставляет только он. Что будет с этими дополнительными баллами при твоей схеме?

**Comment by irinainina** [comment]
Кажется поняла. Ты предлагаешь за качество кода баллы не добавлять, а снимать? Вместо премиальных баллов ха хороший код ввести штрафные санкции за плохой? Мне не нравится это решение. И не уверена, что оно понравится менторам. Но это желательно у них самих уточнить. Подождём, может кто-то из менторов зайдёт в это обсуждение.

**Comment by Musmen** [comment]
Тут как мне видится варианта два:
1. Или делать так чтобы со всеми доп. баллами и возможными штрафами максимальная оценка ментора = максимальной оценке за кросс-чек. Т.е. немного подправить те задания, где это есть. Но на сколько я помню их немного, особенно тех, где именно доп. баллы начисляются. Чаще речь про штрафы, но не суть.
2. Ввести в rs.app коэффициент дублирующей оценки за кросс-чек взамен оценки ментора. Т.е. в данном случае 1,222(2) * 180 максимум за кросс-чек = 220 максимум от ментора.
Т.е. получил студент 150 за кросс-чек. Ментор не поставил ему свою оценку или ментора нет - дублирующая оценку будет по данному таску 1,222(2) * 150 = 183,3 балла.
Но мне больше нравится первый подход, где немножко придется подправить ТЗ. Все равно в них часто вносятся правки и это не должно быть большой проблемой

**Comment by Musmen** [comment]
В самых сложных тасках набора - Fancy Weather, English Puzzle, RS Lang доп. баллы за качество кода и т.п. не предусмотрены, а штрафы менторы имеют возможность применять. Они это могут делать и без прямого указания в ТЗ. И как бы это не было большой проблемой. Можно и в остальных тасках (кодорые перейдут в следующий этап )пересмотреть критерии оценки

**Comment by InikonZS** [comment]
Насколько помню требования к проверке кода достаточно простые в проверке, например - код рабит на модули. Или к качеству именования коммитов тоже сразу видно. Используемые технологии, линт, jest тесты готовые - однозначно проверяются глядя только на гитхаб. Чуть сложнее - дублирование кода сведено к минимуму, но этот пункт достаточно субьективен.
Принимая во внимание тот факт, что на react и angular наборах проверка кода возложена на студентов, то в чем сложности включить эти пункты в кроссчек. Да и студентам полезно смотреть код.
Единственная сложность - приватный репозиторий,  и сложности с запуском плагиат-теста без него.

**Comment by NexGenUA** [comment]
Может есть смысл пересмотреть систему менторства в целом? 
Идея в том, чтобы не было персональных менторов.

Студенты при переходе с первого этапа на второй проходят интервью, как это и задумывалось, им выставляют оценки и условно набравшие 50/100 (или по решению ментора) переходят на второй этап и начинают выполнять задания. 

Оценки за задание можно выставлять по схеме: оценка за кроссчек + оценка ментора / 2 * 0.5 и плюс балл, выставленный ментором за качество кода, структуру, наличие тестов и ошибок с коэффициентом 1.
На примере задания Fancy Weather оценка кроссчека 220, оценка ментора 180 (220 + 180) / 2 = 200 (с коэфициентом 0.5) и менторские 0-50 (с коэфициентом 1). Будет больше мотивации заниматься архитектурой проекта и качеством кода.

Задания, которые будут проверять менторы можно распределять так: количество выполненных заданий / количество менторов, в итоге каждый ментор проверит одинаковое количество работ.

Ментор, с которым я проходил последнее интервью рассказал, что в этом наборе у него было 2 студента, которые не продолжили обучение и он взял еще 2-х, из которых один так же решил не продолжать, а одна девочка проходила курс уже 2-й раз, все знала и вопросов не задавала. Т.е. менторить ему некого было, хотя желание как я понял было. Выходит так, что некоторые менторы перегружены, взяв 3 и более студентов, а у некоторых 1-2 неактивных (опытных). 
Менторинг – очень трудоемкий процесс и далеко не все студенты понимают, что просто проверка заданий занимает много времени, нужно ведь не только оценить функционал, а еще и провести ревью кода с комментариями проблемных мест. Отсюда выходит: 

- Студенты ожидают, что раз есть ментор, то можно особо не стараться, ведь ему и так все расскажут и поправят, в итоге студент плохо учится и не заканчивает курс.
- Менторы выкладываются для студентов, которые потом не продолжают обучение, что сильно демотивирует заниматься менторством в дальнейшем.

Уходом от персонального менторига можно решить несколько проблемных мест:
- Студенты не будут расслабляется при обучении, в ожидании, что ментор закроет все пробелы в знаниях
- Менторы охотней будут соглашаться менторить, т.к. будет понятно сколько времени у них это будет занимать.

Для персонального менторинга можно создать отдельный канал, где, либо менторы будут предлагать провести консультации с 2-5 студентами (созвон в skype, etc), либо студенты будут задавать вопросы, а другие менторы на них отвечать.

**Comment by dzmitry-varabei** [comment]
Предлагаю такой вариант:
- функциональные требования оценивают только студенты во время кросс-чек (50% оценки), ментора участвуют в апелляции
- ментора оценивают только качество кода. Так как ментору не надо оценивать функциональные требование, можно требовать больше комментов по качеству кода (следование clean code, правильная настройка webpack, eslint, тесты и т.д). Можно попробовать разработать чек-лист RSSchool по оценке качества кода

**Comment by irinainina** [comment]
> Идея в том, чтобы не было персональных менторов.

Мне не нравится эта идея, извини. В твоей схеме ментор только проверяет задания и между делом может ещё что-то сделать. Я бы предпочла противоположный вариант, чтобы ментор помогал выполнять задания, делился опытом, отвечал на вопросы, советовал как писать код лучше. А проверка тасков и выставление за них баллов это намного менее важно.

> Т.е. менторить ему некого было, хотя желание как я понял было

Так в твоей схеме ему тоже некого менторить будет. Только проверять работы. Это тоже часть менторства, но не самая важная. 

> 2 студента, которые не продолжили обучение и он взял еще 2-х, из которых один так же решил не продолжать

Студенты, которые прекращают обучение, это действительно проблема и нужно искать пути её решения. 

> Менторы охотней будут соглашаться менторить

Вот да. Не в смысле я с тобой согласна, а в смысле, что предложенную схему было бы хорошо обсудить с самими менторами, услышать их мнение. Если они посчитают её достаточно хорошей, тогда можно думать как это реализовать.

**Comment by irinainina** [comment]
> функциональные требования оценивают только студенты во время кросс-чек (50% оценки)

То есть другие 50% за код? Как-то много

> ментора участвуют в апелляции

Лучше бы апелляциями занимались студенты-активисты. 

> ментора оценивают только качество кода

Хорошо, если только сами менторы с этим согласны. Но мне правда очень жаль тратить время ментора на проверку того, что могут проверить сами студенты. 

> Так как ментору не надо оценивать функциональные требование, можно требовать больше комментов по качеству кода

Было бы очень здорово, если бы на первом месте у менторов была не функция проверки заданий, а помощь студентам в их выполнении

> Можно попробовать разработать чек-лист RSSchool по оценке качества кода

Да, наверное, можно.

**Comment by NexGenUA** [comment]
> > Идея в том, чтобы не было персональных менторов.
> 
> Мне не нравится эта идея, извини. В твоей схеме ментор только проверяет задания и между делом может ещё что-то сделать. Я бы предпочла противоположный вариант, чтобы ментор помогал выполнять задания, делился опытом, отвечал на вопросы, советовал как писать код лучше. А проверка тасков и выставление за них баллов это намного менее важно.

> > 2 студента, которые не продолжили обучение и он взял еще 2-х, из которых один так же решил не продолжать
> 
> Студенты, которые прекращают обучение, это действительно проблема и нужно искать пути её решения.

Появилась мысль, как свести менторов, которые могут/хотят не только ревьюить код, а еще и делать созвоны и помогать с заданиями, со студентами, которые в этом действительно нуждаются.  
При записи на первое интервью добавить чекбокс, в котором спрашивать, хочет ли студент получать помощь при выполнении заданий от ментора (периодические созвоны и т.д.). Если чекбокс отмечен, то за ним/ней закрепится ментор, который хочет это делать и к которому он/она сможет обратится за помощью. Остальным студентам достанутся менторы, которые будут только ревьюить код и выставлять оценки в скор.  В итоге будут 2 группы: студенты, нуждающие в активной помощи менторов и менторы, желающие эту помощь дать и студенты, котрые хотят просто закончить курс и получить сертификат. Первым оценки за работы в скор будут выставлять их менторы, а вторым оценки за скор будут выставлять менторы, которые просто хотят ревьюить код и если студенты будут уходить с курса, менторам просто будет меньше проверок.
Сейчас менторы достаются всем, кто прошел интервью, но некоторому количеству студентов ментор не нужен.

**Comment by irinainina** [comment]
Очень революционные идеи )
И не скажу, чтобы этот вариант мне не нравился, с чекбоксами и прочим.
Я бы даже дополнила чекбокс надписью "Да, мне нужна помощь ментора. Я хочу пройти этот курс полностью. Я понимаю что будет очень сложно. И у меня есть 30-40 свободных часов в неделю, чтобы заниматься. Я умею считать и понимаю, что 40 часов в неделю это шесть часов в день. Да, именно такое количество времени каждый день на протяжении полугода я могу потратить на этот курс. И нет, я его не брошу, потому что у меня есть характер настойчивость и целеустремлённость и это для меня действительно важно".  ставишь галочку - проходишь на интервью. Не ставишь, обходишься кросс-чеками и не отвлекаешь на себя менторов.
