### ISSUE TITLE
Confirm dialog for self expel

### ISSUE THREAD

**Issue by AlksAlena** [rolling-scopes/rsschool-app#514]
**Изменение оформления диалога**
* Добавить строку с предупреждением сразу под заголовком диалога
* В начало строки предупреждения добавить жёлтую иконку ⚠,  для всей строки задать светло-желтый фон
* В качестве текста предупреждения указать последствия, например, "вы завершите обучение", в качестве ключевых слов можно использовать распространенные: *end, finish, close*
* Предлагаю заменить слово *expel* на более распространенные варианты, например на *leave*

**Профит**
Для студентов, не слишком хорошо владеющих английским,  может быть полезно, так как перечисленные слова довольно распространены и помогут сообразить о чем речь, если лень использовать переводчик. 

Дополнительное оформление с предупреждением может послужить сигналом о том, что что-то пошло не так.

**Comment by AlreadyBored** [comment]
Done
