### ISSUE TITLE
Can't select predefined student

### ISSUE THREAD

**Issue by DrDiman** [rolling-scopes/rsschool-app#527]
**Describe the bug**
Can't select predefined student when I confirmed participation as a mentor

**To Reproduce**
1. click confirm to be a mentor 
2. type github in the input for predefined students
3. blur input
4. input is cleared 

**Expected behavior**
expected that student will be mine and input is will be filled in.

**Comment by apalchys** [comment]
@DrDiman please provide an example (github username) to investigate the issue. It works for me when I type random username in different browsers.

**Comment by DrDiman** [comment]
@apalchys  I've typed and tried to copy/paste `toystix1992`, but the select didn't appear.

**Comment by DrDiman** [comment]
Google Chrome | 85.0.4183.83 (Official Build) (64-bit) (cohort: 85_83_Win)
-- | --
OS | Windows 10 OS Version 1809 (Build 17763.1397)
