### ISSUE TITLE
Деплоя задания webdev

### ISSUE THREAD

**Issue by IvanKlesov** [rolling-scopes/rsschool-app#532]
**Course**
JS/FE 2020 Q3

**What is wrong**
При выполнении задания webdev на этапе деплоя. Страница не отображается в браузере по ссылке 
https://rolling-scopes-school.github.io/ivanklesov-JS2020Q3/webdev/
а выдает ошибку 404.
Все делал по инструкции, указанной в документации RS school. Работал в приватном репозитории
 rolling-scopes-school/ivanklesov-JS2020Q3. После  окончания верстки сделал Pull Request из ветки webdev в ветку
gh-pages. Файл index.html лежит на верхнем уровне папки.  
Помоги, пожалуйста, решить мою проблему. Заранее благодарен.

**Comment by apalchys** [comment]
fixed
