### ISSUE TITLE
Cross-check Admin UI

### ISSUE THREAD

**Issue by apalchys** [rolling-scopes/rsschool-app#542]
1. View submitted solutions
2. View pairs and review score

**Comment by anonimCitizen** [comment]
Здравствуйте, 23.09.2020 была засабмичена ссылка по webdev (https://rolling-scopes-school.github.io/anonimcitizen-JS2020Q3/webdev/), но до сих пор не было получено ни одной оценки по этому заданию.
![screen_webdev](https://user-images.githubusercontent.com/68064734/94611402-5a714280-02aa-11eb-8fec-89200b0252c6.png)

**Comment by dzmitry-varabei** [comment]
@anonimCitizen твою работу никто не проверил. Тебе необходимо подать аппеляцию https://docs.rs.school/#/cross-check-flow?id=%d0%90%d0%bf%d0%b5%d0%bb%d0%bb%d1%8f%d1%86%d0%b8%d1%8f
