### ISSUE TITLE
создал лишнюю папку

### ISSUE THREAD

**Issue by Mikhail-Kurilov** [rolling-scopes/rsschool-app#545]
**Course**
webdev (rs2020q3)

**What is wrong**
обнаружил проблему: для задания webdev создал папку с названием webdev с вложенной внутри папкой  webdev, а в ней файлы задания index.html, style.css и assets. не верно истолковал запись: "В приватном репозитории школы создайте ветку с названием webdev, в ней создайте папку с названием webdev". засабмичено все было 21 числа. Теперь студенты не имеют возможности перейти по ссылке, так как выдает ошибку 404. (так в этой папке по адресу находится папка с таким же названием, а требуемые файлы выше). С помощью советов в ветке webdev-2020q3 поступил следующим образом: добавил файлы в нижестоящую папку webdev, сделал pullrequest в папку gh-pages и замерджил. Однако это не помогло. 

мой репозиторий: https://rolling-scopes-school.github.io/mikhail-kurilov-JS2020Q3

**Comment by apalchys** [comment]
Вот ссылка: https://rolling-scopes-school.github.io/mikhail-kurilov-JS2020Q3/webdev/

Для того чтобы работала ссылка, надо класть файлы в корень в бранче `gh-pages`
