### ISSUE TITLE
The student's position in the score is displayed incorrectly

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#546]
![image](https://user-images.githubusercontent.com/2429680/94441360-f4e65e80-01a2-11eb-8123-a1170f627149.png)

![image](https://user-images.githubusercontent.com/2429680/94441217-c8324700-01a2-11eb-833a-929f3c486884.png)

**Comment by apalchys** [comment]
@dzmitry-varabei should be fixed now
