### ISSUE TITLE
Submit review task dropdown doesn't show all tasks and has no scroll

### ISSUE THREAD

**Issue by AlionaSidarenkaTR** [rolling-scopes/rsschool-app#565]
**Describe the bug**
Submit review task dropdown doesn't show all tasks and has no scroll.
Reproducable in Chrome and Firefox, works nice for my acc in Android.

**To Reproduce**
1. Go to Submit review
2. Click on Task
3. There is no scroll and not all of the tasks are available by default.

**Expected behavior**
All of the tasks are available by default or dropdown has scroll

**Screenshots**
![image](https://user-images.githubusercontent.com/18561722/95871002-d45afe80-0d75-11eb-96d3-ef4fdacf3e44.png)

**Device (please complete the following information):**
 - OS: 
![image](https://user-images.githubusercontent.com/18561722/95871275-256af280-0d76-11eb-878c-3772bb9bebec.png)
 - Browser Chrome and Firefox
 - Chrome Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by forkollaider** [comment]
@AlionaSidarenkaTR is it some particular task you can't find in the list? 
I checked code responsible for this logic and I see that not all tasks should be visible in this lists (e.g. some of them should be submitted by course mentor).

**Comment by apalchys** [comment]
@Pulya10c @mikhama @DmitryRomaniuk @AlreadyBored guys, could someone please check if it's reproducible on Windows?
