### ISSUE TITLE
Search results on 2020q3 JS/FE course are incorrect

### ISSUE THREAD

**Issue by hallovarvara** [rolling-scopes/rsschool-app#572]
**Description**
When I'd tried to find a student, I got results from all courses student is involved in.

**To Reproduce**
1. Go to https://app.rs.school/course/score?course=js-2020-q3
2. Click on magnifier icon which belongs to Name column title
3. Type "Dluski"
4. See the results

**Expected behavior**
Result contains student's profile, attached to current course.

**Screenshot**
![image](https://user-images.githubusercontent.com/9438195/96856661-d6ece080-1466-11eb-99a8-c5564e670b30.png)

**Device (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version latest

**Comment by dzmitry-varabei** [comment]
![image](https://user-images.githubusercontent.com/2429680/97696562-0b375100-1aa6-11eb-98d4-c8ebdcf2569e.png)

**Comment by apalchys** [comment]
it should be fixed @hallovarvara
