### ISSUE TITLE
Cross-check submit works unstable near midnight

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#575]
![image](https://user-images.githubusercontent.com/2429680/97355636-752ddb80-1897-11eb-9dac-85fa9ab92cf3.png)

**Comment by Mark-Igorevich** [comment]
Засабмитил Shelter 24 октября в 10-13 часов по Минску. Сейчас хотел проверить работы других студентов, но там не было списка студентов. В сабмите тоже сказано, что дедлайн уже прошел. Видимо, работа не засчиталась. В этот же день сабмитил momentum, и он, пока что, там есть)

**Comment by dzmitry-varabei** [comment]
![image](https://user-images.githubusercontent.com/2429680/97993380-4ad2a580-1de4-11eb-8ed9-cbd6ceecfa7f.png)
