### ISSUE TITLE
задача implement-a-filter-function на кодварс 404

### ISSUE THREAD

**Issue by mauta** [rolling-scopes/rsschool-app#578]
**Describe the bug**
задача implement-a-filter-function на кодварс 404

**Comment by michael-916310** [comment]
У каты https://www.codewars.com/kata/i-spy сломаны тест-кейсы и едва ли будут поправлены. Вероятно её стоит исключить. Решать я не пробовал -  может при каких-то вараинтах и можно пройти тест-кейсы. 
![image](https://user-images.githubusercontent.com/53167052/98241566-90c66f80-1f84-11eb-9f92-d6518228c6e3.png)

**Comment by dzmitry-varabei** [comment]
@mauta поправил, проверь плиз
