### ISSUE TITLE
Возможность перераспределения студентов по менторам

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#58]
Issue на основе сообщения от @cathzetjo
```
После двухнедельного отсутствия мой ментор Алексей (github=unsafefunction) вышел на связь и сообщил, что у него больше нет возможности вести/собеседовать студентов.

Нужно по возможности кому-то отдать его студентов ( не проверено два последних таска - ютуб и презентация).
Для текущего рандомного собеседования нужно назначить студентам, попавшим к нему, другого ментора.
```

**Comment by net-ka** [comment]
Распределите меня, пожалуйста, к другому ментору для собеседования (github net-ka). По таблице распределения пар у меня тот же ментор,  о котором написано в данном issue - unsafefunction. Связалась с ним, он подтвердил, что не сможет провести собеседование. Спасибо)

**Comment by lipnitsky93** [comment]
> Issue на основе сообщения от @cathzetjo
> 
> ```
> После двухнедельного отсутствия мой ментор Алексей (github=unsafefunction) вышел на связь и сообщил, что у него больше нет возможности вести/собеседовать студентов.
> 
> Нужно по возможности кому-то отдать его студентов ( не проверено два последних таска - ютуб и презентация).
> Для текущего рандомного собеседования нужно назначить студентам, попавшим к нему, другого ментора.
> ```
Я буду менторить @cathzetjo

**Comment by apalchys** [comment]
@lipnitsky93 @cathzetjo готово.

@net-ka готово.
