### ISSUE TITLE
В задании codewars part2 ката со сломанными тест-кейсам

### ISSUE THREAD

**Issue by michael-916310** [rolling-scopes/rsschool-app#580]
Пройдите по ссылке https://www.codewars.com/kata/i-spy
Прочитайте сверху
![image](https://user-images.githubusercontent.com/53167052/98242040-4265a080-1f85-11eb-88c6-ad214343fe79.png)

Полагаю, что из за не исправности тест-кейсов данную кату не удасться сдать. Вероятно её стоит исключить или заменить.

**Comment by dzmitry-varabei** [comment]
@michael-916310 проверил, кату можно решить и успешно сдать
