### ISSUE TITLE
Code Clone Detection

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#581]
The ability for the course managers to run the copy-paste detection script for particular students' assignments

**Comment by dzmitry-varabei** [comment]
https://github.com/sovaz1997/CloneChecker

**Comment by AlreadyBored** [comment]
Done
https://github.com/AlreadyBored/CloneChecker

**Comment by dzmitry-varabei** [comment]
@AlreadyBored супер! спасибо!
