### ISSUE TITLE
Оценка по тестам в RS APP

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#617]
@mikhama Дима, привет!
Нужная твоя помощь! :)

В RS APP ты разрабатывал формы для проведения тестов (для замены тестов в google forms). 
Сейчас необходимо поправить алгоритм по которому форма выставляет оценку в score. В текущей реализации она выставляет только 100/50/0 баллов, а необходимо чтобы в score шло столько, сколько набрал студент (с учетом 50% штрафа если тест сдавал больше 2х раз). Например, ответил на 75% вопросов получил 75 баллов (а если это был 3+ сабмит то 38 баллов).

Спасибо!

**Comment by irinainina** [comment]
Спасибо большое! Такая правка нужна для будущих тестов этапа stage1-stage2. Сейчас, пока студенты выполняют тесты этапа stage0 (дедлайн 08.03), вносить её не нужно - у всех студентов должны быть одинаковые условия прохождения тестов.

**Comment by mikhama** [comment]
PR с фиксом я уже открыл, тогда нужно будет замержить его после дедлайна

**Comment by dzmitry-varabei** [comment]
@mikhama Спасибо! очень быстро поправил! 🦸⚡
