### ISSUE TITLE
[Score] Keep location filter in url

### ISSUE THREAD

**Issue by apalchys** [rolling-scopes/rsschool-app#619]
**Describe the feature**
When the "Location" filter applied on Score page, it should be kept in the URL

**Comment by SvetlovVitaliy** [comment]
<img width="1043" alt="Снимок экрана 2021-02-08 в 16 54 10" src="https://user-images.githubusercontent.com/50168127/107222526-77730a80-6a2e-11eb-9d2a-721694053c9a.png">
