### ISSUE TITLE
Bug: In mentor's profile in Public Feedback section bages images doesn't displayed

### ISSUE THREAD

**Issue by 375291601334** [rolling-scopes/rsschool-app#620]
In mentor's profile in Public Feedback section bages images doesn't displayed.

1) Open Profile:
![image](https://user-images.githubusercontent.com/33834629/106866101-1caf7b00-66dd-11eb-9e7d-7531ea413f6b.png)

2) Press fullscreen button under Public Feedback section
![image](https://user-images.githubusercontent.com/33834629/106866152-2b962d80-66dd-11eb-8ff3-c9ac2fc4ff69.png)

3) Close popup with Public Feedback section
![image](https://user-images.githubusercontent.com/33834629/106865803-ba567a80-66dc-11eb-9c0b-74f06faca677.png)

 - Browser: Chrome Version 88.0.4324.104

**Comment by dzmitry-varabei** [comment]
fixed https://github.com/rolling-scopes/rsschool-app/pull/684
