### ISSUE TITLE
I cannot register to React course

### ISSUE THREAD

**Issue by ZhibekKanatbekova** [rolling-scopes/rsschool-app#630]
**Describe the bug**

**To Reproduce**
1. Go to 'https://app.rs.school/registry/student?course=react-2021-q1'
2. I have submitted  all details to be registered
2. Click on 'Submit'
3. Then the new windows comes saying "You have successfully registered"
4. Click on 'Go to home'
5. I saw the error. In stead of being forwarded to React registered student profile, I am in JS registered profile(I have been registered for this course also)

**Expected behavior**
I suppose to see my profile in React course with all dashboard, score, schedule like https://app.rs.school/

**Screenshots**

**Device (please complete the following information):**
  - Browser chrome]
 -

**Additional context**

**Comment by apalchys** [comment]
@ZhibekKanatbekova do you see a dropdown on Home page?

![image](https://user-images.githubusercontent.com/618807/108349316-e51ff300-71f3-11eb-90de-e3dbc20d7504.png)

if not, could you please attach a screenshot?

**Comment by Aleksei-Rozhkou** [comment]
--Отправлено из мобильной Яндекс.Почты18.02.2021, 14:17, "Andrei" <notifications@github.com>:
@ZhibekKanatbekova do you see a dropdown on Home page?

if not, could you please attach a screenshot?
