### ISSUE TITLE
RS APP - Dashboard - Clicking "Send Invite" gives "An error occurred. Please try later" and the deployed site into gh-pages doesn't open 

### ISSUE THREAD

**Issue by VDudevich** [rolling-scopes/rsschool-app#635]
**Describe the bug**
RS APP - Dashboard - Clicking "Send Invite" gives "An error occurred. Please try later".
And as a result a page is not deployed properly into gh-pages of the private school repository: the 404 is given.
Repository: https://github.com/rolling-scopes-school/vdudevich-JSFE2021Q1

**To Reproduce**
The private repository was requested and was got in January 2021.
Now I have done below steps:

1. There are gh-pages and task's branches (it's wildlife)
2. Create and merge a PR to gh-pages.
3. Try to open a deployed task (https://rolling-scopes-school.github.io/vdudevich-JSFE2021Q1/taskName)

I was advised to click "Send invite" in RS APP which gives an error (look at the screenshot below)/

**Expected behavior**
The deployed page should open.
"Send invite" should not bring an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/22483740/109428353-1e781000-79f7-11eb-8465-58861399e08f.png)

**Device (please complete the following information):**
Win10, Chrome/FF

**Additional info**
I got an email from github:
"The page build failed for the `gh-pages` branch with the following error:
Unable to build page. Please try again later.
For information on troubleshooting Jekyll see:
  https://docs.github.com/articles/troubleshooting-jekyll-builds
If you have any questions you can submit a request at https://support.github.com/contact?repo_id=330423449&page_build_id=236583078"

**Comment by apalchys** [comment]
@VDudevich unfortunately, we can't help here. 

`The page build failed for the gh-pages branch with the following error:
Unable to build page. Please try again later` this error indicates that something wrong with your code in your branch and **Github** can't build the site.

Additionally, please pay attention that the URL in this step is wrong: 
"Try to open a deployed task (https://rolling-scopes-school.github.io/vdudevich-JSFE2021Q1/taskName)"

It should include folder name in your branch (`wildlife`)

**Comment by VDudevich** [comment]
@apalchys 
Sure, I know about the link to a deployed task, I didn't put a real task name in the link intentionally.
Okay I reverted the merged PR and will try to deploy again in the evening today. Let's see if it brings some results.
But to point out the deployment into netlify from my private repository was successful. Also deployment from my personal public test repository was successful with no changes in the code.
That's why I asked to check if the settings with my private school repository is correct.

Also what about the error in the RS App?

Thank you.

**Comment by apalchys** [comment]
> Also what about the error in the RS App?

it's a separate issue and relates to access permission but not deployment. it's fixed. please check if you can see it or not.

**Comment by VDudevich** [comment]
So Sent invite issue has been fixed: now it works.
After that I created a new PR with some minor changes and merged it into gh-pages.
The page opens successfully.
So closing this issue.
