### ISSUE TITLE
JSON Attributes can be reset unexpectedly on https: //app.rs.school/admin/tasks

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#636]
![image](https://user-images.githubusercontent.com/2429680/109429132-8a0fac80-79fa-11eb-832e-b5d558fe1efc.png)

**Comment by mikhama** [comment]
@irinainina Привет!
А можешь, пожалуйста, пошагово описать как воспроизвести проблему?
Я попробовал воспроизвести (если правильно понял) - но у меня не получилось.
Возможно что-то упускаю.

**Comment by irinainina** [comment]
Привет!
1. Заходишь в редактирование тасков https://app.rs.school/admin/tasks
2. Выбираешь любой таск, например RSS Test #0. Нажимаешь справа кнопку Edit
3. Меняешь ссылку. Или тип таска. Или название. Что угодно.
4. Кликаешь Save.
Всё. Теперь можно снова открыть редактирование таска и убедиться, что в JSON Attributes пусто (а раньше был код теста).
Важный момент: На третьем шаге JSON Attributes не трогаешь, не кликаешь по ним, вообще не обращаешь на них внимания. Если по ним кликнуть, хоть даже открыть и закрыть, код сохранится без изменений.

**Comment by irinainina** [comment]
Здесь ещё одна небольшая проблема с тестами описана https://github.com/rolling-scopes/rsschool-app/issues/647

**Comment by mikhama** [comment]
@irinainina спасибо!
