### ISSUE TITLE
HTML/CSS Test #0

### ISSUE THREAD

**Issue by Yostek87** [rolling-scopes/rsschool-app#645]
**Describe the bug**
Просьба проверить тест HTML/CSS Test #0 на наличие ошибок, так как есть основание полагать что в нескольких тестах установлены не верные варианты ответов. Либо возможность посмотреть какие ответы я выбрал и проверить еще раз.
Спасибо
**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

**Additional context**

**Comment by mikhama** [comment]
@Yostek87 привет!
Только что проверил дважды. Видимо с автором теста у меня ответы совпали - так как в обоих случаях получил 100%.
![image](https://user-images.githubusercontent.com/3992761/109690739-b7de2800-7b97-11eb-8762-210222906673.png)

Возможность выбрать посмотреть что было отправлено специально не предусмотрена - чтобы предотвратить списывания.

Напиши мне, пожалуйста в дискорде, и скинь скрин своих ответов - я посмотрю есть ли тут место багу.

Спасибо.
