### ISSUE TITLE
Варианты ответов не переносятся на новую строку

### ISSUE THREAD

**Issue by irinainina** [rolling-scopes/rsschool-app#647]
Автотесты в rs app очень хорошие и удобные, большое спасибо за них!
Есть небольшая проблема с вёрсткой. Длинные варианты ответов (и только они, вопросов это не касается) не переносятся на новую строку и прячутся под блок с результатами прохождения тестов.
![screenshot_31](https://user-images.githubusercontent.com/23195079/109810790-a6962980-7c32-11eb-8e33-11e424364b61.png)

**Comment by mikhama** [comment]
Кажется это должно пофикситься этим PR-ом: https://github.com/rolling-scopes/rsschool-app/pull/646

**Comment by mikhama** [comment]
Fixed in #646
