### ISSUE TITLE
Ошибка в тесте — «Как учиться в RS School»

### ISSUE THREAD

**Issue by Onore** [rolling-scopes/rsschool-app#651]
В Гугл опросе и вероятно в авто-тесте ошибка. 

[https://docs.google.com/forms/d/e/1FAIpQLSdkEbm9n5GgTd8sJM0RiVCDnozHhBpgOLVVMZgxJyDLe5EKdA/viewform](https://docs.google.com/forms/d/e/1FAIpQLSdkEbm9n5GgTd8sJM0RiVCDnozHhBpgOLVVMZgxJyDLe5EKdA/viewform)

"По какому времени в анонсах и в расписании указывается начало вебинаров и тестов, дедлайны тасков? *"

**Screenshots**
https://prnt.sc/10cdbd5

![image](https://user-images.githubusercontent.com/5087058/109870743-280dac00-7c73-11eb-9ed1-6f448b498780.png)

Предлагаю переформулировать вопрос, оставить только **время дедлайна**, которое важнее.
1. В рассписание время вебинаров в UTC+3 (GMT+3)
2. Дедлайны же в UTC, в вебинаре тоже делали на этом акцент.
3. Минское и московское это UTC+3 (GMT+3).

**Comment by ErikaMaer** [comment]
Сегодня столкнулась с этим же, снижен балл за реальный тест за этот вопрос, в тренировочном тесте попробовала разные вариации, убедилась, что ошибка.

**Comment by dzmitry-varabei** [comment]
@Onore тест в RS APP обновил. Теперь вопрос только про время дедлайна.
@irinainina Обнови, пожалуйста, формулировку в google form https://docs.google.com/forms/d/e/1FAIpQLSdkEbm9n5GgTd8sJM0RiVCDnozHhBpgOLVVMZgxJyDLe5EKdA/viewform

**Comment by ErikaMaer** [comment]
> @Onore тест в RS APP обновил. Теперь вопрос только про время дедлайна.
> @irinainina Обнови, пожалуйста, формулировку в google form https://docs.google.com/forms/d/e/1FAIpQLSdkEbm9n5GgTd8sJM0RiVCDnozHhBpgOLVVMZgxJyDLe5EKdA/viewform

Подскажите, пожалуйста, а вы ответ оставили такой же? Вчера прошла тест на 97 из-за того, что ответила "Московское", а не "Минское" - это одно и то же. Считаю, что несправедливо снижено.

**Comment by irinainina** [comment]
> @Onore тест в RS APP обновил. Теперь вопрос только про время дедлайна.
> @irinainina Обнови, пожалуйста, формулировку в google form https://docs.google.com/forms/d/e/1FAIpQLSdkEbm9n5GgTd8sJM0RiVCDnozHhBpgOLVVMZgxJyDLe5EKdA/viewform

1. Добавила возможность редактирования формы
2. В rs app указаны дедлайны по минскому времени

**Comment by dzmitry-varabei** [comment]
@irinainina  
1. Спасибо!
2. Странно, я думал что мы договорились указывать их в UTC

**Comment by irinainina** [comment]
> @irinainina
> 
> 1. Спасибо!
> 2. Странно, я думал что мы договорились указывать их в UTC

в расписании прошлого набора все дедлайны указаны по минскому времени https://docs.google.com/spreadsheets/d/1oM2O8DtjC0HodB3j7hcIResaWBw8P18tXkOl1ymelvE/edit#gid=1509181302

**Comment by dzmitry-varabei** [comment]
@irinainina а в RS APP я везде ставил UTC :)

**Comment by irinainina** [comment]
> @irinainina а в RS APP я везде ставил UTC :)

вопрос был не про rs app. "По какому времени в анонсах и в расписании указывается начало вебинаров и тестов, дедлайны тасков?" На момент выдачи теста ответ был правильным. Время в UTC указывается только в новом расписании, которое появилось значительно позже теста

**Comment by dzmitry-varabei** [comment]
@irinainina 
> На момент выдачи теста ответ был правильным. Время в UTC указывается только в новом расписании, которое появилось значительно позже теста

Да, конечно. Жалко, что сразу не вспомнил об этом вопросе в тесте.

**Comment by irinainina** [comment]
> Да, конечно. Жалко, что сразу не вспомнил об этом вопросе в тесте.

Я помнила и не стала ничего менять. До появления расписания вопрос про время в чате прозвучал десятки раз и десятки раз на него был получен ответ. Один и тот же ответ, не соответствующий тому, который указан как правильный после редактирования теста. В обновлённом расписании для дедлайнов и вебинаров используются две разные системы времени, а вариант ответа в тесте только один. В связи с этим у студентов появляется противоречие, которое им нужно решить. И это тоже часть теста "как учиться в rs school" - не только выбрать правильный ответ, но и научиться самостоятельно находить ответы на возникшие вопросы. Кто-то спрашивает в чате, предварительно попытавшись найти ответ самостоятельно [пример](https://discord.com/channels/516715744646660106/799659626958028850/814488337153916949), кто-то использует поиск по дискорду и находит ответы там. Ответы, которые на данный момент не соответствуют тому, что считается правильным ответом в отредактированном тесте.

**Comment by dzmitry-varabei** [comment]
@irinainina хорошо, приведу все к UTC и отпишусь в анонсы. Спасибо!

**Comment by irinainina** [comment]
> @irinainina хорошо, приведу все к UTC и отпишусь в анонсы. Спасибо!

Время UTC не очень удобное, так как перекидывает на следующий день. Если раньше студенты путали время (по какому часовому поясу его считать) то с переходом на UTC будут путать ещё и даты Например, в rs app отображается 09.03 01:59 и уже кто-то спрашивал, означает ли это, что что дедлайн перенесли на 09.03 вместо 08.03.  Можно сделать опрос, например, какое время удобнее.
P.S. для таких сложных вопросов, на которые разные источники дают разный ответ, раньше в тестах был допуск в 10% и я просила его оставить https://github.com/rolling-scopes/rsschool-app/issues/617#issuecomment-771951168 . Вероятно нужно будет результаты тестов пересчитать и выставить с этим допуском. К тому же это будет честно по отношению к студентам, которые присоединились к курсу после 2 февраля
