### ISSUE TITLE
Некорректно поставлен вопрос в тесте HTML/CSS Test

### ISSUE THREAD

**Issue by Eremeow138** [rolling-scopes/rsschool-app#652]
Course: JS/FE-2021-q1

**What is wrong**
Студенты путаются в вопросе "Возможные значения атрибута display".
Их смущает слово "атрибута". Потому что display - это свойство и у него есть значение, а не атрибут. 
Студенты думают, что это вопрос с подвохом и думают, что правильных ответов нет.
Предлагаю заменить слово "атрибута" на слово "свойства".
![image](https://user-images.githubusercontent.com/60056105/109932296-f8a77f80-7d04-11eb-8407-d7503c69c195.png)

**Comment by dzmitry-varabei** [comment]
@Eremeow138 спасибо! поправил!
