### ISSUE TITLE
Некорректно поставлен вопрос в тесте HTML/CSS Test #0

### ISSUE THREAD

**Issue by leolark** [rolling-scopes/rsschool-app#653]
**Course: JS/FE-2021-q1**

**What is wrong**
У этого вопроса
![](https://user-images.githubusercontent.com/32207706/109938581-3f837e00-7ce1-11eb-805a-3748a2d494ef.JPG)
может быть несколько трактовок
1. Если атрибут у тега, например p, то значения будут left, right, center, justify
2. Если атрибут у тега img, то значения будут bottom, left, middle, right, top

**Comment by dzmitry-varabei** [comment]
@leolark спасибо! поправил!
