### ISSUE TITLE
HTML, CSS & Git Basics

### ISSUE THREAD

**Issue by tkachukione** [rolling-scopes/rsschool-app#658]
**Course**
Specify your course (e.g. rs-2019-q1)
frontend 2021q

**What is wrong**
Describe data issue

Failed task requirements: No CV at https://tkachukione.github.io/rsschool-cv/. (Status: 404)
--

**Comment by apalchys** [comment]
I see it now

![image](https://user-images.githubusercontent.com/618807/110433029-ffe1db00-80c0-11eb-9131-a360f00f2d78.png)
