### ISSUE TITLE
Тестирование Cross-check 1.5

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#664]
Будем рады вашим замечаниям и предложениям!

**Comment by igorlyatskiy** [comment]
Добавить поле "Something else" для общего комментария, если проверяемый хочет что-нибудь дополнить, но эти изменения не вписываются в комментарии к каждому из пунктов. Туда же можно вручную написать контакты для связи с проверяемым при битой ссылке/спорном моменте

Score в условии 50 
![image](https://user-images.githubusercontent.com/77933579/110789504-00c16b00-8281-11eb-8aed-d2ff7c6d3cc6.png)

Score в футере 100
![image](https://user-images.githubusercontent.com/77933579/110789546-0cad2d00-8281-11eb-88ac-da829603f1b9.png)

**Comment by hallovarvara** [comment]
1. Максимальный балл сверху в форме 50, а снизу 100

2. Минусовые значения идут в скор как минусовые значения или как 0? Если как минусовые, надо предупредить студентов, что они могут не просто не получить баллы, но еще и потерять уже заработанные.

3. Хорошо бы менять надпись на кнопке submit на Update, когда заходишь после успешного сабмита, выбираешь снова таск и видишь предыдущую самооценку. И notification поменять на Self-review for task ”{taskname}“ was updated. И в идеале confirm сделать (Are you sure, that you want to update self-review for task ”{taskname}“? Previous version won't be available.) А то не до конца ясно, что случится после того, как нажмешь на кнопку во 2 раз.

**Comment by apalchys** [comment]
> На странице https://app.rs.school/course/student/cross-check-submit?course=test-course не указано явным образом, что это самооценка. Это может ввести в заблуждение.
 
by @spherical-horse

**Comment by irinainina** [comment]
Андрей, спасибо большое, апдейт очень полезный и нужный.
Три предложения. 
1. сделать все пункты обязательными, не разрешать отправить форму без их заполнения
2. добавить галочку "Отметить как лучшую работу" и возможность получить доступ к работам, отмеченным как лучшие.
3. пункт "выполнено частично - Partial" очень неоднозначный. Это может быть и 10% выполненных требований и 90%. Было бы хорошо, если студент отмечает этот пункт, дать ему возможность указать конкретное количество баллов за пункт (от нуля до максимального количества баллов за пункт требований)

**Comment by dzmitry-varabei** [comment]
@irinainina 
> 3. пункт "выполнено частично - Partial" очень неоднозначный. Это может быть и 10% выполненных требований и 90%. Было бы хорошо, если студент отмечает этот пункт, дать ему возможность указать конкретное количество баллов за пункт (от нуля до максимального количества баллов за пункт требований)

При введении градации внутри пункта будет еще больше разброс оценок для одной и той же работы, еще больше влияния удачи при рандоме (хороший/плохой/злой проверяющий). Еще больше споров/разочарований "Я фичу почти сделал, а мне поставили только половину баллов, надо было снял только 1. Кросс-чек - боль" и т.д. 

Студенты не должны решать сколько снять баллов за неполную реализацию.  Идеальный вариант - фича либо реализована полность, либо нет. А возможность получить хотя бы половину - приятный бонус.

**Comment by hallovarvara** [comment]
Прилетели студенты на проверку:

1. Нет блока самооценки.

2. Если дискорд не привязан к аккаунту, лучше не показывать строку со Student Discord.
![Screenshot 2021-03-12 at 11 14 40](https://user-images.githubusercontent.com/9438195/110913464-4126f480-8326-11eb-8567-45a696743ad9.png)

**Comment by VDudevich** [comment]
Нет чек-листа в Cross-check review

**Comment by irinainina** [comment]
> При введении градации внутри пункта будет еще больше разброс оценок для одной и той же работы, еще больше влияния удачи при рандоме (хороший/плохой/злой проверяющий). Еще больше споров/разочарований "Я фичу почти сделал, а мне поставили только половину баллов, надо было снял только 1. Кросс-чек - боль" и т.д.
> 
> Студенты не должны решать сколько снять баллов за неполную реализацию. Идеальный вариант - фича либо реализована полность, либо нет. А возможность получить хотя бы половину - приятный бонус.

Как оценивать пункт, когда "Я фичу почти сделал, но там остался незамеченный мной небольшой баг"?
Перечислить все возможные баги в критериях оценки невозможно, так как 
а) баги у всех разные
б) перечисление даже известных багов заставит писать критерии в сотни пунктов

**Comment by valerydluski** [comment]
После наступления дедлайна ссылку можно пересабмитить.

**Comment by spherical-horse** [comment]
Можно не отображать самооценку, если ссылка уже засабмичена. А то до ревью моей работы другими студентами приходится долго скроллить.

**Comment by valerydluski** [comment]
Так как у нас баллы за каждый пункт кратны 5. Может отображать 5 звезд?

**Comment by andreikovna** [comment]
1. Comments required
![image](https://user-images.githubusercontent.com/86688910/220545184-aea4d89f-725a-40bd-b039-d9305e9af005.png)

2. Think about validation while adding criterias (score)
![image](https://user-images.githubusercontent.com/86688910/220547007-dd2bcde6-21dd-4455-9bf8-127ece8eb934.png)

3. Check score calculation
![image](https://user-images.githubusercontent.com/86688910/220547407-0574a041-21c3-4c11-8ea5-69ab69b3a714.png)

4. 
![image](https://user-images.githubusercontent.com/86688910/220547645-21873d2b-f2ee-4658-a193-89bba89ab320.png)

5. Stars change to slider
![image](https://user-images.githubusercontent.com/86688910/220547757-adbc1133-4fad-41da-90a9-adccd7090d73.png)
