### ISSUE TITLE
error in the link

### ISSUE THREAD

**Issue by IvanDelendik** [rolling-scopes/rsschool-app#666]
**Describe the bug**

**To Reproduce**
1. Go to 'https://docs.rs.school/#/private-repository'
2. Scroll down to 'Как работать с приватным репозиторием?'
3. 2. Click on ' (см. требования к коммитам.'
4. Go to another page

**Expected behavior**
I click on the link "требования к коммитам.", and I get to the stage # 2 page

**Screenshots**If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/22748930/111065704-1a0a2780-84cc-11eb-863a-d2e9d08a85e1.png)

**Device (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [89.0.4389.90 ]

**Additional context**

**Comment by apalchys** [comment]
@IvanDelendik thanks. please use https://github.com/rolling-scopes-school/docs/issues in the future
