### ISSUE TITLE
не приходит инвайт для доступа в репозиторий

### ISSUE THREAD

**Issue by Alena3112** [rolling-scopes/rsschool-app#668]
не приходит инвайт для доступа в репозиторий

**Comment by apalchys** [comment]
Доступ к этому репозиторию должен быть:
https://github.com/rolling-scopes-school/Alena3112-JSFE2021Q1

Инвайт принят в гитхабе.

**Comment by Alena3112** [comment]
спасибо большое. а где инвайт в гитхабе смотреть?

**Comment by apalchys** [comment]
@Alena3112 Обычно приходит письмо на почту. В гитхабе не уверен, где его смотреть

**Comment by Alena3112** [comment]
Добрый день..мне опять не пришел инвайт для доступа в приватный репозиторий15.03.2021, 12:17, "Andrei" ***@***.***>:
Closed #668.
