### ISSUE TITLE
Teams: Integrate with RSS Teams app

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#673]
Yulia Galuzo просит помочь с интеграцией функционала https://rss-teams.web.app/ в RS APP

**Comment by MadaShindeInai** [comment]
@AlreadyBored maybe you can help?)

**Comment by AlreadyBored** [comment]
> @AlreadyBored maybe you can help?)

Unfortunately, I don't have a time for this right now :)
