### ISSUE TITLE
Course Task: Validation and description

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#678]
Возможность указать дополнительные параметры при создании таска (например, https://app.rs.school/course/admin/tasks?course=js-fe-2021Q1) проверяемого с помощью cross-check:
- требование, что сабмитуемая студентом ссылка должна содержат его github-username
- произвольный текст. Например, сообщение о необходимости сабмитить ссылку на демо, а не на pull request

**Comment by apalchys** [comment]
- CourseTask entity
- a field with free text
