### ISSUE TITLE
Нет ментора для проверки Piskel Clone

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#68]
Если по каким либо причинам ментор не может проверить вашу работу - отмечаемся здесь.

**Comment by ungear** [comment]
Студентка **alexalizurchik** не может связаться с ментором **dzianisreznik**

**Comment by mrstalon** [comment]
Студент petriken, ментор сказал что месяц не сможет проверить таск ( arhigod )

**Comment by leonidshparun** [comment]
А какой дедлайн для проверки таска?  Мой ментор отвечал до того, как скинул pr. После того, как скинул - тишина неделю. Но думал, что просто занят, плюс у него много студентов.
Поэтому вопрос, когда краний срок проверки?

**Comment by uniorunr** [comment]
@leonidshparun у тебя ж вроде проверили уже таск, судя по скору)

**Comment by net-ka** [comment]
мой ментор для проверки piskel (unsafefunction) уже не занимается менторством.

**Comment by leonidshparun** [comment]
> @leonidshparun у тебя ж вроде проверили уже таск, судя по скору)

лол, проверка как-то тихо прошла) спасибо, что заметил)

**Comment by AnLeonovich** [comment]
У студента mbulldozer ментор не может проверить.

**Comment by Eugenio7779** [comment]
студент Eugenio7779 ментор arhigod (в течении месяца не может проверить таск)

**Comment by strannik345** [comment]
у strannik345 ментор не отвечает

**Comment by VorobeyKirill** [comment]
Ментор unsafefunction оставил комментарии на pr, но потом не отвечал на сообщения и просто исчез из онлайна (не отвечает уже больше недели).

**Comment by grenbork** [comment]
Ментор morozzzz не отвечает, студент grenbork

**Comment by vovikilelik** [comment]
Я взял студента Eugenio7779-2019Q1 для проверки piskel-clon

**Comment by dzmitry-varabei** [comment]
@mrstalon @net-ka @AnLeonovich @strannik345 @VorobeyKirill @grenbork 
 Передал проверку работ ментору https://github.com/Killerkip10, его скайп live:b1680f2ef5b6dce5

**Comment by alex91pro** [comment]
добрый вечер не могу связаться с ментором 
amsterget написал на почту ему он не отвечает может другие контакты его есть ?

**Comment by Blackmantle** [comment]
ментор zhukovets не выходит на связь уже более двух недель, хотя на первое сообщение на почту ответил и попросил добавить в ревьюверы к пулл реквесту, но после добавления не принимает реквест и больше не отвечает на почту

**Comment by pavelrazuvalau** [comment]
Всем привет!
@alex91pro, @Blackmantle если до выходных ничего не изменится, стучитесь ко мне, проверю.
Skype: https://join.skype.com/invite/fj5LK3iu21gC
Telegram: https://t.me/pavelrazuvalau

CC: @dzmitry-varabei

**Comment by marry705** [comment]
студент marry705. Делала таск в команде. Мой ментор не отвечает на сообщения. Прошу перевести меня к ментору моего сокомандника. Ментор san4ezgig.

**Comment by AnastasiyaKul** [comment]
здравствуйте!
студентка anastasiyakul
ментор unsafefunction тоже не отвечает уже долго, хотя изначально выходил на связь

**Comment by apalchys** [comment]
@alex91pro @Blackmantle 
Отпишитесь, если вы перейдете к @pavelrazuvalau - я переведу вас в системе.

**Comment by Blackmantle** [comment]
> @alex91pro @Blackmantle
> Отпишитесь, если вы перейдете к @pavelrazuvalau - я переведу вас в системе.

Всё ок, ментор проверил таск)

**Comment by alex91pro** [comment]
а скор таска будет отображен ?хотел узнать свой результат )


>Среда, 17 июля 2019, 17:10 +03:00 от Dmitriy Krivitsky <notifications@github.com>:
>
>>@alex91pro @Blackmantle
>>Отпишитесь, если вы перейдете к  @pavelrazuvalau - я переведу вас в системе.
>Всё ок, ментор проверил таск)
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

С уважением,
alex al
warins91pro@mail.ru

**Comment by tppd67421** [comment]
Ментор korotkin говорил, что проверит таск, но в итоге перестал выходить на связь.
Студент tppd67421

**Comment by marry705** [comment]
@alex91pro переведите, пожалуйста, @marry705 к ментору @san4ezgig

**Comment by apalchys** [comment]
@marry705 
Уточни, пожалуйста. @san4ezgig будет именно ментором или проверяющим задание Piskel Clone?
Если второе, то он уже назначен проверяющим.

**Comment by vovikilelik** [comment]
Переведите @Eugenio7779-2019Q1 к ментору @vovikilelik, пожалуйста

**Comment by apalchys** [comment]
@Eugenio7779 -> @vovikilelik
готово.
