### ISSUE TITLE
[Course Mentors] Синхронизация списка менторов с GitHub Teams

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#682]
Иногда, ментора после регистрации на курс не получают инвайт в соответствующий курсу RSSchool GitHub Teams
https://github.com/orgs/rolling-scopes-school/teams и необходима возможность выслать инвайт повторно.

Андрей писал, что необходимый API уже есть, нужно только добавить кнопку `Sync with GitHub Teams` на страницу course/admin/students слева от кнопки `create repos`.

**Comment by apalchys** [comment]
POST `/course/${courseId}/repositories/mentors`

**Comment by SvetlovVitaliy** [comment]
Done
