### ISSUE TITLE
[Registration] - Неиспользуемое поле Comments при регистрации студента

### ISSUE THREAD

**Issue by YuliyaZhur** [rolling-scopes/rsschool-app#686]
**Course**
Specify your course (e.g. rs-2019-q1)

**Убрать неиспользуемое поле Comments в форме регистрации, занимающее большую часть полезного пространства страницы**
31/03/2021

**Comment by dzmitry-varabei** [comment]
@Pulya10c Речь только о странице регистрации студентов https://app.rs.school/registry/student
