### ISSUE TITLE
Changed my github login and lost all my data.

### ISSUE THREAD

**Issue by kejno** [rolling-scopes/rsschool-app#693]
**Describe the bug**
My data , process into app school profile page were lost

**Expected behavior**
I changed my user login for github and my status, statistics, courses were lost.

**Screenshots**
![rss](https://user-images.githubusercontent.com/48594817/113563653-bf6a7400-9610-11eb-8ecb-192b9e5c7428.png)

**Additional context**
How can I restore my access in app school?

**Comment by apalchys** [comment]
@kejno what's you old github id?
