### ISSUE TITLE
Добавить comment к оценке кроссчека, присылаемой ботом в телеграм 

### ISSUE THREAD

**Issue by natein** [rolling-scopes/rsschool-app#695]
На текущий момент бот присылает в телеграм такое уведомление об оценке:

![CropperCapture 1](https://user-images.githubusercontent.com/12632270/113925960-49befd80-97f4-11eb-88b1-04f71de9cc6f.jpg)

Хотелось бы также получать комментарий, оставляемый студентами при проверке, чтобы не приходилось запускать rsschool-app для его просмотра.

**Comment by Student-Java** [comment]
https://github.com/rolling-scopes/rsschool-app/pull/702
