### ISSUE TITLE
Restore access to 

### ISSUE THREAD

**Issue by Margarita-3M** [rolling-scopes/rsschool-app#697]
Describe the bug
My access into app school profile page was lost due to change of GitHub account name.

Expected behavior
I changed my user login from Mystika007 to Margarita-3M in GitHub and my status, statistics, courses were lost. I would like to restore access under a new account name Margarita-3M.

**Comment by apalchys** [comment]
Done. Please re-login https://app.rs.school/login

**Comment by Margarita-3M** [comment]
Thank you!!!
