### ISSUE TITLE
Score не верные id

### ISSUE THREAD

**Issue by EgnGron** [rolling-scopes/rsschool-app#698]
**Describe the bug**
Во вкладке Score, id отображаются как 999999

**To Reproduce**
1. Go to 'Score' into course iOS 2021 

**Screenshots**
<img width="508" alt="Screenshot 2021-04-11 at 00 24 13" src="https://user-images.githubusercontent.com/5830632/114285068-e1268980-9a5c-11eb-99c0-672968b7d5d3.png">

**Device (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version [89.0.xxxxx]

**Comment by apalchys** [comment]
Currently Score for all courses is calculated once per day. For new users, position is set to 999999 by default until we do first calculation for them.
