### ISSUE TITLE
не могу найти проверяющего (нет данных о нем)

### ISSUE THREAD

**Issue by magerrrr** [rolling-scopes/rsschool-app#710]
**Course**
Specify your course (e.g. rs-2021-q1)

![image](https://user-images.githubusercontent.com/17405745/115278641-5de8f000-a14e-11eb-9743-40d1274327bd.png)
https://prnt.sc/11pkqp3

Отсутствует информация о человеке и найти его не могу (ни гитхаба, ни дискорда) - можете может в БД посмотреть? он заасайнен на проверку пулл реквеста - https://github.com/magerrrr/rslang/pull/8

**Comment by tastypurgen** [comment]
С каких пор видимость проверяющего не опциональна?

**Comment by magerrrr** [comment]
дело в том, что человек, который проверял - даже не регистрировался в приложении, судя по базе данных, а выставил оценки либо на рандоме, либо как-то еще :))) и это не совсем честно и объективно :) Я конечно рад, что он не один это сделал, но когда баллы около 400 у всех и один человек пишет 200, это неприятно, когда мы старались на максимум баллов :) @tastypurgen

**Comment by tastypurgen** [comment]
С чего вы взяли что он не зарегистрирован? @magerrrr

**Comment by Iogsotot** [comment]
@magerrrr в таких случаях просто ждёте 4ю оценку и тогда наименьшая отбрасывается. Если совсем всё плохо, то апелляция и, возможно, ручная проверка от активистов. 
Деанонить студента, как бы нечестно он ни выставил баллы, никто не будет в такой ситуации.

**Comment by magerrrr** [comment]
@tastypurgen Посмотрел в монге юзеров зареганых) 3 человека проверяющих, а только 2 аккаунта. Все остальные аккаунты моей команды
@Iogsotot дааа, я вот и ждал 4 оценки :) но она все еще не появилась, к сожалению :) и скорее всего уже не появится

**Comment by tastypurgen** [comment]
@magerrrr все действительно как описал человек выше: либо ждете четвертую оценку, либо подаете на апелляцию. Проблема тут только в говнистости этого проверющего, но никак не в приложении rsapp.

Поэтому можете закрывать issue :)

**Comment by magerrrr** [comment]
@tastypurgen да :) согласен, теперь я понял и спасибо большое всем за быстрые ответы! а приложение огонь!! :)
но я бы выпилил эту анонимность )))))
