### ISSUE TITLE
[Score] Упорядочить название городов

### ISSUE THREAD

**Issue by mariohs22** [rolling-scopes/rsschool-app#713]
**Course**
js-fe-2021Q1

**What is wrong**
Один и тот же город у разных студентов записан по разному. Например Гомель может быть записан как Gomel, Homyel, Homel - необходимо установить какое-то одно наименование, например Gomel.

**Comment by dzmitry-varabei** [comment]
@mariohs22 мы используем google api, это стандартное поведение
