### ISSUE TITLE
A new type of achievement (gratitude) for the best works

### ISSUE THREAD

**Issue by maksumov** [rolling-scopes/rsschool-app#720]
**Describe the feature**
It is necessary to create a new type of achievement that will be awarded to the authors of the best works. It is assumed that this functionality can be created as a kind of gratitude. The award will be given by the author of the task or the administration (not available for everyone). Valery Dluski promised to find the designer of the badge.

**Comment by dzmitry-varabei** [comment]
@Pulya10c Олег, привет!
Название бейджа - "Outstanding work"
Исходник - https://www.dropbox.com/s/veok1dlet5k5lqi/Fav.svg?dl=0
