### ISSUE TITLE
Not able to select a student on the TechScreening feedback form page

### ISSUE THREAD

**Issue by OlegSubik** [rolling-scopes/rsschool-app#722]
**Describe the bug**
Not able to select a student on the TechScreening feedback form page

**To Reproduce**
1. Go to https://app.rs.school/course/mentor/interview-technical-screening?course=js-fe-en&githubId=%7Bputgithubidhere%7D
2. Click on "student" input/selector
3. See that no options are available to select, however, there are students assigned to a interviewer (see network result on the screenshot)
4. Clicking outside the selector resets its value to default, and the form is not valid to submit

**Expected behavior**
a student shows in the dropdown list of the input field

**Screenshots**
![image](https://user-images.githubusercontent.com/51403321/116695739-abc0ec00-a9c9-11eb-96e7-8d30778302d8.png)

**Device (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version latest
 
 Interviewer: Oleh Subbota
 Student: Dzmitry Shchapiorka

**Comment by ShekoMaxim** [comment]
I have a similar bug
