### ISSUE TITLE
New registration form for students 

### ISSUE THREAD

**Issue by Proleyko** [rolling-scopes/rsschool-app#724]
New registration form for students RS School

https://www.figma.com/file/cZUmYEeRLuXh8G4uj1zlCj/RS-School-student-registration?node-id=29%3A2

**Comment by Pulya10c** [comment]
@Proleyko We need the design of one more page, where we can select from the list of courses available for registration.

![image](https://user-images.githubusercontent.com/30927000/121783114-938de080-cbb5-11eb-9316-f93ada6012ef.png)

**Comment by Pulya10c** [comment]
@Proleyko  We need a design for the mobile version.

**Comment by Proleyko** [comment]
@Pulya10c https://www.figma.com/file/AcKnnGExCkZx9wFohKGAZJ/Ant-Design-Open-Source-Community-Copy-Copy?node-id=29%3A2

New form!
