### ISSUE TITLE
[Technical Screening] Возможность вручную ввести Score 

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#728]
**Проблема**
Ментор может увидить оценку за Technical Screening только после сабмита формы https://app.rs.school/course/mentor/interview-technical-screening?course=js-fe-2021Q1

**Решение**
Предоставить возможность ментору задать оценку вручную. Например, так:
![image](https://user-images.githubusercontent.com/2429680/117301006-765d4800-ae7a-11eb-9d09-8438532a6019.png)

В идеале. Оценка рассчитывается сама (как сейчас), видна в поле "score" сразу, у ментора есть возможность ее изменить.

**Comment by taccianka** [comment]
Очень жду данное обновление. Почему-то конкретно у меня оценка у ментора не проставляется. С другими его студентами такой проблемы нету. Ментор отправлял оценку несколько раз
