### ISSUE TITLE
Rename "items" to "students" in Score

### ISSUE THREAD

**Issue by hallovarvara** [rolling-scopes/rsschool-app#747]
**Describe the bug**
It's a little confusing to realize, that all of us just items :)

**To Reproduce**
1. Just go to Score and look at right-bottom screen corner.

**Expected behavior**
"items" will be fixed for "students"

**Screenshots**
![image](https://user-images.githubusercontent.com/9438195/118354249-e488c580-b572-11eb-80bb-4d77bc396d52.png)

**Comment by apalchys** [comment]
Closed in https://github.com/rolling-scopes/rsschool-app/pull/749
