### ISSUE TITLE
Add to Score filtering settings possibilities to select and deselect all tasks

### ISSUE THREAD

**Issue by hallovarvara** [rolling-scopes/rsschool-app#748]
**Describe the feature**
Add buttons for selecting and deselecting all options. On Front-end course it's struggling to selecting/deselecting all manually.

![image](https://user-images.githubusercontent.com/9438195/118354394-8b6d6180-b573-11eb-851f-fcb155aef3fc.png)

**Comment by apalchys** [comment]
Closed in https://github.com/rolling-scopes/rsschool-app/pull/750
