### ISSUE TITLE
Cannot expel student, who has not been interviewed

### ISSUE THREAD

**Issue by iliyaking46** [rolling-scopes/rsschool-app#751]
There is no way to expel a student you did not interview

**Actual result**:
https://app.rs.school/course/mentor/expel-student?course=js-fe-2021Q1
At this page I can expel only students, which I have been interviewed
<img width="997" alt="Screenshot 2021-05-18 at 16 30 09" src="https://user-images.githubusercontent.com/11744741/118659826-545ab280-b7f6-11eb-9f4d-8ccf1b397322.png">

**Expected result**: the ability to exclude all attached students

**Comment by apalchys** [comment]
@iliyaking46 it's by design. Why do you want to expel someone who is not interviewed?

**Comment by iliyaking46** [comment]
@apalchys it needs when a student was appointed but refused interview (in my case student find a job and I can't interviewed him or expel 😕)
