### ISSUE TITLE
Can't save Subscription's change in profile 

### ISSUE THREAD

**Issue by VestryOd** [rolling-scopes/rsschool-app#753]
### Description
When change Subscriptions in profile doesn't appear "Save" button. All changes stay unsaved. 

**Steps to reproduce the behavior:**
1. Open RS-App home page.
2. Click on Profile button in right top corner
 ![image](https://user-images.githubusercontent.com/13331142/118873474-7afe1380-b8f2-11eb-9c28-ddf4b82a6088.png)
3. Click on the Edit item
4. Change some items in Subscriptions area 
![image](https://user-images.githubusercontent.com/13331142/118873634-a2ed7700-b8f2-11eb-8816-a6b96e8c6929.png)
5. Save button doesn't appear (near the Profile drop-down menu) 
![image](https://user-images.githubusercontent.com/13331142/118873926-fc55a600-b8f2-11eb-8e84-46fa642e08fb.png)

**Expected behavior**
After Subscriptions flags change save button is appeared and all changes will save

**Device (please complete the following information):**
 - OS: Windows
 - Browser Chorme
 - Version 90.0.4430.212

**Comment by dzmitry-varabei** [comment]
@Pulya10c 
1) Since the "Email Notifications" feature is not implemented yet, please remove it from the user interface.
2) Please also change the "Subscriptions" header to "Telegram Notifications".

**Comment by Pulya10c** [comment]
@VestryOd 
I cannot reproduce the bug for the specified steps. Could you give me more information?
