### ISSUE TITLE
Schedule 2.0 Issues

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#760]
1) При добавлении таска типа "Cross-check"  нет возможности указать количество пар кросс-чек проверки

2) Нельзя добавить таск типа Jupiter Notebook

3) У курс-менеджеров нет возможности редактировать расписание. ( см https://github.com/rolling-scopes/rsschool-app/issues/785)

**Comment by dzmitry-varabei** [comment]
2) Нельзя добавить таск типа Jupiter Notebook

**Comment by valerydluski** [comment]
![image](https://user-images.githubusercontent.com/57412523/122757851-c7958f80-d2a0-11eb-9469-674a15e1f5e9.png)
мне кажется эта кнопка не должна быть видна для студентов

**Comment by valerydluski** [comment]
![image](https://user-images.githubusercontent.com/57412523/124575326-f93b5880-de53-11eb-9d5a-29b2abac0768.png)

**Comment by valerydluski** [comment]
![image](https://user-images.githubusercontent.com/57412523/126264922-684ab935-2818-49fb-8e45-87e74bd49bab.png)
при попытке поменять оценку ошибка.
![image](https://user-images.githubusercontent.com/57412523/126265009-0c1bc511-e7e2-4ca8-9fac-7399cb7fd2f0.png)
![image](https://user-images.githubusercontent.com/57412523/126265028-a3b5d102-ec02-4384-b2a0-914b9b24a516.png)
