### ISSUE TITLE
After gtihub username was renamed mentor's menu not showing on RSS site

### ISSUE THREAD

**Issue by veranikashneidzer** [rolling-scopes/rsschool-app#772]
**Describe the bug**
I renamed my GitHub nickname and then log in to https://app.rs.school/
Unfortunately, I don't see anymore mentor's menu. 
Instead of this, I see 2 buttons - Register as a student and register as a mentor.

**To Reproduce**
1. Go to GitHub setting => Account
2. Change your username
3. Save
4. Go to https://app.rs.school/
5. Login via Github

**Expected behavior**
I see the mentors menu since I've already registered on this site as a mentor and pass verification

**Device (please complete the following information):**
 - Browser Chrome
 - Version  91.0.4472.77

**Comment by apalchys** [comment]
@veranikashneidzer please tell me your old github username. I will update it in the database.

**Comment by veranikashneidzer** [comment]
@apalchys veronikashneidzer

**Comment by apalchys** [comment]
@veranikashneidzer  fixed
