### ISSUE TITLE
There are no scores for Technical Screening task in the mentee statistic dialog

### ISSUE THREAD

**Issue by Gervenel** [rolling-scopes/rsschool-app#777]
There are no scores for Technical Screening task in the mentee statistic dialog, but they are in the score table.
Such issue reproduces for every one of my mentees.

1. Go to mentee page.
2. Select mentee statistic for JavaScript/Front-end 2021Q1 course.
3. Scroll down to Technical Screening task.
4. See there no scores.
5. Go to [score table](https://app.rs.school/course/score?course=js-fe-2021Q1) 
6. See there are scores for this task

Expected behavior
In the mentee statistic for JavaScript/Front-end 2021Q1 course should displays Technical Screening scores.

![image](https://user-images.githubusercontent.com/48750202/122029548-02e61900-cdde-11eb-8b5b-65fe57d507ae.png)
![image](https://user-images.githubusercontent.com/48750202/122029588-0c6f8100-cdde-11eb-95e2-cb548fe1319e.png)
[mentee github](https://github.com/tatsiana-bivoina)

 - OS: Windows 10
 - Browser chrome
 - Version 91

**Comment by kirban** [comment]
+1
[My student](https://github.com/zabalueva) has the same issue.

![Capture](https://user-images.githubusercontent.com/24736598/122036326-1d1ef780-cddc-11eb-8a2f-64366eac2604.PNG)
![photo_2021-06-08_09-34-33](https://user-images.githubusercontent.com/24736598/122036362-24de9c00-cddc-11eb-88ba-721f2ce498f2.jpg)
