### ISSUE TITLE
Dashboard task statistics bug

### ISSUE THREAD

**Issue by igorlyatskiy** [rolling-scopes/rsschool-app#784]
**Course**
JS/Fronend 2021Q1

**What is wrong**
В RSAPP в dashboard в Tasks statistics отсутствует таск presentation (recorded), хотя он присутствует и в score, и в Next event этого же dashboard. Отсутствует — значит его просто нет, не только отметки 0 (ментор пока что не оценивал), но и в принципе таска

Суммарно в dashboard в Tasks statistics 34 таска, хотя у остальных людей их 35

![image](https://user-images.githubusercontent.com/77933579/122879726-e4ce6a80-d341-11eb-8071-c98fedfd22cd.png)
![image](https://user-images.githubusercontent.com/77933579/122879748-e9931e80-d341-11eb-9767-eecde09c3d8f.png)
![image](https://user-images.githubusercontent.com/77933579/122879778-f0ba2c80-d341-11eb-8755-8d24ad768962.png)

Прикрепляю три раздела tasks statistics, нигде его нет

**Comment by valerydluski** [comment]
не воспроизводится
