### ISSUE TITLE
Registry: Improve mentor registration process UX

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#787]
1) https://app.rs.school/admin/mentor-registry
    - Курс менеджеры не видят менторов, которые преселектнули несколько курсов
    - Курс менеджеры не видят менторов на основании выбранного ментором скилла при регистрации (javascript, nodejs, react).  Например, ментор указал, что знает nodejs но не указал конкретный курс, на котором он хочет менторить. В результате менеджер nodejs курса не увидит заявку этого ментора.  
2) Процесс регистрации
    - Ментора не получают контактов координатора и тг группу, до одобрения из заявки на менторинг
    - Ментора не знают об одобрении заявки на менторинг, если нотификации отключены. Ссылка вида https://app.rs.school/course/mentor/confirm?course=test-course не приходит
3) Процесс регистрации для "ветеранов" rs school. 
- Необходимо предоставить возможность для тех, кто сам закончил школу или уже менторил, получать одобрение на менторинг автоматически, без лишнего ожидания и аппрува админа
<img width="728" alt="image" src="https://user-images.githubusercontent.com/2429680/168062542-5fd62c09-4322-4d59-a2b3-c65fae351429.png">

4) Текст не всегда актуален
<img width="604" alt="image" src="https://user-images.githubusercontent.com/2429680/168551500-7a2c5a92-01f8-48f9-9451-9ac497b63cef.png">

**Comment by valerydluski** [comment]
@dzmitry-varabei I think we can close this issue

**Comment by dzmitry-varabei** [comment]
@valerydluski let's discuss on the next weekly
