### ISSUE TITLE
Change location in profile settings bug

### ISSUE THREAD

**Issue by foggylight** [rolling-scopes/rsschool-app#795]
**Describe the bug**
В настройках профиля нет возможности поменять локацию: input схлопывается, поиск локации не осуществляется.

**To Reproduce**
1. Баг можно увидеть в разделе редактирования профиля, надо нажать иконку редактирования основной информации (имя и локация):
<img width="278" alt="Снимок экрана 2021-07-02 в 16 29 04" src="https://user-images.githubusercontent.com/54042631/124284020-3c947f00-db55-11eb-86ca-e6aa9c1bb2ad.png">

2. Вид после нажатия на input с текущей локацией:
<img width="278" alt="Снимок экрана 2021-07-02 в 16 29 14" src="https://user-images.githubusercontent.com/54042631/124285239-6a2df800-db56-11eb-9329-22b15ab7292e.png">

3. Баг появляется после начала ввода: 
<img width="278" alt="Снимок экрана 2021-07-02 в 16 29 23" src="https://user-images.githubusercontent.com/54042631/124285591-b7aa6500-db56-11eb-9880-1ba566ce1ffb.png">

Введенное значение появляется в атрибуте value, но не выводится в сам input и не осуществляется поиск, новое значение нельзя сохранить.

**Expected behavior**
После начала ввода ожидается появление выбора из предложенных локаций, совпавших с введенным значением.

**Device:**
 - Browser Сhrome
 - Version 91

**Comment by MikolaSh** [comment]
Актуально для 07.07

**Comment by taccianka** [comment]
Актуально для 19.07
