### ISSUE TITLE
i cant open HTML for beginners. It's been three days and she still gives 404

### ISSUE THREAD

**Issue by eroha-python** [rolling-scopes/rsschool-app#800]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

**Additional context**

**Comment by dzmitry-varabei** [comment]
@eroha-python Hello! Could you please provide more details? E.g., course name, task name, etc.

**Comment by irinainina** [comment]
Вопрос о курсе https://ru.code-basics.com/languages/html, когда у нас новый набор, они не справляются с нагрузкой. Вопрос не касается rs app, ишью можно закрывать
