### ISSUE TITLE
Schedule: Error when changing max score

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes/rsschool-app#816]
Error when changing max score 
![image](https://user-images.githubusercontent.com/57412523/126605058-f3d60e16-f507-4481-9775-c6d93d9d94c0.png)
![image](https://user-images.githubusercontent.com/57412523/126605071-2f8cf3ba-b92f-4af8-a052-0708fa446ec3.png)
![image](https://user-images.githubusercontent.com/57412523/126605079-91347c59-3f03-43c3-b868-e592c7a59c41.png)

**Comment by not-SAINT** [comment]
@apalchys нужна помощь. Без логов и данных базы (constraint) разобраться не представляется возможным.

**Comment by valerydluski** [comment]
![image](https://user-images.githubusercontent.com/57412523/132386778-1423e3ea-ac8a-45bd-a5c6-47304e411093.png)
не тянется json тестов и при попытке отредактировать такая же ошибка
