### ISSUE TITLE
Schedule React. Routing

### ISSUE THREAD

**Issue by Wolf-Den1994** [rolling-scopes/rsschool-app#826]
Не показывает в Schedule выдачу задания React. Routing в виде списка. В виде таблицы и календаря всё показывает.
08.03.2021 должна быть выдача, у других людей показывает, у меня нет. Пробовал перезагружать страницу со сбросом кэша, смотрел с другого браузера и с телефона тоже нету.

**Screenshots**
![image](https://user-images.githubusercontent.com/68957176/128066508-4bf50897-9ebc-4c7a-945c-7097fd728457.png)

**Device (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Версия 92.0.4515.107 (Официальная сборка), (64 бит)

Курс React 2021q1

**Comment by not-SAINT** [comment]
С исправлениями в #839 проблема должна быть решена.

**Comment by Wolf-Den1994** [comment]
Проблема решена 👍
