### ISSUE TITLE
New members get personal number 999999 after registration for JavaScript/Front-end 2021Q1 course.

### ISSUE THREAD

**Issue by gmakeev** [rolling-scopes/rsschool-app#830]
New members get personal number 999999 after registration for JavaScript/Front-end 2021Q1 course.

**To Reproduce**
1. Go to link https://app.rs.school/course/score?course=js-fe-2021Q1 after registration for JavaScript/Front-end 2021Q1 course
2. Click on 'Sort by unique number' (first column)
3. Scroll down to last page( 14th page)
4. See error - last dozen new members have same unique numbers 999999

**Expected behavior**
New member's number must be assigned in sequence +1.

**Screenshots**
Screenshot has been added by link
![image](https://user-images.githubusercontent.com/19663756/128887091-839fbdfb-4d67-4d98-8f46-f3b35ec1e083.png)

**Comment by apalchys** [comment]
Fixed. Now we display `New` to avoid confusion. The score calculated once per day and for newcomers will be updated during max 24h.
