### ISSUE TITLE
Bug: Codewars basic-2

### ISSUE THREAD

**Issue by 69abadon69** [rolling-scopes/rsschool-app#843]
**Describe the bug**
When I submit it writes me 0 scores and in details written "Request failed with status code 404"

**To Reproduce**
1. Go to 'RS School'
2. Click on 'Auto-test'
3. Scroll down to 'coders basic-2'
4. Request failed with status code 404

**Expected behavior**
It was working earlier, but now not.

**Screenshots**
![image](https://user-images.githubusercontent.com/58501268/130271816-8179e3d0-8daa-47d8-b23d-fcb065fe7c14.png)

**Device (please complete the following information):**
 - Browser [chrome, ]

**Additional context**

**Comment by mikhama** [comment]
@69abadon69 can I ask you to specify your codewars username?

**Comment by mikhama** [comment]
@69abadon69 is this issue still actual?

**Comment by 69abadon69** [comment]
Sorry for the late answer, that task is closed and I think the issue is
solved,  5-th kata it is deleted from Codewars that caused a problem I
wrote in Codewars support and that's what they said.

**Comment by mikhama** [comment]
@69abadon69 Thank you!
