### ISSUE TITLE
О Auto-test

### ISSUE THREAD

**Issue by Jirafek** [rolling-scopes/rsschool-app#859]
**Course**
Specify your course (e.g. rs-2021-q3)

**What is wrong**
Мои очки за тесты

Здравствуйте, я вчера проходил тесты по html (100%), RSS test (93%), Css test (75%, тоесть 0 очков). Но по css тесту у меня еще есть 1 попытка, и написано что если тест здан на ноль все боллы делятся пополам. Так у меня все баллы разделились на 10, у меня сейчас 19.3 баллов. Так вот если я здам тест по css у меня все баллы востановятся?

**Comment by dzmitry-varabei** [comment]
@Jirafek Оценки за тесты идут в общий score c коэффициентом 0.1.
За три теста вместе можно получить максимум 30 баллов.

![image](https://user-images.githubusercontent.com/2429680/132337941-12c93f9a-f5d2-4e85-ac94-fff06afee24b.png)
