### ISSUE TITLE
Static text "number of attempts" in section "Description" -> "Note"

### ISSUE THREAD

**Issue by goryaginvs** [rolling-scopes/rsschool-app#862]
**js-fe-2021Q3**

**What is wrong**
In auto-tests (https://app.rs.school/course/student/auto-test?course=js-fe-2021Q3) confuses me static text "number of attempts" in section "Description" -> "Note" -> You must score at least 70% of points to pass. You have only 2 attempts.

I am a beginner and during the first attempts to pass the test, I did not notice this warning, and only the third time did I notice the text that I have only 2 attempts (I thought that I had 2 more attempts left). I did not pass the test, I was greatly discouraged and demotivated by this fact. The insult remained that I did not immediately notice the total number of attempts, it was my own fault.
![test](https://user-images.githubusercontent.com/90096776/132304458-b59d9b1f-e6a2-4968-988a-54c4a3547cb7.png)

I suggest to display the number of attempts:

- [x] 1. Increase the font
- [x] 2. Change the color of the number depending on the number of attempts.
- [x] 3. Display dynamically the number of REMAINING attempts
- [x] 4. At the last attempt, indicate "Your last attempt"
- [x] #885

**Comment by mikhama** [comment]
When you have more than one attempt:
![image](https://user-images.githubusercontent.com/3992761/133450592-374a2b95-ada8-4954-b842-43fadee8e8e4.png)

When you have only one:
![image](https://user-images.githubusercontent.com/3992761/133450815-45c407af-df10-407f-b80a-8e3cdbe1804c.png)

When you've wasted all your attempts:
![image](https://user-images.githubusercontent.com/3992761/133450879-642e252c-163c-4b65-b0f2-445f784b33dc.png)

When you've wasted all your attempts, and strict mode have been enabled:
![image](https://user-images.githubusercontent.com/3992761/133450969-1c85ebf0-d0be-4f6c-b9dc-0d417af07978.png)

**Comment by mikhama** [comment]
@goryaginvs we don't support dark theme, and this highlight is only the part of ant-design, and it's the same for the whole app. I've converted this point in issue, so probably if someone will be interested in creating dark theme for the app, he take care of this issue.
