### ISSUE TITLE
HTML Basics [RU]: В описании теста была допущена грамматическая ошибка

### ISSUE THREAD

**Issue by KuperIvan** [rolling-scopes/rsschool-app#866]
**Device:** 
  **OS:** Linux Ubuntu 21.04 LTS
  **Browser:** Google Chrome Version 93.0.4577.63

**Description:** 
  1. Go to [link](https://app.rs.school/);
  2. Click on button "Auto-Test";
  3. In drop-down menu choose "Test HTML Basics [RU];
  4. See grammatical error
 
**Result:**  There is a grammatical error in test "Какой атрибут указывает путь к файлу или стринице, где располагается обработчик данных формы?" at word "стринице",  check screenshot in attachements.
**Expected Result:** The word "стринице" should be correct "странице".

![34](https://user-images.githubusercontent.com/59666842/132507537-8597ac8f-b7d6-49d1-b1cd-c8f14183cb8f.png)

**Comment by helenakrasnova** [comment]
Fixed
