### ISSUE TITLE
Повтор одного вопроса в тестах

### ISSUE THREAD

**Issue by algolj** [rolling-scopes/rsschool-app#892]
**Describe the bug**
В таске вопрос выпал два раза подряд.

**To Reproduce**
1.  Сhoose course JavaScript/Front-end 2021Q3
2. Go to 'Auto-Test'
3. Open task 'JS Scope & Functions'

**Screenshots**
![повтор](https://user-images.githubusercontent.com/36418446/134302069-d40535b9-4467-4cfd-b618-a455a7e63f42.png)
![screencapture](https://user-images.githubusercontent.com/36418446/134306048-3909dedb-7acb-4d71-9871-22fed54a3288.png)
*Мои ответы закрыл черными прямоугольниками

**Device (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 93.0.4577.82

**Comment by mikhama** [comment]
Hi @algolj,
Look carefully, it's not a bug.
There are different pictures (var vs let).
