### ISSUE TITLE
Idea: Job board

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#893]
Примеры объявлений: 
![image](https://user-images.githubusercontent.com/2429680/134357429-25e72f1a-b779-41b7-ba76-8309a2ca7922.png)
![image](https://user-images.githubusercontent.com/2429680/134357543-b310189a-329c-4d6a-b6fe-10c2ecaff641.png)
![image](https://user-images.githubusercontent.com/2429680/134357634-2eea2bba-615e-44de-9dfe-4ae2568e56bb.png)

- Возможность для супервазеров разместить объявление
- Возможность для студентов предложить свое CV

**Comment by apalchys** [comment]
Related https://github.com/rolling-scopes/rsschool-app/issues/942
