### ISSUE TITLE
Tech Debt: Replace moment.js with day.js

### ISSUE THREAD

**Issue by apalchys** [rolling-scopes/rsschool-app#928]
See https://ant.design/docs/react/replace-moment

**Comment by Semigradsky** [comment]
Maybe `date-fns`? It looks more maintainable: [`date-fns`](https://github.com/date-fns/date-fns/pulse/monthly) vs [`dayjs`](https://github.com/iamkun/dayjs/pulse/monthly)

https://www.npmtrends.com/dayjs-vs-date-fns

**Comment by apalchys** [comment]
or `date-fns` :) 

I put `dayjs` because it has a webpack plugin that potentially could allow to make changes without changing single line of code.
