### ISSUE TITLE
Schedule: Improve schedule page

### ISSUE THREAD

**Issue by pnv13** [rolling-scopes/rsschool-app#931]
Во вкладке schedule есть колонка score, в которой студенты могут видеть какое кол-во баллов за задание он/она получил, при этом студент не всегда знает, а какое вообще кол-во баллов можно получить за то или иное задание, а главное где это посмотреть.

Моё предложение: добавить во вкладке schedule в колонку score значение "насколько сдал / максимальный балл за задание". Например задание codewars "60 / 70".

**Comment by agitaev** [comment]
Имеется еще один баг связанный с этим таском. В данное время если оценка еще не выставлена по заданию, то вкладка отображает его как `null / 100`, что не читабельно. 
![image](https://user-images.githubusercontent.com/23414386/144072155-95fa9dad-89e6-4fb3-a831-e6151d40de6d.png)
Предлагаю следующее: если студенту еще не выставлена оценка по конкретнему заданию, то показать значение как `0 / 100` вместо `null / 100`

**Comment by dzmitry-varabei** [comment]
@pnv13 @agitaev спасибо за ваши предложения, все готово!
