### ISSUE TITLE
Crash error in profile-edit tab

### ISSUE THREAD

**Issue by shpakkdv** [rolling-scopes/rsschool-app#95]
**Unable to edit the profile info**

**Steps To Reproduce:**
1. Go to 'http://app.rs.school/'
2. Click on profile icon with dropdown (top right hand corner)
3. Choose 'My profile'
4. In open tab (http://app.rs.school/profile) click on 'EDIT' button (top right hand corner)
5. See the screen 'AN UNEXPECTED ERROR HAS OCCURRED.' and console message 'Cannot read property 'find' of undefined'

**Expected behavior:** Ability to edit the profile.

**Screenshot**
![image](https://user-images.githubusercontent.com/24900675/63542049-10a31e00-c528-11e9-837d-2f0df6c43944.png)

**Device:**
 - Latest Google Chrome (Win10)

**Comment by apalchys** [comment]
Please check now. it should be fixed in new UI.
