### ISSUE TITLE
Github pr link is not clicable

### ISSUE THREAD

**Issue by Shastel** [rolling-scopes/rsschool-app#96]
**Describe the bug**
Github PR URL seems to be a link, but it is not clickable.

**To Reproduce**
1. Go to any student profile with a score that you have access on
2. Scroll down
3. Data is a not-clickable link

**Expected behavior**
Since it's a link it seems logical that it should be clickable

**Device (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version: 76.0.3809.100 (Official Build) (64-bit)

**Comment by apalchys** [comment]
fixed
