### ISSUE TITLE
Feedback: Errors when sending gratitude 

### ISSUE THREAD

**Issue by valerydluski** [rolling-scopes/rsschool-app#991]
При попытке отправить бэйджи нескольким людям. Часть запросов падает с ошибками.
https://app.rs.school/gratitude
![image](https://user-images.githubusercontent.com/57412523/138560010-71c3f827-688f-4457-9940-71013ad7365d.png)
![image](https://user-images.githubusercontent.com/57412523/138560045-6b531923-824a-4495-9b14-e3667aaa25ac.png)
`message: "Request failed with status code 429"`

**Comment by apalchys** [comment]
Fixed
