### ISSUE TITLE
CV: Phone format in CV

### ISSUE THREAD

**Issue by natein** [rolling-scopes/rsschool-app#999]
В текущий момент сложно догадаться, в каком формате указывать номер телефона в CV.
Предлагается добавить подсказку формата.

![phone](https://user-images.githubusercontent.com/12632270/138565074-e235bfc0-68ce-4733-96d3-6e452475d784.JPG)

Разрешить добавлять пробелы между кодом страны, кодом города и самим номером телефона для улучшения читаемости. Но и без пробелов номер должен вводиться.

+код_страны код_города телефон

**Comment by AlreadyBored** [comment]
I think that we don't need hyphens or whitespaces there
